### ISSUE TITLE
DataExporter: Date is exported as number

### ISSUE THREAD

**Issue by pfumi** [primefaces/primefaces#10015]
### Describe the bug

Exporting data with DataExporter within a DataTable causes date values formatted in German format (DD.MM.YYYY) as number.

### Reproducer

1) Run [reproducer.zip](https://github.com/primefaces/primefaces/files/11213142/reproducer.zip)
2) Click on the button XLSX
3) Open the downloaded file with an excel program
4) The value for the column "LocalDate (German)" is formatted as a number. 12.04.2023 -> 12.042.023
See output here: https://docs.google.com/spreadsheets/d/e/2PACX-1vRKayGLshKz14RohUuHWc36CzK7Fk1EDd_dwzipl2tdy9SFbID12IDfBEIWKwdE1gpqf79dWwYhSft2/pubhtml

### Expected behavior

A date formatted with pattern dd.MM.yyyy should be formatted the same in the Excel output.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.4

### JSF implementation

All

### JSF version

2.3

### Java version

1.8

**Comment by pfumi** [comment]
Prior to 12.x the number check was done with `LangUtils.isNumeric(value)`. Result for "04.08.2021" is **false**
-> https://github.com/primefaces/primefaces/blame/d7bb7360fe5b6719c788e0bca61762354b2c6594/primefaces/src/main/java/org/primefaces/util/ExcelStylesManager.java#L109
In the current version it is done with `BigDecimalValidator.getInstance().validate(value, numberFormat)`. Result for "04.08.2021" is "4082021", so it's recognized as a number
-> https://github.com/primefaces/primefaces/blame/master/primefaces/src/main/java/org/primefaces/util/ExcelStylesManager.java#L115

**Comment by melloware** [comment]
Yep so it determines if its a number based on your locale if NumberFormat is not set.

```java
private DecimalFormat getNumberFormat() {
        if (options != null && options.getNumberFormat() != null) {
            return options.getNumberFormat();
        }
        else {
            return (DecimalFormat) DecimalFormat.getInstance(locale);
        }
    }
```

So that must be a valid German locale number and thus its evaluating as a number not a date.

You have two choices.

See docs: https://primefaces.github.io/primefaces/12_0_0/#/components/dataexporter?id=customization

1. `excelOpt.setStronglyTypedCells(false);`  This is the simplest and doesn't perform any smarts on your Excel cells and just writes the data out as is.
2. Change `excelOpt.setNumberFormat(new DecimalFormat("#,##0.00"));` to something that won't evaluate `04.08.2021` being a valid number.
