### ISSUE TITLE
DataTable: sorting of reflow table does not work if ariaHeaderText is set on column

### ISSUE THREAD

**Issue by sunriseO** [primefaces/primefaces#10043]
### Describe the bug

[DataTable Sort](http://www.primefaces.org:8080/showcase/ui/data/datatable/sort.xhtml) fails if reflow is activated and column has additional ariaHeaderText and ariaHeaderText string does not start with headerText string. 

Steps to reproduce with [primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/11285215/primefaces-test-master.zip):
1. Request test.xhtml
2. Zoom browser to higher level until dataTable reflows 
3. See DataTable now appears in reflow mode and sort select field appears
4. Choose sort item for the column "Year of release"
5. See sorting by release column is done but select item switches back to 1st select item

### PrimeFaces edition

None

### PrimeFaces version

12.0.0, 12.0.4

### JSF implementation

Mojarra

### JSF version

2.3.17.SP01

### Java version

1.8.0_202, 17.0.6

**Comment by melloware** [comment]
The bug is right here

```js
this.selected = optionLabel.startsWith(columnHeader) && optionSortOrder == sortOrder;
```

Your column is "Release" and your AriaText is "Year Of Release" so when it does `optionLabel.startsWith(columnHeader)` its basically making it `"Year of Release".startsWith("Release")` and the answer is `false` so it defaults back to the first one.  I would make your Aria Text "Release Year" and then it will work.
