### ISSUE TITLE
InputNumber: symbol display when hovering with a float label

### ISSUE THREAD

**Issue by azzaro-dev** [primefaces/primefaces#10088]
### Describe the bug

There is no consideration of the float label for the inputNumber component.

### Reproducer

When hovering over the inputNumber component, the currency symbol is displayed mixed with the label.

### Expected behavior

Handling could be added as for the inputMask component.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.4

### Theme

Serenity

### JSF implementation

All

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
Reproducer: 
[pf-10088.zip](https://github.com/primefaces/primefaces/files/11415009/pf-10088.zip)

This one will be tough to fix as the FloatLabel won't know how big the symbol is or when its displayed because that is controlled by AutoNumeric not PF.

here is a workaround you can use.

```css
.ui-float-label > label {
   left: 1em;
}
```

![image](https://user-images.githubusercontent.com/4399574/236686123-4fc8e3a8-6277-43a1-a4d7-ed0f3f518ab4.png)

**Comment by azzaro-dev** [comment]
After taking a closer look at the documentation I can use the emptyValue attribute.
