### ISSUE TITLE
Sticky: add position flag

### ISSUE THREAD

**Issue by wernerchr** [primefaces/primefaces#1017]
It would be nice to set position of sticky component to bottom or top of the screen.
When sticky element is placed at the bottom of the screen, it should be visible as soon as the page is loaded, even when the element is placed outside the field of view.

**Comment by kukel** [comment]
uhmmm... that is like using css position:fixed and bottom:0... So imo no real advantage to that.

**Comment by sudheerj** [comment]
Even though it is easy to overwrite CSS or JS functionality it is better to have position attribute.Ofcourse it is less priority.

**Comment by wernerchr** [comment]
But when the position is fixed, the component appears always at the bottom. If the content is taller than the user’s viewport height, then the component should disappear from view and rest at the bottom of the page, as it would naturally.

Ok, but I don't know how to overwrite it.

**Comment by kukel** [comment]
@wernerchr : that is not what you stated above:

>  it should be **visible** as soon as the page is loaded, even when the element is **placed outside** the field of view.

Now you say it should float down if there is enough whitespace between the end of the document and the bottom of the screen, otherwise it should be at the end of the document text and 

> **disappear** from view

Two different things... Which one is it? The latter is just css: http://stackoverflow.com/questions/311990/how-do-i-get-a-div-to-float-to-the-bottom-of-its-container

**Comment by melloware** [comment]
No comments in 5 years and this can easily be accomplished with just CSS as mentioned. Closing this ticket.
