### ISSUE TITLE
FileDownload: downloading .xhtml instead of PDF in Google Chrome (works in Mozilla Firefox)

### ISSUE THREAD

**Issue by pedrovnarruda** [primefaces/primefaces#10251]
### Describe the bug

When attempting to download a PDF file and opening it in a new window using the `contentDisposition="inline"` attribute with `p:fileDownload` and `ajax="false"` on `p:commandButton`, the file is downloaded as .xhtml instead of a PDF in Google Chrome and Microsoft Edge. This issue does not occur in Mozilla Firefox.

![FileDownload](https://github.com/primefaces/primefaces/assets/51999509/8cf174a4-f892-4a65-8ce1-b36c69d20ed6)

### Reproducer

[FileDownloadReproducer.zip](https://github.com/primefaces/primefaces/files/11792741/FileDownloadReproducer.zip)

1. Download the project.zip file;
2. Extract the contents of the project.zip file;
3. Deploy the project using a web application server (I'm using the Wildfly 27);
4. Open a web browser (Google Chrome or Microsoft Edge) and navigate to the following URL: "http://localhost:8080/filedownload/";
5. On the web page, click on the "Download" button;
6. Observe that the downloaded file has the incorrect extension (.xhtml) instead of being downloaded as a PDF.

### Expected behavior

The PDF file should be downloaded correctly with the correct file extension (.pdf) in all supported browsers, including Google Chrome and Microsoft Edge.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0 Jakarta

### Theme

AdminFaces

### JSF implementation

Mojarra

### JSF version

Jakarta Faces 4.0

### Java version

20

### Browser(s)

Google Chrome v114.0.5735.133; Brave Browser v1.52.126; Microsoft Edge v114.0.1823.51.

**Comment by melloware** [comment]
Works fine for me in Chrome and Edge:  
[pf-10251.zip](https://github.com/primefaces/primefaces/files/11793024/pf-10251.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

**Comment by Pedr0Vitt19** [comment]
> Works fine for me in Chrome and Edge: [pf-10251.zip](https://github.com/primefaces/primefaces/files/11793024/pf-10251.zip)
> 
> Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/
> 
> Same Mojarra 4.x and Jakarta EE10 version as Wildfly.

Thank you for providing the project and instructions. I appreciate your assistance.

I downloaded and tested the provided project following your instructions. However, I am still experiencing the issue where the downloaded file is in the .xhtml format instead of being downloaded as a PDF. I have tested it on the latest versions of Google Chrome and Microsoft Edge.

**Comment by melloware** [comment]
Working fine for me in Windows 11 on latest Chrome and Edge. I have a feeling it is your machine?

**Comment by Pedr0Vitt19** [comment]
Just to clarify, my computer is also running Windows 11. I have tested it on my brother's and father's computers as well, and the same issue occurred consistently using your provided project.

Additionally, I created a virtual machine running Lubuntu 23.04, and surprisingly, the problem persisted.

![LubuntuError](https://github.com/primefaces/primefaces/assets/51999509/8481a4f8-1eee-4a9d-8b5c-f6abb3e5fd95)

**Comment by Pedr0Vitt19** [comment]
I noticed that the problem only occurs when I use the CTRL + S command or click on the download icon. However, if I use the CTRL + P command or click on the print icon and then choose "Save as PDF," it works correctly.

**Comment by melloware** [comment]
So maybe I am confused.  You click the button and in my chrome is displays the PDF in the Chrome PDF Viewer no?   

Are you saying when you then click the download button inside the chrome Viewer it tries to save it as XHtMl and not a PDF? 

This is NOT a PF issue is just how Chrome\ edge works. See this Stack Overflow: https://stackoverflow.com/questions/53548182/can-i-set-the-filename-of-a-pdf-object-displayed-in-chrome#:~:text=In%20Chrome%2C%20the%20filename%20is,page%20using%20the%20object%20element.

**Comment by Pedr0Vitt19** [comment]
Thank you for the suggestion to use the "PrimeFaces Extensions Document Viewer Component." I appreciate your recommendation and will definitely explore it further as it might be beneficial for another screen in my application.

I understand that Google Chrome interprets the URI to initiate the file download. However, the reason for opening this issue is that in older versions of PrimeFaces (specifically version 6.2), with Wildfly 20 and using the Javax namespaces instead of Jakarta, the file download process works as expected when using the CTRL + S command or clicking on the download icon (resulting in a proper .pdf file download).

I wanted to highlight this difference in behavior between the older version of PrimeFaces and the current one, where the file is mistakenly downloaded as an XHTML file instead of a PDF file. This led me to believe that there might be some compatibility or configuration issue specific to the latest PrimeFaces version.

Here is a Reproducer file showcasing the proper functioning of the PDF download feature (please note that you will need an application server that supports the javax namespaces instead of Jakarta, as the older versions of PrimeFaces utilize the javax namespaces):

[FileDownloadReproducerPrimefaces6.2.zip](https://github.com/primefaces/primefaces/files/11795312/FileDownloadReproducerPrimefaces6.2.zip)

**Comment by melloware** [comment]
Some interesting observations.  The request / response looks practically identical.

**PF 6.2 on Jetty 9:**
![image](https://github.com/primefaces/primefaces/assets/4399574/7b1cd59d-0c1b-4da0-aa3e-04278486f5df)

**PF 12.0 on Jetty 11:**
![image](https://github.com/primefaces/primefaces/assets/4399574/b2585efa-bb06-42df-b741-aeadd90a90d0)

Notice the URL is identical as well as the Content-Disposition etc.

**Comment by melloware** [comment]
OK @Pedr0Vitt19 got to the bottom of it.  This ticket is what is causing the issue: https://github.com/primefaces/primefaces/issues/6359

That was introduced in 10.0.0 to add NO Cache Control for GDPR.  Firefox seems to like it but Chrome and Edge see that its not cached and no longer have the real file so they must fall back to the URL for the file name.  Not sure if its an issue with Chrome or with Firefox not respecting the HTTP spec.

@tandraschko from reading the ticket the idea was since these files are always dynamic they should never be cached.  Not sure if this is worth fixing for this corner case?

**Comment by tandraschko** [comment]
caching dynamic generates files does not make any sense TBH

**Comment by Pedr0Vitt19** [comment]
I believe it would be beneficial to address this issue to ensure consistent behavior across different browsers. One possible solution could be that we add a property to the "p:fileDownload" component that allows us to specify whether dynamically generated files should be cached or not. By default, the "NO Cache Control" behavior could be retained, but we would have the flexibility to enable caching if desired, depending on our specific project requirements.

I would like to suggest considering this enhancement as it would provide more control and flexibility to developers while still maintaining compliance with GDPR regulations.

**Comment by Pedr0Vitt19** [comment]
I believe it would be beneficial to address this issue to ensure consistent behavior across different browsers. One possible solution could be that we add a property to the `p:fileDownload` component that allows us to specify whether dynamically generated files should be cached or not. By default, the "NO Cache Control" behavior could be retained, but we would have the flexibility to enable caching if desired, depending on our specific project requirements.

I would like to suggest considering this enhancement as it would provide more control and flexibility to developers while still maintaining compliance with GDPR regulations.

**Comment by melloware** [comment]
I submitted a PR for review.

**Comment by Pedr0Vitt19** [comment]
Ok thank you for this.

**Comment by Bukama** [comment]
Just saw this ticket. This is EXACTLY the same problem I mentioned in Discord some months ago.
We decided to change the download to enforce downloading the file instead of showing the PDF (but we could do this, because our requirements do not force us to show the PDF)

**Comment by JonatanRoo** [comment]
Hi,
We are on PF10 right now and are having problem with this bug. We would need to solve it asap and an upgrade to 13 could take some time. Is there something we can do to fix this?

I looked at https://github.com/primefaces/primefaces/pull/11349/commits/ca23137e9f81a11caa02f674b5358c2bbd71aab2
and blocked/modified the headers with a Filter and a HttpServletResponseWrapper but it's still not opening as an PDF in Chrome.

Any advice appreciated.

**Comment by melloware** [comment]
If you are on PF10 you would porbbaly have to grab a Tag of PF10 here in GitHub and rebuild from Source with the hacked fixed for nostore

**Comment by JonatanRoo** [comment]
@melloware ok thanks. Any ideas why just modifying the headers does not work? I tripple checked that they really are the same as in the fix. no-store is gone but still not working.
![Screenshot 2024-03-21 at 22 08 24](https://github.com/primefaces/primefaces/assets/164416422/c1b489b8-9e42-4fbe-948a-4346e20ac046)

**Comment by melloware** [comment]
hmmm nope? that looks right.

**Comment by JonatanRoo** [comment]
Ok thanks anyway for your quick replies 👍
