### ISSUE TITLE
CommandLink: does not show status indicator

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#10482]
### Describe the bug

I am not sure if this is a bug or a missing configuration by myself (I think so):

I have a `p:commandLink` and when clicking, then its css ".ui-state-loading .ui-state-disabled" will be applied correctly, however instead of the loading indicator, the icon will be shown in _disabled_-mode (which could be irritating in some circumstances because the user does not know what happens now). How can I show the loading indicator instead? Using a `p:commandButton` instead of `p:commandLink` works as expected - the status indicator is shown within the button. 

### Reproducer

[primefaces-test-jakarta.zip](https://github.com/primefaces/primefaces/files/12327424/primefaces-test-jakarta.zip)

### Expected behavior

A status indicator when waiting for the ajax-response after clicking a `p:commandLink`.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

4

### Java version

17

### Browser(s)

Firefox 115.0.2

**Comment by melloware** [comment]
cc @jepsar

**Comment by jepsar** [comment]
This is by design. Where would we add a loading indicator without shifting the width of the commandLink?

If you don't like that it is disabled, simply use `disableOnAjax="false"`.

If you do want to show a loading indicator, you can by using custom CSS (as you have noticed, we do add the class for loading). See for example the custom loading indicator in the commandButton: https://www.primefaces.org/showcase/ui/button/commandButton.xhtml
