### ISSUE TITLE
Overlay panels are closed if the page is scrolled

### ISSUE THREAD

**Issue by arunvc** [primefaces/primefaces#10490]
### Describe the bug

Click overlay panel and scroll the page using mouse overlay panel is closed

 overlay panel stays in v 8

### Reproducer

https://www.primefaces.org/showcase/ui/overlay/overlayPanel.xhtml?jfwid=9b533

just click and overlay and scroll using mouse middle button

### Expected behavior

https://www.primefaces.org/showcase-v8/ui/overlay/overlayPanel.xhtml

overlay panel stays when you scrolls

### PrimeFaces edition

None

### PrimeFaces version

13

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

17

### Browser(s)

Firefox

**Comment by melloware** [comment]
@arunvc this is by design as user interface guidelines state that when you are scrolling the page you are no longer interacting with the Overlay (FaceBook and many others do this now by default).

However if you want to disable this behavior (not reccommended for ARIA reasons) you can with 1 line of JS code.

```js
PrimeFaces.hideOverlaysOnViewportChange = false;
```

See: https://github.com/primefaces/primefaces/issues/10085
