### ISSUE TITLE
Picklist: move selected (with CTRL button) with mouse is not working - only the touched one is moved

### ISSUE THREAD

**Issue by jnr25** [primefaces/primefaces#1081]
In picklist when selecting elements from source with CTRL button and mouse and then moving with the mouse to the target, only the touched one is moved but not other all marked as selected.

Try it in showcase http://www.primefaces.org/showcase/ui/data/pickList.xhtml

**Comment by jxmai** [comment]
Although it could be an inconsistent UI issue,  the main issue is not on Primefaces but because jquery UI does not support multi-sortable out of the box (http://jqueryui.com/sortable/).

There are some other jquery ui extension libraies such as https://github.com/shvetsgroup/jquery.multisortable to provide such a missing feature, but it might not worth a shot and we better stick with the native jquery library than an out of support lib.

**Comment by melloware** [comment]
Third party issue in Jquery UI sortable.
