### ISSUE TITLE
Charts: unified and consistent data interface classes

### ISSUE THREAD

**Issue by asdef** [primefaces/primefaces#10849]
### Description

As a developer of charts that often stack multiple elements (bar, line) to show the relationship between 2 or more data sets where my number of data points is not consistently equal; I want a consistent way to feed data to the Cartesian chart types that preserve my x / y tuples so that I do not need to pre parse all my data points to get a distinct list of X axis labels, then build each data set ensuring that I provide a value for each X value I found across all datasets, but instead let chart.js figure it out for me, instead of needing to write a potentially error prone hack to massage all the data points to fit the primefaces wrapper when the underlying chart.js can handle the tuples.

### Describe the solution you would like

For each of the ChartDataSet implementations, have the data field accept a List<Object> instead of List<Number> (or a list of an abstraction that makes sense to collect x / y tuples)  like the LineChartDataSet currently does so that if a developer wants to pass in a list of NumericPoint, or a class of their own that has a toString implementation that produces JSON that will output correctly when processed by ChartUtils.writeDataValue() the same way BubblePoint and NumericPoint do.

### Additional context

The specific classes that would need to be modified to need a minimally viable fix are:  BarChartDataSet, PolarAreaChartDataSet, and RadarChartDataSet.

**Comment by melloware** [comment]
@asdef interested in submitting a PR?

**Comment by fcorneli** [comment]
> when the underlying chart.js can handle the tuples

I always wondered what the reason is to try to hide away the underlying JS library while it can be so much more powerful.

This is one of the reasons I wrote an ECharts based component, that exposes the bare metal ECharts API as is.
https://demo.e-contract.be/ejsf-demo/echarts.xhtml

I got tired of fighting Java wrappers around JS APIs that serve no purpose at all.

Just like with chart.js, the ECharts APIs are well documented. There is absolutely no reason to try to wrap this within some Java model thingy.

**Comment by melloware** [comment]
@fcorneli i think for the most part I agree with you.  The larger the JSON API the harder it is to chase.

**Comment by Rapster** [comment]
I already had a few thoughts about this explained there: #8819

In a few words: current implementation is way too complicated and not permissive enough (if you need a new attribute in Dataset for instance, you better hope for @melloware to have time and be able to fix it and hope that the next release is coming up  soon...)

My idea on this is really simple:
-  create a very simple wrapper taking a String (JSON value), give it to chart.js and you done! 
- now, having some pre-made DataSet is also very helpful instead of working with a String: depend on https://github.com/xdev-software/chartjs-java-model, takes a `Chart` object as input

I believe it covers major point you all mentionned

**Comment by fcorneli** [comment]
@Rapster Totally agree with you. How I attack charts these days:
* first I construct the ECharts look-and-feel that I'm chasing after completely outside of JSF, like for example:
https://github.com/e-Contract/enterprise-jsf/blob/master/ejsf-demo/src/main/resources/echarts.json
* next I do some `gson` magic to replicate the JSON structure that I want
* next I can use this as kind of "chart template" to inject my data into it

The thing is, you should not need to redefine the entire JSON structure within Java, only the how-to-name-it "data injection points".

What we need is kind of a https://www.thymeleaf.org but for JSON.
The nice thing about Thymeleaf is that you can use the template as-is. I.e., the "data injection points" are defined by means of Thymeleaf specific attributes, which are nicely ignored by the web browser. Hence your HTML template can hold some example data, handy when developing your template, and in production you can use this template as-is.

Due to the nature of JSON, it's difficult to define this "injection metadata" inline without risking that chart.js/ECharts/whatever explodes on it.

So, something like the following would be nice:
```java
JSONTemplate template = new JSONTemplate.Builder()
    .template("/location/of/your/template.json")
    .dataInjection("/json/xpath/like/location/where/to/inject/data", MyDataMapper.class)
    .dataInjection("relativeInjectionPoint", Boolean.class)
    .build();
```
And then instantiating the JSON template as follows,
```java
MyDataMapper data = new MyDataMapper("... whatever"); // gson, Jackson, ...
String result = template
    .inject("/json/xpath/like/location/where/to/inject/data", data)
    .inject("relativeInjectionPoint", true)
    .output(String.class);
```
Don't know if such thing already exists out there.

**Comment by melloware** [comment]
Reasonable to me since we won't break backward compatibility as I know my clients have a bunch of charts JS charts already in place.

**Comment by tandraschko** [comment]
We should think about that really well.
Some customers are using chart libs without modell support as this libs removed it in the past. See amcharts e.g.
So you actually just serialize your data and map it via JS functions.

Its just always hacky if the chart lib itself doesnt provide a model or at least something like a json schema.

Maybe also better placed in pfe. I dont have any client which is using PF charts. Everyone is using a different js solution.

**Comment by Rapster** [comment]
> Some customers are using chart libs without modell support as this libs removed it in the past. See amcharts e.g.
So you actually just serialize your data and map it via JS functions.

Same here we're using amCharts

> Maybe also better placed in pfe. I dont have any client which is using PF charts. Everyone is using a different js solution.

I don't know if it has a better place in PFE, I don't see any issue having it in PF

**Comment by tandraschko** [comment]
I just dont like to rely on dependecies with 2 stars in PF core

**Comment by Rapster** [comment]
But that's what I said, PF wouldn't rely on anything (users are free to use plain string, or something like [chartjs-java-model](https://github.com/xdev-software/chartjs-java-model)

OF: it's a new fork of https://github.com/mdewilde/chart

**Comment by fcorneli** [comment]
This point here is that PF should not force a half baked model down the throat of developers. As stated by @Rapster, provide a String API, and maybe some documentation reference where to find a Java-to-the-thing library if you feel like using this.

**Comment by Rapster** [comment]
I created a new ticket summing up all the ideas shared so far (and a draft PR to give you an idea what it could look like, see #10871)

**Comment by asdef** [comment]
@Rapster I just took a look at the chartjs-java-model that you linked to, and while it covers quite a bit, it doesn't appear to handle the data points as tuple interface that chartjs provides, and I need for my particular application.  The data in my application that I need to chart is largely datetime / numeric mappings, and when plotting more than one dataset (eg one bar one line), the x axis date values don't line up between the two datasets, so I have a preference for solutions that write the two values together in the same object instead of the split data array ,  labels array approach.  If I missed something in reviewing the chartjs-java-model implementation, and it can do this, please let me know.

**Comment by Rapster** [comment]
I'm guessing you're refering to this: https://www.chartjs.org/docs/latest/general/data-structures.html#object

AFAICS, indeed `Dataset#data` is a simple list and doesn't seem to support tuple. I might also miss something, I would advise you to open an issue on chartjs-ava-model and see what they have to say

**Comment by melloware** [comment]
@asdef i am also ok with you providing a PR for our current chart model. I don't think we will remove it from PF.

**Comment by asdef** [comment]
@melloware I've got the model changes done, and a good start on the showcase changes on my local clone; but I'm not happy with how my date x values are rendering, and I think I need to add [chartjs-adapter-date-fns](https://www.npmjs.com/package/chartjs-adapter-date-fns/v/3.0.0) from NPM and am studying the existing NPM includes (I haven't developed in node much, so the structure doesn't make sense in my head yet) to figure out how to add it.  Would a link to my WIP be useful to anyone?

**Comment by melloware** [comment]
Yes you can submit your PR as a "Draft" so we can review it but it can't be merged.

**Comment by asdef** [comment]
created PR https://github.com/primefaces/primefaces/pull/10903 in draft.  Still working on being able to format the x axis dates, probably using [chartjs-adapter-date-fns](https://www.npmjs.com/package/chartjs-adapter-date-fns/v/3.0.0).

**Comment by Rapster** [comment]
@asdef chartjs-java-model committer has updated the model, feel free to have a look

**Comment by Rapster** [comment]
I suppose we can close this then?

**Comment by asdef** [comment]
closing in favor of @Rapster 's solution [here](https://github.com/primefaces/primefaces/pull/10871)
