### ISSUE TITLE
Datatable: setting scrollable to true makes columns' text not responsive

### ISSUE THREAD

**Issue by YotillaPablo** [primefaces/primefaces#10989]
### Describe the bug

I have a datatable with a column that can contain really long text. Reducing the browser's width, when `scrollable` is set to false, makes the text split into multiple lines. This is not the case when `scrollable` is set to true, as the text stays unchanged and overflows over the cell border, making the text unreadable.

This behaviour can be reproduced with v13.0.3 and v12.0.0.

### Reproducer

A reproducer can be found [here](https://github.com/YotillaPablo/primefaces-scrollable-table)

How to reproduce: 

1. Go to [http://localhost:8080/primefaces-test/](http://localhost:8080/primefaces-test/)
2. Resize the browser so the text in the datatable column doesn't fit.
3. Verify the text doesn't split into multiple lines.
4. Set `scrollable="false"` in the datatable inside test.xhtml
5. Go to [http://localhost:8080/primefaces-test/](http://localhost:8080/primefaces-test/)
6. Resize the browser so the text in the datatable column doesn't fit.
7. Verify the text splits into multiple lines.

### Expected behavior

Long texts split into multiple lines when they don't fit inside a column, independently of the value of the `scrollable` property.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.3

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

17

**Comment by melloware** [comment]
I believe this to be the correct behavior.  If you say you want your table scrollable it can scroll infinitely to the right so there is no wrapping of your text. When you say scrollable="false" you want a fixed with table thus as you shrink the browser the text will wrap. You have also given no WIDTH to your column to its unbounded.

Try this reproducer: 
[pf-10989.zip](https://github.com/primefaces/primefaces/files/13393139/pf-10989.zip)

**Comment by YotillaPablo** [comment]
It works as expected now, thanks for the help!

**Comment by YotillaPablo** [comment]
It's not a bug but the expected behaviour.

**Comment by melloware** [comment]
Thanks for reporting back!
