### ISSUE TITLE
DataTable: Pre selected disabled rows are dismissed on serverside

### ISSUE THREAD

**Issue by pfumi** [primefaces/primefaces#11356]
### Describe the bug

If a DataTable is submitted with a disabled row which is checked, then the selection on serverside is updated and dismisses the disabled checked row.

There were multiple issues with disabled rows in DataTable, some were fixed here https://github.com/primefaces/primefaces/issues/11290. One still persists, see my comment here https://github.com/primefaces/primefaces/issues/11290#issuecomment-1895630040

### Reproducer

1. Start the reproducer [primefaces-14.0.0-test-master.zip](https://github.com/primefaces/primefaces/files/13949336/primefaces-14.0.0-test-master.zip) or [primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/13948324/primefaces-test-master.zip)
2. The first row (enabled) is checked, and the second row (disabled) is checked
3. Click on the button "Submit"
4. The first row is still checked, but the second row is unchecked

### Expected behavior

All checked rows, either disabled or not, should be kept in the selection list on serverside.

### PrimeFaces edition

Community, Elite

### PrimeFaces version

14.0.0-SNAPSHOT, 13.0.4

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

8

**Comment by melloware** [comment]
This is the same issue right?  Disabled rows are being ignored on the server side submit just like normal HTML checkbox behavior correct?

**Comment by pfumi** [comment]
Yeah is the same, just wanted to create a new on because the other one is allready closed.

**Comment by melloware** [comment]
cc @Rapster @christophs78 @tandraschko @jepsar we need to discuss and decide what to do here.

**Summary:**  When you use `disabledSelection="#{xxx}"` that will evaluate and prevent any row from being marked selected and was fixed in issue: https://github.com/primefaces/primefaces/issues/9552   I think this is the correct behavior. It works the same as an HTML Checkbox that is disabled the submitted value is ignored/not applied.

@pfumi would like that if he marks something selected on the backend that it shows up Selected AND Disabled on the UI (which it does). But when he submits those disabled records are being unchecked because of #9552.

So we need to decide what to do here but we cannot satisfy both scenarios I don't think.  And my two cents is the current behavior is correct.

**Comment by Rapster** [comment]
The current behavior is the right one, there is a very simple as of why there is this `disabledSelection` check once selection is submitted. Let's say, you have items you don't want be able to select, if you don't have that `disabledSelection` check, you can simply modify the input state holder (in the HTML) to force the selection of these unselectable items.

For your issue, every time you submitted your action, remember to add the disabled items to the list you want before you call your action

**Comment by melloware** [comment]
@pfumi i am going to close this as Not planned.  Rapster and I agree the current behavior is the correct behavior.
