### ISSUE TITLE
DataTable: selection issue with overlayPanel and dialog 

### ISSUE THREAD

**Issue by Egodrone** [primefaces/primefaces#11600]
### Describe the bug

There is an issue with datatable selection when datatable is inside the overLayPanel which is inside the dialog. The value that is sent to the setter is null. 

### Reproducer

https://github.com/Egodrone/primefaces-test-overlayPanel-issue/tree/jpa 
1) click on open wizard dialog
2) press any of the ui-buttons in the datatable
3) Select any row in the pop up datatable 
4) Press the same ui button and there you can see that nothing is selected.

### Expected behavior

When the row is selected it should be selected in the dataTable.

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.7

### JSF implementation

MyFaces

### JSF version

5.1.2

### Java version

17.0.6

**Comment by melloware** [comment]
OK when I add a System.out.println the value is always NULL on the AJAX selection even though the AJAX request looks correct.

```java
public void setSelectedRow(TestJpa selectedRow) {
        this.selectedRow = selectedRow;
		System.out.println(selectedRow);
    }
```

```
[INFO] Started Jetty Server
null
null
```

**Comment by melloware** [comment]
@Egodrone ok try my reproducer I moved some of your code around but i think the real issue is you did not have a `rowSelect` event grabbing the new selection you were expecting it to to update the selection itself?

[pf-11600.zip](https://github.com/primefaces/primefaces/files/14541424/pf-11600.zip)


```java
    public void onRowSelect(SelectEvent<TestJpa> event) {
        System.out.println("TestJpa Selected " + String.valueOf(event.getObject().getId()));
	this.selectedRow = event.getObject();
    }
```

**Comment by Vikkear** [comment]
@melloware I have a followup question, do you really need to set the selectedRow through onRowSelect? Isn't it supposed to be set through the setter?

In this showcase, https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml?jfwid=385ed
The selectedProduct is set through the setter rather than via onRowSelect() where the only code that is executed creates a popup.

The setter seems to be working properly if you remove the p:dialog and only have an overlayPanel with the dataTable, so why does onRowSelect() have to be added only because it is put inside a p:dialog?

I did some debugging and it seems like the reason for setSelectedRow() having null as value is because inside context.getExternalContext().getRequestParameters(), the id + "_selection" parameter is missing.

**Comment by melloware** [comment]
@Vikkear you may be right all i see in the AJAX request is `instantSelectedRowKey`

![image](https://github.com/primefaces/primefaces/assets/4399574/f5f6922c-96c9-4cb4-a8f8-304b8bae3011)

**Comment by melloware** [comment]
I can also see the selection is in the HTML form.

```xml
<input id="frmOverlay:tblJpa_selection" name="frmOverlay:tblJpa_selection" type="hidden" autocomplete="off" value="1">
```

That should have been submitted with the form.

**Comment by melloware** [comment]
Got it. @tandraschko was right.

![image](https://github.com/primefaces/primefaces/assets/4399574/ab81f4c0-8422-4fcf-bb1e-18619e84a3e7)

You need `appendTo="self"` on the OverlayPanel.  basically the OverlayPanel was being appended to the `body` by default which is outside the `<h:form>` so that value was not being submitted because it was not inside the `<form>`.

**Comment by melloware** [comment]
OK I grabbed the original reproducer and changed the 1 line `appendTo="self"` and its all working.

```xml
            <p:overlayPanel id="overlayPanel"
                            widgetVar="overlayPanelWidget"
                            hideEvent="keyup"
                            showCloseIcon="true"
                            dismissable="true"
                            dynamic="true"
                            appendTo="self"
                            style="width: 60%">
```
