### ISSUE TITLE
SubTable: still alive even after been announced deprecated in 10.0.0

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#11875]
### Describe the bug

`p:subTable` component still appears to be alive in PF, yet, showcase has been deleted for this compnent, still there in docs, any idea what we should do about this? 

### PrimeFaces version

15.0.0-SNAPSHOT

**Comment by melloware** [comment]
I think when we had talked before we left it in there for people still using it but we removed the showcase examples so people would stop using it.  Basically it's there just for backward compatibility from what I remember.

**Comment by martin654** [comment]
Hi, we are still using it in production. I don't think that it could be replaced by other DataTable features (we use it with lazy and pagination).

**Comment by Rapster** [comment]
I understand that, but also understand that so far, the way I see it, it feels we're maintening 2 features wich does the very same thing and I could be 100% wrong, but I asked in the past whoever using that feature to give us a reproducer which shows row grouping can't replace subtable and nothing...

If that turns out to be true, then we should update our docs, and our showcase. Do you think you could make a reproducer of how you're using subtable?

**Comment by martin654** [comment]
I will try to find time to create reproducer

**Comment by Rapster** [comment]
Ok got it, if I understand well that coment https://github.com/primefaces/primefaces/issues/2269#issuecomment-762110559 It's useful in case of one-to-many association (non flat model) but because you "can't" change that into a flat model, you have no other choice than use subTable right?

Also, do features like sorting/filtering/exporting works on subtable?

**Comment by martin654** [comment]
Great that you found the old comment with the explanation. Yes, the data provided by backend are not flat, but structured with one-to-many association. We are not able to change existing backend impl just because some feature is deprecated in frontend component.

Well, good question... We use just the lazy loading and pagination feature in this case. We use filtering in this case, but it is placed above the table in "Filtering panel", not in column headers. And the filter data are filled into service request in lazy load method.

**Comment by Rapster** [comment]
I'm okay to undeprecate subTable, we should put the showcase pages back, remove deprecated logs etc.

**Comment by melloware** [comment]
OK i will take care of that!
