### ISSUE TITLE
Improve Menubar Submenu positioning

### ISSUE THREAD

**Issue by mores** [primefaces/primefaces#120]
Original Bug: https://code.google.com/p/primefaces/issues/detail?id=5987

Testcase using 5.2. can be found here: https://github.com/mores/maven-examples/tree/master/prime-menuBar
clone; mvn jetty:run 

As you can see from the picture - New -> Project can not bee seen.
![primemenu](https://cloud.githubusercontent.com/assets/1318377/7230400/6ecd6f28-e73b-11e4-8036-d8d07fa095c3.png)

**Comment by cagataycivici** [comment]
Thank you, we'll review.

**Comment by cagataycivici** [comment]
I've applied flipfit collision algorithm and removed scrollbars as it breaks nested submenus.

See flipfit at;

http://api.jqueryui.com/position/

It will also take care of horizontal collision as well.

**Comment by VsevolodGolovanov** [comment]
@cagataycivici, it seems like this fix was lost when @mertsincan was messing up menu.js in #121.
More interestingly, the fix is not present in the current menu.js on GitHub, yet somehow the fix is there in the 5.2.8 Elite release. I wonder, how could that happen? I guess you have a private repository with branches for maintaining different versions?
Anyway, the fix is lost in the public repository.

**Comment by cagataycivici** [comment]
Not sure, what is happening, need to investigate.

**Comment by cagataycivici** [comment]
I cannot replicate the issue and the fix is in menu.js here at GitHub. No private repos for 5.x major releases.
