### ISSUE TITLE
DatePicker: yearNavigator appears as "spinner" instead of "select"

### ISSUE THREAD

**Issue by Royercas** [primefaces/primefaces#12097]
### Describe the bug

Since Primefaces 13 yearNavigator appears as "spinner" instead of "selectOne" type. This is totally complicated when you have to (in a list of 100 years) get to 1917 when you are in 2024 and you have to click those small arrows to go down one by one.
Could be possible to replace the spinner for the old "selectOne" type? just the same as the monthNavigator ?
Thanks in advance

### PrimeFaces edition

Community

### PrimeFaces version

13

### JSF implementation

All

### JSF version

2.3

### Java version

21

### Browser(s)

All browsers

**Comment by jepsar** [comment]
You don't need to click, you can type as well.

See #8950

**Comment by melloware** [comment]
Exactly as @jepsar said this was to make it more accessible and EASIER to select dates not harder.

**Comment by jepsar** [comment]
Question on SO https://stackoverflow.com/questions/78604912/primefaces-14-yearnavigator-in-datepicker-appears-as-spinner-instead-of-a-se

**Comment by melloware** [comment]
@Royercas think about it from a visually impaired perspective.  If you have 100 years they have to click down arrow 100 times to get to the first year.  This way because its using input type="number" its more screen reader friendly AND a year can be typed.= for quick entry if I know i was born in 1974 don't make me scroll that far back.

**Comment by melloware** [comment]
Going to close this as not planned.

**Comment by melloware** [comment]
Re-opening this as now more than one person has asked for this.
