### ISSUE TITLE
DataTable Showcase: add missing POJOs and ENUM

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#12169]
if you wanna copy the showcase/ui/data/datatable/basic.xhtml samples, there is no linked Product.java and no InventoryStatus.java

would be great if we can check our samples to make it easier to understand everything

**Comment by melloware** [comment]
I was able to get it working: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/data/datatable/basic.xhtml?jfwid=6a067

The issue is how we were scanning for classes because of erasure it would see `List<Product>` and return `List.java` and we would ignore it.  So I had to pull out the generic type "Product.java" and recursively walk those found POJO's.

All seems to be working now!
