### ISSUE TITLE
DatePicker: Focus remains after selecting date, popup not re-opening

### ISSUE THREAD

**Issue by mkomko** [primefaces/primefaces#12361]
### Describe the bug

When selecting a date using the DatePicker component, the focus remains on the component. This causes the date selection popup to not re-open when clicking in the field again. This worked in PF13, since the focus was not on the component after selecting a date.

### Reproducer

1. Go to http://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml
2. Click on the "Basic" field
3. Select a date
4. Click on the "Basic" field again
5. The popup does not open

### Expected behavior

The popup should open every time when clicking on the field (except it is already open).

### PrimeFaces edition

Elite

### PrimeFaces version

14.0.2

### Theme

Rain

### JSF implementation

All

### JSF version

4.0

### Java version

17

**Comment by melloware** [comment]
@mkomko that is by design with ARIA standards.  What happens is when you select a date and close the popup ARIA says focus must go back to the `input` from where the modal poup was initiated from.  the input now has focus so clicking on the input that "already has focus" so `showOnFocus` says don't display the popup if you already have focus.  

ENTER/SPACE can re-open it so I suppose clicking on it again can make it open but its definitely not a focus event.  I would have to add special handling for `click` event.
