### ISSUE TITLE
Datatable: Filtering dynamic columns from a composite component

### ISSUE THREAD

**Issue by gpo2307** [primefaces/primefaces#12744]
Hi all,

I'm trying to filter dynamic columns (<p:columns ...), but filtering doesn't work if it's called from a composite component.

I made a standalone project (from primefaces-test) to try this (link is on bottom of this message).

If i move, for example, <p:inputText from file.xhtml to test.xhtml (just after <sf:file .....), then filtering will work properly.

Am i missing something or this is a bug ?

I tried it with PF 14.0.6.

Thank you !

[primefaces-test (1).zip](https://github.com/user-attachments/files/17437123/primefaces-test.1.zip)

**Comment by gpo2307** [comment]
Seems to be same issue [https://github.com/primefaces/primefaces/issues/12507](url)

**Comment by Rapster** [comment]
Ok, so... First, whenever you use a composite and you need to target an input, then you have to use `<cc:editableValueHolder name="myinput"/>`This works pretty well when you only have one component (which makes composite pretty useless in that case... 😅)

Second, and this is probably a limitation of JSF/composites or might actually be PF 😅 ... Like I said before, your composite needs to target ONE and ONLY input using his `id`. But here you have 3 different inputs contained in your composite and only one  should be eligible depending a value (e.g column.type). 

So how to use same id for 3 differents components? Quick reminder: you can't use the same id even though only one is rendered because these 3 inputs are still present in the JSF tree. So the final answer is: JSTL _(which allows you to manipulate the JSF tree structure)_

You could wrap every children using `<c:if test=#{column.type eq 'xxx' />` but it won't work because `column` is available at render time, and JSTL applies at build time which happens to be before render time...


You could write a facelet tag:

```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:cc="jakarta.faces.composite"
                xmlns:f="jakarta.faces.core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:c="jakarta.tags.core"
                xmlns:ui="jakarta.faces.facelets" xmlns:h="jakarta.faces.html">


    <p:datePicker selectionMode="range" onchange="PF('customersTable').filter()"
                  rendered="#{column.type eq 'date'}"/>
    <p:selectOneMenu onchange="PF('customersTable').filter()" rendered="#{column.type eq 'enum'}">
        <f:selectItem itemValue="#{null}" itemLabel=""/>
        <f:selectItems value="#{column.klazz.enumConstants}"/>
    </p:selectOneMenu>
    <p:inputText onchange="PF('customersTable').filter()" rendered="#{column.type eq 'string'}"/>
</ui:composition>
```

But I can try to tackle this one in PF 🤞 

Meantime, désolé @gpo2307 but this is not a bug 😄

**Comment by tandraschko** [comment]
@melloware currently target 14.0.x - you would need to merge or change target

**Comment by melloware** [comment]
I will backport this to 14.0.7 as this used to work.
