### ISSUE TITLE
Readonly option for SelectBooleanCheckbox

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#130]
Please add readonly option for SelectBooleanCheckbox component so it can be used e.g. in tables for showing boolean values graphically. Thank you very much.

**Comment by mauromol** [comment]
Another use case for readonly vs disabled state for checkboxes (although in `selectManyCheckbox`, instead of `selectBooleanCheckBox`) is the following.
I have a list of elemens in a `selectManyCheckbox`. I want to prevent the user from changing the state of just some of these check boxes (ie.: some must be clickable, some must not).
However, if I use `itemDisabled="true"` for the values I want to make read-only, on submit PF will consider those values as "unchecked" and change my model by removing any corresponding elements from the underlying collection. This is due to the way HTML handles the "disabled" state for input fields (i.e.: they are not submitted - and for a single checkbox this is interpreted as "set to false").

**Comment by mauromol** [comment]
Maybe the `selectManyCheckbox` case is worth opening a dedicated bug (I can't think of a proper use case for the current behaviour), what do you think?

**Comment by cagataycivici** [comment]
https://stackoverflow.com/questions/155291/can-html-checkboxes-be-set-to-readonly

**Comment by mauromol** [comment]
It's not clear to me whether this has been implemented or not (and in which version?).

**Comment by melloware** [comment]
@mauromol I don't believe it was fixed because there were no commits associated with it.  I think what @cagataycivici is pointing out is that there is NO such thing as a ReadOnly checkbox.   That Stack Overflow article states as much and just points out a bunch of hacky workarounds to try and make it look readonly.

**Comment by mauromol** [comment]
@cagataycivici can you confirm what @melloware says?
