### ISSUE TITLE
DataTable: Editable cell updated second time not moving focus properly with tab key

### ISSUE THREAD

**Issue by BryceMcGilly** [primefaces/primefaces#13099]
### Describe the bug

After a cell in an editable DataTable has been updated for the second time, focus is not moving properly to the next cell when pressing the tab key out of the edited cell.

### Reproducer

https://github.com/BryceMcGilly/primefaces-test-tabbing-issue

To reproduce the behavior:

1) Increment the Quantity of the Thriller item to 1
2) Press tab to tab through the cells in the rows, notice the tabbing order is correct
3) Increment the Quantity of the Thriller item again to 2
4) Press tab to tab through the cells in the row again, notice the tabbing order is messed up after trying to tab out of the "Minimum Order Quantity" cell to the next cell
5) The order remains messed up if you left click on the Thriller cell and try to tab through the table
6) Increment the "Minmum Order Quantity" cell of the Thriller row to 1 and try to tab through the table starting with the Thriller cell, notice the Minimum Order Quantity cell is now skipped. Also notice once it's skipped over, the spinner in this cell is now frozen and you cannot increment or decrement the Minimum Order Quantity.

### Expected behavior

Tabbing order through the DataTable will remain correct even after an editable cell has been updated for a second time by a previous cell.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.9

### JSF implementation

Mojarra

### JSF version

4.0.9

### Java version

17.0.7

**Comment by melloware** [comment]
Thanks for the reproducer. Confirmed issue.

**Comment by melloware** [comment]
@BryceMcGilly OK I don't think you can do what you are trying to do with this.

If you remove `<p:ajax update="minOrderQuantitySpinner minOrderQuantity" />` it now works.  but your second spinner is not constrained by Min Max.

The issue is the cell editor needs to blur and show the cells and your AJAX update trying to update the next cell editor wipes out the DOM while its trying to display the new cell.

I doubt we will try and fix this you should switch to ROW Editing if you really need to manipulate one cell with values of another.

Row Edit: https://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml

This way all your editable cells are on the screen so you can AJAX update the next one.
