### ISSUE TITLE
BatchSize for Export of Lazy Data

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#134]
The DataExporter should allow to set a different "batchSize" as the datatables rows to improve performance of lazy lading large amount of data. For example when there are 6000 results and we have a page size of 10, the DataExporter would issue the sql 600 times in order to export all rows.

It should be sufficient to set the row size of the table to a greater sitze before exporting and resetting this value after exporting.

**Comment by hades646** [comment]
If I'm not mistaken, right now only one query is being executed, because the `org.primefaces.component.export.Exporter.exportAll(FacesContext, DataTable, Object)` method sets the page size to the size of the whole list before exporting and then it restores the previous value.

Actually, considering the fact that `LazyDataModel` is used for handling huge lists, I think the attribute you are proposing should even be mandatory. The present implementation can potentially lead to `OutOfMemoryError` if the list is huge enough.

**Comment by melloware** [comment]
This is no longer an issue as pointed out by @hades646
