### ISSUE TITLE
FileUpload XSS vulnerability

### ISSUE THREAD

**Issue by whaleshogun** [primefaces/primefaces#1439]
Primefaces version 5.1.141 (ELITE Build)

``` xml
<p:fileUpload fileUploadListener="#{calendarMappingController.handleFileUpload}" mode="advanced" label="#{msg['calendarmapping.importfromexcel']}"
                                allowTypes="/(\.|\/)(xls|xlsx)$/"
                                update="calendarMappings" 
                            />
```

Uploading a file named  `<img src=x onerror=alert('XSS')>.xlsx` (under Linux, since Windows won't allow file names with special characters).

Result:

html content in file name is not escaped.

![image](https://cloud.githubusercontent.com/assets/7386341/15400741/e40d6e80-1dec-11e6-8b87-ab5b0dea56bc.png)

**Comment by cnsgithub** [comment]
Note: This XSS vulnerability is not dependant on any OS since there is always the possibility to tamper with POST data and use specially crafted file names albeit those characters would be invalid in Windows file names...

**Comment by tandraschko** [comment]
Does it still occur in 6.0?

**Comment by whaleshogun** [comment]
The problem still occurs in PrimeFaces 6.0.RC3

**Comment by viaram** [comment]
Are there any news regarding this issue?

**Comment by orange-buffalo** [comment]
The problem is still reproducible on ['FileUpload - Single' demo page](http://www.primefaces.org/showcase/ui/file/upload/single.xhtml), running PrimeFaces-6.0.12 on Mojarra-2.2.8.

**Comment by melloware** [comment]
I think I can fix this.  I will submit a PR.

**Comment by tandraschko** [comment]
Thanks!

**Comment by GedMarc** [comment]
Can't seem to find an update - 

Is the upload using JQuery File Upload? Is Prime faces affected by the exploit? 
https://securityaffairs.co/wordpress/77245/hacking/jquery-file-upload-plugin-0day.html 

https://github.com/blueimp/jQuery-File-Upload/blob/master/SECURITY.md

**Comment by cnsgithub** [comment]
@GedMarc I cannot see how the exploit is related to this issue.  See this one also: https://github.com/primefaces/primefaces/issues/3269

Probably there are issues with jQuery-File-Upload's client validations, however this does not automatically imply that PrimeFaces is vulnerable to malware infection because that highly depends on the server-side implementation, i.e. the upload handler storing the uploaded files somewhere at the server. Of course, then it further depends on the webserver configuration and the stored upload location, if e.g. malicious PHP files may get executed or not...

**Comment by cnsgithub** [comment]
I looked at the PoC: it's just trying to exploit the PHP server-side sample implementation on misconfigured Apache httpd installations, quite boring.
