### ISSUE TITLE
Scrollable Tree

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#15]
Add scrolHeight attribute to tree, when defined tree should scroll if content height overflows scroll height.

**Comment by HipDragon** [comment]
Any time table for this feature to be added?

**Comment by yennor** [comment]
I've also stumbled over that one. RIght now you can halfway solve it like that:
```
<div height="XXX" or flex:1>
    <p:tree styleClass="treeFullHeight">
```
and
css:
```
.treeFullHeight  {
	height: 100%;
	display: flex;
	flex-direction: column;
	padding-right: 0 !important;
	padding-bottom: 0 !important;
}

```
Like that it uses 100% of the height of the parent container and adds scrollbars if necesarry.
If the parent container is a flexbox maybe even using flex instead of height in treeFullHeight would work. But I didn't try it out.
It doesn't look 100% perfect, but good enough :-).

**Comment by jepsar** [comment]
Easy to fix with style override:
```css
html body .ui-tree .ui-tree-container {
    max-height: 200px;
    overflow: scroll;
}
```
Not sure if it's worth adding a component property for.

**Comment by melloware** [comment]
Closing as good workaround has been provided.
