### ISSUE TITLE
Spinner with suffix does not change value.

### ISSUE THREAD

**Issue by MaxEl-W** [primefaces/primefaces#1561]
The method `PrimeFaces.widget.Spinner.prototype.updateValue` has a mistake in the condition:
`if (this.cfg.suffix && value.indexOf(this.cfg.suffix) === (value.length - this.cfg.suffix.length))`
If  the value does not have suffix and `value.length - this.cfg.suffix.length` is -1, than the value is NaN and it does not change.

ver. 5.2.12

Sorry for my English

**Comment by michael-las** [comment]
Affects 6.1-SNAPSHOT, too.

## Steps to reproduce

``` html
<p:spinner id="first" suffix=" €" min="0" />
<p:spinner id="second" prefix="$" min="0" />
```
1. Enter '5' (without suffix) into the input field of the first spinner.
2. Focus the second spinner.
3. The input field of the first spinner will read '0 €'.
4. Enter '5' (without suffix) into the input field of the second spinner.
5. Focus the first spinner
6. The input field of the second spinner will read '$5'.

At 3, the input field will read '0 €' only because the spinner was configured to have a minimum value of 0. If you don't do this, the input field will read '5' (instead of '5 €') but the value is unchanged. That is, if you press the increase button afterwards, the input field will read '1 €'.

**Comment by michael-las** [comment]
PR is here #1565
