### ISSUE TITLE
Problem Delta Theme and TabView

### ISSUE THREAD

**Issue by xKopax** [primefaces/primefaces#1598]
On PF6, the Delta theme breaks the tabview component, this might be seen on Primefaces Showcase:

http://www.primefaces.org/showcase/ui/panel/tabView.xhtml

Instead of showing the content below, it starts to show them on the right.

**Comment by tandraschko** [comment]
what do you mean? looks fine for me.

**Comment by xKopax** [comment]
I tried on Firefox and Chrome, both of them showed the same problem.

Look at the image below 

\/

![sem titulo](https://cloud.githubusercontent.com/assets/8135364/16781065/de2e0a6e-484f-11e6-8f28-495cddbb73be.png)

**Comment by tandraschko** [comment]
Could you please try to clear your cache? works fine in both browsers for me

**Comment by michael-las** [comment]
## Steps to reproduce
1. Clear cache
2. Open http://www.primefaces.org/showcase/ui/panel/tabView.xhtml
3. Switch to Delta theme
4. If necessary, make the window wide enough or use the browser's zoom to give more space to the components, so that you'll get the results above.
5. Switch to Afterdark theme
6. Clear cache
7. Reload the page
8. Switch to Delta theme

**Comment by xKopax** [comment]
Thank you =)
