### ISSUE TITLE
data table edit row

### ISSUE THREAD

**Issue by arunvc** [primefaces/primefaces#1824]
## 1) Environment

http://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml
## 4) Steps to reproduce
1. Edit the first row, 
2. Remove the value in year field, ie make it blank
3. Save

java.lang.IllegalArgumentException

**Comment by jxmai** [comment]
Confirmed. But this is not a valid **Primefaces core** issue ticket I guess (It should be redirected to the showcase).  One way to solve this issue is to put a validation annotation on the field.

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19364842/85d60da4-9155-11e6-8b86-dd4087b507a3.png)

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19364888/c0f60c86-9155-11e6-8b48-7dab78f6bbfb.png)

**Comment by tandraschko** [comment]
Works fine for me in the showcase.
