### ISSUE TITLE
Close dialog from DialogFramework causes NS_ERROR_NOT_AVAILABLE (Firefox)

### ISSUE THREAD

**Issue by sergi-mm** [primefaces/primefaces#186]
Hello,

When using Primefaces 5.1.16 (last version of 5.1 at the moment),  we close a Dialog created by DialogFramework using the method: 
`RequestContext.getCurrentInstance().closeDialog(null);  //Or passing any object`

Sometimes, it causes the following error on Firefox 37.0.2 (latest version): **NS_ERROR_NOT_AVAILABLE**. After this error, it is impossible to open the dialog again.

The strange think is that ith Google Chrome it works fine. Testing with a previous version of Primefaces, in this case 5.1.8, also works fine, so the error has been introduced in later versions.

Our application runs over Mojarra 2.2.7 and Tomcat 7.0.57.

Regards.

**Comment by cagataycivici** [comment]
Is there an easy way to replicate it?

**Comment by sergi-mm** [comment]
There is not an easy way to replicate it. The fact is that the error only occurs on some occasions and I cannot find the pattern to reproduce it. I will investigate a little more and I hope I could copy here some code.

**Comment by cagataycivici** [comment]
Thank you, let's reopen if you can provide case. I could not see it with some testing.

**Comment by javan-mehdi** [comment]
Hi, 

When I have an ajaxStatus tag in my dialog it happens. It took me almost a week to figure it out. I think it's easy to reproduce it as I did. However, I can send a sample project if it helps. I uses PrimeFaces 6.1 and FireFox 55.0.2 which is the latest version now.

Until this problem is resolved by PrimeFaces, there are two workarounds: Either remove the ajaxStatus tag or set ajax attribute of close button in the dialog to false.
