### ISSUE TITLE
Add CellEditInit feature to Datatable with editMode="cell"

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#1869]
An event is sent to server after clicking a cell and the input editor is filled with its content.

**Comment by kukel** [comment]
In my opnion changes like this are to big to be in a 'z' release (x.y.z) even though they are elite releases. The chance of changes like this breaking things in a complex component as the datatable are simple to high...

**Comment by firsthour** [comment]
They have to introduce these features sometime though, and while it's unfortunate these bugs happen, I'm not sure how else their release schedule would handle it.

**Comment by regenduft** [comment]
Nearly anywhere else, we have the possibility to decide, if we want lazy-loading or late loading via ajax from server, for example with the attribute like dynamic="true" in the p:overlayPanel.

Please add such a configuration possibility to the cell-editor, too. 

After this change, we cannot use the cell-editor anymore, because every click onto a data-table row now takes 1second to load the cell-editor contents from server.

Our lab cannot do its work anymore, everybody is complaining. So we had to rollback to 6.0.7 

If primefaces will not make this late-loading disable-able (for example with an attribute like dynamic="true" as its with the p:overlayPanel), then we need to delete all the cell-editors from our code and replace them with another solution, programmed by ourselves... before implementing this large change, we can never go ahead and update to a newer primefaces release.

Please add an attribute to disable this change and to load the cell-editor contents directly, without an additional ajax-request per cell.

**Comment by mertsincan** [comment]
Added CellEditMode attribute to Datatable; https://github.com/primefaces/primefaces/issues/1957
