### ISSUE TITLE
AutoComplete: allow label to be defined using facet

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#1903]
Currently the label of selected elements of _p:autoComplete_ can only be defined using _itemLabel_ attribute.

To give user more visual feedback it would be nice if the developers gain more control of the rendering using a facet. 

**Example**
In the drop down list we render a little + icon next to a property if it is not persistent and will be created by ORM on cascade save operation. This information is lost once being selected. For the user it is helpfull if he still sees the + in the input area. (I visualized it on the property _Lemon_ in the screenshot)

![Image of autocomplete with enhanced item label](http://fs5.directupload.net/images/161115/sh9vvupp.jpg)

**Comment by melloware** [comment]
I think this original ticket was just about changing the rendering of the label.  Yours is considerably more complex with multiple facets.  

I marked this for 14.0.0 because my plan was to investigate it and either implement it or decide to close it as `WontFix` is the implementation is not feasible.

**Comment by melloware** [comment]
I am looking now and I don't think this will be possible at all with the current implementation.  99% of the code is rendering using the JS code. So using server side facet's will do no good.   For example here is what happens when and item is added to the autocomplete.

https://github.com/primefaces/primefaces/blob/437e783900d0ff7dc92e20e227971bb881ce9815/primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js#L1170-L1200

I don't think without a major rewrite of this component using facets will be possible.

**Comment by melloware** [comment]
I am going to mark this WontFix.

**Comment by melloware** [comment]
Deeper explanation why this is a WontFix here: https://github.com/primefaces/primefaces/issues/10411#issuecomment-1656756740
