### ISSUE TITLE
primefaces Input fields on form holds previous value after their value is cleared/set blank and form is submitted

### ISSUE THREAD

**Issue by ppandey01** [primefaces/primefaces#1942]
# Problem Statement

If there is already validation error on submitted form then in this situation, if user tries to clear/set blank value for any other mandatory prime-faces input field and resubmit the form then this Input fields on form holds previous value.

This Prime-faces behavior is different then pure JSF behavior where value from model is always shown in input field when input field is cleared/set blank and form is submitted. 

## Steps to reproduce using sample code:
1. Load the page so that there is no validation error on page. Page should contain 4 input fields.
2. Choose "Primefaces Input Field1" and clear it's value. 
3. Submit the form
4. There is no value in this input field. Validation error is displayed "Primefaces Input Field1 may not be empty". 
5. Choose "Primefaces Input Field2" and clear it's value. 
6. Submit the form

## Actual behaviour
Previous value is shown on "Primefaces Input Field2". However Validation error is displayed "Primefaces Input Field2 may not be empty". 

## Expected behaviour
Expected behavior should be similar as mentioned in step # 4. i.e. There should be no value presents in input field "Primefaces Input Field2". Validation error should be displayed "Primefaces Input Field2 may not be empty". 

## Environment

Primefaces 5.3.14 / JSF 2.2.12.redhat-1
Server: JBoss EAP 7

## Sample Code XHTML + Model Bean

[validation.zip](https://github.com/primefaces/primefaces/files/625230/validation.zip)

**Comment by kukel** [comment]
http://www.primefaces.org/showcase/ui/misc/resetInput.xhtml

**Comment by dmaidaniuk** [comment]
Hi @kukel,
Seems you understand wrongly target of given bug. Here described scenario when on second and other attempts for sending form with failed validation previous values will be restored instead of leaving mandatory fields as is (empty) as expected.

**Comment by jxmai** [comment]
I tried to run the code using **primefaces 6.0.9**, but I cannot reproduce the bug.

Clear value3 and submit:

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/20840214/1575afb4-b875-11e6-88fe-332e12e97e3a.png)


Clear value4 and submit:

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/20840228/223ae278-b875-11e6-871f-223262038b00.png)

**Comment by dmaidaniuk** [comment]
Hi @jxmai,

In bug description clearly said that bug reproduced for version Primefaces 5.3.14.

**Comment by jxmai** [comment]
I saw that, but if it has been fixed on the latest version such as v6.0.9. This ticket will be no longer valid. We always need to try the latest version first.

**Comment by ppandey01** [comment]
Thanks @jxmai. I will test it on latest primefaces version and then will provide my feedback.

**Comment by jxmai** [comment]
@ppandey01 I looked at your code again, and I found out an issue:

In your java code:

```java
import javax.enterprise.context.RequestScoped;
import javax.faces.bean.ManagedBean;
```

**You are mixing JSF ManagedBean with CDI's RequestScoped. This is prohibited.**

Please use the following imports if  you don't need to use CDI

```java
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
```

Plus I don't see any reason to use requestScoped in this case. ViewScoped might be more suitable.

I guess the issue will be solved after you fix the import

**Comment by jxmai** [comment]
The sample code has incorrect implementation and there is no update for months. Suggest to close this issue since it is working fine on 6.0 +.

> I tried to run the code using primefaces 6.0.9, but I cannot reproduce the bug.

**Comment by alexey-anufriev** [comment]
Hi @jxmai,

For me it is still reproducible on 6.1.3.
Please let me know if you need a reproducer or you can check the problem yourself on this particular version.

Regards,
Alex

**Comment by jxmai** [comment]
@ice-pro Please provide a complete reproducer if you have a different set of code since I have already tested the sample code provided in this issue previously. But before doing that, please try to build the latest snapshot to see if the issue has been resolved by the latest code (https://github.com/primefaces/primefaces/wiki/Building-From-Source).

**Comment by alexey-anufriev** [comment]
@jxmai, I have tried to use the reproducer attached to the very first message. And I've used latest SNAPSHOT version. It is still reproducible for me.

**Comment by jxmai** [comment]
@ice-pro OK, I have tried to test again to make this clear. (Tested against on PF Up to https://github.com/primefaces/primefaces/commit/628da77239cb85ac6b685dc09e05817f6ad1c5d7)

I slightly modified the sample code since it has incorrect import (mixing CDI and managed bean)

Xhtml

```xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html lang="en"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      >
	<h:head>
		<title>Validation</title>
	</h:head>
	<h:body>
		<h2>Validation problem showcase</h2>
	      <h:form id="validationForm">
	      
	      	<p:panelGrid id="generalDataGrid" columns="3">
		  		
		  		<p:outputLabel value="JSF Input Field1" for="jsfField1Input" />
				<h:inputText id="jsfField1Input" value="#{testModel.jsfField1}" />
				<p:message for="jsfField1Input" />
				        
		  		<p:outputLabel value="JSF Input Field2" for="jsfField2Input" />
				<h:inputText id="jsfField2Input" value="#{testModel.jsfField2}" />
				<p:message for="jsfField2Input" />
	
		  		<p:outputLabel value="Primefaces Input Field1" for="primefacesField1Input" />
				<p:inputText id="primefacesField1Input" value="#{testModel.primefacesField1}" />
				<p:message for="primefacesField1Input" />
	
		  		<p:outputLabel value="Primefaces Input Field2" for="primefacesField2Input" />
				<p:inputText id="primefacesField2Input" value="#{testModel.primefacesField2}" />
				<p:message for="primefacesField2Input" />
				
	      	</p:panelGrid>
	
	          <p:panelGrid id="masterDataGrid" styleClass="crxFormGrid" columns="2">
	            <f:facet name="footer">
	              <p:row>
	                <p:column colspan="2">
	
	                  <p:commandButton id="updateMasterDataButton"
	                                   value="Submit"
	                                   action="#{testModel.save()}"
	                                   update="@form"/>
	
	                  <p:commandButton id="discardChangesButton"
	                                   process="@this"
	                                   value="Discard Changes"
	                                   action="#{testModel.discard()}"
	                                   update="@form">
	                   <p:resetInput target="validationForm"/>
	                  </p:commandButton>
	
	                </p:column>
	              </p:row>
	            </f:facet>
	          </p:panelGrid>			        
	      </h:form>  
	</h:body>
</html>

```

Model

```java
package test;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.hibernate.validator.constraints.NotEmpty;

@ManagedBean
@ViewScoped
public class TestModel implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -714444765439074288L;

    @NotEmpty
    private String jsfField1;

    @NotEmpty
    private String jsfField2;

    @NotEmpty
    private String primefacesField1;

    @NotEmpty
    private String primefacesField2;

    @PostConstruct
    private void init() { // NOSONAR method is used
        this.jsfField1 = "value1";
        this.jsfField2 = "value2";
        this.primefacesField1 = "value3";
        this.primefacesField2 = "value4";
    }

    public void save() {
    }

    public void discard() {
        this.jsfField1 = "value1";
        this.jsfField2 = "value2";
        this.primefacesField1 = "value3";
        this.primefacesField2 = "value4";
    }

    public String getJsfField1() {
        return jsfField1;
    }

    public void setJsfField1(String jsfField1) {
        this.jsfField1 = jsfField1;
    }

    public String getJsfField2() {
        return jsfField2;
    }

    public void setJsfField2(String jsfField2) {
        this.jsfField2 = jsfField2;
    }

    public String getPrimefacesField1() {
        return primefacesField1;
    }

    public void setPrimefacesField1(String primefacesField1) {
        this.primefacesField1 = primefacesField1;
    }

    public String getPrimefacesField2() {
        return primefacesField2;
    }

    public void setPrimefacesField2(String primefacesField2) {
        this.primefacesField2 = primefacesField2;
    }

}

```


---


> 1. Load the page so that there is no validation error on page. Page should contain 4 input fields.

![image](https://user-images.githubusercontent.com/10467831/28534007-bc17b81a-7064-11e7-9cae-8494c13428b6.png)


> 2. Choose "Primefaces Input Field1" and clear it's value.

![image](https://user-images.githubusercontent.com/10467831/28534025-d2605348-7064-11e7-89c6-29cd35887eae.png)


> 3. Submit the form

![image](https://user-images.githubusercontent.com/10467831/28534038-e0aa4404-7064-11e7-8eb0-0fa0903b515a.png)



> 4. There is no value in this input field. Validation error is displayed "Primefaces Input Field1 may not be empty".

This part is fine

> 5. Choose "Primefaces Input Field2" and clear it's value.

![image](https://user-images.githubusercontent.com/10467831/28534070-02cdfb66-7065-11e7-8325-c4cada49cc71.png)

> 6. Submit the form

![image](https://user-images.githubusercontent.com/10467831/28534075-106359d8-7065-11e7-9679-dc06748a1f8e.png)


> Previous value is shown on "Primefaces Input Field2". However Validation error is displayed "Primefaces Input Field2 may not be empty".

This is not what I saw

> Expected behavior should be similar as mentioned in step # 4. i.e. There should be no value presents in input field "Primefaces Input Field2". Validation error should be displayed "Primefaces Input Field2 may not be empty".

This is what I saw

**Comment by alexey-anufriev** [comment]
> I slightly modified the sample code since it has incorrect import (mixing CDI and managed bean)

Maybe this could be the reason for me, I will try it as well.

**Comment by jxmai** [comment]
It could be the cause as I mentioned in https://github.com/primefaces/primefaces/issues/1942#issuecomment-264506875. Please take a look and see if it works.

**Comment by alexey-anufriev** [comment]
@jxmai, I did all the adjustments you have recommended and unfortunately, it is still reproducible for me:
![image](https://user-images.githubusercontent.com/932500/28722106-cfd59a42-73b2-11e7-99f8-2fcf88d3d439.png)

I have Primefaces v.6.1.3

**Comment by jxmai** [comment]
@ice-pro  Do you have a small runnable project that can be run directly ? As there is no way to tell what went wrong since the same code can behave differently.

**Comment by jxmai** [comment]
@ice-pro Hi, I have created a sample for you, so you can compare what went wrong with your code.

[primefaces-test.tar.gz](https://github.com/primefaces/primefaces/files/1183788/primefaces-test.tar.gz)

In order to run the project.

1. unzip the file, use terminal to go into the unzipped directory and type `mvn clean jetty:run`

2. open browser and go to the following url: http://0.0.0.0:8080/primefaces-test/

![snapshot1](https://user-images.githubusercontent.com/10467831/28728698-35cfe2c2-738f-11e7-942c-8e81fb74b811.png)

**Comment by alexey-anufriev** [comment]
@jxmai, thank you for help. I will provide a feedback soon. But don't you think environment can cause some differences? I mean I run the app within JBoss EAP. And it has some JSF-related libs provided.

**Comment by jxmai** [comment]
In my opinion, it is unlikely that the bug is causing by environment differences. I haven't tried to use Jboss  but the code above can run on Tomcat without issues. But in the programming world, never say never since bugs can arise from somewhere unexpected :smile:  I suggest you to 

1. Try to run the code I provided to see the result

2. Copy the exact same code from the sample to run in your environment

3. Compare and check the differences to debug

**Comment by alexey-anufriev** [comment]
Hi @jxmai,
I am sorry for the delay.

I have tried to do as you have advised me. And the result is very strange.
It works under Tomcat but it doesn't under JBoss EAP.

How can I debug this?

**Comment by dmaidaniuk** [comment]
Hi @ice-pro,

I suppose you are using JBoss EAP 7. If so than this enterprise container use Undertow as application server, not Tomcat anymore. So this issue could be related to JBoss EAP 7 JSF spec integration.

**Comment by jxmai** [comment]
@ice-pro I agree with @dmaidaniuk so this could be a web container's bug. I don't deal with Jboss often so I might not be able to provide useful info, so I just try my best.

Firstly, I know Jboss has been renamed to wildfly for some time (https://en.wikipedia.org/wiki/WildFly), so the easiest way before stepping into any implementation might be trying to upgrade wildfly to the latest version if you are still using Jboss 6-7.

If this issue is still not solved, here is Wildfly's issue tracker: https://issues.jboss.org/projects/WFLY/issues/WFLY-9295?filter=allopenissues

**Comment by dmaidaniuk** [comment]
@ice-pro,

From my side I can recommend next articles for JSF 2 debugging entry point:

- [Debugging JSF Life Cycle - what exactly happens in each phase](https://stackoverflow.com/a/21928634/2881869)
- [How JSF Works and how to Debug it - is Polyglot an Alternative? ](https://dzone.com/articles/how-jsf-works-and-how-debug-it)
