### ISSUE TITLE
p:autoComplete displays unconverted text when validation fails

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#20]
When having a `p:autoComplete` with a validator and the validation fails, the "raw" (unconverted) value of the invalid selection is displayed instead of the previously selected valid value.

Suggestion:
In `AutoCompleteRenderer#encodeInput` replace

```
            if(ac.isValid()) {
                requestMap.put(var, ac.getValue());
                itemLabel = ac.getItemLabel();
            }
            else {
                Object submittedValue = ac.getSubmittedValue();
                itemLabel = (submittedValue == null) ? null : String.valueOf(submittedValue);

                if(itemLabel == null && ac.getValue() != null) {
                    requestMap.put(var, ac.getValue());
                    itemLabel = ac.getItemLabel();
                }
            }
```

with 

```
            if(ac.isValid()) {
                requestMap.put(var, ac.getValue());
                itemLabel = ac.getItemLabel();
            }
            else {
                // Display label of previously set value if validation fails
                itemLabel = ac.getItemLabel();

                if(itemLabel == null && ac.getValue() != null) {
                    requestMap.put(var, ac.getValue());
                    itemLabel = ac.getItemLabel();
                }
            }
```

**Comment by fanste** [comment]
I can confirm this bug. As soon as the validation fails you will get the submittedValue in the autocomplete inputfield instead of the label of the submittedValue.

**Comment by dariorios** [comment]
Correct. This problem is confirm when a validator fails and the autocomplete renders the value of the id instead of the object.

**Comment by Selaron** [comment]
For reproduction please cherry-pick my commits in https://github.com/Selaron/showcase/tree/reproduce:
https://github.com/primefaces/showcase/commit/95cfc49a866c580cdd1e1ee98e65e1a3dcdf83bd
https://github.com/primefaces/showcase/commit/7cc470ca9c300f51994323793895bb1fde8deae6
And invoke /ui/autoComplete.xhtml 

All the bottom five components expose internal POJO String representation returned from converter getAsString(..). I share the opinion that users want to see the value(s) they have selected instead of technical encoding or a blank field.

One might argue why an autoComplete should ever suggest invalid values. On the other hand, I'd like to explicitly tell the user why an item is currently not selectable instead of just hiding it from suggestions, leaving the user alone with uncertainty "umh....yesterday there was an item X ... where is it gone?".

I also tried out the lines of code suggested by @jfgeiger, but this didn't change anything for me in case of my reproducer mentioned above.

This issue seemes related to an old issue sadly marked as "wontFix":
https://code.google.com/p/primefaces/issues/detail?id=3491

**Comment by tandraschko** [comment]
Sorry for the late response.
