### ISSUE TITLE
Subtable should not be deprecated

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2269]
Subtable should not be deprecated since row grouping does not provides same functionality as subTable does.

We have already grouped data in bean like following simple example. I don't know how to realize it without subtable? So subtable should not be deprecated.

  	Map<String, List<String>> data;

  	<p:dataTable var="varType" value="#{bean.data.keySet()}">
  	  	<p:subTable var="varValue" value="#{bean.data[varType]}">
		  	<f:facet name="header">
			  	<h:outputText value="#{varType}"/>
		  	</f:facet>
		  	<p:column>
			  	<h:outputText value="#{varValue}"/>
		  	</p:column>
	   	</p:subTable>
  	</p:dataTable>

@Fanste also commented about it in this issue: 

https://github.com/primefaces/primefaces/issues/1950

**Comment by HipDragon** [comment]
I agree that this should be revisited and not be deprecated.

**Comment by Dragonsol** [comment]
Subtable is very useful, especially when you have a list of data entity object that contains a list other objects - i.e. a list of people where each has a list of children.

To implement something like that with row grouping, I will need to create a flat list with duplication (of parents) to be able to group on the parent object, which is a waste of bandwidth, memory and computing resources.

**Comment by hfluz** [comment]
I agree. The result might be the same for the user, but depending on how the data is queried it's easier to use subtable instead of row grouping.

**Comment by eversnarf** [comment]
I fully agree. subtable is quite useful in some scenarios, as already mentioned. With subtables, you can nicely work on two separate levels of aggregation (iterate parents, then iterate their children). There are many scenarios where data comes in this flavour, rather than a flat list of children.
Also, as far as I know, to use row grouping, you need to specify a `sortBy` expression. Consider huge lists that come pre-ordered, you don't want to sort them again just to be able to perform row grouping.

**Comment by mmariotti** [comment]
Totally agree. 
You should, instead, enhance subTables to be used more easily for grouping.

In example, using `<p:column>`s alongside `<p:subTable>`:

```
<p:dataTable var="brand" value="#{bean.brands}">
	<p:column headerText="brand">
		<h:outputText value="#{brand.name}" />
	</p:columnGroup>

	<p:subTable var="car" value="#{brand.cars}">
		<p:column headerText="year">
			<h:outputText value="#{car.year}" />
		</p:columnGroup>
		<p:column headerText="color">
			<h:outputText value="#{car.color}" />
		</p:columnGroup>
		<p:column headerText="id">
			<h:outputText value="#{car.id}" />
		</p:columnGroup>
	</p:subTable>
</p:dataTable>
```

 should be used to render the same [row-grouping - rowspan](https://www.primefaces.org/showcase/ui/data/datatable/rowGroup.xhtml) of the showcase example:
![example](https://user-images.githubusercontent.com/7235289/36391290-387821ce-15a6-11e8-9f9d-131ec874f522.PNG)

which is impossible to obtain unless flattening the box objects and using `groupRow`

**Comment by jbgomond** [comment]
Is there a solution to that problem in PF 6.2 ? https://github.com/primefaces/primefaces/issues/391

I'm lost :(
Are subtables deprecated ? If so, with what can I replace it ? (columnGroup has not the same goal ...).

I really need to use rowspan on a subtable and it doesn't work (it used to work with richfaces) :(

Thanks !

**Comment by jpangamarca** [comment]
I agree with @Dragonsol  and @f-r-a-n-s , there are valid use cases for subtables and creating flat lists is not an option in many cases.

**Comment by pfdeveloper** [comment]
thats mean its still deprecated????

**Comment by pfdeveloper** [comment]
its work fine on pf 6.2 can i still using it???
deprecated mean that i cant use it any more or it doesnt upgrade any more???
....thank you very much

**Comment by eduarddrenth** [comment]
subtables is a must have, it doesn't seem to work in 7.0.7. What is the status?

**Comment by melloware** [comment]
@eduarddrenth It has not been removed yet so it still should be in 7.0.7.  What error are you getting?

It is still available in 7.1 see here: https://www.primefaces.org/showcase/ui/data/datatable/subTable.xhtml

**Comment by eduarddrenth** [comment]
I saw, I tried (a lot of things..), no error, just no data

**Comment by melloware** [comment]
it could be another bug introduce but at least I can assure you the SubTable has not been removed yet.  Might want to look through the 7.01-7.0.7 release notes for any Datatable changes that might have broken it.

**Comment by eduarddrenth** [comment]
Thanks, I will

**Comment by eduarddrenth** [comment]
In those releases datatable was touched. I have a not so nice work around (datatable in a cell). My use-case that isn't working:

- datatable with lazy loading
- for each row I want to show a subtable

When I use columnGroup type="header" (or no type) and subtable I only see subtable data, no row data. I cannot spend time to file a bug.

**Comment by melloware** [comment]
Subtable is still in PF 8.0 and I don't see any reason to remove it for 9.0 so closing this ticket for now.

**Comment by Rapster** [comment]
We should then remove log "SubTable has been deprecated, use row grouping instead" then no?

**Comment by Rapster** [comment]
We should then remove log "SubTable has been deprecated, use row grouping instead" then no? Also, if you all think subTable is not deprecated then showcase should be updated accordingly with a better example, because as far as I can tell (and I'm not using subTables) subTable does not seem to be bring a lot to the table as it look like a row grouping/column grouping/summary row example 😅

**Comment by melloware** [comment]
Or @Rapster we can reopen this ticket if you think during your refactoring removing it makes the Datatable more maintainable and its able to accomplish this with other ways?

**Comment by Rapster** [comment]
Nah basically I'm just asking to fellow users to propose a better example in showcase 😉

**Comment by martin654** [comment]
Hi. 
Here is an example:

Imagine a paginated backend service where you have **list of lists.** For example a contract list and for each contract you have a list of documents. Pagination is done on the "outer contract list" (so the height of the table can be different for each page). 

This cannot be done with row grouping, because you would have to change the backend service (not possible) to serve paginated flat list of documents that could be grouped. And still it would be different, because you could't achieve having "5 contracts per page and its documents" without loading wholde dataset from BE (thousands of items = impossible).

From my perspective SubTable feature is irreplacable with other features.

![obrazek](https://user-images.githubusercontent.com/22746146/104896437-66773200-5977-11eb-86d4-1fe9f0c2b728.png)

Best regards

**Comment by Rapster** [comment]
I strongly suggest you submit a PR on showcase then, but you mentionned your model is not flat, could `p:treeTable` be a solution here? Ah but you're lazy loading stuff also... don't know how well `p:treeTable` handle that stuff, last time I tried I can't say it worked perfectly :/

**Comment by martin654** [comment]
Hi, 
yes, it is lazy loaded using backend service pagination. And AFAIK i don't think that p:treeTable supports this. And the expand/collapse feature is not wanted in this case (at least it would have to be expanded initially). 

I reported this as a PRO ticket. 

In my opinion many PRO users are stuck on previous PF versions so they didn't notice the deprecation yet?

Thanks

**Comment by tandraschko** [comment]
it was deprecated by a statement of cagatay in the past, but not official in the docs AFAIR.
If there is a usecase and PrimeTek is ok with it, we should not deprecate it.
Nevertheless, we wont remove it for 10.0 anyway, so you are not stuck on older versions for now.
