### ISSUE TITLE
SelectOneMenu: onkeyup and onkeydown not effective

### ISSUE THREAD

**Issue by Selaron** [primefaces/primefaces#2331]
## 1) Environment
- PrimeFaces version:
6.0, 6.1

- Does it work on the newest released PrimeFaces version?
no

- Does it work on the newest sources in GitHub?
no

- Application server + version:
Apache Tomcat 8.5.14

## 2) Expected behavior
When selectOneMenu component has focus, configured onkeydown/onkeyup events should trigger when pressing down/releasing a key.
I'd expect these events to be triggered at least for editable selectOneMenus when typing some text. (This way, I'd be able to use it as dataTable filter component allowing custom input and filtering while typing.)
...

## 3) Actual behavior
Events ain't triggered.
..

## 4) Steps to reproduce
Add a selectOneMenu component to your view with javascript filled onkeyup and onkeydown attributes.
In browser, focus that component and press (the one and only) any key. Your expected javascripts do not get executed. In example below, you will only see alert message 'change' popup when changing by mous or on blur (for editable component after you typed something).

## 5) Sample XHTML
Only event fired properly is onchange event:
```
<p:selectOneMenu editable="false" onkeydown="alert('down')"
	onkeyup="alert('up')" onchange="alert('change')">
	<f:selectItem itemLabel="1" itemValue="1"/>
	<f:selectItem itemLabel="2" itemValue="2"/>
</p:selectOneMenu>

<p:selectOneMenu editable="true" onkeydown="alert('down')"
	onkeyup="alert('up')" onchange="alert('change')">
	<f:selectItem itemLabel="a" itemValue="a"/>
	<f:selectItem itemLabel="b" itemValue="b"/>
</p:selectOneMenu>
```

This issue has already been discussed in some forum threads:
https://forum.primefaces.org/viewtopic.php?f=3&t=42733
https://forum.primefaces.org/viewtopic.php?f=3&t=41793
https://forum.primefaces.org/viewtopic.php?f=3&t=35037

**Comment by kukel** [comment]
Did you try using these events in a `p:ajax` or in a `pe:javascript` in case you do not actually need to call something serverside

**Comment by Selaron** [comment]
I now tested it with
<p:ajax event="keydown" ../>
but this does not fire either, while event="change" works es expected..

**Comment by melloware** [comment]
From looking at the code in forms.js for selectOneMenu I don't think the callbacks for keyup and keydown are actually hooked up.

**Comment by Selaron** [comment]
I also guess that SelectOneMenuRenderer is missing some lines of code to actually render "onkeyup" and "onkeydown" element attributes and DOM behavior events.

For **editable** SelectOneMenu, this is my quick & dirty workaround:
```

public final class PfSelectOneMenuRenderer extends SelectOneMenuRenderer {

	@Override
	protected void encodeLabel(final FacesContext context, final SelectOneMenu menu, final List<SelectItem> selectItems)
			throws IOException {
		/*
		 * copy & pasted from:
		 * org.primefaces.component.selectonemenu.SelectOneMenuRenderer.
		 * encodeLabel(FacesContext, SelectOneMenu, List<SelectItem>)
		 */
		@SuppressWarnings("resource")
		final ResponseWriter writer = context.getResponseWriter();
		final String valueToRender = ComponentUtils.getValueToRender(context, menu);
		if (menu.isEditable()) {
			writer.startElement("input", null);
		      .....

			if (menu.getOnkeydown() != null) {
				writer.writeAttribute("onkeydown", menu.getOnkeydown(), null);
			}
			if (menu.getOnkeyup() != null) {
				writer.writeAttribute("onkeyup", menu.getOnkeyup(), null);
			}
		    this.renderDomEvent(context, menu, "onkeyup", "keyup", "keyup", null);
			
                      .....

			writer.endElement("input");
		} else {
			writer.startElement("label", null);
			writer.writeAttribute("id", menu.getClientId(context) + "_label", null);
			writer.writeAttribute("class", SelectOneMenu.LABEL_CLASS, null);
			if (menu.getPlaceholder() != null) {
				writer.writeAttribute("data-placeholder", menu.getPlaceholder(), null);
			}
			writer.write("&nbsp;");
			writer.endElement("label");
		}
	}
```

**Comment by iZorkon** [comment]
Hi everyone!

There is any news on this issue?

I'm asking this because right now I'm trying to implement keyboard arrow navigation on a datatable. For that matter I'm using the onkeydown event in each component of that table. Then it calls a JavaScript function that will evaluate if the pressed key is an arrow or not and will focus() or click() accordingly.

Everything was working fine until one of that components is a editable <p:selectOneMenu, after clicking to edit this component, the events onkeyup/down aren't triggered, this is pretty much what was reported on this issue. 

Tried with onkeydown"alert('I feel it...')" > didn't work...  however the onchange event works.
Tried with the ajax event as well: <p:ajax event="keydown" oncomplete="alert('Ok I feel it...')" > didn't work as well.

With this said there's 2 things that I'm not understanding:
1. On the PrimeFaces documentation (https://www.primefaces.org/docs/guide/primefaces_user_guide_6_1.pdf), on the page 463 it says that the _onkeyup/down_ are SelectOneMenu's attributes.1. 

2. If I change from <p:selectOneMenu to <h:selectOneMenu, both events start to get triggered... but on the other hand I'll stop to be able to edit or search/filter from the list results.

Any solution/sugestion?

Thanks in advance!

Kind regards.

**Comment by melloware** [comment]
@Selaron @iZorkon can you review the PR I just submitted.  I used @Selaron and it works great and tested it.

**Comment by cidylong** [comment]
@melloware , is there possible to modify a particular js file to enable keyup event please!! I'm using Primefaces 6.1

**Comment by melloware** [comment]
@cidylong Are you asking if you can hack this functionality into 6.1 with a JS override?  Ithink the simple answer is not easily, but the longer answer is you can probably definitely do it with Jquery by finding the input box by its id or widgetvar and adding the .on("keyup") hook to it.
