### ISSUE TITLE
Escaping "/" character problem on Watermark

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2341]
Reported By PRO User;
> I have added watermark component to input:
<p:inputText id="name" value="#{beanValidationView.name}" label="Name" styleClass="ignoredInput"/>
<p:watermark for="name" value="dd/mm/aaaa" id="watermark" />
but value ("dd/mm/aaaa") is showing wrong: "dd\/mm\/aaaa".
...

**Comment by Lanzjess** [comment]
Since PrimeFaces 6.0.19 onwards including 6.0.20 and 6.1.x(6.1.1 and 6.1.2) our code for column filter watermark is not working as below:

`<h:form id="myForm">
  <p:dataTable id="myTable">
<p:column id="column2" filterBy="column2">
      <f:facet name="header">
      <p:watermark for="@(#myForm\\:myTable\\:column2\\:filter)"
      value="Watermark 2" />
      <h:outputText value="Column2" />
      </f:facet>
    </p:column>
</p:dataTable>
</h:form>`

Can you please help us how to make the watermark on  the column filter of the table work?
I also tried the code below but still not working
`<p:watermark for="*[@id=form\\:singleDT\\:userName\\:filter]" 
                                             value="#{bundle.userName}"/>`

**Comment by mertsincan** [comment]
Hi @Lanzjess,

Could you please create a new Github issue for your issue?
