### ISSUE TITLE
p:dataExporter PDF export does not show Euro (€) sign

### ISSUE THREAD

**Issue by rho66** [primefaces/primefaces#2363]
# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: WildFly-10.0.0.Final
- Affected browsers: Firefox, Chrome, IE

## 2) Expected behavior

PDF dataExporter should export Euro sign correctly with UTF-8 encoding

## 3) Actual behavior

PDF dataExporter does not show Euro sign in exported PDF file

## 4) Steps to reproduce

Create a p:dataTable with column headers containing an Euro sign and a PDF dataexporter with encoding type UTF-8

## 5) Sample XHTML

<p:dataTable id="data" paginatorTemplate="{Exporters}" value="#{dataExporterView.cars}">
  <f:facet name="{Exporters}">
    <p:commandButton title="PDF Export" ajax="false" icon="fa fa-file-pdf-o">
      <p:dataExporter type="pdf" target="data" fileName="export.pdf" encoding="UTF-8"/>
    </p:commandButton>
</p:dataTable>

## 6) Sample bean

see https://www.primefaces.org/showcase/ui/data/dataexporter/basic.xhtml

**Comment by melloware** [comment]
@rho66 Have you debugged this at all to see where its not being encoded to UTF-8 in the code?

**Comment by rho66** [comment]
I debugged this and in `PDFExporter.addColumnFacets()` the `textValue` from `col.getHeaderText()` still contains the Euro (€) sign in Intellij Debugger. This textValue is then put into the PDF document with `pdfTable.addCell(new Paragraph(textValue, this.facetFont)`.  I think the problem is probaly in the outdated iText Version which is marked deprecated since 2012 (see [http://www.lowagie.com/iText/](http://www.lowagie.com/iText/)). In my application I am also generating PDF documents using dependencies for com.itextpdf version 7.0.1 and these PDF documents contain the Euro sign correctly!

**Comment by NicolaIsotta** [comment]
You can try [OpenPDF](https://github.com/LibrePDF/OpenPDF), it'a fork of LGPL iText.
Also, the JasperReports guys are mantaining a [fork](http://jasperreports.sourceforge.net/maven2/com/lowagie/itext/) of iText 2.1.7.

**Comment by melloware** [comment]
I wonder if PF is staying on that old version of iText to a) maintain compatibility with Java 5 or b) because of the licensing of the old version vs the newer ones? 

From itext: "After release 2.1.7, iText moved from the MPLicense to the AGPLicense. The groupId changed from com.lowagie to com.itextpdf and the artifactId from itext to itextpdf.  See htttp://itextpdf.com/functionalitycomparison for more information."

**Comment by tandraschko** [comment]
exactly, we can't use the newer versions.
But we maybe we should create a enhancement, so that users can easily switch the generation mechanism via a factory or something. So the user can create a new exporter-type for a new itext version.
But as i said, we likely can't develop a support for a newer itext version directly in PF.

**Comment by melloware** [comment]
@tandraschko Do you mind if I investigate switching from iText 2.1.7 to this friendly fork of it https://github.com/LibrePDF/OpenPDF as mentioned by @NicolaIsotta ???  This may be the best answer as it has a friendly license and is still being maintained and fixed unlike the frozen iText version?

**Comment by tandraschko** [comment]
No idea.
The project doesn't look very active either.

**Comment by tandraschko** [comment]
Also not sure if LPGL or MPL fits our Apache license.

**Comment by rho66** [comment]
Can someone confirm my guess, that iText is the reason for that behavior?

**Comment by melloware** [comment]
@rho66 It looks like you have debugged already. if it still has the symbol when the iText add cell code is called my guess is it is a bug in iText.

**Comment by melloware** [comment]
@rho66 here is a post that talks about the font being used by iText needs to support your character.  REad bruno's response in this stack overflow..   http://stackoverflow.com/questions/21254628/set-encoding-when-converting-text-file-to-pdf-using-itext

**Comment by kukel** [comment]
@melloware is correct. That post contains all relevant information (try exporting some 'indian' texts ;-))

**Comment by rho66** [comment]
Does that mean I have to modify the released primefaces version and build my own one?!

**Comment by melloware** [comment]
No I would think that means the PDFExporter needs some way for you to specify which font to use. The Primefaces Exttensions exporter has a way for you to declare what font to use.  I have never used it myself but I think that is the gist...

https://www.primefaces.org/showcase-ext/sections/exporter/customizedFormatTable.jsf

**Comment by tandraschko** [comment]
@melloware 
Would you like to take care of this?
Maybe someone should also analyze whats better in PFE and check if we can port it to PF.

**Comment by melloware** [comment]
I can take a look at this one.  I know the PFE code is way more complex than the PF code as its doing way more and its a little confusing to follow.  I will see what I can do though.

**Comment by melloware** [comment]
OK after researching this is a bigger change than I thought.   First some things..

1. PF already allows you to customize the font size, style, and color in this demo but NOT the font family.  https://www.primefaces.org/showcase/ui/data/dataexporter/customizedDocuments.xhtml   

2. It looks like the Font is hard coded to TIMES here on this line:  https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/export/PDFExporter.java#L169

3. We would have to add Font Family to the PDFOptions class.  https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/export/PDFOptions.java

4. Then using that PDFFontOptions if the FontFamily is set instead of using the FontFactory.TIMES we would have to construct the font using  iText APIs for properly getting a Font.

It can be done I think.  I would love @sudheerj to weigh in on this?

**Comment by kukel** [comment]
I'll see if I can open up my FlyingSaucer based html to pdf renderer. It also renders images in tables and many other css3 things...

**Comment by melloware** [comment]
Looks like this is a way old enhancement request:  https://github.com/primefaces/primefaces/issues/146

**Comment by sudheerj** [comment]
Hi Guys,
I will analyze and work on the issue after 2 weeks.Thanks.

Regards,
Sudheer

**Comment by melloware** [comment]
This PR switches to OpenPDF . https://github.com/primefaces/primefaces/pull/3203

**Comment by cnsgithub** [comment]
https://pdfbox.apache.org/  Could also be an alternative. if you want a different licence. This one has Apache 2.0 licence

I also think you should remove the dependency to com.lowagie as the author itself does not recommend to use it: https://www.lowagie.com/iText

**Comment by Mararsh** [comment]
Hi, 
My codes are hit by this issue. Thanks detailed analysis from melloware! My project is in Chinese, and the PDF exporter shows messed texts since it is in hard code of "FontFactory.TIMES".
[PDFExporter.java
](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/export/PDFExporter.java)

```
        this.cellFont = FontFactory.getFont(FontFactory.TIMES, encoding);
        this.facetFont = FontFactory.getFont(FontFactory.TIMES, encoding, Font.DEFAULTSIZE, Font.BOLD);
```

I have to customized PDF exporter for each table just to make it using Chinese Font:
`
 ChineseFont = new Font(BaseFont.createFont("STSONG.TTF", BaseFont.IDENTITY_H, BaseFont.EMBEDDED));
`

Is it possible to add  Font Family to the PDFOptions, as melloware mentioned? If it is true, efforts would be saved for programmers and they would not search internet and check source codes of PF.

Best Regards.
Mara

**Comment by Mararsh** [comment]
Maybe it is better to open a issue especailly about messed texts by PDF exporter for Chinese developers and users~ I will open it since the phenomena is different.

**Comment by melloware** [comment]
@Mararsh I think the correct solution is to allow the Font to be defined on the component and only defaulted to FontFactory.TIMES if no font is provided.  Sudheer from PF said he would look into this but it looks like he never implemented it.

**Comment by melloware** [comment]
PR will allow you to set the Font to any installed font you have for example to set to "Courier"...

```java
        PDFOptions pdfOpt = new PDFOptions();
        pdfOpt.setFontName("Courier");
        pdfOpt.setFacetBgColor("#F88017");
        pdfOpt.setFacetFontColor("#0000ff");
        pdfOpt.setFacetFontStyle("BOLD");
        pdfOpt.setCellFontSize("12");
```
