### ISSUE TITLE
RequestContext#update(...) throws an exception if the id is not found on the view

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#2382]
## 1) Environment
- PrimeFaces version: 
6.0
- Does it work on the newest released PrimeFaces version? Version?
No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
No
- Application server + version:
WildFly 10
- Affected browsers:
Firefox 53

## 2) Expected behavior
When we call **RequestContext.getCurrentInstance().update("componentId")** if the component ID doesn't exist the app should run without give us an exception.

## 3) Actual behavior
When we update a component programatically, now an exception is thrown if the component doesn't exist and the JSF stage is set as Development. This is causing a problem for apps that are using the tag **c:if** for example.

## 4) Steps to reproduce
Update a component that doesn't exist using **RequestContext.getCurrentInstance().update("componentId")**

## 5) Sample XHTML
The component shouldn't exist on the view.

## 6) Sample bean
RequestContext.getCurrentInstance().update("componentId");

In the migration guide there is not a part to indicate this change that affect the development stage. I think that should be better add a parameter to conditionally enable this validation, because the versión 5 is ignoring if the ID is not present. The methods changed were **public void update(String clientId)** and **public void update(Collection<String> clientIds)** in the file **DefaultRequestContext.java**.

**Comment by tandraschko** [comment]
For me there is no reason for deactivating this feature.
IMO it's a dirty code trying to update parts of the UI, which are not available.

**Comment by wsaca** [comment]
Well, I just realized this change because we are migration the apps to PF 6. The problem is introduced when the view uses **c:if** to render components. Our case is affected because the view is too complex and the app is old, to use the rendered attribute is not optimal in JSF, because even hidden components make calls to related beans. I understand your point of view, I don't have any problem changing the app to add lazy load, but this type of changes should be documented because PF didn't have a section saying that **c:if** should be avoided.

**Comment by tandraschko** [comment]
i don't think that c:if should be avoided for every case!
I just think that some such calls like #update should only be called if it's available on the view. This makes the code clearer.

**Comment by tandraschko** [comment]
Lets wait a while if other developer need something, too.
If yes, we can introduce a context param to disable this behavior (also i don't recommand it, it feels wrong).

**Comment by taylor-seth** [comment]
Has this been flagged for an upcoming release? 

I understand the idea that it "feels wrong" since ideally a component shouldn't be updated if it isn't available.  Most of the time this is true and could be seen as a code smell that should be fixed with some simple refactoring.  However, in our case, the most pain has been with the dialog framework.  

We have business logic that is shared between the main application panels and some of the dialog panels.  Most of the time this business logic is used by the main application panels and when updating a component, it is in the correct view.  However, some of this business logic handles updating some components on the main view side and when in the dialog framework these components are not available, which causes an error.  We've been able to do some refactoring, but for some items this will require a good deal of refactoring and some code duplication just handle updating or not updating components based on if the user is in a dialog or not.

I agree with this concept most of the time, but when dealing with the dialog framework I think there needs to be some flexibility.

**Comment by tandraschko** [comment]
No plans, sorry.
I suggest to use the underlying facesContext.getPartialViewContext().getRenderIds().add(clientId)

**Comment by tandraschko** [comment]
Switched from throwing to logging ;)

**Comment by adjiandov** [comment]
I would just like to add that I have simmilar, but opposite problem. I get the same exception, but the component exists in the HTML DOM with the same ID for which the exception is thrown. Any ideas?
