### ISSUE TITLE
Update Extensions Showcase

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#2428]
Please update the Extensions Showcase as it is still showing the 6.0 features and not the 6.1 features.

https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/447

**Comment by jxmai** [comment]
Just personally speaking. I know this ticket might not be in the right place but it seems there is no other way to get any reply which is not appreciated. As a community driven project like primefaces extension, we should appreciate the work getting done by @melloware to keep the project alive.  Otherwise, primefaces extension project should be less active unlike now since **the original developers are no longer active in PFE** (Details discussion in here: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/409). After melloware took over primefaces extension, any pull and issue raised in PFE recently were all well organized by melloware,  and any forum post related to PFE got quickly response by melloware.

I have also seen @melloware   tried to write a comment for the same request in https://www.primefaces.org/primefaces-6-1-1-released/ but **to be the only one got ignored**.

![snapshot1](https://user-images.githubusercontent.com/10467831/27008180-4b46b24a-4e30-11e7-9551-5578d8670c73.png)

I have also seen @melloware  tried to unpin the old comment from PFE extension but also **got ingored**.
https://forum.primefaces.org/viewforum.php?f=14

![snapshot1](https://user-images.githubusercontent.com/10467831/27008188-9632ab88-4e30-11e7-8953-62621c3efe56.png)

![snapshot1](https://user-images.githubusercontent.com/10467831/27008195-c9b1787c-4e30-11e7-953e-3b6447a9441e.png)



**Being an open-source maintainer is not an easy task and it is especially hard to keep highly motivated**. Personally speaking, it is a luck for us to have @melloware in Primefaces community. **What primefaces official team needs to do is to acknowledge the good work and show the work in the showcase**. For anyone who does not look into github might think primefaces extension is probably dead since the showcase is way outdated and the latest released is 4.0.0 based on the top pin information in the forum.

**We are all busy but what's worth more to spend a few minutes to keep a skilled community developer around ??? :confused:**

I know I rant a lot, so I should hide now... :sweat_smile:

**Comment by tandraschko** [comment]
Hey, i'm not inactive :D I just don't develop new features here.
Everyone of the PrimeFaces team knows about the good work in PFE and PF.
I would deploy the showcase but i don't have access, so we can just ping optimus prime again.


@melloware 
Please ping me if you have a showcase to deploy, i will contact cagatay again.
I will also ask them about admin rights in our sub-forum for both you and me.

**Comment by Rapster** [comment]
It's a been while now.... @cagataycivici please can you have a look?

**Comment by melloware** [comment]
I have been sending a reminder email once a week to him.

**Comment by melloware** [comment]
Showcase has officially been updated!
