### ISSUE TITLE
SplitButton p:menuitem is tabable in disabled state

### ISSUE THREAD

**Issue by adrianfiedler** [primefaces/primefaces#2436]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: JBoss EAP 7
- Affected browsers: Firefox (53.0.3 32-Bit), Chrome (58.0.3029.110 (64-bit))

## 2) Expected behavior
The menuitem should not be tabable in disabled state

## 3) Actual behavior
The menuitem is tabable in disabled state

## 4) Steps to reproduce
Tab trough splitButton dropdown menu

## 5) Sample XHTML
<p:splitButton icon="fa fa-search">
	<p:menuitem value="Disabled and tabable"
		disabled="true"
		itemDisabled="true">
	</p:menuitem>
	<p:menuitem value="Enabled"/>
</p:splitButton>

## 6) Sample bean

..

**Comment by adrianfiedler** [comment]
![2017-06-14_10h36_17](https://user-images.githubusercontent.com/7136570/27123536-78fa3c50-50ee-11e7-8e55-9d07bea22764.png)

**Comment by tandraschko** [comment]
a PR would be great

**Comment by jxmai** [comment]
This issue is no longer relevant. Please close.


Here is the code: 

https://github.com/primefaces/primefaces/blob/6cb428c0cf608263868d6ecae733c1ccc19ebb36/src/main/resources/META-INF/resources/primefaces/forms/forms.splitbutton.js#L109-L111

The current behavior is tabbing will always make the menu disappear, which is not the same behavior as the reporter's description

> The menuitem is tabable in disabled state

---

![image](https://user-images.githubusercontent.com/10467831/31751593-d8856526-b44b-11e7-89bd-9676d214c9c1.png)


and tab

![image](https://user-images.githubusercontent.com/10467831/31751614-f9ea4b5a-b44b-11e7-968c-615ff93dfcb9.png)
