### ISSUE TITLE
LazyDataModel#load() called twice on initial load

### ISSUE THREAD

**Issue by ohlsen3000** [primefaces/primefaces#246]
When using a dataTable with the following attributes:
`
<p:dataTable id="items" var="item"
  value="#{itemView.items}"
  paginator="true"
  rows="10"
  lazy="true">
`

the `load()` method of the `LazyDataModel` gets called twice on the initial load of the page.

In fact _all_ components in the view (a simple page - no dialogs etc.) get rendered twice - unless I take the table out.

I'm using PF 5.2.

**Comment by npalikuca** [comment]
So i did some research, trying to help you here. In my case this happens when i have data table inside dialog or overlay panel with attribute `dynamic"=true"`. Without `dynamic="true"` the `load()` method is called only once. But yes, i agree, this should (i think) be only called once.
I'm using PF5.0

EDIT: as ohlsen3000 closed this ticket, i will try to figure out whats problem in my case ...

**Comment by ohlsen3000** [comment]
Was caused by another component, sorry for the inconvenience.

**Comment by cagataycivici** [comment]
Thank you for the update.
