### ISSUE TITLE
ColumnToggler not displaying headerText text if facet used.

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2479]
## 1) Environment

- PrimeFaces version: 6.1
- Application server + version: Glassfish 4.1.1 Mojarra 2.2.9

## 2) Expected behavior

Either display content of facet _header_ or as a fallback display _headerText_ if value is empty.

## 3) Actual behavior

No label is shown.

http://i.imgur.com/mY2PyBW.jpg

## 4) Steps to reproduce

Just display an icon in facet _header_ and use column toggler.

## 5) Sample XHTML

	<p:column headerText="Test">
		<f:facet name="header">
			<h:pnlGroup styleClass="fa fa-lock" pt:data-tooltip="Row is locked."/>
		</f:facet>
	</p:column>

## 6) Workaround

Use hidden text in facet

	<h:outputText value="Test" style="display: none;"/>

**Comment by tandraschko** [comment]
Please provide a PR

**Comment by sarvigalava** [comment]
I have multiple components in the header facet (including buttons and dropdowns), the column toggler generates invalid column names (selects all text from the column header). There should be an option to override the default behaviour (.text() method called in the js widget).

I think that the simplest solution would be to search a custom class instead of .ui-column-title and select the text if any element is found otherwise to select all text from the default class to keep backwards compatibility.

**Comment by sarvigalava** [comment]
This is the fix I used:

`children = column.children('.ui-column-title');
var columnTitle;
if (children.children('.ui-custom-title').length !== 0)
{
	columnTitle = children.children('.ui-custom-title').text();
}
else
{
	columnTitle = children.text();
}`

**Comment by melloware** [comment]
I chose a slightly different path for fixing it by simply searching for the first "label" inside the facet so if you have a <h:outputText> or <p:outputLabel> it would use that text.  While still being backwards compatible for headerText="xxx".

**Comment by ravihariharan** [comment]
Refer Documentation : ColumnToggler: Label Issue on ColumnToggler (#5062)
