### ISSUE TITLE
Remember caret position on refocus after ajax update

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#25]

**Comment by frederikd** [comment]
This sounds like a fantastic feature/change. May I just ask what exactly is planned here? Will this work across all text input fields (e.g. also for pe:inputNumber or h:inputText) as long as p:ajax is used? Or will this be implemented for each component separately and/or also work with f:ajax?

**Comment by tandraschko** [comment]
for all inputs and p:ajax :)

**Comment by frederikd** [comment]
Awesome. Will this also re-enter the previous value, or is that out of scope?
E.g. if the user starts typing and in the middle of typing an ajax request finishes and re-renders the currently selected field, will it only put the caret back to where it was before, or will it also apply the value that was applied before so that the user wouldn't even notice that it was re-rendered?

**Comment by tandraschko** [comment]
out of scope! ;)

**Comment by frederikd** [comment]
Fair enough. Just thought I ask. :)

**Comment by cagataycivici** [comment]
@tandraschko There is a plugin we already use in textarea autocomplete functionality to get caret position. Do you consider using it?

**Comment by tandraschko** [comment]
Sure :)
