### ISSUE TITLE
picklist: using transfer button and then fast double clicking on the element causes the item to disppear

### ISSUE THREAD

**Issue by michalfotyga** [primefaces/primefaces#2583]
![picklist-fast-clicking-error](https://user-images.githubusercontent.com/5294702/28670267-317a8f04-72d8-11e7-8e2b-1d24f8af2e1b.gif)

## 1) Environment
- PrimeFaces version: 6.1 (current showcase)
- Affected browsers: firefox + chrome, but probably all

## 2) Expected behavior

Clicking fast on the transfer button and then on the same element in the source list does not mess up the lists.

## 3) Actual behavior

Clicking fast in the described way removes the element from both lists.

## 4) Steps to reproduce

- go to https://www.primefaces.org/showcase/ui/data/pickList.xhtml
- scroll down to 'PickList on Steroids' example
- select "Afterdark' element (works the same with all elements but it is easy to reproduce with this one because it's close to the 'select' button
- click the -> button
- very fast, right after clicking the transfer button in the previous step, do the double click on the same element (Afterdark in this case). 

Doesn't always happen but if you're fast enough you will see the described problem.
It maybe easier to reproduce with changed `effectSpeed`.

**Comment by tandraschko** [comment]
A PR would be great!

**Comment by tandraschko** [comment]
And thanks, great way to capture a bug with a gif!

**Comment by michalfotyga** [comment]
Sure, you're welcome :) Picture is worth a thousand words :v: 
Will try to work on it during the weekend.

**Comment by jxmai** [comment]
I will take care of this ticket.

**Comment by jxmai** [comment]
This problem is quite obvious and we can replicate in https://www.primefaces.org/showcase/ui/data/pickList.xhtml as the reporter's description.


There are more serious problems than this bad behavior  if we don't fix this issue.

![image](https://user-images.githubusercontent.com/10467831/33444587-510e3424-d5c0-11e7-8b96-ff3d887bb6a4.png)


If we hold the ready to be transferred item during transfer. There will be javascript error and the whole screen will be frozen.


PR: #3031
