### ISSUE TITLE
PF 6.1: p:messages does not work

### ISSUE THREAD

**Issue by piyushsingh90** [primefaces/primefaces#2648]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? 6.0
- Application server + version: Mojarra 2.2.13 on Glassfish.

## 2) Expected behavior
```
<h:form>
    <p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" />
 
    <p:commandButton value="Info" actionListener="#{messagesView.info}" />
</h:form>
```

When we click the commandButton, the message component should be displayed, with the appropriate message.

## 3) Actual behavior
p:messages component is not rendered on the GUI. No error message are seen in the Logs.

## 4) Steps to reproduce
To reproduce, we can use the code on the Primefaces showcase site:
https://www.primefaces.org/showcase/ui/message/messages.xhtml

## 5) Sample XHTML
```
<h:form>
    <p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" />
 
    <p:commandButton value="Info" actionListener="#{messagesView.info}" />
</h:form>
```

## 6) Sample bean
```
@ManagedBean
public class MessagesView {
     
    public void info() {
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Info", "PrimeFaces Rocks."));
    }
}
```

**Comment by tandraschko** [comment]
This example works fine in the showcase when copied into the showcase with trunk.

**Comment by erickdeoliveiraleal** [comment]
I'm also with this problem and was working in past, same code works in 6.1 but not in 6.2-SNAPSHOT. Using WildFly 11 and SNAPSHOT of today.

**Comment by tandraschko** [comment]
Did you check the migration guide? we removed autoUpdate as attribute

**Comment by cagataycivici** [comment]
@tandraschko We should not break backward compatibility, we should keep autoUpdate property as well, deprecate it and remove it in a future release, we can't remove features before deprecating them. Otherwise many users will have troubles like these.

**Comment by jxmai** [comment]
Agree with cagatay. In the comment section of the original proposal (https://github.com/primefaces/primefaces/issues/2838#issuecomment-337923332), we agreed that 

> any other component with <p:autoUpdate />as a child can be searched and updated accordingly

and proposal itself did not indicate removing `autoUpdate` attribute, otherwise I would catch it at that time.

I thought it was only an enhancement on top of the current `autoUpdate` at least in PF 6.2.

Not sure about the policy, but .y version bump shouldn't introduce such breaking change IMHO.

---
If user simply replaces the PF jar without taking a look at the migration guide first:

All the growl, message will stop working since they are usually implemented with autoupdate. and `p:outputpanel` + `autoUpdate` hack is a commonly known trick that will also break. :disappointed: 

We cannot rely on the migration guide completely IMHO since the version number `0.1` bump can speak for itself about the amount of breaking changes.

**Comment by tandraschko** [comment]
the problem is you can't avoid breaking changes - in 90% you also need some changes AND this change is quite small for the user.
You just need to search for autoUpdate=true and add the child tag instead, it's almost impossible to do something wrong here.

**Comment by tandraschko** [comment]
versionsnumbers are like: major.minor.bugfix/hotfix
for me it's a minor feature.
Upgrading jquery to 2.x is IMO a much more risky task in such a minor version upgrade ;)

**Comment by jxmai** [comment]
did not check the implementation. Looking at https://github.com/primefaces/primefaces/commit/68e456357d0c45720d9854204c16426b12b5033a right now: it seems like a major refactoring was done in one commit (enhancement and removal)

---

> You just need to search for autoUpdate=true and add the child tag instead, it's almost impossible to do something wrong here.

Yes, that's true.  :+1: 

>  it's a minor feature.

Hmm, It is hard to tell whether it is a minor feature or major. Since all the components are now supporting autoUpdate, and the previous attributes were removed, so it could be a major, or am I wrong ? :thinking:

**Comment by jxmai** [comment]
> Upgrading jquery to 2.x is IMO a much more risky task in such a minor version upgrade ;)

Yes, but most end users don't see the differences :) Mostly backend work.

**Comment by tandraschko** [comment]
not sure :D but if the user don't read the migration guide, it will not work in the major version, too... So we can never remove any attribute anymore :P

**Comment by jxmai** [comment]
Alright. That's a point. Overall I still think it is a cool feature, but it might be even better to keep backward compatible in this point release :cowboy_hat_face:, but as you said, migration is not that hard and migration guide is clear enough.  I have no problem then :+1:

**Comment by jxmai** [comment]
> it might be even better to keep backward compatible in this point release

https://github.com/primefaces/primefaces/commit/195dba19c01cf2772416e26ae90ae7cf5789b45a
