### ISSUE TITLE
Add Grid CSS support to components that use ui-grid-col- for resposive feature 

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2677]
"ui-grid-col-6" =  "ui-g-12 ui-md-6"

**Comment by ssibitz** [comment]
Hello,

It seems that you now have a bug in the Primefaces DataGrid-Component-Rendering,
because this code is working right in Primefaces version 6.1.4 but not in 6.1.5:

```
                                    <p:dataGrid id="ProfileSelection" var="allProfiles" value="#{calc.profiles}"
                                                columns="4" layout="grid"
                                                rows="12" paginator="true"
                                                paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                                rowsPerPageTemplate="10,20,50,100,200">

                                        <h:panelGroup id="SelectedProfile">
                                            <div class="col" id="MyColDiv">
![selection-primefaces-6 1 4](https://user-images.githubusercontent.com/652355/30812310-ba48e978-a20a-11e7-8ae6-c71f7151af7a.png)

                                            </div>
                                        </h:panelGroup>
                                    </p:dataGrid>

```
This code will render 4 columns as i espected by the given "columns" parameter in Primefaces 6.1.4.
I am using Bootstrap 4 (Beta) for rendering the "MyColDiv" which is working fine and is already responsive:
![selection-primefaces-6 1 4](https://user-images.githubusercontent.com/652355/30812380-dde25a5e-a20a-11e7-9cc8-a41f4722a278.png)


In the new Primefaces version 6.1.5 i am only geting it shown row by row instead of 4 columns:
![selection-primefaces-6 1 5](https://user-images.githubusercontent.com/652355/30812388-e82e6174-a20a-11e7-8fd3-a6db78f012ee.png)


Please take a look on the attached screenshot which shows you the right rendering within the old version and the "buggy" rendering in the 6.1.5 version.
