### ISSUE TITLE
DataExporter issue with selectionOnly="true"

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#273]
Was already reported on the old versioning system.

https://code.google.com/p/primefaces/issues/detail?id=7406

Can somebody pick this up?

Tnx.

**Comment by cagataycivici** [comment]
We've tried it before and could not replicate.

**Comment by sudheerj** [comment]
The issue existed with 5.2 release as well.It can be replicated with "Multiple with Meta and Shift keys" and " Checkbox" datatable features.Here we need to make sure only one datatable is available in the page with dataExporter component because all the datatables using same selection record(i.e, It will cause only headers exported).

Instead of exporting the selected records it will export the wrong records from the beginning of datatable.

**Comment by cagataycivici** [comment]
Ok, reopening. I'll take care of it myself.
