### ISSUE TITLE
Column filtering with filterOptions: style can be improved

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#2763]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? It shouldn't
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) It shouldn't
- Application server + version: Tomcat 8
- Affected browsers: All

## 2) Expected behavior
The select created by filterOptions should look like a p:selectOneMenu

## 3) Actual behavior
The select doesn't look like the p:selectOneMenu
![cattura](https://user-images.githubusercontent.com/18428155/31047613-5ec3be4a-a60e-11e7-98de-1894fd01f6f5.JPG)

## 4) Steps to reproduce
Just add filtering to a column with filterOptions

## 5) Sample XHTML
```xhtml
<p:dataTable value="#{index.test}" var="var">
	<p:column headerText="Column 1" filterBy="#{var}">
		<f:facet name="filter">
			<p:selectOneMenu>
				<f:selectItems value="#{index.items}"/>
			</p:selectOneMenu>
		</f:facet>
		#{var}
	</p:column>
	<p:column headerText="Column 2" filterBy="#{var}" filterOptions="#{index.items}">
		#{var}
	</p:column>
</p:dataTable>
```

## 6) Sample bean
```java
@ManagedBean
@ViewScoped
public class Index {

	private List<String> test;

	public List<String> getTest() {
		return test;
	}

	public void setTest(List<String> test) {
		this.test = test;
	}
	
	private List<SelectItem> items;

	public List<SelectItem> getItems() {
		return items;
	}

	public void setItems(List<SelectItem> items) {
		this.items = items;
	}
	
	@PostConstruct
	public void postConstruct() {
		test = new ArrayList<>();
		items = new ArrayList<>();
		for (int i = 1; i <= 10; i++) {
			test.add("String " + i);
			items.add(new SelectItem("String " + 1));
		}
	}
}
```

**Comment by melloware** [comment]
You have solved it the way I have solved it and just use a Facet instead of the native FilterOptions.  

PF have specifically chosen to use the Browser Native select options for rendering the filterOptions.  Because the PF SelectOne is not just a styled browser native selectOne its actually a totally custom component with CSS to make it look like a browser native select one menu.

**Comment by NicolaIsotta** [comment]
I guess this can be closed then, since the quick fix I tried (adding the `ui-inputfield` class) doesn't really work, and there's an easy, working alternative.

**Comment by Rapster** [comment]
I was about to write a ticket explaning that issue... True, PF is using a native select to render `Column#filterOptions` but I don't know why... Actually using filterOptions is a lot more easier than writing boiler plate code like:
```xml
<p:selectCheckboxMenu label="Colors" onchange="PF('carsTable').filter()" scrollHeight="150" styleClass="custom-filter">
                            <f:selectItems value="#{dtFilterView.colors}" />
                        </p:selectCheckboxMenu>
```

+1 from my side to fix this, unless there is a good reason to keep native rendering

**Comment by melloware** [comment]
@Rapster I think this is similar to this issue as well: https://github.com/primefaces/primefaces/issues/2270

**Comment by Rapster** [comment]
Paginator combox style does not really bother me, though this one does... I had a quick look how we could render a SelectOneMenu instead of native HTML select, I was thinking of having a `RendererUtils#encodeSelectOneMenu`. `SelectOneMenuRenderer#encodeMarkup`  could have reused this method but I don't think it's be possible, it's doing too much stuff for what we want in this ticket.

So my best bet right now, it's to create that method `RendererUtils#encodeSelectOneMenu`, WDYT?

**Comment by melloware** [comment]
I am OK with that.  It clearly states what it does and it prevents duplicate code.

**Comment by tandraschko** [comment]
lets talk about after 8.0
