### ISSUE TITLE
Add escapeJQueryId method again to ComponentUtils

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2801]
Reported By PRO User;
> We face problems with pe:blockUI. pe:blockUI uses the Method ComponentUtil.escapeJQueryId which was remove in PrimeFaces 6.1.6 or 6.1.5.

**Comment by tandraschko** [comment]
JFYI @mertsincan: We also released a small bugfix version (6.1.5) but can't find in the maven repo? @melloware ?

**Comment by melloware** [comment]
Yes I did not do a public release to the repo because 6.1.5 is tied to this exact fix in Elite 6.1.5+.  

Because if someone downloads 6.1.5 thinking its got fixes for 6.1 Community and tries to use it against the PF Community release 6.1 it would break in the opposite direction.

So my thought was Maven Central releases should only be to match up to Community Releases to prevent having this issue. Thoughts?   

And I can simply provide a download for Elite users.

**Comment by mertsincan** [comment]
>  I can simply provide a download for Elite users.

Thanks, @melloware. Our PRO User wanted me to add ComponentUtil.escapeJQueryId for now. If you send me a download link for PRO/Elite Users, I can suggest it for such problems.

**Comment by melloware** [comment]
@mertsincan you can refer them to this thread and download.

https://forum.primefaces.org/viewtopic.php?f=14&t=52458
