### ISSUE TITLE
[Documentation] primefaces.MOVE_SCRIPTS_TO_BOTTOM  / move above the fold scripts to the bottom

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#2888]
it's a new feature, implemented via a custom ResponseWriterWrapper, which does the following:
- Collect all script tags, skip rendering of them
- before the body tag ends, render all script tags
- all of the inline scripts (widget init scripts) will be merged to one big inline script
- the inline-scripts will be also minimized a little bit (like replacing all PrimeFaces.cw with pf.cw)

overall it improves the visible loading of the page a lot + it reduced the generated html up to 5% in my application

it can be activated via primefaces.MOVE_SCRIPTS_TO_BOTTOM =true in the web.xml

we should really promote it, it makes the rendering really really really fast.

**Comment by rdebusscher** [comment]
It will also remove the white flickering between page navigation like you can see for example on the online Omega Layout demo. (https://www.primefaces.org/omega/sample.xhtml and click on the different items under the components menu item)

It is caused by one of the jquery-plugins.
If this is removed from the head (and placed just before the end of the body) it is solved.

`<script type="text/javascript" src="/xxxx/javax.faces.resource/jquery/jquery-plugins.js.xhtml?ln=primefaces&amp;loc=&amp;v=6.1"></script>
`

I didn't dig into the Javascript to find out which JQuery plugin is the cause.

**Comment by tandraschko** [comment]
@rdebusscher thanks for the hint! If you have time someday, we should check that.

**Comment by rdebusscher** [comment]
@tandraschko 

I found the statement in question which causes the flickering.

`if ( !$( "<a>" ).outerWidth( 1 ).jquery ) {`

It WAS in the _jquery.ui.js_ file. But that code part is removed for issue #2233 (upgrade JQuery UI to 1.12, date 9 Aug 2017)

And indeed, with the current SNAPSHOT, there is no flickering anymore. Without using the MOVE_SCRIPTS_TO_BOTTOM.

**Comment by tandraschko** [comment]
great, thanks for testing this!
