### ISSUE TITLE
TimeLine: Add localization to the wiki

### ISSUE THREAD

**Issue by stasal** [primefaces/primefaces#2941]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest sources in GitHub? Didn't build the latest version. But according to sources the problem still exists
- Application server + version: Weblogic 12.2.1.0 (Don't think it matters)
- Affected browsers: all

## 2) Expected behavior
Primefaces i18n (https://github.com/primefaces/primefaces/wiki/Locales) works fine for Timeline component

## 3) Actual behavior
Locale files presented in wiki page contain options keys not supported by Timeline component.
E.g.: in locale file there is an option 'monthNames' but Timeline uses 'MONTHS' instead and so on:
'MONTHS_SHORT' instead of 'monthNameShort'
'DAYS' instead of 'days
'DAYS_SHORT' instead of 'dayNamesMin'

## 4) Steps to reproduce
1. add PrimeFaces Timeline component with valid model to the page
2. set component locale attribute to 'ru' (for example)
3. add reference to js file containing 'ru' locale from wiki (https://github.com/primefaces/primefaces/wiki/Locales) to the page
4. run the application, open the page with Timeline component from step 1 and see the text representation of dates.

**Comment by tandraschko** [comment]
A PR for the wiki (if possible) would be great. Seems like the documation was not moved to primefaces.

**Comment by melloware** [comment]
This page from Extensions needs to be ported over to the PF wiki.

https://github.com/primefaces-extensions/primefaces-extensions.github.com/wiki/PrimeFaces-Extensions-Locales

**Comment by tandraschko** [comment]
Yep, we must also check if the locales js namespace has been changed.

**Comment by melloware** [comment]
@stasal can you help here with this one since you are an active user of the component and are familiar with the settings to update that Wiki page?

**Comment by stasal** [comment]
@melloware which kind of help is needed? I can see the wiki page is already updated.
But the namespace **PrimeFacesExt.locales.Timeline** is not  working, so these constants must be put directly into **PrimeFacesExt.locales[locale]**

**Comment by melloware** [comment]
@stasal  That WIKI is for PrimeFaces Extensions.  The Timeline component used to be a pe:timelime component but was moved over to be in PrimeFaces core as p:timeline.  So that WIKI page on PF Extensions really needs to be updated in PF.

I think the Locales namespace has to change to it should not be PrimeFacesExt in 6.1?

**Comment by stasal** [comment]
I don't think that just updating wiki is a good scenario. We already have localization for months in 'monthNames' attribute of PrimeFaces.locales.
So why do we need to add another key ('MONTHS') with the same content. Month names will not depend on whether we use them in calendar, timepicker or timeline. January will always be January. 

So maybe the correct way is to refactor the component's code so it could use already existing constants?

**Comment by melloware** [comment]
i think you are right.  Is the namespace of Timeline still PrimeFacesExt.locales. or is it PrimeFaces.locales?  

I will look it over.

**Comment by stasal** [comment]
@melloware I added attributes described in PrimeFaces Extensions wiki to PrimeFaces.locales along with already existing (from PrimeFaces wiki) and TimeLine component became translated into my language.
Though I did not even try it with PrimeFacesExt.locales but PrimeFaces.locales worked for me.

**Comment by melloware** [comment]
OK I dug more into this.  It is because the core Jquery component the Timeline is based on this component.

https://github.com/almende/chap-links-library/blob/master/js/src/timeline/timeline.js

So if we were to update the constants for the Locales labels I would have to edit this component's source code.

https://github.com/almende/chap-links-library/blob/master/js/src/timeline/timeline.js#L221

Which I don't mind doing but I would need @tandraschko permission to make that sort of change!

**Comment by melloware** [comment]
Linked to #2504
