### ISSUE TITLE
Focus: (for, context) with selectOneRadio results in a non-selected item being focused

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#3029]
## 1) Environment
PrimeFaces 6.2-SNAPSHOT

## 2) Expected behavior

p:focus should set the focus on a selected radio item if there is one, not the first.

## 3) Actual behavior

p:focus always sets the focus on the first radio item.

## 4) Steps to reproduce

Use p:focus with `for` or `context` attributes with p:selectOneRadio.

## 5) Sample XHTML

	<p:focus for="console" />
	<p:selectOneRadio id="console" value="PS4">
		<f:selectItem itemLabel="Xbox One" itemValue="Xbox One" />
		<f:selectItem itemLabel="PS4" itemValue="PS4" />
		<f:selectItem itemLabel="Wii U" itemValue="Wii U" />
	</p:selectOneRadio>

This results in:
![radio_focus](https://user-images.githubusercontent.com/8070317/33436901-6507aff0-d5f7-11e7-8398-93976fcd6c40.png)

And if you press space:
![radio_focus_space](https://user-images.githubusercontent.com/8070317/33436912-6ae4c1c4-d5f7-11e7-96b0-fc156f11d47c.png)

This was partially fixed in #1182 only when p:focus is used without attributes.

**Comment by jxmai** [comment]
@VsevolodGolovanov  I can replicate this bug, the reason is that

https://github.com/primefaces/primefaces/blob/102b4b93e80546b8b70650820eeb9ef258a07d71/src/main/resources/META-INF/resources/primefaces/core/core.js#L412-L421

The block of code above located in the else statement for the other scenriao you mentioned about.

But we need to take care of all other cases too.

I will raise a patch shortly.

**Comment by jxmai** [comment]
PR: #3037
