### ISSUE TITLE
MultiViewState support to DataTable that has columnToggler component

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#3044]
```
<p:dataTable id="cars" var="car" value="#{dtBasicView.cars}" multiViewState="true">
                <f:facet name="header">
                    List of Cars

                    <p:commandButton id="toggler" type="button" value="Columns" style="float:right" icon="ui-icon-calculator" />
                    <p:columnToggler datasource="cars" trigger="toggler">
                        <p:ajax event="toggle" />
                    </p:columnToggler>
                </f:facet>
       ....
</p:dataTable>
```

Required;
- <p:ajax event="toggle" /> in columnToggler
- <h:form>

**Comment by escay** [comment]
I tried the 6.1.10 release. I took the tableState example from: https://www.primefaces.org/showcase/ui/data/datatable/tableState.xhtml and added the columnToggler using the example above. 

I tested selected row and paginator states: they are preserved using multiViewState="true" but when testing the columnToggler the state is not preserved when switching between pages.

I could also reproduce it using:
```
<p:dataTable id="cars" var="car" value="#{dtBasicView.cars}" multiViewState="true">
    <f:facet name="header">
        List of Cars
        <p:commandButton id="toggler" type="button" value="Columns" style="float:right" icon="ui-icon-calculator" />
        <p:columnToggler datasource="cars" trigger="toggler">
            <p:ajax event="toggle" />
        </p:columnToggler>
    </f:facet>
    
    <p:column headerText="Id" sortBy="#{car.id}"><h:outputText value="#{car.id}" /></p:column>
    <p:column headerText="Year" sortBy="#{car.year}"><h:outputText value="#{car.year}" /></p:column>
    <p:column headerText="Brand" sortBy="#{car.brand}" ><h:outputText value="#{car.brand}" /></p:column>
</p:dataTable>
``` 

Is there a concrete example available to test the columnToggler?

~~Did the fix make it into release 6.1.10?
When looking at the 6.1.10 released source code I do not see the changes of commit  682d992.
Example: src/main/java/org/primefaces/component/columntoggler/ColumnTogglerRenderer.java decode method does not contain the changes.~~ The fix is in my 6.1.10 code, but does not seem to work.

**Comment by escay** [comment]
Please ignore my previous comment. 
After successfully testing #3041 (reorder) and #3046 (resize) I retested this one again and now it works. 
I upgraded from 6.1.4 to 6.1.10, perhaps some old javascript was cached in the browsers I used to test.

The columnToggler now also works and it is a much nicer solution compared to saving the column visibility in a backing bean manually as in: https://www.primefaces.org/stateful-column-toggler/
Thank you for the effort!

**Comment by mertsincan** [comment]
Thanks a lot for the update!
