### ISSUE TITLE
Galleria component throws a js error on jQuery 3.2.1 

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#3066]

**Comment by jxmai** [comment]
This issue and #3067 are caused by the same piece of code as there is no load function in JQ 3

https://jquery.com/upgrade-guide/3.0/#breaking-change-load-unload-and-error-removed

https://github.com/primefaces/primefaces/blob/d2ab98b55185b71b5ed8697023dfea82ef7bf346/src/main/java/org/primefaces/util/WidgetBuilder.java#L83-L91

**Comment by melloware** [comment]
Nice debugging!
