### ISSUE TITLE
Link/Button: prepend contextPath on href if relative

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#3154]

**Comment by rmpestano** [comment]
Hi @tandraschko,

Just to confirm that the commit 41921c4 just fixed the problem we [discussed here](https://github.com/primefaces/primefaces/pull/3133#issuecomment-357109581).

Thank you very much!

**Comment by tandraschko** [comment]
I will revert this, sorry.
As i already said, it's not correct to modify the href in this way.

If you need to reference a JSF view in the same app, just use outcome.
Href it not built for this.

**Comment by rmpestano** [comment]
No problem, go ahead, replace href with outcome is doable.

**Comment by rmpestano** [comment]
In the end we had to replace p:link with plain `a href` because we're generating links dynamically and a wrong generated outcome can make the whole application unavailable (invalid navigation rule) because the outcome (href now) is declared on a template that every page uses.

details on this commit https://github.com/adminfaces/admin-template/commit/d243aa0f444449d5cdb6cefa6ff3f2d46eeef0c5#diff-34d5c4358dd08bfbeb3955c809570ec9

**Comment by tandraschko** [comment]
@rmpestano 
in the upcoming PF, href="#{request.contextPath.concat(b.link)}" would work the same on p:link.

**Comment by rmpestano** [comment]
Yea this way we'll be able to support currently and future PrimeFaces versions.
