### ISSUE TITLE
Datatable: add "all" option to rowsPerPage

### ISSUE THREAD

**Issue by ankitacroit09** [primefaces/primefaces#3228]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers: all

## 2) Expected behavior
  I want to show all the rows on datatable by using the paginator rows per page select as All option( rows per page="All")
...

## 3) Actual behavior
 paginator rows per page dropdown not have the select All rows per page option.

..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
<p:dataTable var="car" paginator="true" rows="10" paginatorTemplate="{FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}" rowsPerPageTemplate="5,10,15,25,30" >

## 6) Sample bean

..

**Comment by cnsgithub** [comment]
Why not add the total dynamically to the rowsPerPageTemplate, will solve your problem without codechange:

rowsPerPageTemplate="5,10,15,25,30,#{collectionValue.size()}"

**Comment by JHookDev** [comment]
A change was implemented with 6.2 to allow '\*' and 'All rows'. However only the '\*' works as expected. The 'All rows' option doesn't work, due to the regular expression used to split the options, as it is splitting on commas and spaces.

`String[] options = pageable.getRowsPerPageTemplate().split("[,\\s]+");`

The EL option suggested by cnsgithub works, however it does possibly require the implementer to build the entire rowsPerPageTemplate via an EL expression to account for the hard coded values not being larger than the size of the collection. Otherwise it might look like 5, 10, 15, 25, 16.

I think a better out of the box solution should be available. I suggest that the regex mentioned before gets changed to only split on commas, of course unless the design is to allow space delimited options. Also modifying the following if statement, `if (option.equalsIgnoreCase("*") || option.equalsIgnoreCase("All rows"))` while looping through the options and checking for a non-numeric option should trigger the "show all feature" where the rows is set to the row count. This allows the implementer to use whatever verbiage is pertinent to their implementation or language.

**Comment by avinashmoram** [comment]
Just stumbled upon this one during our upgrade to 6.2. I think if we just stick with one word like "All" instead of "All rows" would be a quick fix. Then we can still stick with the existing regex for supporting split on both commas and space delimiters.
