### ISSUE TITLE
Timeline: Migrate to vis.js

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3245]
http://almende.github.io/chap-links-library/

> CHAP Links Library now has a successor: vis.js. A couple of fundamental limitations in the current architecture of CHAP Links Library have been reached. Therefore, a new initiative has been started, aiming at more flexible data manipulation, better performance, and expandable visualization tools.

http://visjs.org/

**Comment by markusg80** [comment]
Are here any news? I think it would be a good idea to change to vis.js! This way primefaces eill get a more powerfull Timeline Component

**Comment by melloware** [comment]
I think I will do this for PF 7.1  My client started using this component and it would be good to update but its too close to 7.0 release.

**Comment by jasonex7** [comment]
What should be the strategy to migrate to vis.js? Create a new component based on vis.js or update existing timeline component to use vis.js?

**Comment by melloware** [comment]
I would prefer to upgrade the current component to vis.js to make the upgrade for users as seamless as possible.

**Comment by jasonex7** [comment]
I've revised current vis.js [documentation](https://visjs.github.io/vis-timeline/docs/timeline/) and how to migrate current `<p:timeline>` to vis.js and see, until now, one main difference: in vis.js the events (or items) are identified by a new field called `id` and not by positional `index` as current timeline.js is. So I think a new field called `id` must be created in primefaces class `TimelineEvent` and modify classes TimelineEvent (equals and hash methods), Timeline, TimelineModel, TimelineUpdater and javascript file `1-timeline.js` to work by that `id` field instead of `index`, in fact I recommend remove all references to index field because there are no such property on items data of vis.js and I think no safe manner to obtain it.

Maybe that change affect existing projects that use `<p:timeline>` and the migration to the new version was not so seamless.

**Comment by melloware** [comment]
Couldn't we just use the "Index" field in the current event but just map it to the new "ID" field i nthe vis.js?   Basically its what makes a timeline even unique right?

**Comment by jasonex7** [comment]
That would be a good option, having Primefaces work by positional index and when rendered the list of `TimelineEvent` instances then map positional index to id property. There are more subtle differences like more fine grained control over editable property of an item (editable.remove, editable.updateTime, editable.updateGroup) but I think that wouldn't be a major problem.

Another major difference I see is that vis.js version 5.1.0 (https://visjs.github.io/vis-timeline/docs/timeline/) is not compatible with IE11 but archived (no longer mantained) vis.js version 4.21 (https://almende.github.io/vis/) and of course current `<p:timeline>` it does support IE11. Maybe it's some to consider about seamless migration.

**Comment by melloware** [comment]
There is also TimeLine-Plus which is a fork of 4.21: https://github.com/yotamberk/timeline-plus

And it looks like that developer has now taking over the 5.x branch of vis.js and will be incorporating his changes in v6: https://github.com/visjs/vis-timeline/issues/56

**Comment by mojoaxel** [comment]
Hi, I'm one of the visjs maintainer.

I would recommend using our up-to-date timeline library [vis-timeline](https://github.com/visjs/vis-timeline) after the upcoming v6 release. We have come a long long way sind the chaps library and we are not longer fully compatible. But now is a good time to change because the timeline is now 

Our repository includes all features of the [timeline-plus](https://github.com/yotamberk/timeline-plus) (what will not me maintained anymore in the future).

There is a IE11 bug at the moment, but this will be also be fixed in the upcoming v6 release. We support IE11.

**Comment by jasonex7** [comment]
Hi @mojoaxel. It's great that you joined this thread. Do you have any estimation about when v6 release is going out? 

I'm analyzing and I'm doing some coding related to migration of the Primefaces timeline component to visjs v5.1 right now, do you think existing code that is working with v5.1 will be compatible with v6? Or do you recommend not to invest efforts until v6 goes out?

**Comment by mojoaxel** [comment]
> Do you have any estimation about when v6 release is going out?

Not sure but I would guess within a few days from now.

> Or do you recommend not to invest efforts until v6 goes out?

The v6 includes a ton load of new features and bugfixes from the [timeline-plus](https://github.com/yotamberk/timeline-plus) fork. I would wait a few more days for the integration but v6 is propably 95% compatible to the current v5.1 release.

**Comment by melloware** [comment]
Thumbs up all around guys.  @jasonex7 much appreciated that you are working on the PR! and @mojoaxel appreciate all your great work keeping the Timeline alive, its a great component.
