### ISSUE TITLE
Calendar: dateSelect is not fired when entering date manually and leaving field with tab

### ISSUE THREAD

**Issue by jmichler** [primefaces/primefaces#3346]
## 1) Environment
- PrimeFaces version: 6.1.13
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Glassfish 4.1
- Affected browsers: At leastChrome

## 2) Expected behavior
when manually entering a date into a calendar with ajax enabled (event dateSelect) that event should also be triggered
...

## 3) Actual behavior
it is however not triggered
..

## 4) Steps to reproduce
Go to https://www.primefaces.org/showcase/ui/input/calendar.xhtml
click into the field "Select Event:"
Enter a date, e.g. 2/2/18
Press tab
=> No event is fired
.. 

## 5) Sample XHTML
<p:calendar id="event" value="#{calendarView.date4}">
            <p:ajax event="dateSelect" listener="#{calendarView.onDateSelect}" update="msgs" />
        </p:calendar>
..

## 6) Sample bean
public void onDateSelect(SelectEvent event) {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Date Selected", format.format(event.getObject())));
    }
..

**Comment by tandraschko** [comment]
Expected behavioar.
You need to define a change envet for this purpose.
change and dateSelect catches both cases:

`                                <p:ajax  event="dateSelect" />
                                <p:ajax  event="change" />
`

**Comment by jmichler** [comment]
Thank you very much for your reply, this did indeed fix the problem.

**Comment by VsevolodGolovanov** [comment]
Makes no sense that change/valueChange doesn't include selected dates, only textual input. And this distinction is probably not interesting in almost 100% of cases, but often leads to faulty UI that only handles dateSelect, since devs generally just click a random date to test, unlike real users who may want to input a specific date by hand. And both guide and showcase make a point of presenting dateSelect only, promoting this kind of usage. "OK, but change still gets triggered for selected dates right, just later on blur?" No, it doesn't, it never triggers. There should be one event that triggers by both selection and textual input, and it should be the default ajax event for calendar. 

Ended up augmenting the Calendar widget to fire dateSelect for textual input.
```
(function(orig) {
	PrimeFaces.widget.Calendar.prototype.init = function(cfg) {
		orig.call(this, cfg);

		var $this = this;
		this.input.off('change.calendar-override').on('change.calendar-override', function(e) {
			// check originalEvent to distinguish actual textual change, not provoked by dateSelect,
			// cause we don't want to fire dateSelect a second time
			// (this doesn't support mask="true" though, cause it has no originalEvent too)
			if (e.originalEvent && $this.cfg.behaviors) {
				var dateSelectBehavior = $this.cfg.behaviors['dateSelect'];
				var changeBehavior = $this.cfg.behaviors['change'];
				var valueChangeBehavior = $this.cfg.behaviors['valueChange'];
				if (dateSelectBehavior && !changeBehavior && !valueChangeBehavior) {
					// log.debug('Triggering dateSelect on change for Calendar', $this.id, e);
					$this.fireDateSelectEvent();
				}
			}
		});
	};
})(PrimeFaces.widget.Calendar.prototype.init);
```
This is for PrimeFaces 6.2.30.
