### ISSUE TITLE
Testing: general considerations and replacement of EasyMock with Mockito

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3348]
As many PrimeFaces contributors and members prefer Mockito as a mocking framework we should go with it as of PrimeFaces 2.3, see https://github.com/primefaces/primefaces/pull/3333#issuecomment-365910872.

In general better test coverage should be aimed at, especially for complex things. For instance currently there are just three components under test. Therefore efficient regression testing is impossible since there are sometimes so many cases to consider manually. Tests may also serve as documentation for use cases that we often might not think of. Recently, for example, many bugs were introduced after changes.

At mojarra, for example, almost all issues are backed by unit and/or integration tests.

**Comment by cnsgithub** [comment]
Pull request for the lib replacement part: https://github.com/primefaces/primefaces/pull/3349

**Comment by tandraschko** [comment]
+1 - for security improvements in the decode method, a unittest should be there.
Contributions are very welcome.

Often components just renders the widget script, for such easy things i would not create unittests.

**Comment by ekennedy80** [comment]
Why not JMockit?

**Comment by cnsgithub** [comment]
@ekennedy80 I just gave JMockit a read and I'm open to new things. Since you seem to be experienced with JMockit, could you provide a port of `InputNumberTest ` (https://github.com/primefaces/primefaces/pull/3349) to let us directly compare JMockit and Mockito? 

Although modern IDEs (Eclipse Oxygen.2, IntelliJ 2017.3) come with code coverage analysis out-of-the-box, the different metrics that JMockit calculates sound interesting. 

Maybe, JMockit's different approach of class instrumentation via ASM versus Mockito's JDK dynamic proxying and cglib subclassing might be also of benefit to us.

**Comment by melloware** [comment]
@ekennedy80 I think Mockito and JMockit are the clear leading API's in the Java realm right now for mocking.  Just for me personally Mockito syntax is more readable for future developers looking at and modifying tests.    I guess the best I can explain it as is the following example...

An Interest Manager class we want to mock when someone calls getInterestPercentage() method to return the value of 5 in the test.

**Mockito:**
```java
when(interestManager.getInterestPercentage()).thenReturn(5d);
```
**JMockit:**
```java
new Expectations() {{
            interestManager.getInterestPercentage();
            result = 5;
}};
```

The readability difference of the two is crazy.  The first one reads like a test.  The second one my brain has to stare at to figure out what its doing.  And that is a **simple** example.  The complex JMockit examples are even crazier..

For me I just prefer the "When This Then That" syntax of Mockito.  But I could be swayed especially if we plan on mocking out anything static like FacesContext.  It seems JMockit allows Static mocking while Mockito basically has the philosophy "you should never mock static classes" which is why someone created PowerMock for Mockito.
