### ISSUE TITLE
DataList and DataGrid should support multiViewState

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#3391]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? no
- Does it work on the newest sources in GitHub? no
- Application server + version: does not matter
- Affected browsers: does not matter

## 2) Expected behavior

DataTable supports multiViewState since Version 6.1.
DataList and DataGrid should support multiViewState too

## 3) Actual behavior

DataList and DataGrid do not support multiViewState

## 4) Steps to reproduce

Attribute/Feature multiViewState does not exist for DataList and DataGrid

## 5) Sample XHTML

Attribute/Feature multiViewState does not exist for DataList and DataGrid

## 6) Sample bean

Attribute/Feature multiViewState does not exist for DataList and DataGrid

**Comment by Saturos88** [comment]
Vote for this feature too!

**Comment by Rapster** [comment]
@christophs78 I'd like to have your thoughts on #4329 The idea is to make the impl more concise, instead of using different keys in the session map, the same one will be used either it's a datatable, datagrid, datalist etc. 

The problem with this, is that I don't know which component hides behind the key, so methods like `PrimeFaces#clearDataListStates` can't really be implemented instead you'd use `PrimeFaces#clearMultiViewStates` which clears up everything.

Do you have a use case where you want to clear states of datalist but not datatable for example?
