### ISSUE TITLE
Datatable: always fire event cell edit

### ISSUE THREAD

**Issue by nxtruong72** [primefaces/primefaces#3397]
## 1) Environment
- PrimeFaces version: 6.2

## 2) Expected behavior
The event onCellEdit change is fired only when the value is changed.

## 3) Actual behavior
onCellEdit event is fired even I didn't change anything (just click on the cell).

## 4) Steps to reproduce
Click on the cell.

## 5) Sample XHTML
I implement as the same as this https://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml

## 6) Sample bean
I implement as the same as this https://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml

**Comment by cnsgithub** [comment]
I just tried to reproduce this issue on the showcase and can confirm. 

That's kind of weird behavior: sometimes `onCellEdit `gets called although the value didn't change. 

When looking at `datatable.js `it seems that the original intention was to only submit on changes. However, the implementor of `EditView.onCellEdit `must have known about the fact, that it is not working properly in all cases, because `!newValue.equals(oldValue)` is checked here, which normally would be unnecessary. :wink: 

JS debugging reveals that `doCellEditRequest `is called (`datatable.js`, line 2538) since `valid `is `undefined ` but `changed `is `false`.

![image](https://user-images.githubusercontent.com/13161711/36887200-5bca63ec-1df0-11e8-9e5f-abbd25aec7d5.png)

**Comment by nxtruong72** [comment]
Thanks for your reply, @cnsgithub 
Do you know a way to work-around for this ?

**Comment by cnsgithub** [comment]
I'll try to make a PR.

**Comment by cnsgithub** [comment]
Pull request: https://github.com/primefaces/primefaces/pull/3399

@nxtruong72 If it is really fundamental, you could do some dirty patching in primefaces-6.2.jar directly. Therefore change `if(d||!a){g.doCellEditRequest(k)}` in `META-INF/resources/primefaces/components.js` to` if(d||a==false){g.doCellEditRequest(k)}`. Otherwise, better wait for the next patch release.
