### ISSUE TITLE
Slider: does not allow manual decimal input

### ISSUE THREAD

**Issue by stevendegroote** [primefaces/primefaces#3400]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Affected browsers: All

## 2) Expected behavior
A slider that slides between decimal numbers should also allow manual input in the linked inputfield.

## 3) Actual behavior
Currently, the linked input field does not allow typing , or . , but only accepts 0-9

## 4) Steps to reproduce
Go to https://www.primefaces.org/showcase/ui/input/slider.xhtml
Second example: Slider with decimal values
Try to enter 4.5 in the input field. The . is ignored when typing.

## 5) Sample XHTML
https://www.primefaces.org/showcase/ui/input/slider.xhtml

## 6) Sample bean
https://www.primefaces.org/showcase/ui/input/slider.xhtml

**Comment by cnsgithub** [comment]
If you copy+paste a decimal value like -234.5 it even accepts invalid values outside the range.

![image](https://user-images.githubusercontent.com/13161711/36899859-3f22adae-1e21-11e8-8f0d-e7139dc60234.png)

See #3282  what should be done on server side should probably also be done on js side so that the user cannot enter values outside the range

Enhancement? This should be a 'Defect'

**Comment by tandraschko** [comment]
A PR is welcome here ;)

**Comment by thiagosena** [comment]
There is still a bug when using ajax with decimal values, this bug occurs in line 53 of file [SliderTemplate.java](https://github.com/primefaces/primefaces/blob/e8d31a629688934ffb863e9a08f2a8127335a8b2/src/main/java-templates/org/primefaces/component/slider/SliderTemplate.java#L53)

**Comment by tandraschko** [comment]
basically it works now BUT its not perfect and a range check e.g. should be implemented.
