### ISSUE TITLE
DataTable: addRow() widget method should use partialSubmit and avoid posting all inputs

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#3564]

**Comment by tandraschko** [comment]
Close in favor of: https://github.com/primefaces/primefaces/issues/3571

**Comment by kukel** [comment]
First of all, this has nothing to do with the EditableDatatable. It happens for a normal datatable with inputs as well. I've analyzed all this and the addRow by default processes the children of the datatable but submits the whole surrounding form (the default if nothing else is specified)

```
    addRow: function() {
        var $this = this,
        options = {
            source: this.id,
            process: this.id,
            update: this.id,
            params: [{name: this.id + '_addrow', value: true},
                    {name: this.id + '_skipChildren', value: true},
                    {name: this.id + '_encodeFeature', value: true}],
            onsuccess: function(responseXML, status, xhr) {
                PrimeFaces.ajax.Response.handle(responseXML, status, xhr, {
                    widget: $this,
                    handle: function(content) {
                        this.tbody.append(content);
                    }
                });

                return true;
            }
        };

        PrimeFaces.ajax.Request.handle(options);
},
```

By changing the `process: this.id` to `process: "@none"` **AND** adding a `partialSubmit: true`, the addRow() does not submit anything.  

This might however break existing functionality since if I remember correctly,  in IE the blur/click events might be in a different order, so the submission of the editable input in the onblur event might occur after clicking a button that does an 'addRow()'. So maybe an additional `addRow(boolean partialSubmit)` is a safer backwards compatible way to solve this.

**Comment by kukel** [comment]
So I vote to re-open this. It is as stated **NOT** related to an editableDataTable and removing that from the title makes it a generic issue.

**Comment by tandraschko** [comment]
I think you need a process=datatable, so that the datatable can trigger teh AddRowFeature.
A simple fix would be to filter out, via partialSubmitParameterFilter, all child parameters of the datatable. Similar, but much smaller, as: https://github.com/primefaces/primefaces/commit/a0cc0ca8d22ac3acec6a42f6c01c95fc3bee3e28

**Comment by kukel** [comment]
The addRowFeature seems to be working without it... I checked live in the showcase. The feature is triggered by a special parameter in the request https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/datatable/feature/AddRowFeature.java#L52 which still is there (form%3Acars2_addrow=true for the showcase)! But I'll check never the less...

**Comment by kukel** [comment]
The AddRowFeature is normally called, so it is a fix... maybe the 'skipChildren' attribute of the datatable can be used as well to do a 'partialSubmit' by default or not...

**Comment by tandraschko** [comment]
I will close it for now. No work done here and #3571 would be the real way IMO.
