### ISSUE TITLE
Title (tooltip) in components not displayed when disabled

### ISSUE THREAD

**Issue by LordFirlefanz** [primefaces/primefaces#3565]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces (6.2) version? No
- In Version 6.1 it worked.
- Application server + version: Payara 4.1.1.171.1
- Affected browsers: Tested in Chrome 65.0.3325.181 (Offizieller Build) (64-Bit) and Firefox 52.7.2 (32-Bit)

## 2) Expected behavior
Tooltip should be displayed, no matter if the component is disabled or enabled.
Tested in p:menuitem and p:commandButton. 

## 3) Actual behavior
Tooltip is not displayed when the component is disbled. 

## 4) Steps to reproduce
Just create a menuitem within a menuButton or simply a commandBotton with a title-attribute and the disabled-attribut = true, see example.
Also the <p:tooltip> does not work for diabled components.

## 5) Sample XHTML
`<p:menuButton value="Button">
      <p:menuitem value="Item" title="Title text" disabled="true"/>
</p:menuButton>
`
or

`<p:commandButton value="AnotherButton" id="btn" disabled="true"/>
<p:tooltip for="btn" value="Texxxxt"/>`

So, is it a bug or a feature? ;)
For me it is a bug cause I show important information in the title to the user why an items is disabled.

**Comment by cristhianguedes** [comment]
(UPDATE)
I had the same problem...
To fix it, I need to wrap my components with
`<h:panelGroup id="group" style="display: inline-block;">`
`<div style="width: fit-content;" title="myTitle">
`<YOUR_COMPONENT_HERE/>
`</div>`
`</h:panelGroup>`
`<p:tooltip for="group" value="value" />`

This worked very fine for me...
Too much code for a simple bug, but I found no other solution...

**Comment by LordFirlefanz** [comment]
Thank you for the workaround, cristhianguedes! I agree, it is a little much code for a simple bug. :) 
Gonna try it that way or simply skip PF 6.2, hoping that the next release works like 6.1 and lower.

**Comment by cristhianguedes** [comment]
Note: if you just need title attr, just <div> component is needed... In my case, I need both, so I create one composite component that wrapps the code for tooltip, and when needed, I put it on code...
So, this way, all components has only div for title, resulting in less code...
The way that i create my component need one wrapper, so div was a good replacement for previous wrapper (<h:pannelGroup>), so I will let it on the code when this issue was done...
But if you just need title, put only div, and if you need both title and tooltip, the best way I found is 
`<h:panelGroup id="group" style="display: inline-block;">
<cc:insertChildren/>
</h:panelGroup>
<p:tooltip for="group" value="value" />`
in an composite component...
For me, after recoding, results in less code, because with or without issue, I need div wrapper inside my previous component...
(PREVIOUS COMMENT UPDATED, FOR ANY OTHERS THAT NEED IT...)

**Comment by LordFirlefanz** [comment]
Good idea, cristhianguedes. I sometimes forget that I can create composites. :grin: 
Thank you for sharing!

**Comment by wolf97084** [comment]
How about for p:menuitem? The solution above works well for p:commandButton but not menuitem. 

SEVERE: Servlet.service() for servlet [Faces Servlet] in context with path [/cm] threw exception [javax.faces.component.html.HtmlPanelGroup cannot be cast to org.primefaces.model.menu.MenuElement] with root cause
java.lang.ClassCastException: javax.faces.component.html.HtmlPanelGroup cannot be cast to org.primefaces.model.menu.MenuElement at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeElements(TieredMenuRenderer.java:98)
	at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeMenu(TieredMenuRenderer.java:79)
	at org.primefaces.component.contextmenu.ContextMenuRenderer.encodeMarkup(ContextMenuRenderer.java:66)
	at org.primefaces.component.menu.BaseMenuRenderer.encodeEnd(BaseMenuRenderer.java:117)

**Comment by wolf97084** [comment]
Please see https://stackoverflow.com/questions/50281355/primefaces-6-2-commandbutton-title-not-working-when-commandbutton-is-disabled/50296275#50296275 Issue is from jQuery and can be fixed with CSS. Kudos to @kukel

**Comment by tandraschko** [comment]
duplicate of 3656
