### ISSUE TITLE
DefaultCommand: Problem with keypad comma with ABNT2

### ISSUE THREAD

**Issue by kemperalves** [primefaces/primefaces#3615]
## 1) Environment

- PrimeFaces version: Running PrimeFaces-6.2.3 on Mojarra-2.3.2.
- Keyboard Model: Microsoft Wireless Keyboard 800
- Keyboard Layout: Brazilian ABNT 2 https://ibb.co/kBQMOc 

ps - Tested with others anbt 2 keyboard layouts with the comma in the same position and the problem occurs too

## 2) Expected behavior

User type a comma in the keypad and the comma need to be "typed" in the component.

## 3) Actual behavior

When typing data in a form and this form has a defaultCommand, if I press the comma key in the numeric keypad inside at any input component, the defaultCommand is actioned

## 4) Steps to reproduce

Go to this page on primefaces showcase, using an keyboard with the keypad, press the comma button and the form will be submitted...

https://www.primefaces.org/showcase/ui/misc/defaultCommand.xhtml

## 5) Sample XHTML

No need, its possible to simulate in the primefaces showcase

## 6) Sample bean

No need, its possible to simulate in the primefaces showcase

**Comment by lagar84** [comment]
I am from Brazil too, and I can also reproduce the problem. But in ABNT2 layout, above numpad enter is a 'period', or 'dot', not a comma. Comma is on the left side, and does not trigger defaultCommand. The key above "keypad enter" is indeed triggering defaultCommand, and obviously should not. From the picture, is the key between the 'plus' (+) key and 'enter'.

(my keyboard is a generic mtek abnt2)

Edit: event.which report it as keycode 108

Workaround: put this in your template or xhtml file: 
```
<script type="text/javascript">
//<![CDATA[
  try{
	$.ui.keyCode.NUMPAD_ENTER = 13; //fix primefaces defaultCommand
  }catch(e){}
//]]>
</script>
```

**Comment by cnsgithub** [comment]
Sorry, I am not able to reproduce this issue, even after switching to Brazil ABNT2 keyboard layout.

**Comment by kemperalves** [comment]
This is the key in my keyboard thas are submitting the form with the defaultCommand

![whatsapp image 2018-04-26 at 14 00 46](https://user-images.githubusercontent.com/27026273/39320465-9572b58c-495a-11e8-87d1-bdc1b280c620.jpeg)

**Comment by lagar84** [comment]
In file
`https://www.primefaces.org/showcase/javax.faces.resource/jquery/jquery-plugins.js.xhtml?ln=primefaces&v=6.2.3`

line number 15806

there is this fragment:
```
(function () {
    $.extend($.ui.keyCode, {
        NUMPAD_ENTER: 108
    });
```

This is the root of the problem. Looks like 108 means different things in different keyboards. (I really don´t know in other models, but in 2 different abnt2 keyboards (home and work), 108 is mapped to period key, above numpad enter.)

To easily check, open browser dev tools and put this on input (showcase):
`onkeydown="alert(event.which)"`

Now the REALLY strange thing... in Firefox latest (windows 7, 59.02), event.which reports 108 for my period key. In Google Chrome, it reports 194, so this bug is browser dependent.

In both browsers, numpad enter and regular enter, both report keycode 13, so I don´t know if this "NUMPAD_ENTER: 108" is still necessary.

**Comment by jxmai** [comment]
Please see my investigation at https://github.com/primefaces/primefaces/pull/3455#issuecomment-386097198. 108 is keypad separator,  so `,` key that can submit the form makes perfect sense https://github.com/primefaces/primefaces/issues/3615#issuecomment-384716172

---

conclusion: keycode 108 and NUMPAD_ENTER should be removed

**Comment by melloware** [comment]
By removing this it has reintroduced the Chrome AutoFill issue:  https://github.com/primefaces/primefaces/issues/2448  
https://github.com/primefaces/primefaces/issues/4672

In PF 7.0.  So removing that NUMPAD_ENTER broke the DefaultCommand again.
