### ISSUE TITLE
Empty List SelectCheckboxMenu-grouped (ShowCase)

### ISSUE THREAD

**Issue by 1jose234** [primefaces/primefaces#3779]
Hi
Iam working with primefaces 6.2 and i need use the SelectCheckboxMenu grouped as the example in PrimeFaces [SHOWCASE](https://www.primefaces.org/showcase/ui/input/checkboxMenu.xhtml)  But the example don't work fine, because the options selected is not added in the String[].

somebody have a solution or alternative ?

thanks

![image](https://user-images.githubusercontent.com/38274938/41321836-66419144-6e6b-11e8-9c45-076d8c7140e9.png)

**Comment by jxmai** [comment]
@1jose234 FYI: the bug should be fixed by https://github.com/primefaces/primefaces/issues/3676

**Comment by 1jose234** [comment]
@jxmai    thanks for your reply, but i am  using the version 6.2, i can understand that the bug is solved  in the version 6.3, its true?

**Comment by jxmai** [comment]
No problem. Yes, the bug is solved for version 6.3. 6.3 has not been released yet so currently you may need to build the source (don't recommend for production usage though). The other option is to report it to see if it can be got into elite build.

---

By the way, this issue can be closed though since it is a duplicate one.
