### ISSUE TITLE
Ajax: Escaping XML properly for control characters

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#3875]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Application server + version: Jetty
- Affected browsers: All

Attached is a reproducible test case:  
[primefaces-xml.zip](https://github.com/primefaces/primefaces/files/2198829/primefaces-xml.zip)

Input a form feed character ("/f" in java or 0x0C in hex) into a request that is handled via ajax it causes the ajax request to fail because the xml generated is considered invalid.

XHTML:
```xml
<h:form id="browseItem" prependId="false" accept-charset="UTF-8">
	<p:tabView dynamic="true">
		<p:tab title="default tab">
			this tab will load without issue
		</p:tab>
		<p:tab title="click me for ajax parse error">
			<h:outputText value="#{testView.formFeed}"/> can you see this
		</p:tab>
	</p:tabView>
</h:form>
```

Java:
```java
    public String getFormFeed() {
        return "\f";
    }
```

Example Chrome Response:
```xml
<partial-responseid="j_id1">
  <parsererror>
    <h3>This page contains the following errors:</h3>
    <div>
      error on line 2 at column 68: Input is not proper UTF-8, indicate encoding !
      Bytes: 0x0C 0x20 0x63 0x61
    </div>
  <h3>Below is a rendering of the page up to the first error.</h3>
  </parsererror>
  <changes>
    <update id="j_idt5"/>
  </changes>
</partial-response>
```

I noticed that in PrimePartialWriter it is calling `ComponentUtils.escapeXml(json);` but that only escapes the basic XML characters and not if it contains something like Form Feed /f.   Not sure if this should be handled by PrimeFaces or if this is a JSF error but it feels like something PF should handle?

**Comment by melloware** [comment]
As a note we have `ComponentUtils.escapeXml()` which is pretty bare bones and we have `XmlUtils.escapeXml()` which is more comprehensive.  I think we had talked about in the past why the Ajax response writer uses the simpler one but I can't remember why.

**Comment by tandraschko** [comment]
Where does the parse error come from? normally JSF renders the content in CDATA?!

UPDATE: our callback params :D

**Comment by tandraschko** [comment]
What happens if we would render it inside CDATA?

**Comment by melloware** [comment]
Just more investigation here is what FireFox reports.

```xml
<?xml version='1.0' encoding='UTF-8'?>
<partial-response id="j_id1"><changes><update id="j_idt5"><![CDATA[XXX can you see this
				]]></update><update id="j_id1:javax.faces.ViewState:0"><![CDATA[9044195630476338743:8737698257514286639]]></update></changes></partial-response>
```

But the text "can you see this" is not displayed in the tab.  And the XXX is actually a control character displayed with a "dot" but not copied correctly when I tried to copy and paste.

**Comment by tandraschko** [comment]
Ok, so we must escape it and rendering it inside CDATA doesn't help, right?

**Comment by melloware** [comment]
So far the CDATA doesn't look like it works.  It escapes it but it somehow breaks the browsers parsers anyway for rendering.  I am trying a couple of things.

**Comment by melloware** [comment]
OK nothing I have tried so far has fixed the issue.  What we really need is the PrimePartialWriter to do this for every character it processes like our XMLUtils does...
```java
char c = value.charAt(i);
if (c > 0x7e) {
      sb.append("&#" + ((int) c) + ";");
}
else {
     sb.append(c);
}
```
I am wondering if it is related to this issue:  https://github.com/primefaces/primefaces/issues/3629

**Comment by mustafamizrak** [comment]
any tricky solution found to handle this defect?

**Comment by melloware** [comment]
I think at its core its a Mojarra bug: https://github.com/javaserverfaces/mojarra/issues/4370

So I am not sure if a PF fix alone can solve this issue.

**Comment by cnsgithub** [comment]
I managed to reproduce this issue only with Mojarra, it doesn't seem to be directly related to the CDATA issue. The Mojarra `PartialResponseWriter `fails to remove unicode characters which are not allowed according to the XML1.0 spec, threrefore the browsers cannot parse the ajax response. 

I opened a separate issue at Mojarra for this: eclipse-ee4j/mojarra#4516

@tandraschko maybe add the security tag, because this could be used for a denial of service

**Comment by tandraschko** [comment]
But it's not related to PF then? Does it work in MyFaces?

**Comment by cnsgithub** [comment]
Not directly I think. Client side handling fails with a different error because JQuery is used instead of a plain ``XMLHttpRequest``, but if the ResponseWriter is fixed in Mojarra, it should work for Primefaces as well. 

Haven't tested MyFaces yet.

**Comment by tandraschko** [comment]
I would be great if you can try it - primefaces-test offers a way to run with myfaces.
Could we close the issue then`?

**Comment by cnsgithub** [comment]
Just tried it with myfaces. The \u000C used in the Mojarra example is handled properly there. 

But if you try the whole range of illegal XML characters, the same type of error occurs. See the myfaces branch in [cnsgithub/mojarra-ajax](https://github.com/cnsgithub/mojarra-ajax/tree/myfaces).

**Comment by cnsgithub** [comment]
@tandraschko Since you seem to be very active there, maybe you are interested in fixing this at https://github.com/apache/myfaces? 😛 

Doing it the OWASP way should do it: https://github.com/OWASP/owasp-java-encoder/blob/master/core/src/main/java/org/owasp/encoder/XMLEncoder.java

And maybe the CDATA stuff as well:
https://github.com/OWASP/owasp-java-encoder/blob/master/core/src/main/java/org/owasp/encoder/CDATAEncoder.java

**Comment by cnsgithub** [comment]
> Could we close the issue then

Since we do not render the `partial-response` XML in [PrimePartialResponseWriter](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/context/PrimePartialResponseWriter.java) ourselves (because we simply delegate all `writes` to the wrapped `PartialResponseWriter` i.e. the myfaces or mojarra implementation) this issue seems not to be related to PrimeFaces. 

In short, yes you may close this issue. 

However, that being said means that almost all JSF applications out there are potentially vulnerable... 😢 
As long as these bugs have not been fixed in the JSF implementations servlet filters may help to filter out such illegal XML characters. @tandraschko Should we provide such a filter in PrimeFaces?

**Comment by tandraschko** [comment]
i'm very active in refactoring old code for 3.x, yes :D
Feel free to create issues there and provide a PR + unittest. I can merge it ;)

PrimeFaces is a component library, we should not fix bugs in the implementations by wrapping and wrapping and wrapping code of the JSF impls.
I can not talk about Mojarra (i'm not a commiter there) but in MyFaces we can simply fix the bug and do a release.

**Comment by cnsgithub** [comment]
@tandraschko [MYFACES-4266](https://issues.apache.org/jira/browse/MYFACES-4266)

**Comment by tandraschko** [comment]
+1
thanks

**Comment by cnsgithub** [comment]
Servlet filter workaround that might be temporarily used as long as there is no MyFaces release containing the bugfix: https://github.com/cnsgithub/mojarra-ajax/blob/master/src/main/java/main/IllegalXmlCharactersFilter.java

Also not sure how long it will take at [Mojarra](https://github.com/eclipse-ee4j/mojarra/) to provide a fix (PR https://github.com/eclipse-ee4j/mojarra/pull/4517 was closed unmerged).
