### ISSUE TITLE
Datatable: AddRow on lazy table duplicates values from last row.

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#3901]
Based on this stack overflow:  https://stackoverflow.com/questions/51485413/is-primefaces-addrow-feature-compatible-with-lazyloading-datatable

## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? NO
- Does it work on the newest sources in GitHub? NO
- Application server + version: Test App Provided
- Affected browsers: ALL

## 2) Expected behavior

Add new blank row to a Lazy Datatable should add the row with the values from the newly added POJO even if they are blank.

## 3) Actual behavior

Table is adding the row and copying the values from the last row.

## 4) Steps to reproduce

Run this sample app using "mvn clean jetty:run" and navigate to http://localhost:8080/primefaces-test/test.xhtml and press the AddRow button.

[primefaces-3901.zip](https://github.com/primefaces/primefaces/files/2225084/primefaces-3901.zip)

**Comment by melloware** [comment]
The suspicious lines are here I think:  https://github.com/primefaces/primefaces/blob/09848d4db7a6f9101a4806f82fd24fbf59cc47ff/src/main/java/org/primefaces/component/datatable/feature/AddRowFeature.java#L37

Looks like it gets the old last row and re-encodes that row?

**Comment by melloware** [comment]
Debugging further that -1 is correct.   There must be something deeper going on here.

**Comment by melloware** [comment]
Thanks to @mertsincan I was able to get the issue resolved by adding the following to my code in between the START and STOP:

```java
public void onAddNew() {
        // Add one new car to the table:
        Car car2Add = new Car();
        car2Add.setId("8675309");
        lazyModel.datasource.add(car2Add);
       
        // *** START ADD CODE ***
        lazyModel.setRowCount(lazyModel.datasource.size());
        lazyModel.setWrappedData(lazyModel.datasource);
        // *** STOP ADD CODE ***

        FacesMessage msg = new FacesMessage("New Car added", car2Add.getId());
        FacesContext.getCurrentInstance().addMessage(null, msg);
}
```

**Comment by VaazhgaV** [comment]
Thanks melloware. The solution above didn't help in my case. I modified the sample code to demonstrate the issue (with multiple pages). It is attached here. When Add Row button is clicked while on the first page, a duplicate row is added in the first page and a blank row is added on the last page. It seems like a bug and Add Row in Lazy datatable only works on Last page? 

Also in real application, we load the data (from database) one page at a time (unlike in showcase where the list is populated during PostConstruct) so I couldn't see the blank row added to the last page 
because the data is fetched from database on page change.
[primefaces-lazyaddrow.zip](https://github.com/primefaces/primefaces/files/2242727/primefaces-lazyaddrow.zip)

**Comment by melloware** [comment]
Your use case definitely might be more complicated as you are manipulating the list as you are adding to it (database paging) and inserting new records into the database.  I can see how the Add Row would be confused.   There are probably deeper issues with the lazy datatable and AddRow that need to be resolved.
