### ISSUE TITLE
Bug in p:editor 5.2 - Firefox only 

### ISSUE THREAD

**Issue by leomeurer** [primefaces/primefaces#395]
I am with the same problem that this issue https://code.google.com/p/primefaces/issues/detail?id=6580

After running an ajax update a strange "true" appear inside editor, and the editor is blocked(read only).

Environment
Primefaces 5.2
Firefox 38.0.1 (latest)
Win 7
Tomcat 7.0.42
Java 1.7.0_60

**Comment by leomeurer** [comment]
I found a workaround.

I don't know why but if you change f:ajax for p:ajax like this:

<p:ajax execute="@form" update="editorContainer" />

everything works fine.

**Comment by cagataycivici** [comment]
Thank you for the update.

**Comment by arunvc1** [comment]
Working fine if you update a section of the page
f:ajax change render="@form" to render="panelGroupId"

**Comment by mauromol** [comment]
If I understand it correctly, this was closed just because a workaround was found?

I have this problem, a p:editor in a form in a p:dialog. When the p:commandButton for "OK" is pressed, if I either specify the editor or the parent form (in any way, i.e. with @form or with its id) in the p:commandButton update, the editor content turns to "true" with Firefox 60 (while it works with Chrome).
The workaround is invalid for me, I do not have any f:ajax to turn into p:ajax (I'm just using the p:commandButton update attribute).

I think it's a severe issue.

**Comment by tandraschko** [comment]
p:editor is just deprecated because the used CLEditor is not in development anymore.

**Comment by mauromol** [comment]
I see. So, what's the recommended replacement?

**Comment by melloware** [comment]
p:texteditor https://www.primefaces.org/showcase/ui/input/textEditor.xhtml

**Comment by tandraschko** [comment]
or extensions CKEditor ;)

**Comment by mauromol** [comment]
Wow, I really missed textEditor!! Thank you very much!
