### ISSUE TITLE
Media: Resize on click when uses IE

### ISSUE THREAD

**Issue by abialas** [primefaces/primefaces#3975]
## 1) Environment
- PrimeFaces version: 6.2
- Affected browsers: Internet Explorer 11

## 2) Expected behavior

The dialog with quicktime player should have the same size when video control is clicked.

## 3) Actual behavior

Each time when the user clicks on player controls like rewind or play the dialog getting smaller

## 4) Code to reproduce

https://github.com/abialas/primefaces-test

**Comment by tandraschko** [comment]
Would be great if you can provide a PR to fix it.

**Comment by melloware** [comment]
@abialas I used you example and I can't reproduce using IE 11.472.   I also tested in Edge, Chrome and Firefox and I am not seeing the dialog move at all when fast forwarding, rewinding or anything?

When I right click on the video in IE11 it says Windows Media Player 12.0 not QuickTime.  So I am not sure what your issue is or whether its QuickTime but its definitely not anything related to PrimeFaces.  I feel like it might be a QuickTime bug.  Any more information you can give if not I would close this as not reproducible.

**Comment by melloware** [comment]
@tandraschko I was not able to reproduce this and without a reproducible test case I think this is safe to close.
