### ISSUE TITLE
New Component: BarChart

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#4011]
BarChart component use Chartjs API (http://www.chartjs.org/docs/latest/charts/bar.html) and it is created with a BarChartModel.

Demo; https://www.primefaces.org/showcase/ui/chartjs/bar/bar.xhtml

**Comment by markusg80** [comment]
Is Grouped Stacked Barchart also supported?

**Comment by mertsincan** [comment]
Hi @markusg80 ,

Stacked - yes (https://www.primefaces.org/showcase/ui/chartjs/bar/stacked.xhtml)
Stacked groups -no, I'll add it.

**Comment by melloware** [comment]
@mertsincan nice job on this!  Because ChartJS is so powerful and extensible should in the chartsjs-widgets.js should we add "extender" capability like the old Charts had.  I think this will help future proof if it someone wants to use some custom ChartsJS feature.

**Comment by mertsincan** [comment]
Thanks a lot for your feedback, @melloware. Chart components that use ChartJS are not completely finished. I'm still working on them.

**Comment by mertsincan** [comment]
@markusg80, please see 'stacked group bar' demo; https://www.primefaces.org/showcase/ui/chartjs/bar/stackedGroup.xhtml

**Comment by melloware** [comment]
@mertsincan no problem!  I figured you were still working but I wanted to make sure that didn't slip off your radar!   The new components look great.

**Comment by markusg80** [comment]
Super! You cant imagine how i‘m happy about this new chart components! Aleays bet on prime 😉

**Comment by mertsincan** [comment]
Thanks @melloware and @markusg80 ;) 

@melloware, the 'extender' feature was added to models.

**Comment by melloware** [comment]
@mertsincan Nice work!  Makes this an even more powerful component!

**Comment by mertsincan** [comment]
Thanks a lot for your feedbacks, @melloware ;) Fixed XSS issues now.

**Comment by Rapster** [comment]
Great job @mertsincan, I know a lot of people who'll be about happy to hear about this :wink:

Please don't forget to look at https://sonarcloud.io/dashboard?id=org.primefaces%3Aprimefaces, quality gate has failed since

**Comment by Rapster** [comment]
My 2 cents:

- `CartesianScales#encode()`: Maybe you could change into `CartesianScales#encode(Writer writer)`, the `FastStringWriter` is created only once (in `ChartRenderer`) and closed once.
- Comment of `CartesianScales#encode()` should be:
```java
    /**
     * Write the common options of cartesian axes
     *
     * @return options as JSON representation
     * @throws java.io.IOException If an I/O error occurs
     */
```
- Being said, maybe create an interface that will be extending by `CartesianScales` and the others, to give a better clarity to your classes

I can help you with that, I'm sure migrating ChartJs into PF takes you a lot of time :smile: 

FYI, there is a very nice plugin called `SonarLint` available on Eclipse/IntelliJ (not sure about Netbeans though) that will help you to avoid few mistakes (and avoid to wait for SonarCloud scan to see any potential bugs). I advise everyone to use it :wink:

**Comment by mertsincan** [comment]
- Sonarcloud issues related to Chartjs have been fixed. Please check it.
> Comment of CartesianScales#encode() should be: ...
- Fixed now. Thanks a lot ;)
> Being said, maybe create an interface that will be extending by CartesianScales and the others, to give a better clarity to your classes
- Maybe next time. But, if you can send a PR, I would appreciate 😄 
>  there is a very nice plugin called SonarLint available on Eclipse/IntelliJ (not sure about Netbeans though) that will help you to avoid few mistakes (and avoid to wait for SonarCloud scan to see any potential bugs). I advise everyone to use it 
- Thanks a lot!!! I'll try it. ;)

**Comment by Rapster** [comment]
@tandraschko FastStringWriter is the type to use whenever String manipulation has to be done? It is meant to replace StringBuilder in PF?

**Comment by tandraschko** [comment]
Im in vacation, lets Talk about it end of September.

**Comment by melloware** [comment]
@Rapster From what I understand FastStringWriter is used when you want to construct a components say inner children without going through the FacesResponseWriter.  it lets you collect them as strings first and then pass it to the outgoing Faces Response.    If you are just constructing strings for JSON or some other reason then normal StringBuilder is the correct choice.

**Comment by Rapster** [comment]
Sorry Thomas, enjoy and have fun!

Thank you @melloware but I don't see the real benefit over a `StringBuilder` though (specially that FastStringWriter is backed by StringBuilder)... I see MyFaces/Mojarra use it as well, so I guess I'm missing something (we can continue this conversation on gitter)

**Comment by melloware** [comment]
Yep I think its only because it supports the "Writer" interface so it can be swapped with Response Writer.  Like i said I think its when you need to render a component without sending it to Faces Response yet. so writer.write() works.

**Comment by Rapster** [comment]
Yes that's what I thought, the Writer interface... For now, I won't worry about it too much.

@mertsincan It wouldn't have be possible to create a chart just like the old chart API (e.g `<p:chart type="bubble" model="#{chartView.bubbleModel1}" />`)? Depending what the type is, ChartRenderer would delegate the rendering to an object doing the final job? It would make the chart API easier to use don't you think?

For example, I have a combobox containing a list of value which are all `ChartModel` once selected I only have to update the `<p:chart />` and the job is done. With this new approach, I'll have to make a switch/case depending the value selected (which is much more cumbersome)

BTW, are you aware of this library https://github.com/mdewilde/chart I figured it could help a lot for your devs

**Comment by Rapster** [comment]
@mertsincan what about using JSON structure instead of String? I'd recommend you to have a look in this library, which I think does exactly what you want https://github.com/mdewilde/chart. Only problem, jackson is used as a library, but can be easily(?) adapt with org.json.

Optional: I've been looking around, org.json is limited and doesn't have good benchmark, so I want to see if we could replace it by something as lightweight but better performance.

I started working on it, we can work on that if you're interested :wink: (At least let me know what you think?)

**Comment by mertsincan** [comment]
Hi @Rapster, 

Thanks a lot for the PR! But, we don't think of something like p:chartjs or p:chart; https://www.primefaces.org/primefaces-6-2-9-released/

Also, my personal idea is to add the minimal dependency(exp; com.google.code.gson) on the project. Therefore, I didn't use the gson. Cagatay said it would be more accurate to do this with Writer like FastStringWriter. 

In addition, I think it would be better if these features were added by the PrimeFaces committers ;) it will be easier for us to solve it if a problem is reported by the PRO/Community user in the future.
For example, we think of adding our own datepicker component.  As you know, jQuery UI datepicker limits us from adding new features and we are constantly trying to change its some codes. Also, when a User reports a problem with a 3rd party API, I think we are trying to understand the code of this API in the majority of our time.
Note: new DatePicker will contain new features such as multiple date selection, range selection and touch UI mode. Please see; https://www.primefaces.org/primeng/#/calendar

**Comment by Rapster** [comment]
Thank you for your answer Mert,

> In addition, I think it would be better if these features were added by the PrimeFaces committers ;) it will be easier for us to solve it if a problem is reported by the PRO/Community user in the future.

Well, I am a PF committer :smile: 

> For example, we think of adding our own datepicker component. As you know, jQuery UI datepicker limits us from adding new features and we are constantly trying to change its some codes. Also, when a User reports a problem with a 3rd party API, I think we are trying to understand the code of this API in the majority of our time.
> Note: new DatePicker will contain new features such as multiple date selection, range selection and touch UI mode. Please see; https://www.primefaces.org/primeng/#/calendar
> 

Gson would be the only 3rd party, and I'm pretty sure you won't have to do something that gson can't do :wink:

> Thanks a lot for the PR! But, we don't think of something like p:chartjs or p:chart; https://www.primefaces.org/primefaces-6-2-9-released/
> Also, my personal idea is to add the minimal dependency(exp; com.google.code.gson) on the project. Therefore, I didn't use the gson. Cagatay said it would be more accurate to do this with Writer like FastStringWriter.

Now back to the real issue... First, chartjs is driven by the model. Meaning, the model is the decisional factor of what's going to be rendered. That's make the use of the component super easy. From what you have wrote so far, if new charts are added to chartjs, you'll have to write as much component as new charts (which is big effort), and does it support [extensions](http://www.chartjs.org/docs/latest/notes/extensions.html)?

Second, regarding gson dependency, yes I'm fully aware of "one-jar" goal of PF (even though adding dependencies to PF remains one jar...). This is why I picked gson which is a lightweight json impl so we can shade it (several discussions regarding org.json, owasp etc. talk about this). So adding this dependency is not a problem.

Now comes to FastStringWriter, I'm not sure I understand what you mean by "accurate", faster maybe? Well mayyyyybe... I believe I understand why you used FastStringWriter, but I don't think this is the right approach. I would always prefer simplicity over slight performance (if there is any). FYI, using try/catch will prevent the JIT compiler to make code optimizations, but again see my comment. And by simple approach, I mean serializing POJOs.

Using a raw String to build a complex Json structure is reinventing the wheel, takes a lot of effort and also taking a big risk. Developers have been struggling for years to have the most robust library, I'm sure librairies like gson or jackson covers most of our use cases pretty well (including performance). As I said, I don't think you'll have use cases that any good json impl can't solve. Being said, you just shooting yourself in the foot by not using json impl and not using library like chart.java. Reusing this library (or another) gives you a good start, all the pojo have been created! And it's quite easy to understand since it follows chart.js model and it's basically 97% of POJOs (if you need to update the model, basically, you just need to CRUD the model. Much more easy than understanding a 3rd party like jquery calendar isn't it? :wink: )

I'm just sharing my point of view. Again I'd be happy to help :wink:
