### ISSUE TITLE
KeyFilter: drag and drop allows any character

### ISSUE THREAD

**Issue by Zerounodue** [primefaces/primefaces#4219]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: -
- Affected browsers: Chrome, Firefox, Safari... On Mac

## 2) Expected behavior

only the characters defined in the regex should be allowed

## 3) Actual behavior

every character is allowed

## 4) Steps to reproduce
**On macOS**
- Create a file with .webloc or .txt extension with this content:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>URL</key>
	<string>This is a test</string>
</dict>
</plist>
```

- Drag and drop a file from the finder into the input. The URL on the file is inserted into the input.

## 5) Sample XHTML
```
<p:inputText id="text1">
    <p:keyFilter regEx="/[ABC]/i"/>
</p:inputText> 
```

##  Screenshot

<img width="1266" alt="screenshot 2018-11-07 at 11 56 29" src="https://user-images.githubusercontent.com/9017650/48127678-a1a05580-e284-11e8-86b7-fcd062c7c628.png">

**Comment by cnsgithub** [comment]
Not only that the filter can be bypassed at frontend side, I suspect it to lack user input validation at backend side as well.

**Comment by tandraschko** [comment]
A PR would be great

**Comment by tandraschko** [comment]
i'm really not sure if this is the right component for you.
a keyfilter filters a keyboard-input and doesn't validate the input by a regex.
maybe inputMask is more correct

**Comment by cnsgithub** [comment]
`inputMask `however is not capable of regex... Also notice that there are two different regex attributes in keyFilter, `regEx `and `inputRegEx`.

**Comment by tandraschko** [comment]
Oh, can't remember... I developed this component soo many years ago

**Comment by Zerounodue** [comment]
I a looking for exactly this component and not for `inputMask` 
It works fine but i noticed this unexpected behaviour.  People should be aware that there is the possibility to enter characters that are different from what defined in the `regEx` and `mask` attributes.

**Comment by cnsgithub** [comment]
Please provide a PR.

**Comment by cnsgithub** [comment]
There seem to be some problems with jquery plugin https://github.com/akzhan/jquery-keyfilter used by `p:keyFilter` to handle mutual exclusive attributes `regEx`, `testFunction `and `mask`. 

The problem is that the plugin does not seem to handle `paste `and `drop `events at all because it's just listening to `keypress `events. The plugin is quite old and it is unlikely to get things fixed there.

On the other hand, when using `p:keyFilter inputRegEx` attribute I guess everything would be fine since @tandraschko wisely listens to jquery's `input` event which includes `paste `and `drop` as well. :wink: 

So in my opinion, I would not spend too much time and effort and fixing functionality that can be achieved in simple alternative ways, e.g. by using `inputRegEx `instead of `regEx `or `p:inputMask` instead of `mask `attribute or even` f:validateRegex` instead of `p:keyFilter`. The latter has the clear advantage that it would also be considered at backend side during validation phase.

I would drop `p:keyFilter` attributes based on `jquery-keyfilter` and just keep the `inputRegEx` attribute.

@Zerounodue Your example should work as expected when doing this:
```xml
<p:inputText id="text1">
    <p:keyFilter inputRegEx="/^[ABC]*$/i"/>
</p:inputText>
``` 

Btw, as another workaround, you could do something like `input.on('drop', function(e) { e.preventDefault(); });` to prevent drag&drop. But bear in mind that it resolves in no way the _lack of user input validation_ problem.
