### ISSUE TITLE
Add Nova and Luna Theme

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#4223]
Nova and Luna are free and open source community themes with a premium design and comes in 7 flavors;
- luna-amber
- luna-blue
- luna-green
- luna-pink
- nova-colored
- nova-dark
- nova-light

**Comment by cossioricardo** [comment]
Hi, i need how know to apply the themes, please can you help me?

**Comment by cnsgithub** [comment]
@cossioricardo 
General information on how to apply a theme: [user guide](https://www.primefaces.org/docs/guide/primefaces_user_guide_6_2.pdf), section 8.1

If you have elite or pro subscriptions, you can download the latest version from https://www.primefaces.org/downloads/. 
@mertsincan Despite PF 6.2.11 being released as mentioned in your [blog post](https://www.primefaces.org/primefaces-6-2-11-released-with-modern-themes-and-icons/) the download is still missing? Edit: After login to the store it'll be available.

Otherwise you may build PF 6.3-SNAPSHOT on your own.

Go to https://www.primefaces.org/showcase/ui/misc/themeSwitcher.xhtml to see the new themes in action.

**Comment by czare** [comment]
Can you please point me out the right way to add luna and nova themes? I can't find their libraries at the prime faces repository, neither any tutorials teaching how to add those specific themes. I know how to add a theme, I just can't find a way to add nova and luna themes. Thanks.

**Comment by melloware** [comment]
@czare Nova and Luna are included in PF 7.0 core JAR. So there is no other additional jars to add they are built in.  Simply reference them like you were doing with Aristo or whatever previous theme you were using.

**Comment by czare** [comment]
Thank you @melloware!
