### ISSUE TITLE
FileUpload: Classloading Error in JSF 2.1

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#4236]
## 1) Environment
- PrimeFaces version: 6.2.11, 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? NO
- Does it work on the newest sources in GitHub? NO
- Application server + version: Mojarra 2.1
- Affected browsers: ALL

Error trying to upload on JSF 2.1.

> [WARNING] /primefaces-test/test.xhtml
> java.lang.NoSuchMethodError: org.apache.commons.fileupload.servlet.FileCleanerCleanup.getFileCleaningTracker(Ljavax/servlet/ServletContext;)Lorg/primefaces/shaded/commons/io/FileCleaningTracker;
>     at org.primefaces.webapp.filter.FileUploadFilter.createFileItemFactory (FileUploadFilter.java:122)
>     at org.primefaces.webapp.filter.FileUploadFilter.doFilter (FileUploadFilter.java:92)
>     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1634)
>     at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter (WebSocketUpgradeFilter.java

Attached is a sample test project proving the issue. 
[pf-fileupload.zip](https://github.com/primefaces/primefaces/files/2573569/pf-fileupload.zip)

**Comment by melloware** [comment]
Reported through PRO account.

Relates to: https://github.com/primefaces/primefaces/issues/4198

**Comment by fcorneli** [comment]
Indeed rather painful to see this on a PrimeFaces production release:
`Caused by: java.lang.NoSuchMethodError: org.apache.commons.fileupload.servlet.FileCleanerCleanup.getFileCleaningTracker(Ljavax/servlet/ServletContext;)Lorg/primefaces/shaded/commons/io/FileCleaningTracker;
        at org.primefaces.webapp.filter.FileUploadFilter.createFileItemFactory(FileUploadFilter.java:123) [primefaces-6.2.11.jar:6.2.11]
        at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:93) [primefaces-6.2.11.jar:6.2.11]`

hint: Selenium based QA tests....

**Comment by cnsgithub** [comment]
@fcorneli Feel free to provide meaningful selenium UI tests for each component. :wink: That would be a great benefit for the community!

**Comment by fcorneli** [comment]
@cnsgithub The reason why I have an ELITE subscription, is because I don't have time to deal with such things in the first place.

Regarding the community edition: I understand that it's not always -from a moral/business point of view- easy to find the sweet spot between quality of community edition and creating -how to put it- a "reason" for subscriptions. But if I look at the number and age of open bugs in Github, maybe PrimeTek swinged a bit too far to one side, no?

Regarding the pay-for-it edition: with all due respect for the hard work being done, but bugs as these should be captured by some QA process...

**Comment by cnsgithub** [comment]
@fcorneli Have you reported this bug to PrimeTek through your ELITE account? I don't have any insights on how quickly things get resolved there... I agree, those bugs should be captured somehow... But I think we're already going in the right direction, e.g. @Rapster introduced sonarqube shortly and installed a quality gate. Did you know that? Anyway, testing should be done more eagerly.

**Comment by tandraschko** [comment]
There is something wrong with shading:
org/primefaces/shaded/commons/io/FileCleaningTracker

this file shouldn't even be shaded

**Comment by tandraschko** [comment]
Fixed it. @mertsincan can you port it and test the attached project with elite?

**Comment by mertsincan** [comment]
Thanks @tandraschko ;)
