### ISSUE TITLE
PF shortcut for PrimeFaces util class

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#4350]
Just a shortcut which uses PrimeFaces.current() -> PF.current().

Nothing special, just makes the line lenghts bit shorter.

**Comment by Rapster** [comment]
I would have simply rename `PrimeFaces` into `PF` and make all methods static, to make the use of this util more straightforward. I don't see the benefit of this new util, save 8 characters on the line?

Being said, I would personnaly rename every `PrimeXXX` classes into `PFXXX`

**Comment by tandraschko** [comment]
1) static is not nice
2) We don't have any class with starts with "PrimeFaces" - only the Prime"FacesContext"
3) We newly introduced "PrimeFaces" last release, renaming it now isn't good

**Comment by Rapster** [comment]
1. What's not nice about it? You might think static is not nice but every call done by `PrimeFaces` methods delegate to a static method, so I'm not sure if it makes sense to change that...

2. The idea is to make it shorter and understandable, `PF` is the acronym we used most of the time so, it sounds better to me than "Prime" prefix

3. Your call, if you think it sounds better, it's better to do it now, RC1 is not released yet and for elite version, it's not like a huge breaking change. Otherwise let it be

That's only my opinion :wink:

**Comment by tandraschko** [comment]
1) where are static methods? As PrimeFaces is the main entry for user-utils its much better to make the instance exchangable. Also for unittesting.

2) i dont see a benefit, it saves 3 chars and none of the classes are used by users

3) i dont see a reason to do that. We can still deprecate and move slowly. I will leave it as it is. PF js method is also just a shortcut.

**Comment by Rapster** [comment]
1. Take for example PrimeFaces#isAjaxRequest(): under the hood it's a static which is called (same goes for all the methods, either they are or do not depend on a PrimeFaces instance: so static). Unit test is a good argument though... What's the use of PrimeFaces#instance? So far, not much no? I guess that's for "exchangable" purposes, even though I'm not sure what you mean by that (considering the current code since it's not used anywhere)

2. What you're saying contradict this ticket then, what's the benefit to save 8 chars on the line? _(I should have said "I would personnaly rename every `PrimeXXX` classes into `PFXXX`" my bad _(updated)_... but I don't honeslty don't mind leaving it like this)_ 

3. Your call, I don't mind

In the end, I think developers need a PF _(or `PFaces` just thought about it)_ util containing shortcuts but definitely not like this https://github.com/primefaces/primefaces/commit/d925b6370dcb5964e93b1396bf0484dd88b4e723. If I understand what you want to do, you want to make the use of PF API less verbose for users. Also, to do this, we need a proper reflexion about what `PF`  should look like. IMO, we should be able to call methods like this `PF.update("form")`, or `PF.getContext()` etc. (full of static methods). This class internally delegates calls to PF/JSF API. This API however should be as less static as possible, to make it unit-testable.

**Comment by tandraschko** [comment]
1) PrimeFaces#setInstance can easily be used in UnitTests, same like the JSF FacesContext#setCurrentInstance or in the old RequestContext. This exchangeable instance was even used in the past from users to fix a possible XSS.
The handling is absolute the same as in JSF, i just shortened the getCurrentInstance to current (like in CDI).
I just decided the make the instance static instead of doing the same in the old RequestContext as there should not be a performance difference and we save 1 instance per request.

2) The difference is internal<>external API. I like PrimeXXX more then PFXXX, so thats just matter of taste.


3)
