### ISSUE TITLE
Dialog Framework: DOM XSS through conversation parameter

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#4383]
## 1) Environment
- PrimeFaces version: 6.3-snapshot

## 2) Expected behavior
It's not sufficient to escape the `pfdlgcid` conversation parameter in `DialogNavigationHandler.java` when constructing the `openDialog` call. 
Since it's added to the DOM in `openDialog` function at the client side it needs to be escaped there as well.

## 3) Actual behavior
The `pfdlgcid` request parameter is user-supplied input and therefore can be used to enable DOM XSS.

## 4) Steps to reproduce
1. Open http://localhost:8080/showcase/ui/df/data.xhtml?pfdlgcid=test%22%3E%3Cscript%3Ealert(%27xss%27)%3B%3C%2Fscript%3E%3Cdiv%20data-pfdlgcid%3D%22test.
2. Click at the _Select Car_ button.

**Comment by cnsgithub** [comment]
@melloware Since you already provided PRs for all other recent XSS issues: did you forget this one? :stuck_out_tongue_winking_eye:

**Comment by melloware** [comment]
I did miss it. Can you review my fix please?

**Comment by tandraschko** [comment]
@melloware Thanks for all those PRs!

**Comment by mallorygiles** [comment]
Should this also prevent javascript:alert(1) from being passed for pfdlgcid? Asking because when scanning my application, it reports XSS vulnerability for my dialogs. Also XSS vulnerability reported when passing pfdlgcid=%3Cimg+src%3Dx+onerror%3Dalert%281%29%3B%3E because the response then contains
`<![CDATA[PrimeFaces.closeDialog({pfdlgcid:'<img src=x onerror=alert(1);>'});;]]>`

**Comment by melloware** [comment]
But did you try the above steps in the test?  do you actually get a javascript alert?  I cannot reproduce using the steps in the ticket.

**Comment by mallorygiles** [comment]
I do not get the alert when I try, but since it was flagged as a possible vulnerability, I wanted to make be sure it's looked into. I'm not a pen-tester or hacker, but I just imagine that if it can be put into the response, then it can probably be exploited somehow. For example, if they already can get `pfdlgcid:'<img src=x onerror=alert(1);>'` what's stopping them from closing out that `<![CDATA[PrimeFaces.closeDialog({pfdlgcid:'` with the value they pass and then inserting a script.

**Comment by melloware** [comment]
I am not a pen tester either but I don’t think unless you can get it to alert that it’s vulnerable. What tool is telling you it is?

**Comment by mallorygiles** [comment]
I used OWASP ZAP.

**Comment by melloware** [comment]
Hmm @cnsgithub care to weigh in here?
