### ISSUE TITLE
TreeTable/DataTable: Header row is misplaced when blockui is set for the table and stickyHeader is true

### ISSUE THREAD

**Issue by ken-han** [primefaces/primefaces#4393]
## 1) Environment
- PrimeFaces version: 6.2
Note: Using version 6.2.13 gives the same result

- Application server + version: Wildfly 13
- Affected browsers: Firefox and Chrome (not tested on any other browser)

## 2) Expected behavior

![image](https://user-images.githubusercontent.com/46558687/50971226-c662b480-14e3-11e9-9266-976e43a9bc16.png)

## 3) Actual behavior

Two header rows are visible, one of the rows is in a silly position.
![image](https://user-images.githubusercontent.com/46558687/50971285-f01bdb80-14e3-11e9-8d99-95cd2780c7cc.png)

## 4) Steps to reproduce

Clone and run this repo: https://github.com/ken-han/primefaces-treetable-blockui-bug
Important notes: This happens when the treeTable has stickyHeaders and a blockUI is linked to the treeTable

NOTE: When not at the top of the screen, the table looks less messed up.
![image](https://user-images.githubusercontent.com/46558687/50971527-7fc18a00-14e4-11e9-80d1-b49ea64aa1ed.png)

**Comment by melloware** [comment]
@ken-han Any debugging you have done as to why or provide a PR to help us fix it?

**Comment by sbcontinuum** [comment]
In order for `BlockUi` to be contained to the view it is attached to, it adds `position: relative` to the DOM element we are attaching it to (the table in this case).

`StickyHeader` gets `postion: absolute` with `top` and `left` offsets that are based on the position of the actual table header relative to the page root. (e.g. `top: 50px; left: 20px`). An element with `position: absolute` gets positioned relative to its nearest parent container that has `position: relative`. 

When we have both of these options enabled, `StickyHeader` is positioned relative to its parent element (the table in this case, because of `BlockUi`), but its offset is calculated relative to the page root. (e.g. `top: 50px; left: 20px` relative to the position of table instead of page root).

A possible solution could be to let `StickyHeader` `top` and `left` offsets be `0` if its parent has `position: relative`

**Comment by melloware** [comment]
@sbcontinuum Interesting proposal.  Interested in trying it and submitting a PR?
