### ISSUE TITLE
new feature request for confirmDialog in <p:ajax /> and or <p:droppable />

### ISSUE THREAD

**Issue by 452** [primefaces/primefaces#467]
I think this be wonderful to use:

one global `<p:confirmDialog />`

``` xhtml
<p:confirmDialog widgetVar="confirmation" global="true" showEffect="fade" hideEffect="explode">
    <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
    <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
</p:confirmDialog>
```

`<p:ajax />` with `<p:confirm />`:

``` xhtml
<p:ajax listener="#{catalogBean.onDragDropTree}" update="nomenclatureTable msgs">
    <p:confirm header="Confirmation" message="Are you sure?" icon="ui-icon-alert" />
</p:ajax>
```

`<p:droppable />` with `<p:confirm />`:

``` xhtml
<p:droppable for="selectedCategoryNode">
    <p:ajax listener="#{catalogBean.onDragDropTree}" update="nomenclatureTable msgs">
    </p:ajax>
    <f:attribute name="category" value="#{node}" />
    <p:confirm header="Confirmation" message="Are you sure?" icon="ui-icon-alert" />
</p:droppable>
```

**Comment by cagataycivici** [comment]
p:ajax and p:confirm are both behaviors so not possible to nest them, they can be chained though. Confirm support for droppable could be useful it is too much work and we'd prefer waiting for more user requests regarding this. So closing it for now, if more users demand it we'll reopen. Thank you for your feedback.

**Comment by dreadk2002** [comment]
I am also in need of the feature with confirm on ajax, as described in: http://stackoverflow.com/questions/20581634/show-confirmdialog-before-roweditor-updates-the-model.
I don't want to use a js confirm like onstart="return confirm('Are you sure?')", because I need more control and I want it to look as the standard primefaces dialog and I don't want to tinker too much with jquery(client's request - use primefaces components, don't create custom components or workarounds).
