### ISSUE TITLE
inputmask doesn't work properly with tooltip and tooltip need a update @form to work

### ISSUE THREAD

**Issue by joaopmi** [primefaces/primefaces#4768]
Hi, i'm making a web page with jsf2.3 and [primefaces 7.0] https://mvnrepository.com/artifact/org.primefaces/primefaces/7.0) and i was thinking in using p:tooltip to display front-end validation messages. First of all the p:tooltip disappear after i update a single component related to it, i need to update the entire form or panel of the inputs to the tooltip work properly and stay normal, so i need to update all the inputs unnecessaries to a single tooltip.
Second is the inputmask, when i use a tooltip related to it, it doesn't erase the input from user if it not matches the mask.
Ex:
```
<p:inputMask id="input" mask="999"/>
<p:tooltip for="input" value="Tooltip"/>
```

then if i insert only one 9, it will not disappear even with autoclear="true". But if i remove the tooltip, it works normally.

Thanks!!!

**Comment by tandraschko** [comment]
Please create a ticket for each issue, we don't mix X issues in 1 tickets.

the first issue is by design as we need to reregister the event listener of tooltop when the input was removed and readded. Maybe we can resolve it by other jquery binding mechanism. @melloware we had a similar ticket for another component. Do you remember?

**Comment by melloware** [comment]
Nothing is coming to mind but I think you are right we had a similar issue.  once he creates the ticket with test case we can experiment.
