### ISSUE TITLE
fileUpload: Update works sporadically

### ISSUE THREAD

**Issue by mallorygiles** [primefaces/primefaces#4843]
1) Environment
- PrimeFaces version:
Tried on versions 7.0, 7.0.2. 7.0.3

Browsers: I initially discovered while using IE 11, but also was able to reproduce in the showcase using Chrome 74.

 2) Expected behavior
After uploading a file, the component given by "update" should always update

 3) Actual behavior
The component given by "update" does update sometimes, but frequently, it does not.

 4) Steps to reproduce
I was able to reproduce using the showcase. https://www.primefaces.org/showcase/ui/file/upload/single.xhtml

I select a file then click upload. The growl message does not always appear as it should. It usually takes me 3 or less tries to reproduce.

5) Sample XHTML
6) Sample bean
See showcase code

**Comment by melloware** [comment]
Hmmm I just tried it 9 times in a row in Chrome 74 and the growl appeared every time?

**Comment by mallorygiles** [comment]
I just noticed something. When I tried with a file that is 40 KB, it always appears, but with a file that s 20 KB it never appears. Could it be in the short difference in time it takes to upload those 2 files?

**Comment by melloware** [comment]
Possibly. I tried it with file as small as 6K and as large as 88K and all of them seems to work.

**Comment by mallorygiles** [comment]
I think I've narrowed it down now. It has to do with the file extension, and not the file size. The showcase has allowTypes="/(\.|\/)(gif|jpe?g|png)$/". Of course if I try to upload a .txt file for instance, I get a warning message saying "Invalid file type" before I can even try to upload. If I select a file that has .PNG or .GIF in all caps, I don't get the "Invalid file type" message and can upload, but I also don't see the message growl get updated either.

I am still having an issue with the update not always working that's not tied the file type. Since my usage of fileupload is not as simple as that of the showcase (inside a dialog, hiding the fileupload component and using a separate button to trigger a click to the fileupload), I'll search for a workaround.

**Comment by melloware** [comment]
Its probably related to all the security fixes add to check file names and content etc.  https://github.com/primefaces/primefaces/issues?q=is%3Aissue+filename+is%3Aclosed

**Comment by mallorygiles** [comment]
I don't know if I should open a separate issue for this, or rename this one, but can there be some type of indication when a file is rejected because of these other security measure. I can see my users uploading a file such as this, and then wonder why there was no message to say that the upload was successful or not.

After looking at the issue in the link you gave, my uneducated guess would be that it was "check allowTyped on server side" #2791 that may have caused this. Is there a way to display a message when the server side file validation fails?

**Comment by melloware** [comment]
Maybe it’s the showcase code not properly written but I believe it throws an exception that could be handled and display an error message.  The showcase might not be doing that.

**Comment by melloware** [comment]
@mallorygiles Can you confirm?  I am seeing it throw proper exceptions in the server side code.

**Comment by mallorygiles** [comment]
I do not see an exception. My code is as follows:
`<p:fileUpload id="upload" fileUploadListener="#{reportUploadHandler.handleFileUpload}"
                              mode="advanced" auto="true" widgetVar="upldWV" update="upldPnl"
                              allowTypes="/(\.|\/)(pdf|xlsx|xlsm)$/"/>`

`public void handleFileUpload(FileUploadEvent event) {
        currentUploadedFile = event.getFile();
    }`

I even added in the dependency to tika
`<dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-core</artifactId>
            <version>1.19.1</version>
        </dependency>`

My environment is:
Primefaces 7.0.3
JDK 11
JBoss EAP 7.2

**Comment by melloware** [comment]
@mallorygiles You are right.   Looking at this code if the "allowTypes" does not match it simply sets the submitted value to "" instead of throwing an error.

https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/fileupload/NativeFileUploadDecoder.java#L83-L88

@cnsgithub All it does is LOG a message but gives the user no feedback when the file type is not valid if it does not match allowTypes etc?

**Comment by melloware** [comment]
another temporary fix is to make the regex case insensitive like adding the "i" option.

```
/(.|/)(gif|jpe?g|png)$/i
```

**Comment by melloware** [comment]
OK I figured this out.  So if you have a file name like "test.JPG" with a capital extension the UI is checking this...
https://github.com/primefaces/primefaces/blob/663f06f4ea3c6049ef279982549883830af11cfb/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js#L446

Its check the file type "image/jpeg" or the file name "test.JPG" matches the allowTypes regex.  Since the file type is "image/jpeg" its passing the check.   However when it gets to the server side its failing the file name check as the file name does not match the allowType REGEXP.

To fix this we would need to do 1 of the 2 following solutions:
1. Remove the File Type check from the UI.
2. Even though we have Tika checking types on the backend we would need something that did this same check where the regexp was checked against the MIME Type OR the file name.

**Comment by tandraschko** [comment]
+1 for 2)

**Comment by melloware** [comment]
Agree with #2 submitted a PR and updated unit tests.
