### ISSUE TITLE
ColumnToggler: Label Issue on ColumnToggler

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#4891]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? NO
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: All
- Affected browsers: All

## 2) Expected behavior
Only Label should be show in p:columnToggler

...

## 3) Actual behavior
OutputLabel  value and Tooltip value are show in p:columnToggler
![image](https://user-images.githubusercontent.com/15189434/59362358-4db98b80-8d01-11e9-8cdd-6c34ebe5573a.png)

..

## 4) Steps to reproduce

Change code is showcase.

.. 

## 5) Sample XHTML

```
<p:column>
                <h:outputText value="#{car.id}" />
                <f:facet name="header">
		        <p:outputLabel value="ID" id="outputTextID"/>
			<p:tooltip value="Tooltip for ID" for="outputTextID"></p:tooltip>
		</f:facet>
</p:column>
```

..

## 6) Sample bean
NA
..

**Comment by melloware** [comment]
Looks like multiple duplicates and a solution posted:

https://github.com/primefaces/primefaces/issues/2479
https://github.com/primefaces/primefaces/issues/1592

Looks like we can kill 3 tickets with 1 fix.  Care to try out the solution and submit a PR?

**Comment by melloware** [comment]
I just tested it and it works great.  Want me to submit the PR?

**Comment by ravihariharan** [comment]
i was about to look at the issue and you have already tested the fix.  Thanks @melloware

**Comment by melloware** [comment]
Still testing looks like its not quite working all the way.

**Comment by melloware** [comment]
OK please code review my PR. I tested using your exact example.

**Comment by ravihariharan** [comment]
@melloware  the fix is working. Thanks

**Comment by ravihariharan** [comment]
@mertsincan  can this be tagged for 7.0.5?

**Comment by mertsincan** [comment]
@tandraschko and @melloware,

I think there are three ways to fix this issue;
1) wb.initWithWindowLoad instead of wb.init on encodeScript
2) Users can add a class such as ui-columnToggler-label, etc. and we can find it in columnToggler's render method then, we only write the text of this label into columnToggler's item.
3) After DataTable is loaded, we can throw a callback to load columnToggler widget;
```
// core.js
onElementLoad: function(element, listener) {
            if (element.prop('complete')) {
                listener();
            }
            else {
                element.on('load', listener);
            }
        },
```
Unfortunately, ```<div>``` element doesn't support load event :/ Therefore, we need to do this manually

Also, we have an issue on 7.1 about columnToggler; https://www.primefaces.org/showcase/ui/data/datatable/columnToggler.xhtml
Steps;
- Click "Columns" button to open the panel
- Click it again to close the panel
- Clicking again will not open the panel
@melloware, could you please check it? Maybe, it doesn't work on my browser ??? Thanks a lot ;)

WDYT?

**Comment by melloware** [comment]
@mertsincan A few things.

1. This fix just addressed the Column Toggler finding the "wrong" element and using it as a label.  It seems a huge improvement in expected behavior.  I have seen other comments about adding a custom style to find the right element for the label which is cool but a user would have to know to look in the documentation for that style.  I am still OK with that but we should also leave my "find the first label" fix in.

2. As for the Showcase I am seeing the same thing in Chrome and Edge.  If you click the button and click anywhere outside the button it works every time. But if you click the button to close it it won't re-open without 2 clicks.

**Comment by mertsincan** [comment]
Thanks a lot for the update, @melloware ;) Users can use span tag instead of label tag in f:facet;
var label = columnChildren.find('label');
Maybe, we can change the above code in your fix.

Thanks again ;)

**Comment by melloware** [comment]
So I think what you are saying is we need to support both SPAN and LABEL so any of these would work...

```xml
<f:facet name="header">
	<p:outputLabel value="ID" id="outputTextID"/>
</f:facet>
```

```xml
<f:facet name="header">
	<h:outputText value="ID" id="outputTextID"/>
</f:facet>
```

```xml
<f:facet name="header">
	<span>ID</span>
</f:facet>
```

**Comment by mertsincan** [comment]
Hi @melloware,
> we need to support both SPAN and LABEL so any of these would work...
OR <p> , <u> etc.  Please see;
![image](https://user-images.githubusercontent.com/11868120/62761511-8a9ac800-ba8f-11e9-9b4c-d619cc8820e6.png)
```
          <p:column>
                <h:outputText value="#{car.id}" />
                <f:facet name="header">
		        <p:outputLabel value="ID" id="outputTextID"/>
                        <span>Test</span>
                        <p>test2</p>
			<p:tooltip value="Tooltip for ID" for="outputTextID"></p:tooltip>
		</f:facet>
            </p:column>
```

Hi @ravihariharan,
You need to use globalTooltip with globalSelector attribute such for such these issues. Please remove tooltip in column. 
You will see the same problem when exporting data. Therefore, please use globalTooltip.

Exp;
```
<p:tooltip globalSelector="a,:input,:button,.header" />
<p:dataTable id="cars" var="car" value="#{dtBasicView.cars}">
      <p:column>
                <h:outputText value="#{car.id}" />
                <f:facet name="header">
                    <p:outputLabel value="ID" id="outputTextID" styleClass="header" pt:data-tooltip="Tooltip for ID"/>
                </f:facet>
            </p:column>
```

**Comment by melloware** [comment]
@mertsincan I read your comment and I don't see the problem?  if a "label" is found in a header then that label is used for the toggler else it uses the detault. In your example where you have an Label, a Span, and a text it finds the label and uses that for the column.  To me the column doesn't make sense if your Column Toggler had "ID test test2" as the column title. The fact that you included a label means you want the label to be used specifically as the Column Toggler name.

And also since it was reported on 3 different tickets this is clearly an issue the community keeps running into that to me needs to be fixed.

**Comment by ravihariharan** [comment]
Create a PR for - Documentation : ColumnToggler: Label Issue on ColumnToggler #5062
