### ISSUE TITLE
MenuItem: NullPointerException

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#4963]
All menus seems to be broken currently with an NPE.

See: https://www.primefaces.org/showcase/ui/menu/menu.xhtml and click on Save menu.

```
java.lang.NullPointerException
        at org.primefaces.component.menu.BaseMenuRenderer.findMenuitem(BaseMenuRenderer.java:86)
        at org.primefaces.component.menu.BaseMenuRenderer.decode(BaseMenuRenderer.java:67)
```

**Comment by tandraschko** [comment]
PR would be great :)

**Comment by melloware** [comment]
I have been searching through the fixed issues trying to determine what could have caused this break.

**Comment by Rapster** [comment]
I quickly analysed the problem last night, the problem appears with static ajaxified items, @melloware 
 can you confirm? 

Basically key `clientId + "_menuId"` is not set in request parameters. So first, I tried to find where this "_menuId" is supposed to be set, and apparently it's in `BaseMenuRenderer#encodeMenuItem`. But it is set if item has been programmatically built, see https://github.com/primefaces/primefaces/blob/91dd496976a3aa0a31ca392625b8ede0701d37be/src/main/java/org/primefaces/component/menu/BaseMenuRenderer.java#L194

And since, the menuitem is defined in xhtml, the key is not defined and occurs a crash.

**Comment by melloware** [comment]
Yep i noticed that too.  But looking through commit history it looks like this code has not changed in a long time.  That is why I am stumped trying to figure out what change caused this.

**Comment by Rapster** [comment]
Same here, we'll have to try with an older version of PF

**Comment by Rapster** [comment]
Working on it

**Comment by Rapster** [comment]
I think there is 2 issues here:

1. This test is wrong, it's not clientId but should be  `clientId + "_menuid"` https://github.com/primefaces/primefaces/blob/91dd496976a3aa0a31ca392625b8ede0701d37be/src/main/java/org/primefaces/component/menu/BaseMenuRenderer.java#L65
2. Now, how it worked before? Well in 7.0, this test was not returning true back then

I'm trying to figure out, what change has been made so that clientId is in the request map from now on

UPDATE: Fixing 1. makes no crash but action not called :(

**Comment by melloware** [comment]
Was is this fix that caused it adding the client ID now?  https://github.com/primefaces/primefaces/issues/4898

**Comment by melloware** [comment]
I am really stumped to find the change that broke this or seeing how it ever worked before.

**Comment by Rapster** [comment]
Found the problem...

This is 7.1
![image](https://user-images.githubusercontent.com/7521311/60762536-33a26d00-a063-11e9-859e-907ad19a356c.png)

And 7.0
![image](https://user-images.githubusercontent.com/7521311/60762540-44eb7980-a063-11e9-8e20-70e1b54294e1.png)

The `source` is wrong, that's why action is not called, this is due to 2dddd4b8ce9649ea850e1a14038877cb067d154d, @tandraschko could you fix it please?

**Comment by Rapster** [comment]
I'll try to make a proposal and you'll let me know what you think

**Comment by Rapster** [comment]
I'm not really happy with the fix, I think it's actually a temporary fix... I would have a closer look to these `buildAjaxRequest` methods which are too many in my opinion. WDYT?

**Comment by melloware** [comment]
Well I know this was refactored because the copy and past of building Ajax requests was all over the code.  This was an attempt to standardize the call and it also fixed a few issues like this one: https://github.com/primefaces/primefaces/issues/2358 .  So I like the refactoring it just looks like for Menus this regression was introduced.

**Comment by Rapster** [comment]
I'm not talking about the refactoring itself, I think it's a good thing at the end of the day. I'm saying since they are 3 possibilities (and i'm sure there is a good reason for it) but it's quite easy to make a mistake. And since I had a closer look, I must say it's hard to analyse. IMO, javadoc should be introduced about these methods.

I'll try to suggest something if something comes up to my mind. I just need to make sure why we have `UIComponent` and `AjaxSource` as parameter?

**Comment by melloware** [comment]
Ahh I understand now, yes the clearer we can document the API the better!

**Comment by Rapster** [comment]
@tandraschko I made a few cosmetics change on 2afc4a80e8e317a8ef688a160eb66aebad34dbbe, hope you'll be cool with it

**Comment by Rapster** [comment]
@tandraschko could you confirm that `BaseMenuRenderer#buildNonAjaxRequest` is more or less a duplicate of `CoreRenderer#buildNonAjaxRequest`. The difference I see is the support of params in `BaseMenuRenderer#buildNonAjaxRequest`?

**Comment by tandraschko** [comment]
Not exactly. We can easily move the params support to CoreRenderer but CoreRender also supports target AFAICS. We would need to check this
