### ISSUE TITLE
SelectBooleanCheckbox: Not updating model when used with DataTable with editMode="cell"

### ISSUE THREAD

**Issue by ReedElliott** [primefaces/primefaces#5088]
## 1) Environment
- PrimeFaces version: 7.0.4
- Does it work on the newest released PrimeFaces version? Unknown
- Does it work on the newest sources in GitHub? Unknown
- Application server + version: GlassFish 5.1
- Affected browsers: Firefox

## 2) Expected behavior

Checking and unchecking the checkbox should update the model object bound to the widget.

The issue was described in issue https://github.com/primefaces/primefaces/issues/1854.

I believe the issue was closed because a work around was described.  However, the work around is not ideal because it requires a round trip to the server.

@BalusC provided a description of the issue and a potential fix in the [SelectBooleanCheckbox in editable DataTable doesn't change](https://stackoverflow.com/questions/27862661/selectbooleancheckbox-in-editable-datatable-doesnt-change) stackoverflow question.

## 3) Actual behavior

Checking and unchecking the checkbox has no effect on the model object.

## 4) Steps to reproduce

See https://github.com/primefaces/primefaces/issues/1854

## 5) Sample XHTML

See https://github.com/primefaces/primefaces/issues/1854

## 6) Sample bean

See https://github.com/primefaces/primefaces/issues/1854

**Comment by melloware** [comment]
Looks like this has changed quite a bit since BalusC's first suggestion but the problem still remains..
https://github.com/primefaces/primefaces/blob/61be8893c644ac6b6b011719cab777a3cf27bd37/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L2617-L2654

**Comment by melloware** [comment]
@ReedElliott Can you do me a favor and try this on your page?

Just add this javascript to your page which will override the Datatable Save Cell.  Let me know if this works and fixes the issue.

```javascript
PrimeFaces.widget.DataTable.prototype.saveCell= function(cell) {
        var inputs = cell.find('div.ui-cell-editor-input :input:enabled'),
        changed = false,
        valid = cell.data('valid'),
        $this = this;

        if(cell.data('multi-edit')) {
            var oldValues = cell.data('old-value');
            for(var i = 0; i < inputs.length; i++) {
                var input = inputs.eq(i),
                    inputVal = input.val(),
                    oldValue = oldValues[i];

                if(input.is(':checkbox')) {
                    inputVal = inputVal + "_" + input.is(':checked');
                }
                
                if(inputVal !== oldValue) {
                    changed = true;
                    break;
                }
            }
        }
        else {
            var input = inputs.eq(0),
                inputVal = input.val(),
                oldValue = cell.data('old-value');
            
            if(input.is(':checkbox')) {
                inputVal = inputVal + "_" + input.is(':checked');
            } 
            changed = (inputVal !== oldValue);
        }

        if(changed || valid == false)
            $this.doCellEditRequest(cell);
        else
            $this.viewMode(cell);

        if(this.cfg.saveOnCellBlur) {
            this.currentCell = null;
        }
    };
```

**Comment by ReedElliott** [comment]
@melloware 
After removing the ajax call from my checkbox and adding your script above, I was able to change and save the checkbox state, so your script appears to work.   Unfortunately, after adding the script, I noticed an unwanted post from the client to the server when I selected a new row on my table.

**Comment by melloware** [comment]
@ReedElliott is that unwanted post related to my fix?  Can you revert and do you see the unwanted post?  When you debug the unwanted Post in the F12 network browser you should see its origin for example who is generating that post and what "event" caused it.

I also just updated my script slightly above to use "!==" instead of "!=" can you try again?

**Comment by ReedElliott** [comment]
@melloware 
The POST does seem to be related to your script.   My current working code has a p:ajax tag embedded in my checkbox.  Using this code, I see a POST when I change the state of the checkbox and the post is related to the selected checkbox. 

If I remove the p:ajax from my checkbox, I do not get any POSTs when changing the state of the table's checkboxes, but the checkbox state does not display or save correctly.   

If I remove the p:ajax and add your script, I see a POST when I select another component after selecting a checkbox.  The following are some values from the POST Params:

- javax.faces.partial.ajax: true
- javax.faces.source: my dataTable

The data sent in the POST contains all the data from the form.

The checkboxes display and save correctly when using your script.

**Comment by melloware** [comment]
Can you do a Celledit with just a simple PrimeFaces Inputtext and change the value of the text?  I bet you see the same POST with our without my code.  Because the datatable has this code...

```javascript
if(changed || valid == false)
            $this.doCellEditRequest(cell);
```

Which looks like it send the POST data of the CellEdit whenever the Cell Edit changes.  So it looks like that is how the CellEdit changes get propagated to the server side.

**Comment by ReedElliott** [comment]
You're correct.  If I change the value of a text box and exit the checkbox, I see similar looking post to the one I reported seeing after adding your code.   If I enter invalid data in the text box such as a null value in a field that doesn't accept nulls, p:messages displays an error.   I remember struggling with these validation POST in cell edit dataTables in the past because they send the entire form even though you only need to validate a single field.

I wonder if this bug was associated with the original developer trying to prevent this validation POST on checkboxes because checkbox don't need validation.

**Comment by melloware** [comment]
So the way CellEditing works is when the CellEdit is change it does a FORM POST to basically fill out your backing bean with the value that was just changed.    The checkbox not submitting was definitely a bug because in the code directly above it they were handling checkboxes in "RowEdit" mode just not in CellEdit mode.

So I am going to fix this bug.  However, if your real goal is you only want to submit the 1 cell that was edited and not resubmit the whole datatable that is not going to be fixed.  That is the way the datatable works.

If however that is what you really desire then that is exactly why we wrote the PFE Sheet component.  it only submits the single cell you edit each time and does not resubmit the whole sheet.  See: https://www.primefaces.org/showcase-ext/sections/sheet/basicUsage.jsf
