### ISSUE TITLE
Timeline throws null pointer exception when using "select" and "add" ajax event

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#5118]
if users select that event after adding a new event, the timeline throws an exception.

Test code;
```
<h:form id="myform">
    <p:timeline id="timeline" value="#{customTimelineView.model}" widgetVar="myTimelineWidget" 
                editable="true" selectable="true" eventMargin="10" eventMarginAxis="0"  
                start="#{customTimelineView.start}"  
                end="#{customTimelineView.end}"  
                showNavigation="true"
                showButtonNew="true" axisOnTop="true" stackEvents="false"
                var="event" varGroup="group" groupMinHeight="50"
                zoomMin="3600000" zoomMax="35000000000"
                eventStyle="box">
        <p:ajax event="rangechanged" oncomplete="console.log('rangechanged event')"/>
        <p:ajax event="add" listener="#{customTimelineView.onAddEvent}" oncomplete="console.log('add event')"/>
        <p:ajax event="select" oncomplete="console.log('select event')"/>
        <p:ajax event="edit" oncomplete="console.log('edit event')"/>
    </p:timeline>
</h:form>
```

**Comment by jasonex7** [comment]
Is the method `#{customTimelineView.onAddEvent}` adding the new `TimelineEvent` to `TimelineModel`? Because when the backing bean method is fired, the timeline javascript event is already added on UI so you have to add the new TimelineEvent to the TimelineModel object to keep sync. If you want to cancel the add in UI then you have to call `cancelAdd();` javascript method in `onstart` property of <p:ajax event="add" />

I see that on PrimeFaces Extension docs:

![image](https://user-images.githubusercontent.com/16229253/64438068-071fc700-d08d-11e9-9fa0-59f4e360a3a4.png)

By this commit ff603e3 you are cancel the add of the timeline javascript event on UI always.
