### ISSUE TITLE
Timeline: Support for multiple events with same data

### ISSUE THREAD

**Issue by mores** [primefaces/primefaces#5143]
## 1) Environment
- PrimeFaces version: 7.0.7
- Does it work on the newest released PrimeFaces version? No Version? 7.0.7

## 2) Expected behavior
You should be able to move an event - the label on the event gets updated.

## 3) Actual behavior
The label on the event is changed - but a duplicate event is created.

## 4) Steps to reproduce
https://github.com/mores/primefaces-test/tree/timeline001-updater
mvn jetty:run-exploded

## 5) Sample XHTML
see github

## 6) Sample bean
see github

![image](https://user-images.githubusercontent.com/1318377/64738451-3aaf8680-d4bd-11e9-92d1-c65e8ef38023.png)

Then slide and event left:
![image](https://user-images.githubusercontent.com/1318377/64738482-4e5aed00-d4bd-11e9-85e4-e76ad9763bf7.png)

Now slide that same event right:
![image](https://user-images.githubusercontent.com/1318377/64738503-5dda3600-d4bd-11e9-963d-82fc17bdfb54.png)

**Comment by melloware** [comment]
@jasonex7 Care to investigate this one and see if its fixed in your new vis.js branch?

**Comment by jasonex7** [comment]
I've investigated and the problem is the current implementation of TimelineModel assumes that TimelineEvent data property is unique (you can see `equals` and `hashCode` of TimelineEvent), but this example uses the same data (string in this case) among multiple TimelineEvent, so in the method model.getIndex(timelineEvent) we get the wrong id and then update a different timeline event on UI.

> `int index = model.getIndex( timelineEvent );`

https://github.com/mores/primefaces-test/blob/eca0b26570d2bec374df973e07f352828e90731f/src/main/java/org/primefaces/test/CustomTimelineView.java#L79

In order to allow TimelineEvent's data property can be repeated, I think we should change the implementation of TimelineModel in particular methods `getIndex`, `add`, `delete`, `select` and `getOverlappedEvents` because TimelineEvent doesn't has an id (or index) property (see https://github.com/primefaces/primefaces/issues/3245#issuecomment-526622772).

**Comment by melloware** [comment]
Couldn't we just fix the equals() and hashcode() of TimelineEvent to account for more than the data?  Such as start and stop date to make the object unique?  would that solve this issue?  So the same data could be attached to 2 different events as long as the start/stop were different.

**Comment by melloware** [comment]
OK I just tested it with PF 7.0 and I get the issue but if I test with 7.1-SNAPSHOT I do not see this issue.

**Comment by melloware** [comment]
You can test it with 7.1-SNAPSHOT by just changing the pom.xml to this..

```xml
 <dependency>
     <groupId>com.github.primefaces</groupId>
     <artifactId>primefaces</artifactId>
     <version>master-SNAPSHOT</version>
 </dependency>
```

That will use the JitPack version which is the latest SNAPSHOT from GitHub Master.

**Comment by jasonex7** [comment]
> Such as start and stop date to make the object unique?

I think we didn't resolve the real problem doing that, because in that case we couldn't have two events with the same data and with the same start and end date which the timeline javascript component (any version, old and new) already allows and can be displayed nicely using stackEvents="true".

**Comment by jasonex7** [comment]
> OK I just tested it with PF 7.0 and I get the issue but if I test with 7.1-SNAPSHOT I do not see this issue.

I've just test that and the issue is still present:

![timeline-test](https://user-images.githubusercontent.com/16229253/64806004-e73e4680-d557-11e9-9854-97f82f1c83a1.gif)

**Comment by melloware** [comment]
Ahh its not as drastic on 7.1 it happens really fast on my machine.  in 7.0 I get it leaving the old one behind.

So what is the proposed fix?

**Comment by jasonex7** [comment]
I propose to change the implementation of TimelineModel to behave similiar to a list (in fact the events property is an ArrayList) and require user pass index param on `update`, `delete`, `select` and `getOverlappedEvents` methods and remove (or deprecate if you wish) `getIndex` method. Also create a property called `index` in event classes `TimelineModificationEvent` and `TimelineSelectEvent` for the listeners could know the index of the added/edited/removed TimelineEvent.

**Comment by melloware** [comment]
You are right I think we almost have to do that to make this type of issue go away.  Want to do that in your 7.1 PR since we already making major changes why not fix this along the way?

**Comment by jasonex7** [comment]
Yeah, is a good fix. I'll do on my PR.

**Comment by mores** [comment]
Since you are overhauling this feature.....Assuming you have more than 1 model ( as in linked timelines ) is there an easy way reference the correct model after the changed event fires ?

**Comment by jasonex7** [comment]
> is there an easy way reference the correct model after the changed event fires ?

You can use `timeline.getValue()` method to obtain `TimelineModel`.

**Comment by jasonex7** [comment]
> I propose to change the implementation of TimelineModel to behave similiar to a list (in fact the events property is an ArrayList) and require user pass index param on `update`, `delete`, `select` and `getOverlappedEvents` methods...

@melloware I encountered a problem with this approach, specifically in `delete` method. Imagine you have 3 instances of `TimelineEvent` in `TimelineModel.getEvents()` property which (an ArrayList) with indexes 0, 1 and 2 respectively. Then you delete the one with index=1 in that list, then automatically the TimelineEvent on index 2 has now index = 1, but in the UI the id property is still 2. Another thing related to this https://github.com/primefaces/primefaces/issues/3245#issuecomment-526622772 😄 

I've tested this with my current PR #5113 and this problem raises. So, in order to maintain the given decision of not include an `id` property in `TimelineEvent` class (which has caused little trouble 😅), I recommend change the TimelineModel implementation to behave like a map instead of a list and change `events` property from `ArrayList` to `TreeMap`. What do you think?

**Comment by melloware** [comment]
Or should we just bit the bullet and create a String "id" field that can be assigned by user or if not we can autoAssign it with UUID.random(). ???  We definitely need some unique identifier and index definitely doesn't feel right.

**Comment by jasonex7** [comment]
I'd like to create a `private final String id` property in `TimelineEvent` as I was intended, then add that property in new constructors and change existing ones to use `UUID.randomUUID().toString()` to auto assign it and change equals and hashCode of TimelineEvent to consider only the new id property. Also change the corresponding TimelineModel, 1-timeline.js and other classes to use the id property instead of an index. What do you think @melloware?

**Comment by melloware** [comment]
I like it. We have to have something unique or else we will never be able to solve theee problems.

**Comment by jasonex7** [comment]
@melloware I suggest changing the title of this issue to something like: Timeline: Support for multiple events with same data.

**Comment by melloware** [comment]
Done.

**Comment by mores** [comment]
I think it would be useful if the group on https://www.primefaces.org/docs/api/6.1/index.html?org/primefaces/model/timeline/TimelineEvent.html was an Object and not just a string. 
My use case is that this group is backed by a database and I need the primary key when an event changes groups - but I don't want to display that primary key inside that string....
Should I create a new issue to track that request ?

**Comment by jasonex7** [comment]
> I think it would be useful if the group on https://www.primefaces.org/docs/api/6.1/index.html?org/primefaces/model/timeline/TimelineEvent.html was an Object and not just a string.

That wouldn't be necessary, you can use TimelineGroup and then use their id field (String) as TimelineEvent group parameter. You must add TimelineGroup instances to TimelineModel as you add TimelineEvent instances.

**Comment by mores** [comment]
Great ! Perhaps that calls for another example in the showcase.

**Comment by jasonex7** [comment]
Yeah, I think an issue in showcase should be open for adding the old examples from primefaces extensions.

**Comment by melloware** [comment]
I created a new issue in the showcase project: https://github.com/primefaces/showcase-facelift/issues/63
