### ISSUE TITLE
PieChartDataSet class doesn't implement Serializable

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#5195]
Reported By PRO User;
> The class “org.primefaces.model.charts.pie.PieChartDataSet” does not implement “Serializable” interface which results in the following error: “java.io.NotSerializableException”.

**Comment by melloware** [comment]
@mertsincan It shouldn't have to implement Serializable because it extends ChartDataSet which does implement Serializable?

All the charts were made serializable with this commit: https://github.com/primefaces/primefaces/commit/f3c1486c8be7c32592214ea1e45e30ff54345145#diff-43f82afaac54773f920aad579bcc0380

> If superclass is serializable then subclass is automatically serializable : If superclass is Serializable, then by default every subclass is serializable. Hence, even though subclass doesn’t implement Serializable interface( and if it’s superclass implements Serializable), then we can serialize subclass object.

**Comment by christophs78** [comment]
Maybe this fix makes some sense as patch for 6.2. But not for 7.0 and later. (Because 7.0 contains the commit mentioned by @melloware.)

**Comment by tandraschko** [comment]
Then please remove it If the superclass already has it. Can someone provide a PR?

**Comment by melloware** [comment]
I will fix it.

**Comment by mertsincan** [comment]
Thanks @melloware ;)
