### ISSUE TITLE
TabView with dynamic tabs is not compatible with ui:repeat

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#523]
We have a tabView with dynamic tabs. Each tab has the same appearance but different data (and respectively different data holders). We build a table using ui:repeat and those data holders (p:inputText). The first tab works well, but the second, third, etc. tab won't persist the values entered in the inputText.
After a lot of debugging we found out, that the values of each tab is always stored in the inputText components of the first tab. It looks like a bug in the state saving of the tabView - but I'm far away from a pro concerning the insides of JSF.

**Comment by kukel** [comment]
most likely in some way releated to https://github.com/primefaces/primefaces/issues/88. Also check the old googlecode issuelist. I think it was also mentioned there as an issue.

**Comment by fanste** [comment]
As an additional note: We do not use the p:dataTable but a normal HTML table build using ui:repeat.

Our version is 5.2, sorry that I forgot to mention it.

**Comment by mario-s** [comment]
I got the same problem with a p:dataTable in dynamic tabs, the version is the same.

**Comment by ghost** [comment]
I think it is related to this:
https://code.google.com/p/primefaces/issues/detail?id=7190
https://github.com/primefaces/primefaces/issues/720

i can reproduce a similar issue with a p:tabView (with data model) and a nested p:datagrid or ui:repeat: inputs and commandLinks doesn't work. Only the last tab work and gets the right value binding

**Comment by JensPiegsa** [comment]
I'm also facing this somewhat major issue in PrimeFaces 5.3 (running on Mojarra 2.2.12-jbossorg-2). 
It struck me as submitting the form only triggered validation of the fields in the last tab. Figuring out the underlying problem was really time-consuming.

Please consider reviewing [issue 7217](https://code.google.com/p/primefaces/issues/detail?id=7217) and [its discussion](http://forum.primefaces.org/viewtopic.php?f=3&t=39020) for example code exposing the bug, a possible explanation and a "horrible" workaround.

Are the any plans to fix this?

**Comment by cagataycivici** [comment]
This has to be fixed on ui:repeat as it cannot find out if it is nested in data iteration. Since we can't change it, I guess we need to add p:repeat.

Somewhat related is;

https://github.com/primefaces/primefaces/issues/998

**Comment by cagataycivici** [comment]
@tandraschko What do you think about p:repeat to solve issues like these?

**Comment by cagataycivici** [comment]
I've created p:repeat to solve cases like these, please see #999
