### ISSUE TITLE
DataTable: In liveScroll and on update data rows duplicity

### ISSUE THREAD

**Issue by astranCZ** [primefaces/primefaces#5230]
##  1) Environment
- PrimeFaces version: 7.0 and 7.1-SNAPSHOT
- Application server + version: Apache Tomcat/7.0.47
- Affected browsers: Chrome, Firefox, Explorer

## 2) Expected behavior

After updating datatable not dupliciting rows

## 3) Actual behavior

Rows are duplicated after datatable update

## 4) Steps to reproduce

1) Load data to DataTable
2) Scroll to end data in DataTable (50 rows)
![image](https://user-images.githubusercontent.com/15103640/66392005-f685a800-e9ce-11e9-889e-32348996e3d7.png)

3) Update data in DataTable by click on button (scrollBar has moved)
![image](https://user-images.githubusercontent.com/15103640/66392058-1917c100-e9cf-11e9-8a20-efc7e8abdd59.png)

4) Scroll to end data in DataTable (in table are some rows duplicities - 80 rows)  
![image](https://user-images.githubusercontent.com/15103640/66391843-7bbc8d00-e9ce-11e9-8aff-d5ea2b29b283.png)

## 5) Sample XHTML
```
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>

<h:body>
	<h:form>
		<h3>On-Demand Data</h3>
		
		<p:commandButton value="Refresh"
			actionListener="#{testController.loadCars}" update="tcars"
			styleClass="btn btn-success btn-sm" />

		<p:dataTable id="tcars" widgetVar="cars" var="car"
			value="#{testController.cars}" scrollRows="20" scrollable="true"
			liveScroll="true" scrollHeight="150">
			<p:column headerText="Id" footerText="Id">
				<h:outputText value="#{car.id}" />
			</p:column>
			<p:column headerText="Year" footerText="Year">
				<h:outputText value="#{car.year}" />
			</p:column>
			<p:column headerText="Brand" footerText="Brand">
				<h:outputText value="#{car.brand}" />
			</p:column>
			<p:column headerText="Color" footerText="Color">
				<h:outputText value="#{car.color}" />
			</p:column>
		</p:dataTable>

	</h:form>
</h:body>
</html>
```

## 6) Sample bean

```
private List<Car> cars;

public void loadCars() {
	cars = createCars(50);		
}
	
private List<Car> createCars(int size) {
        List<Car> list = new ArrayList<Car>();
        for(int i = 0 ; i < size ; i++) {
            list.add(new Car(String.valueOf(i), "Skoda", 2019, "Gray", 300000, true));
        }         
        return list;
}

public List<Car> getCars() {
	return cars;
}
```

**Comment by JeeDevUser** [comment]
The wrong behavior seems to depend on the total number of elements in the LazyDataModel (I mean, what return getRowCount() )as well as on values of 

scrollRows=.. rows=...
properties
 For example:
- if LazyDataModel.getRowCount() returns 50, then following combinations:
`    ....scrollRows="15" rows="40"...
    ...scrollRows="20" rows="40"...
`
work as expected, BUT with 
`   ... scrollRows="20" rows="20"...
   ... scrollRows="20" rows="30"...
`

this problem can be reproduced.

**Comment by JeeDevUser** [comment]
Any news about this problem?
Basically, with this problem, the LazyDataModel remains useless...The 8.0 RC2  may be a good opportunity to fix this ;-)

**Comment by melloware** [comment]
Feel free to submit a PR.

**Comment by JeeDevUser** [comment]
Sorry, but what is PR exactly?
Do you mean I need PrimeFaces PRO, in order to have bug fix, or what?

**Comment by melloware** [comment]
a PR = Pull request meaning you have debugged the problem and fixed it and you are providing a fix back to the community.

You could also sponsor is via PrimeFaces PRO.

**Comment by JeeDevUser** [comment]
@melloware, can I comment some observations here? I think I found where the problem lies....and a solution.
The problem affects
https://github.com/primefaces/primefaces/issues/3002
also.
Consider **DataTableRenderer.java,** and following method:
```
public void encodeTbody(FacesContext context, DataTable table, boolean dataOnly, int columnStart, int columnEnd, String tbodyId)
```
Consider following part inside that method:
```
if (table.isVirtualScroll()) {
     int virtualScrollRowCount = (table.getScrollRows() * 2);
     rowCountToRender = virtualScrollRowCount > rowCount ? rowCount : virtualScrollRowCount;
}
```
Now, if p:dataTable have folowing settings:

`scrollRows="20" rows="30"`

_and LazyDataModel.getRowCount() returns 57, then _**rowCountToRender**_ becomes 40
-This implies that
```
`protected void encodeRows(FacesContext context, DataTable table, int first, int last, int columnStart, int columnEnd)
```
will be called with first = 0, last = 40 param values.
So, the for loop in that method goes from 0 to 39.
Now, consider
```
table.setRowIndex(i);
```
statement in that for loop.
**When the  i counter reaches value of p:table rows attribute ( = 30), as a consequence of above statement, the LazyDataModel.setRowIndex() will be called, and Model's internal rowIndex goes to zero!:
```
this.rowIndex = (rowIndex % pageSize); // <-- 30 % 30 = 0 !
```
AND THIS IS WHY TABLE RENDERER renders rows from start (from row at position zero, next 10 rows**
This is why rows duplicates.

**HERE IS A FIX, I think that mentioned part form DataTableRenderer.encodeTbody(...)  can be thrown out from source code, safely**
```
if (table.isVirtualScroll()) {
     int virtualScrollRowCount = (table.getScrollRows() * 2);
     rowCountToRender = virtualScrollRowCount > rowCount ? rowCount : virtualScrollRowCount;
}
```

Tested this, and works without any problem for me.
..huh?

**Comment by melloware** [comment]
So are you saying removing this block entirely fixes your problem?
```java
if (table.isVirtualScroll()) {
     int virtualScrollRowCount = (table.getScrollRows() * 2);
     rowCountToRender = virtualScrollRowCount > rowCount ? rowCount : virtualScrollRowCount;
}
```

**Comment by JeeDevUser** [comment]
**" So are you saying removing this block entirely fixes your problem? "**
-Yeah, exactly.
As I said (because I tried this solution with LazyDataModel), the original issue is:
https://github.com/primefaces/primefaces/issues/3002
which is closed, but _not _resolved. However, I think, the fix I provided here can be applied on this issue as well. I tested solution with paginated and non-paginated  p:dataTable, and with various values for scrollRows and rows properties, and I have not encountered any problem.

**Comment by melloware** [comment]
I submitted your fix for PrimeTek to review.

**Comment by JeeDevUser** [comment]
Thanks.
Please, let me know the result, and do not forget to mention the original issue:
https://github.com/primefaces/primefaces/issues/3002
P.S. If the solution is accepted, may I introduce myself as PrimeFaces contributor? ;-)

**Comment by mertsincan** [comment]
Hi all,

Unfortunately, I don't understand this issue and PR. When I review the above sample code to replicate this problem,
the dataTable has liveScroll="true" but we'll remove the code block that has if(table.isVirtualScroll()). Why??

@JeeDevUser Could you please create new ticket for your issue?

Best Regards,

**Comment by JeeDevUser** [comment]
@ mertsincan ,
" but we'll remove the code block that has if(table.isVirtualScroll()). Why??"
-Because that part of code leads to duplicate rows rendered.

Actually, you should refer to:
https://github.com/primefaces/primefaces/issues/3002
That’s where the virtualScroll is used
(my mistake, sorry, i was supposed to write a comment there but i got confused so I wrote here)
Read the explanation I gave above carefully.
The problem only happens for certain values of scrollRows, rows and LazyDataModel.getRowCount().
For example, scrollRows="20" rows="30", and when getRowCount() returns 57

**Comment by melloware** [comment]
@JeeDevUser I think you should create a reproducible sample using: https://github.com/primefaces/primefaces-test so @mertsincan can see the issue.

**Comment by astranCZ** [comment]
Here is sample (using https://github.com/primefaces/primefaces-test) with defect
[primefaces-test-scrool.zip](https://github.com/primefaces/primefaces/files/4070195/primefaces-test-scrool.zip)

**Comment by JeeDevUser** [comment]
Excellent, thanks @ astranCZ .
@melloware, here is reproducible sample :-)

**Comment by melloware** [comment]
@mertsincan we now have a reproducer for you to look at the issue

**Comment by 123MarkA321** [comment]
I have resolve this problem in Code. After update the DataTable you must reset the scrolloffset state.
```java
//reset result table offset
final DataTable dataTable =  (DataTable)FacesContext.getCurrentInstance().getViewRoot().findComponent("dataTable");

if (dataTable != null) {
  dataTable.setScrollOffset(0);
}
```

**Comment by melloware** [comment]
Thanks to @astranCZ for the reproducer and @123MarkA321 for the hint I have fixed it and submitted this PR: https://github.com/primefaces/primefaces/pull/5908

The trick was 2 things:
1) resetting the scrollOffset back to 0
2) In the JS code after refresh it was still scrolling to row 20 causing a 2nd ajax request on refresh.  Now it resets the table back to the first row on refresh and prevents that 2nd AJAX request
