### ISSUE TITLE
Refactor DefaultStreamedContent + LazyDefaultStreamedContent for Java8

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#5241]
See: https://github.com/primefaces/primefaces/issues/1124

i think we can merge LazyDefaultStreamedContent  to DefaultStreamedContent with usage of a Supplier for the InputStream.

**Comment by tandraschko** [comment]
LazyDefaultStreamedContent has been removed
DefaultStreamedContent now takes a Supplier<InputStream> as constructor argument

**Comment by tandraschko** [comment]
also see #1124

**Comment by Rapster** [comment]
12 constructors -> good reason to use a builder :wink:

**Comment by Rapster** [comment]
I think there is a slight difference between this new version and the old `LazyDefaultStreamedContent`. Whenever `DefaultStreamedContent#getStream` is called, it will constantly instanciate an `InputStream` considering the example given in #1124 

To make it truely lazy maybe reusing `org.primefaces.util.Lazy` instead of `Supplier`? Or add another attribute of type `InputStream` that gets initialized when `DefaultStreamedContent#getStream` is called the first time?

**Comment by tandraschko** [comment]
not sure in which case it should make a big difference but changed it to Lazy + builder ;)

**Comment by Rapster** [comment]
As I said, it's a slight difference. Either choose builder pattern or multiple constructors but both does not  make sense.

**Comment by tandraschko** [comment]
thats by purpose - i don't like to break applications in that way just because of cosmetics.
We could however deprecate it.

**Comment by Rapster** [comment]
+1 deprecate constructors (except no arg) sounds good
