### ISSUE TITLE
EL functions: Add array/list support for page authorization related functions

### ISSUE THREAD

**Issue by irieill** [primefaces/primefaces#5268]
When checking page authorization with p:ifAllGranted(), p:ifAnyGranted() or p:ifNotGranted() you have to build a String containing all roles. When working with constant imports by e.g. using p:importConstants you have to concat one role with another by e.g. #{Role.A += ',' += Role.B += ...}.

It would be very nice if one could just pass an array or list of roles by e.g. #{[Role.A, Role.B, ...]}.

Even if one prepares the valid roles in backing bean he would benefit. Just array or list initialization instead of error-prone string concatination.

**Comment by Rapster** [comment]
<del>Not sure though if varargs are well supported in EL specification, see https://stackoverflow.com/a/9913396/4605161</del>

From omnifaces, BalusC created n functions because varargs were not supported in JSF functions. That would explain why PF have implemented that way. I had a try implementing it and I ended up with an exception

**Comment by melloware** [comment]
I have an idea i will submit a PR for review.

**Comment by Rapster** [comment]
Okay I found a workaround using `String[]` as a signature

**Comment by melloware** [comment]
Does String[] cover using any java.util.Collection of Strings like `List<String>`? 
The PR I submitted follows other PF patterns found in SelectOne etc.

**Comment by melloware** [comment]
Looking more at it maybe change to `String[]` is the correct fix?

**Comment by Rapster** [comment]
First, I'm not a big fan of `Object` parameters, indeed it's convenient since you can use the same method for different expected types like String, String[], Collection, but seeing a method expecting Object parameter makes me always wonder "what the hell does it expect?! How does it work?!" While using varargs is quite convenient in that sense: simple and clear.

Not sure if it's the best but I prefer using `String[]` but I need to test with older JSF versions and impls, and from what I can see IntelliJ is not happy about `String[]` even though it works

Another question is, if it's working properly, should we deprecate `SecurityUtils#ifAllGranted(String role)` in favor of `SecurityUtils#ifAllGranted(String... roles)`

Let me know your thoughts

**Comment by melloware** [comment]
I agree with you on `Object`. If you get it to work with String[] and it works on older JSF that feels like the simplest change.   Also will let @tandraschko weigh in.

**Comment by Rapster** [comment]
Yup i'm not submitting anything before hearing his thoughts

**Comment by tandraschko** [comment]
Overloading with Array is ok for me but please also try old containers like glassfish 3 or tomee5

**Comment by Rapster** [comment]
I don't think it's needed to test with older containers, since JSF functions are built by impls (e.g Mojarra: see `FaceletTagLibProcessor` and MyFaces: see `TagLibraryConfig`). So far I've tested with latest impls, I'll have to give a shot to 2.0 impls)

**Comment by Rapster** [comment]
I gave a quick polish to SecurityUtils, ~but I don't think passing an object fix that issue. The user wants to pass either a `varargs` or `Object[]` in EL facelet function. The fix won't give the possibility to do as such, unless you use an intermediate bean that does the conversion from Object[] to String (of course).~

My bad, I didn't see the `[]` in the EL
