### ISSUE TITLE
TabView: rendered flag is ignored on dynamic tab

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#5301]

**Comment by michaelMarquard** [comment]
Hello @tandraschko , 
I have a JSF view that contains the following snippet
```
<h:form rendered="#{anlagenverwaltung.initialized}" id="formAnlagen">
<p:tabView dynamic="true" cache="false" activeIndex="#{tabHandler.wrap(component).activeIndex}" id="tabs">
...
<p:tab title="#{anlagenverwaltung.findNameTab2()}" rendered="#{!anlagenverwaltung.readOnly}" id="tab2">
...
 something 
that is only allowed if anlagenverwaltung.initialized == true  
and  crashes for anlagenverwaltung.initialized == false 

...
</p:tab>
</p:tabView>
</h:form>
``` 
where `anlagenverwaltung` and `tabHandler` are some CDI-Bean.

This worked fine with Primefaces version `8.0`, 
but after upgrade to version `10.0.0` 
it works when **rendering the view** for `anlagenverwaltung.initialized == false` (the form is not rendered)
but it crashes 
in `com.sun.faces.lifecycle.RestoreViewPhase.doPhase()` 
when **clicking a `<h:commandLink>` in a different `<h:form>` in this view** that renders a **different** view 
since the **content** inside the `<p:tab ...>` is rendered even if `anlagenverwaltung.initialized` is still `false`. 

Interesting to note:
The `rendered`-EL of the `<p:tab ...>` (`anlagenverwaltung.readOnly`) 
and the `title`-EL (`anlagenverwaltung.findNameTab2()`) 
would also crash   for `anlagenverwaltung.initialized == false` 
but it is the **content** of the `<p:tab ...>`  that causes the crash.
It seems that the `rendered`-EL and the `title`-EL of the `<p:tab ...>` are not evaluated.

Is this related to this closed issue #5301 or is this a different (new) issue? 
(I couldn't find any description for this issue. Is there any? How can I view it?)
Is there a chance that the issue that you solved re-appeared in version `10.0.0`?

Kind regards,

Michael

**Comment by melloware** [comment]
@michaelMarquard please create  an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  If you can reproduce it with 11.0.0 then open a new issue.

Also i wouldn't use 10.0.0 i would go to 11.0.0 as it fixed so many more issues than 10.

**Comment by michaelMarquard** [comment]
@melloware , thank you for your quick reply! 
`11.0.0` fixed the problem! 
Sorry that I did not try this version prior to comment on the present issue.

Kind regards,

Michael

**Comment by melloware** [comment]
No problem glad its resolved!
