### ISSUE TITLE
calendar: yearrange can not handle 2 dates in the past

### ISSUE THREAD

**Issue by rcroonenberghs** [primefaces/primefaces#5392]
PF 7.0.7
browser FF, chrome, edge
server: wildfly

## 2) Expected behavior
I put in a calendar component with yearrange "c-76:c-14" to be able to limit the selection for dates where a person is at least 15 years old. I expect the year initially show is current year.

## 3) Actual behavior
When you open the selector the date is defaulted show as december 1943. When clicking on a day (example14) it returns 14/12/2019. That is good, but the fact that initially it displays 1943 is not. 
When I put "c-76:+1" it displays december 2019. 
in both cases the possible year selection is correct.

![2019-12-03 11_18_00-Salesperson details -](https://user-images.githubusercontent.com/8414821/70042685-9b7fc400-15bf-11ea-9318-7044f5a0d678.png)

## 4) Steps to reproduce

put a calendar component with yearrange '-76:-14'
						

## 5) Sample XHTML

<p:calendar id="dateofbirth" label="#{msg.person_dateofbirth}" value="#{contact.dateOfBirth}" small="true" statusmessage="true" locale="#{ws.locale}" showOn="button" yearRange="-76:-14" navigator="true">				
						</p:calendar >

**Comment by melloware** [comment]
I don't think your using it correctly.  When I do your use case above I get the same results because your initial `#{contact.dateOfBirth}` is NULL.  

The `yearRange` only affects the years available for selection in the dropdown. So you need to START the calendar at a date within that year range.

Attached is my example project you can run with "mvn clean jetty:run-exploded" and navigate to http://localhost:8080/primefaces-test/test.xhtml to see it working.

I basically set the initial date value to 4/3/1997 which is inside your range of "-76:-14" and the date is correct and now you **CANNOT** select a date outside that range.

Attachment: 
[pf-5392.zip](https://github.com/primefaces/primefaces/files/3916566/pf-5392.zip)

**Comment by rcroonenberghs** [comment]
ok, that makes sense.
