### ISSUE TITLE
SelectManyButton: accesibility

### ISSUE THREAD

**Issue by dariorios** [primefaces/primefaces#546]
The component selectManyButton doesn't have navigation properties. I can't put a tab index for the component. If I use the tab keyboard to move inside it, The focus tab pass to the nearest component that can navigate. But I can't navigate between the buttons of this component, which is a accesibility problem.

**Comment by workmonitored** [comment]
I have the same issue. This is due to rendering of the input component of each choice. It is rendered with a display of none. That causes it to be skipped. I'd suggest following the jquery ui button where it's rendered but still accessible with a size of 1px. This would cause each button to be toggleable by the keyboard as well. Not sure if keyboard toggle via space will work without looking at the code. Please refer to this url for an example http://jqueryui.com/button/#checkbox . Thanks.

**Comment by tandraschko** [comment]
Still the same with the current version?

**Comment by workmonitored** [comment]
I am no longer using primefaces at my job.

On Jun 29, 2017 9:19 AM, "Thomas Andraschko" <notifications@github.com>
wrote:

Still the same with the current version?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/primefaces/primefaces/issues/546#issuecomment-311999655>,
or mute the thread

**Comment by melloware** [comment]
Just tested this with the Showcase and the Tab key is working properly and navigates to each option properly.  So this has been fixed over the last few years at some point.
