### ISSUE TITLE
DataTable: multiViewState reset doesn't work correctly

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#5463]
Checkout and open:
http://localhost:8080/showcase/ui/data/datatable/tableState.xhtml

If you click on "Clear table state" in the second table, only one clientId is processed in #showMessage.

@Rapster can you check that?

**Comment by tandraschko** [comment]
stop
the reset itself is called, just the DataTable somwhoe isn#t resetted

**Comment by tandraschko** [comment]
hmm weird, it seems to work as it should now 
probably because of #5464 

Could @melloware or @Rapster help me do some testing over the showcase if everything is working fine?

**Comment by melloware** [comment]
I can poke around.  In production my client has a customized Lazy Datatable we use and store sorts and filters and all the refactoring you did last week solved all my problems!  We don't use the TableState stuff but I will poke around the showcase.

**Comment by Rapster** [comment]
I can try later, quite busy right now

**Comment by christophs78** [comment]
I think there´s still something wrong....

before clear table state:
![grafik](https://user-images.githubusercontent.com/10461942/71304868-859a3d80-23cc-11ea-89a5-0ac99d632300.png)

after clear table state:
![grafik](https://user-images.githubusercontent.com/10461942/71304873-9d71c180-23cc-11ea-90a5-0c0d4cafbaed.png)

IMO technically the table-state is cleared. You can check this by navigating to another XHTML and then back to datatable/tableState.xhtml.
But it may be expect, clear table-state should cause a immedate reaction on the current XHTML. (But this does not happen, because the DataTable-instance still has it´s own (ViewScoped) state.

**Comment by christophs78** [comment]
see showcase-PR: https://github.com/primefaces/showcase-facelift/pull/99

**Comment by Rapster** [comment]
There is an obvious bug which might be the root cause of others:
1. Select "Renault" as Brand
2. Refresh (filter kept: OK)
3. Clear table state
4. Refresh
5. Everything looks good
6. Go on page 5: no result (NOK)
7. Go back on page 1: filter Renault is back (NOK)

@christophs78 This is how we use table state, this is why clear method has a consumer so you can reset the datatable from the client id, too bad you're not using it!!! 😋 I'll probably add a method that allows to reset the datatable for 9.0

**Comment by christophs78** [comment]
That's all fake news. ;-) (just kidding)
I updated the showcase-PR.

**Comment by christophs78** [comment]
LazyDataModel does not seem to have this issue.

**Comment by christophs78** [comment]
Did we have this issue with 7.0 too? Or is this something we introduced with 8.0?

**Comment by christophs78** [comment]
Just made a small reproducer based on primefaces-test with PrimeFaces 7.0. The issue described by @Rapster had been there with 7.0 too.

**Comment by christophs78** [comment]
DataTableBase#getFilteredValue returns the same (filtered) instance of ArrayList after the reproducer-steps described by @Rapster. (Even after DataTable#reset which does setFilteredValue(null);)
I don´t unterstand this... hope some of you JSF-Pro´s unterstand this.

**Comment by Rapster** [comment]
`TableStateView` is `SessionScoped` so I guess it brings some unexpected results... I tried with RequestScoped, works much better. Doesn't mean there is nothing wrong. I'll definitely put a new method resetting the component for 9.0, I even think it should be the default behavior as it's quite confusing to clear the state but nothing change on the UI side

**Comment by christophs78** [comment]
> There is an obvious bug which might be the root cause of others:
>     1. Select "Renault" as Brand
>     2. Refresh (filter kept: OK)
>     3. Clear table state
>     4. Refresh
>     5. Everything looks good
>     6. Go on page 5: no result (NOK)
>     7. Go back on page 1: filter Renault is back (NOK)

This issue even exists with multiViewState="false". (Tested with tableState.xhtml) There seems to be a issue. DataTableBase#getFilteredValue has still it´s old value after navigating to another XHTML and back or doing a refresh. But it does not seem related to multiViewState. It seems to be related to the filter mechanism used without LazyDataModel.

**Comment by Rapster** [comment]
That was a good idea to try without

**Comment by Rapster** [comment]
Very good point to try without multiviewstate :wink: At least, we know the problem doesn't come from there. SessionScoped bean shows this issue then:

After refresh (and setting filters), the table is displayed as normal, but when I click on paginator 5 `DataTable#processEvent` is called, which update value with filtered values (previously set in session) I tried without it, works fine. So I think the problem is in that method. Looking at the corresponding commit https://github.com/primefaces/primefaces/commit/20baf62631dd3662c978abb6cb57669940ca967d it doesn't say much what it fixes (except it tries to fix a bad sync of filters but in which situation?)

**Comment by christophs78** [comment]
Now i got it. `org.primefaces.showcase.view.data.datatable.TableStateView` is `@SessionScoped`. And so it´s member `filteredCars` is `@SessionScoped`.
In a real-world-usecase `org.primefaces.showcase.view.data.datatable.TableStateView` propably would be `@ViewScoped`. 

https://github.com/primefaces/primefaces/commit/20baf62631dd3662c978abb6cb57669940ca967d and the introduction of `DataTable#processEvent` does not make that much sense, when we look at it today and out-of-context. We would expect `DataTableBase#getFilterBy` to be the "single source of truth". (With the current implementation `getFilterBy` and `getFilteredValue` may get out of sync.)

IMO input from @cagataycivici , @mertsincan, @tandraschko, @melloware or some other people who have more background would be welcome.

**Comment by Rapster** [comment]
Sorry if I was no clear enough in my previous message. Anyway, I think we can close this one, and open a new one for this problem

**Comment by tandraschko** [comment]
yep, please
i designed getFilterBy to the only source of truth. I didn't see the getFilteredValue anyway.

I created a refactor ticket for the sorting stuff for 9.0.
Please create another ticket to check filterValue
