### ISSUE TITLE
Improve Steps Flow

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#567]
Items on the left of the active one should be clickable and ones on the right should be disabled when readonly="false"

**Comment by justin-wesley** [comment]
You may want to have this more i18n friendly for locales that use RTL layouts.

**Comment by mallorygiles** [comment]
This update broke existing functionality. I actually liked how it previously worked because it gave the ability to select which step if readonly="false" regardless of what step the user was on. It was an alternate component to the wizard which doesn't allow this. Would it be possible to add in an attribute to determine whether or not steps to the right of the active one are clickable? Possibly a highestActiveIndex attribute so that it can be configured how far a user can click. This way, if a user is on 3 and go back to 2, they can get to 3 again.
