### ISSUE TITLE
DatePicker: smart behaviour for showTime and timeOnly-attributes with value-binding to LocalDate/LocalDateTime/LocalTime

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5717]
Base idea by @tuerker as part of https://github.com/primefaces/primefaces/issues/5638.

- LocalDate --> showTime=false, timeOnly=false
- LocalDateTime --> showTime=true, timeOnly=false
- LocalTime --> showTime=false, timeOnly=true

Explicit set showTime / timeOnly-attributes override the smart behaviour.

**Comment by kukel** [comment]
Very important feature for being able to use the component in a custom datatable filter (I think).  Was just going to look into something similar since I cannot get a time to be processed on the server side (time is passed from the client to the server and ignored there. Always get a `LocalDate` instead of `LocalDateTime`
