### ISSUE TITLE
DataTable: ScrollHeight with Flex CSS incorrect parent height

### ISSUE THREAD

**Issue by yennor** [primefaces/primefaces#5722]
## 1) Environment
- PrimeFaces version: 8

## 2) Expected behavior
When putting an Datatable into a Div with flexbox, and setting the scrollHeight to 100%, the datatable component shouldn't become heigher than it's parent component.
Also when there aren't enough element to fill the set scrollheight. The Datatable shouldn't become smaller than the set scrollheight.

## 3) Actual behavior
The datatable component gets as high as it feels like, without ever providing a scrollbar.
When there are only a few elements or none in the dataTable, then the size of 100% is also ignored and the datatable is only of the minimum size it needs to display the elements.
I've tried out the same layout with a selectOneListbox. And there it works.
With own css I can get the DataTable to behave the way I want it to. But it's very cumbersome.

## 4) Steps to reproduce
checkout
https://github.com/yennor/primefaces-test/tree/dataview-height

## 5) Sample XHTML
see above

**Comment by melloware** [comment]
@yennor the datatable only looks at its direct parent for height. See the datatable JS code here.

```javascript
adjustScrollHeight: function() {
        var relativeHeight = this.jq.parent().innerHeight() * (parseInt(this.cfg.scrollHeight) / 100),
```

Your parent of the datatable is this: 
```xml
<div class="p-grid" style="flex: 1">
```

But you are expecting it to respect the 100% height of the parent's parent...
```xml
<div jsf:id="emailListPanel" class="p-grid p-dir-col" style="height: 100%">
```

**Comment by yennor** [comment]
I can also set the parent to style="height: 100%". The Datatable still shows the same behaviour.

Anyway, like that, How am I expected to integrate the Datatable into a full screen application, where the size of any div (part of the screen) is not clear in before?

Instead of calculating the size like that, can't you just set proper style on all html elements belonging to the DataView, so it respects the percentage size?

**Comment by melloware** [comment]
I didn't write the datatable...the code above is what it has always done.

**Comment by yennor** [comment]
I'm not blaming you or anybody else, don't worry ;-).
I'm just reporting a bug, or at least a very very unexpected behaviour which makes it really difficult to use a certain component under certain circumstances. I guess the above code was ok, when people defined the sizes of every part of the UI being fix in pixels. But I guess less and less people work like that.
Anyway.
You can either say, that you don't care about that, it stays the way it is.
Or you could say, that maybe other users would be affected by that, let's find a solution.
(Like dynamically setting the style attributes, as I've suggested above).

For me it doesn't really matter, I've already found my solution.

**Comment by melloware** [comment]
what solution did you land on?

**Comment by yennor** [comment]
it's not beautiful. And I guess somebody with better css knowledge would be able to do it better (I freaking hate css. Otherwise I wouldn't use theme-based components ;-) ):

```
		<div class="p-grid" style="flex: 1; overflow:auto">
			<p:dataTable styleClass="tableFullHeight">
.....

```



css:
```
.tableFullHeight, .tableFullHeight .ui-datatable-tablewrapper  {
	height: 100%;
}

.tableFullHeight .ui-datatable-tablewrapper {
	border: 1px solid #c8c8c8
}

.tableFullHeight th {
 position: sticky;
  top: 0;
  z-index: 2;
}

```

**Comment by yennor** [comment]
So I guess that means: nofix ?

**Comment by melloware** [comment]
Well I can open it but I promise you unless you are a PRO customer and have PrimeTek fix this, this ticket will never get worked on.  

If you look at these issues there are 425 issues open and over 50% of them are Datatable or TreeTable tickets that never get addressed.   This would just be one more on the pile.

**Comment by melloware** [comment]
Here is a similar ticket: https://github.com/primefaces/primefaces/issues/3450

**Comment by yennor** [comment]
ok I see.
I'm afraid pro customer would be outside of my price range, I was more thinking about becoming elite if I like the framework.
The Tree component actually got the same issues as the Datatable. But in that case I guess it doesn't make any sense opening an other bug report.

**Comment by melloware** [comment]
@yennor you can also click the "CASE Get A Quote" for a 1 time fix so you don't have to pay for pro.  They will quote you just for fixing this issue.

https://www.primefaces.org/support/

**Comment by melloware** [comment]
@yennor I had a chance to take a look at this and I think everything is working correctly.

1. Its reporting `this.jq.parent()` as your DIV p-grid.

2. Its reporting its `this.jq.parent().innerHeight()` as 1379 in my resolution because you have it set for flex:1.  So all styles like "height:200px" are ignored because of the fluidity of flex.

3. If I change your DIV p-grid to just 
```xml
<div style="height:200px;">
```

I get the table sizing correctly and the parent.innerHeight reports 200px.
![image](https://user-images.githubusercontent.com/4399574/77928173-14dda980-7276-11ea-9a0d-8f85bcc5caf4.png)

So I think this because you are expecting flex to dynamically size and table is reporting its parent is whatever size the flexed grid is.

**Comment by yennor** [comment]
the flex property in the div element makes it sizing dynamically, according to the size of it's parent. Not it's children.
Since "flex: 1" is set, and it's neighbour element doesn't have a flex set, the div will use all the space which is left from the parent element. What often is used in flexible layouts.
Which works perfectly with other components, like selectOneListbox.
But the table element only works when the parent object has a fixed size (pixel or percentage). So you can't really use it inside of flexible layouts.

**Comment by melloware** [comment]
Yep I updated the title of the ticket to be more specific around Flex CSS.

**Comment by kukel** [comment]
@melloware : I'm abusing this ticket for this comment. I'm going to pick up a number of datatable issues, scrollHeight related things like this issue being the first ones.  But I'd like it to sort of be 'experimental' in that a datatable is added to PrimeFaces Extensions where it can be a sort of 'unstabe' but most likely more used than the PF snapshots.

**Comment by melloware** [comment]
@kukul so you want to have a copy of the datatable in Extensions?  Won't keeping your changes in sync with the real datatable become difficult quickly?  I am only asking because wouldn't just be easier to submit PR's here for each fix?

I appreciate the help though there are a LOT of scrolling height and width issues on here about the Datatable.  This component has abut 200 of the 400+ issues on the board and is probably the MOST popular component in PF.

**Comment by kukel** [comment]
@melloware :  If I sub PR's for each fix, they will not seriously be tested since not a lot of people try snapshots (not only true for PF, for lots of other libs/frameworks as well), so you miss a lot of real life testcases. And since PF does not have the policy to have a community 'bug-fix' release a couple of weeks after a real release, I'm hasitant to make changes that might introduce unknown issues due to the complexity of real-world usecases that we might not able to test and that will only be fixed in the next community release. If all these changes are client-side js solveable, that might pose less of a problem but still then... Getting these in PFE and with the next releases promoting all this to PF so the PF is the 'stable' datatable and the PFE is the experimental is better for my personal state of mind ;-) (I **think**)

**Comment by melloware** [comment]
I see what you mean but now that PF uses JitPack.

```xml
 <dependency>
     <groupId>com.github.primefaces</groupId>
     <artifactId>primefaces</artifactId>
     <version>master-SNAPSHOT</version>
 </dependency>

 <repositories>
 	<repository>
 	    <id>jitpack.io</id>
 	    <url>https://jitpack.io</url>
 	</repository>
 </repositories>
```

As soon as a PR is merged you have instant access to the code without needing an Elite release or a community release?  I know a lot of people use the above channel for testing their code. And also we can't be afraid of introducing bugs...we try not to but that is the nature of a complicated library!

**Comment by stolp** [comment]
This is interesting information. Saves me a lot of effort for building and deploying development versions here.

Would it be possible to tag milestone releases towards 9.0? Preferably at a point where a stable situation is assumed?

**Comment by melloware** [comment]
@stolp if you go here: https://jitpack.io/#primefaces/primefaces

You can grab versions by Release or even commit ID if you click the Commits tab.  So once you know the last commit ID and you grab a version at that commit!  They give you the exact maven coords to use.

**Comment by stolp** [comment]
Got this. Clever indeed.

**Comment by kukel** [comment]
> 
> 
> I see what you mean but now that PF uses JitPack.
> 
> ```
>  <dependency>
>      <groupId>com.github.primefaces</groupId>
>      <artifactId>primefaces</artifactId>
>      <version>master-SNAPSHOT</version>
>  </dependency>
> 
>  <repositories>
>  	<repository>
>  	    <id>jitpack.io</id>
>  	    <url>https://jitpack.io</url>
>  	</repository>
>  </repositories>
> ```
> 
> As soon as a PR is merged you have instant access to the code without needing an Elite release or a community release? I know a lot of people use the above channel for testing their code. And also we can't be afraid of introducing bugs...we try not to but that is the nature of a complicated library!

Ok, did not know this... Did not read the blogs/instagrams/facebook/... posts about PF for a long time (shame). Then I'm indeed less 'afraid' Yeeeehaaa

**Comment by kukel** [comment]
> 
> 
> This is interesting information. Saves me a lot of effort for building and deploying development versions here.
> 
> Would it be possible to tag milestone releases towards 9.0? Preferably at a point where a stable situation is assumed?

Aren't these the 'RC's'?

**Comment by yennor** [comment]
@kukel cool that you are looking into it :-).
just as a hint. meanwhile what I'm doing with the datatable is following:
```
<div class="p-grid" style="flex: 1; min-height: 0">
			<p:dataTable scrollHeight="100%"
				scrollable="true" styleClass="fullHeightTable">

.tableFullHeight .ui-datatable-tablewrapper {
	border: 1px solid #c8c8c8
}

```
min-height: 0 on the parent div is necessary, otherwise the table element can grow bigger than the div (Don't ask me why.... A css genious told me to try it out ;-). I'm still not very fond of css. ).
The css class is necessary, since otherwise there won't be a border around the whole table element, if it doesn't have enough datarows to fill the whole height. That extra border looks a bit ugly, since it is 1px off at the top. But it looks better than just having random length table in full screen designs ;-) and I've already lost too much time with it to care about that single pixel....

**Comment by stolp** [comment]
@kukel: No. RCs are typically located at the end of the release cycle. Milestones would be semi-'stable' snapshots of the current development.

The reason I am throwing this in is, that a release cycle of approx. a year per version (as in 8.0 and expected for 9.0) is a long time without a defined point of reference.

Elite releases are fine if you need a stable version (Elite user already).

Using the current build is fine for development.

I think milestone releases would be a good addition to this and may foster early community feedback during a release cycle.

Just a thought.

**Comment by kukel** [comment]
@Stolp: Yes I know when the RC's are done, but those are the only stable milestones....  introducing alpha's and beta's  (as other stable milestones) would be to cumbersome for the project imo. The amount of feedback even on the RC's has never been to high and those are the most stable, close to release ones. I doubt many people will be interested in testing earlier milestones

**Comment by kukel** [comment]
@yennor: All these scrollable things predate css flex stuff. So instead of trying to combine the two, I' remove `scrollable="true" and am experimenting with adding flex to the datatable. And I am surprised that tbody can be scrollable then. Just some small lines of css wit flex and it already works. Might be that lots of the feature that are hard to combine (scrollable, fixed colums/rows and some more things become easier. 

@stolp, @melloware: I'm going to remove all off-topic comments

**Comment by stolp** [comment]
@kukel: agreed this is the wrong place for this discussion.

**Comment by kukel** [comment]
@stolp: you do the same? ;-)
@yennor: I got some simple scrolling working, but the issue seems to remain the same. The 100% is sort of not doing anything here either. If I set the height of the tbody in vh units it does work. I'll experiment further since I think it would be a nice thing for responsiveness to and make the datatable in general waaaay simpler. But maybe you can experiment some with this too.  The 'bean stays the same. The xhtml I now have is this:


	<!DOCTYPE html>
	<html xmlns="http://www.w3.org/1999/xhtml"
		xmlns:h="http://xmlns.jcp.org/jsf/html"
		xmlns:f="http://xmlns.jcp.org/jsf/core"
		xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
		xmlns:p="http://primefaces.org/ui" xmlns:jsf="http://xmlns.jcp.org/jsf"
		style="height: 100%">
	
	
	<h:head>
		<title>PrimeFaces Test</title>
		<h:outputStylesheet library="primeflex" name="css/primeflex.css" />
	
	<style>
		table {
		  display: flex;
		  flex-direction: column;
		}
		 
		thead tr, tbody tr {
		  display: flex;
		  flex-direction: row;
		 
		}
		
		/* Following two are needed since the PF datatable currently only sets the width on the column 
		 which is sufficient if you don't use flex on the table elements*/
		tr td:nth-child(1) {
		  width: 60%;
		}
		
		tr td:nth-child(2) {
		  width: 40%; 
		}
		
		tbody {
		  overflow: auto; /* tbody can scroll if table is not a real table anymore but flex */
		  height: 50vh;
		  /* height: 100%; does not work, just like with the PF scrollable table!!! */
		
		}
		
		thead tr {
		  padding-right: 18px; /* compensation for the scrollbar widht in firefox. PF datatable has this dynamically for each browser */
		}
		
		.ui-datatable-tablewrapper {
		  overflow: hidden !important;
		}
	</style>
	
	</h:head>
	<h:body>
		<div jsf:id="emailListPanel" class="p-grid p-dir-col"
			style="height: 100%">
			<h3 style="margin-block-start: 0">Email lists</h3>
			
			<div class="p-grid" style="flex: 1">
				<p:dataTable style="width:300px"  value="#{testView5722.list}" var="emailList" selectionMode="single" rowKey="#{emailList.hashCode()}" id="dataTable">
					<p:ajax event="rowSelect" update="" />
					<p:column headerText="Email list" width="60%">
						<h:outputText value="col1 #{emailList}" />
					</p:column>
					<p:column headerText="Email list" width="40%">
						<h:outputText value="col2 #{emailList}" />
					</p:column>
				</p:dataTable>
				<div class="p-grid p-dir-col">
					<p:panelGrid id="companyData" columns="2" styleClass="ui-noborder">
						<p:outputLabel value="Email list name" for="@next" />
						<p:inputText id="inputText" value="#{emailList}" />
					</p:panelGrid>
					<div class="p-grid p-justify-center">
						<p:commandButton id="commandButton" value="add" action="#{testView5722.add()}" update="@root:@id(emailListPanel)" />
					</div>
				</div>
			</div>
		</div>
	
	https://designlink.work/en-US/flex-table/
	</h:body>
	</html>

**Comment by kukel** [comment]
Some improvements...  datatable is all '100%'... Only thing explicitly set now is the height of the p-grid around it but it is set in percentage units of the vh. If you **kown** (since you designed it) for which media selectors, what e.g. the size of the headers and footers are, you could also so a `calc (100hv - <size of header and footer of page>) and you are all set. `calc(100vh - 75px)` in the example below, replace the 88vh there. If you do that, it really comes close..

	<!DOCTYPE html>
	<html xmlns="http://www.w3.org/1999/xhtml"
		xmlns:h="http://xmlns.jcp.org/jsf/html"
		xmlns:f="http://xmlns.jcp.org/jsf/core"
		xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
		xmlns:p="http://primefaces.org/ui" xmlns:jsf="http://xmlns.jcp.org/jsf"
		style="height: 100%; overflow:hidden;">
	
	
	<h:head>
		<title>PrimeFaces Test</title>
		<h:outputStylesheet library="primeflex" name="css/primeflex.css" />
	
	<style>
		table {
		  display: flex;
		  flex-direction: column;
		}
		 
		thead tr, tbody tr {
		  display: flex;
		  flex-direction: row;
		 
		}
		
		/* Following two are needed since the PF datatable currently only sets the width on the column 
		 which is sufficient if you don't use flex on the table elements*/
		tr td:nth-child(1) {
		  width: 60%;
		}
		
		tr td:nth-child(2) {
		  width: 40%; 
		}
		
		tbody {
		  overflow: auto; /* tbody can scroll if table is not a real table anymore but flex */
		}
		
		thead tr {
		  padding-right: 18px; /* compensation for the scrollbar widht in firefox. PF datatable has this dynamically for each browser */
		}
		
		
		/* Some changes for datatable internal css.  */
		.ui-datatable-tablewrapper {
		  overflow: hidden !important;
		  height: 100%;
		}
		table {
			height: 100%;
		}
	</style>
	
	</h:head>
	<h:body>
		<div jsf:id="emailListPanel" class="p-grid p-dir-col"
			>
			<h3 style="margin-block-start: 0">Email lists</h3>
			
			<div class="p-grid" style="height:88vh">
				<p:dataTable style="width:300px; height: 100%"  value="#{testView5722.list}" var="emailList" selectionMode="single" rowKey="#{emailList.hashCode()}" id="dataTable">
					<p:ajax event="rowSelect" update="" />
					<p:column headerText="Email list" width="60%">
						<h:outputText value="col1 #{emailList}" />
					</p:column>
					<p:column headerText="Email list" width="40%">
						<h:outputText value="col2 #{emailList}" />
					</p:column>
				</p:dataTable>
				<div class="p-grid p-dir-col">
					<p:panelGrid id="companyData" columns="2" styleClass="ui-noborder">
						<p:outputLabel value="Email list name" for="@next" />
						<p:inputText id="inputText" value="#{emailList}" />
					</p:panelGrid>
					<div class="p-grid p-justify-center">
						<p:commandButton id="commandButton" value="add" action="#{testView5722.add()}" update="@root:@id(emailListPanel)" />
					</div>
				</div>
			</div>
		</div>
	
	https://designlink.work/en-US/flex-table/
	</h:body>
	</html>

**Comment by kukel** [comment]
Oh btw, this `calc(...)` setting of the grid is not uncommon to do in responsive designs and it might even be a solution when using the current `scrollable="true" scrollHeight="100%"` solution. That is at least I remember it being in my designs. 

### Update: 
confirmed... There is something that needs an explicit height somewhere, not just with the current implementation, but also with flex... and the 100vh IS dynamic but in a different way than 100%, so I'd personally say this issue is for now invalid. I will be looking into reimplementing lots of datatable things so they might in the end result in simplification.

**Comment by yennor** [comment]
wow. You've really put some work into it :-). I'll try it out

**Comment by melloware** [comment]
@kukel i will close this ticket for now.

**Comment by kukel** [comment]
@yennor : Can you create a new issue for 

> Also when there aren't enough element to fill the set scrollheight. The Datatable shouldn't become smaller than the set scrollheight

I'll pick this up and create functionality for this. 

And add 'also for the 'empty message' part
