### ISSUE TITLE
Mobile: Swipe on mobile can cause problems with scroll

### ISSUE THREAD

**Issue by cocorossello** [primefaces/primefaces#5744]
## 1) Environment
- PrimeFaces version: 
**8.0**
- Does it work on the newest released PrimeFaces version? Version?
**It doesn't work with the latest**
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
**No**
- Application server + version:
**Tomee 8.0 (but it doesn't matter)**
- Affected browsers:
**Tested in chrome and safari**

## 2) Expected behavior
**In a mobile browser, I should be able to scroll horizontantly in a datatable with paginator or a tabview, by disabling swipe or making it compatible**
...

## 3) Actual behavior

**I'm not able to scroll horizontally if datatable has paginator and all columns don't fit in the screen, swipe is triggered instead**
..

## 4) Steps to reproduce
**Draw a datatable with a paginator with several columns that don't fit the screen. Making them fit the screen is not always an option (a backoffice page in a mobile, you still want to display most of the columns).

Try to scroll horizontal, swipe is triggered
**
.. 

## 5) Sample XHTML
..

## 6) Sample bean

..

Swipe can be disabled with MonkeyPatch:
```js
PrimeFaces.widget.Paginator.prototype.bindSwipeEvents = function() {}
PrimeFaces.widget.TabView.prototype.bindSwipeEvents = function() {}
```
Swipe should be configurable by component, or globally. I don't really know if more components are affected. It can be disabled globally with 
```js
PrimeFaces.env.touch = false
```
but I'm not sure how everything else will be affected

**Comment by melloware** [comment]
Your current workaround is actually a good one!

PrimeFaces.env.touch is used in the following components...

```
carousel.js
calendar.js
datepicker.js
forms.selectonemenu.js
galleria.js
menu.contextmenu.js
paginator.js
slider.js
tabview.js
```

@tandraschko  I wonder if we should do this similar to RTL support with a web context param and an interface `isTouchable` and add the property `touchSupport=true/false` to all of these components?

**Comment by melloware** [comment]
Components affected:
```
 Calendar
 Carousel
 ContextMenu
 DataGrid
 DataList
 DataTable
 DataView
 DatePicker
 Galleria
 SelectOneMenu
 Slider
 TabView
 TreeTable
```

**Comment by djmj** [comment]
Observations at 10.0.0

**Hierarchy**

If you have a datatable with horizontal scrolling inside a tabview the tabview takes precedence in swipe event. The tabview is just a UI container and should by default not override the content touch events since it limits it use case. Only very simple tabviews with static content can benefit from this behavior.

**Global deactivating has no effect**

I tried deactivating it at global level using "primefaces.TOUCHABLE" web.xml context-param but it does not work. Somehow i need to deactivate it on component level. Maybe not available in 10.0.0?

**Default false?**

Should touchable behavior not be false by default so you can turn it on for mobile specific application and in CRUD applications it breaks backwards compatibility when upgrading to 10.0.0. I must now add `touchable="false"` to very many components cause we and our clients use the "desktop" version also on mobile and basically every table there is horizontally scrollable.

**Comment by melloware** [comment]
If the Web.xml property does not globally disable it then it's a bug please open a new issue with reproducing instructions.

**Comment by melloware** [comment]
@djmj I can see the issue.  You are right. Please open a defect.
