### ISSUE TITLE
Schedule: Upgrade FullCalendar (4.x --> 5.x) 

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5776]
Something we may look into later this year. (Target PrimeFaces 9.0)

FullCalendar 5.x is currently at beta-state. Should go final in may 2020:
https://fullcalendar.io/blog/2020/04/v5-beta-released

**Comment by blutorange** [comment]
FullCalendar is in beta.v4 now and the API is not going to change much. Since I'm also using the schedule component and had a bit of time, I made some initial adjustments, once v5 is released we can finalize it.

### Changes I made so far:

* Updated FullCalendar according to the [upgrade guide](https://fullcalendar.io/docs/v5/upgrading-from-v4#view).
* Updated the JavaScript docs and included the current type declarations shipped by FullCalendar v5.
* FullCalendar now ships as ES6 modules. There is a pre-built bundle, but it includes some modules we are not using (google-calendar) and is missing other modules we are using (moment). So I made a custom FullCalendar build via webpack. The files for building the bundle are in `src/main/resources/META-INF/resources/primefaces/schedule/build` and are excluded in the jar file. This makes it easier to build a new bundle when updating FullCalendar to a new version.
* FullCalendar now logs warnings when it encounters unknown options. Until now, all options for FullCalendar were simply in the widget configuration object together with other widget options. I extracted the FullCalendar configuration into "PrimeFaces.widget.ScheduleCfg.calendarCfg".
* The tooltip element was moved to the document.body, as appending it to the FullCalendard DIV was not working anymore (was changed by FullCalendar).

### TODOs once FullCalendar v5 is officially relased (still in beta4)

* Did a bit of testing with the showcase, but need to test all existing widget options.
* Update extender examples in showcase.
* Check new features, possibly add new options to the widget.
* ~~Some minor CSS adjustments (e.g. scroll bars appearing in all-time day slot)~~ 
* ~~Check if https://github.com/fullcalendar/fullcalendar/issues/5493 has been fixed in the final build.~~
* ~~Check if https://github.com/fullcalendar/fullcalendar/issues/5336 has been fixed in the final build. Otherwise, prevent event submission with something like this~~

### Points to note:

* Since several options have been renamed in FullCalendar, custom extender functions may not work anymore.
* Since several CSS classes have been renamed an changed in FullCalendar, custom CSS may not work anymore.

**Comment by melloware** [comment]
Looks like 5.0 went final today: https://fullcalendar.io/blog/2020/06/v5-official

**Comment by blutorange** [comment]
fullcalendar/fullcalendar#5336 has at least a workaround, not so sure about fullcalendar/fullcalendar#5493 Perhaps we should at least wait a week or two to see whether they fix it?

**Comment by melloware** [comment]
I have no problem with that.

**Comment by blutorange** [comment]
Both bugs should now be fixed in 5.1.0. It's mostly testing that is left, I'll take a look at it in the next few days.

**Comment by melloware** [comment]
Awesome I was going to ping you but I see you are already ahead of it.

**Comment by melloware** [comment]
Updated to FullCalendar 5.2.0
