### ISSUE TITLE
Performance: Replace dot_clear.gif with Base64 URL

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#5794]
See this article: http://png-pixel.com/

This will save an HTTP trip for dot_clear.gif and the browsers will still cache it properly and it will be part of the CSS load and minification.

I kept noticing every page i hit with datatables or spacers was loading dot_clear.gif and found many articles like the one above saying to base64 encode it.  

I tested it thoroughly and it working great. PR Coming.

**Comment by garcia-jj** [comment]
This change caused a weird behavior. Since attribute _src_ is required by _img_ tag, browser expect this attribute, and if no present, prints a broken image. Take a look on the following screenshot using a spacer with 100% x 15px.

<img width="370" alt="Screen Shot 2020-07-03 at 07 04 23" src="https://user-images.githubusercontent.com/140387/86458404-9290d580-bcfb-11ea-8839-98b980a18c09.png">

So the best change to do this is to print a hardcoded base64 value in the _src_ attribute, instead of using CSS.

What do you think @melloware? Do let me know if a PR is welcome.

Thank you, and best regards

**Comment by melloware** [comment]
Sure thing. I originally had it as Base64 SRC but switched to class to reduce duplication but in my testing I didn't notice any difference using spacer?  I am using Chrome and Firefox.  Can you post your XHTML snippet so I can reproduce?

**Comment by garcia-jj** [comment]
Hello @melloware. I ran the following code using both Chrome and Firefox for Mac OS:

```
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	A spacer that works as well: <br />
	<p:spacer />
	A spacer that we can see an image error: <br />
	<p:spacer height="50px" width="50px" />
</ui:composition>
```
The result is:
<img width="314" alt="Screen Shot 2020-07-03 at 10 18 48" src="https://user-images.githubusercontent.com/140387/86473218-e2c96100-bd16-11ea-8677-582181d8a7bd.png">

I'm using Primefaces built from source (master). As I can see the space works as well if you use the default parameters. If you define a value for both width and height, we can see a broken image.

**Comment by melloware** [comment]
OK let me fix it. I will send you a PR to review.

**Comment by melloware** [comment]
OK please review: https://github.com/primefaces/primefaces/pull/6105
