### ISSUE TITLE
Ajax listener not invoked anymore in Payara 5

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#5827]
it seems that MethodNotFound / IllegalArgumentException are wrapped inside ELException

Fixed by: https://github.com/primefaces/primefaces/commit/e880d5ff6f143a1ffec2a5049e5979afb8fef960

See https://github.com/primefaces/primefaces/issues/5711 for details

**Comment by dmatej** [comment]
So ... I was probably too tired yesterday evening. The bug is a bit different than I originally described, the exception in our use case is not wrapped, but thrown from the application code:

1. AjaxBehaviorListenerImpl.processAjaxBehavior calls listener without args (PF)
2. ReflectionUtil.buildParameters constructs an array respecting target method API (EL)
3. ReflectionUtil.invoke calls the method with arguments received, remaining are null -> null event (EL)
4. Target method did not receive the event, in the case of out reproducer it throws NPE (reproducer)

So finally you can revert the e880d5ff6f14 commit as it does not help neither Payara nor PrimeFaces. (see the PR, istead of revert I did another step)

The temporary fix of EL ( https://github.com/payara/patched-src-el-ri/pull/1 ) passes TCK/EL tests and fixes the issue, but it is a very ugly hack. I tried yet to throw IAE from buildParameters if count of arguments does not match the count of parameters, but then this test failed: https://github.com/javaee/uel-ri/blob/f3b5c877da746fc5f6ee5c43d028519dd5fe3a17/src/test/java/org/glassfish/el/test/OverloadedMethodTest.java#L162  

So the only option is to invert the order of calls in AjaxBehaviorListenerImpl.processAjaxBehavior and prefer the call with an argument and let the call without arguments as the second, or even more - those catch blocks seem meaningless on JAVA EE 8 (but they are still important on obsoleted Java EE7 implementations).

**Comment by tandraschko** [comment]
Reverted it for now - as i said in my comments in the PR:
For me it doesn't make sense that index.xhtml example throws a MethodNotFound (which is the correct behavior of the EL impl IMO) and in the other example, the EL impl invokes the method with a null param instead of throwing a MethodNotFound.
Especially as the MethodExpression was created with a empty params array.

**Comment by tandraschko** [comment]
Will close it for now without further feedback.

**Comment by elvisfabiane** [comment]
Hi. Is this issue fixed in community version 5.20 21.7?
