### ISSUE TITLE
Dialogs should appear at the center of the browser, not at the center of the page 

### ISSUE THREAD

**Issue by pm2013** [primefaces/primefaces#583]
Now on longer pages Dialogs are hidden and users cannot even scroll to the dialog
(with default positonType = "fixed")

The only solution is to set in css top:X !important
but in this case dialogs can't be move in vertical by users.

**Comment by cagataycivici** [comment]
Proposed change will break many apps, instead I'd suggest using position attribute to define x and y coordinates for your dialogs that exceed viewport if you don't use scrollable dialog content. There is also fitViewport option so there are other alternatives for your requirements instead of changing defaults.

**Comment by pm2013** [comment]
FitViewport doesn't show the dialog in the center of the browser. Manually setting Top coordinate is possible only with !important clausule, but user cannot then move the dialog.

If change of default behaviour is not possible, I propose to add an parameter, like a "browserCenter", eventually new option for "position" parameter.
