### ISSUE TITLE
FileUpload: add parameters for setting tooltips on buttons

### ISSUE THREAD

**Issue by martinfabry** [primefaces/primefaces#5831]
## 1) Environment
- PrimeFaces version: 8.0

## 2) Expected behavior
- We expect to be able to set tooltips for the given buttons on this component. The FileUpload component has 3 buttons - Choose file, Upload and Cancel. Each of these buttons should have a new parameter that sets its tooltip. The "Choose file" button could have 2 parameters per tooltip - before upload and tooltip after upload. The "upload" and "cancel" buttons could have one parameter each.

## 3) Actual behavior

..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by melloware** [comment]
@doleron interested in looking at this one too?

**Comment by doleron** [comment]
@melloware sure!

**Comment by melloware** [comment]
Thanks I figured you have been in there updating file upload anyway.  Appreciate the help!

**Comment by doleron** [comment]
I'm wondering me if a change would be actually required. By using [PrimeFaces Selectors](https://primefaces.github.io/primefaces/8_0/#/core/searchexpression?id=primefaces-selectors-pfs) it is possible to attach a tooltip to each one of the FileUpload buttons:

```xhtml
<p:tooltip for="@(#frmTest\:uploader > .ui-fileupload-buttonbar > .ui-fileupload-choose)"  ...

```
For example:

```xhtml
<h:form id="frmTest">
   
	<p:messages id="messages" showDetail="true"/>

	<h:panelGrid columns="3" cellpadding="8">
	
		<h:outputText value="fileUpload: " />
		
		<p:fileUpload id="uploader" listener="#{fileUploadView.handleFileUpload}" update="messages tooltipsPanel"/>
	
		<p:outputPanel id="tooltipsPanel">
		
			<p:tooltip id="uploaderChooseFileBeforeUploadToolTip" widgetVar="chooseWV" position="top"
				for="@(#frmTest\:uploader > .ui-fileupload-buttonbar > .ui-fileupload-choose)" 
				value="Choose tooltip - Before Upload" rendered="#{empty fileUploadView.file}"/>
		
			<p:tooltip id="uploaderChooseFileAfterUploadToolTip" widgetVar="chooseWV" position="top"
				for="@(#frmTest\:uploader > .ui-fileupload-buttonbar > .ui-fileupload-choose)" 
				value="Choose tooltip - After Upload" rendered="#{not empty fileUploadView.file}"/>
		
			<p:tooltip id="uploaderUploadButtonToolTip" position="bottom" 
				for="@(#frmTest\:uploader > .ui-fileupload-buttonbar > .ui-fileupload-upload)" 
				value="Upload button tooltip"/>
	    		
			<p:tooltip id="uploaderCancelButtonToolTip" position="right" 
				for="@(#frmTest\:uploader > .ui-fileupload-buttonbar > .ui-fileupload-cancel)" 
				value="Cancel button tooltip"/>
				
		</p:outputPanel>
		
	</h:panelGrid>

</h:form>
```
Results in:
![image](https://user-images.githubusercontent.com/9665358/82765482-b6542800-9ded-11ea-9e63-8f5ba161e189.png)

![image](https://user-images.githubusercontent.com/9665358/82765498-cff56f80-9ded-11ea-9c44-43ef3ebfa18a.png)

![image](https://user-images.githubusercontent.com/9665358/82765506-de438b80-9ded-11ea-94a6-b045fa9c2acf.png)

![image](https://user-images.githubusercontent.com/9665358/82765514-f0bdc500-9ded-11ea-825f-64365f2524b9.png)

Thus, by following this approach no modification is needed. Furthermore, attaching tooltip components is good because we can customize them (position, showEffect, etc) which is more handly than provide a message only .

What do you guys think about it?

**Comment by melloware** [comment]
I am actually OK with this.  Want me to close this ticket since you have provided a solution?  Unless you wanted to create a Showcase PR that has these tooltips?

**Comment by tandraschko** [comment]
Not sure.
i personally like the html native title tooltips :)

**Comment by doleron** [comment]
Ok! I just issued PR https://github.com/primefaces/primefaces/pull/5954 covering the inclusion of the attributes:

```xhtml
<p:fileUpload id="uploader" listener="#{fileUploadView.handleFileUpload}" update="messages @this"

    chooseButtonTitle="#{(empty fileUploadView.file)? 'Choose tooltip - Before Upload' : 'Choose tooltip - After Upload'}"
    uploadButtonTitle="Upload button tooltip"
    cancelButtonTitle="Cancel button tooltip"

/>
```

![image](https://user-images.githubusercontent.com/9665358/82814291-3e2d4700-9e6d-11ea-85f0-3b3b886f4a59.png)
![image](https://user-images.githubusercontent.com/9665358/82814359-61f08d00-9e6d-11ea-8c7c-31e951b157ce.png)
![image](https://user-images.githubusercontent.com/9665358/82814396-79c81100-9e6d-11ea-8b26-aa38d5745ca1.png)
![image](https://user-images.githubusercontent.com/9665358/82814676-f8bd4980-9e6d-11ea-8ce4-338108a1c827.png)
