### ISSUE TITLE
DatePicker: Inline won't change displayed month on update after a date has been selected

### ISSUE THREAD

**Issue by Foobartender** [primefaces/primefaces#5979]
**Describe the defect**
Inline p:datePicker won't change displayed month on update after a date has been selected.

**Reproducer**
[pf-datepicker-test.tar.gz](https://github.com/primefaces/primefaces/files/4720910/pf-datepicker-test.tar.gz)

**Environment:**
 - As in primefaces-test
 - Also 8.0.2 on Wildfly 18
 - Affected browsers: all

**To Reproduce**
See instructions in example HTML / run the attached test project.

**Expected behavior**
p:datePicker should keep updating the displayed month on update after a date has been selected.

**Example XHTML**
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
  xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:p="http://primefaces.org/ui"
  xmlns:h="http://java.sun.com/jsf/html">

<h:head>
 <title>PrimeFaces Test</title>
</h:head>
<h:body>
 <h:form id="frmTest">
  <ol>
   <li>Don't select a date yet.</li>
   <li>Click the button a few times.</li>
   <li>Note that the date picker updates its value, and also updates the displayed month.</li>
   <li>Now select a date.</li>
   <li>Click the button a few times.</li>
   <li>Note that the date picker still updates its value, but no longer updates the displayed month.</li>
  </ol>
  <p:datePicker id="datePicker" value="#{testView.date}" inline="true"/>
  <p:commandButton value="Update date" action="#{testView.updateDate}" update="datePicker"/>
 </h:form>
</h:body>
</html>
```

**Example Bean**
```java
package org.primefaces.test;

import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.time.LocalDate;


@Named
@ViewScoped
public class TestView implements Serializable {
 private LocalDate date=LocalDate.now();


 public LocalDate getDate() {
  return date;
 }


 public void setDate(LocalDate date) {
  this.date=date;
 }


 public void updateDate() {
  date=date.plusMonths(1);
 }
}
```

**Comment by melloware** [comment]
Verified this is still a problem in 9.0-SNAPSHOT as well.

**Comment by melloware** [comment]
This doesn't matter whether its inline or not the problem remains the same.  This is cause by this line in `1-datepicker.js`
```javascript
        this.cfg.viewDate = this.viewDateOption;
```
viewDateOption is NULL and taking the value from the backing bean date so that is why the months update at first.  But once you actually select a date with the mouse the `viewDate` is set and even though your backing bean method added +1 month the viewDate is now set so when the control redraws its on the month where you selected a date.

If I remove the above line everything works as expected but my guess is it break other legit scenarios. But to me I don't know why the viewDate shouldn't default to the date selected in the backing bean. Not sure what problem this solves but to me when the component refreshes i would expect it to be on the date send from the backing bean.

**Comment by melloware** [comment]
@Foobartender If you need a short term fix you can accomplish it with the following:
```xml
  <p:datePicker id="datePicker" value="#{testView.date}" inline="true" widgetVar="wgtDatePicker">
      <p:ajax event="dateSelect" oncomplete="PF('wgtDatePicker').viewDateOption = null;"/>
  </p:datePicker>
```
