### ISSUE TITLE
DataScroller: Lazy loading losing track of items loaded

### ISSUE THREAD

**Issue by SteveIreland** [primefaces/primefaces#6087]
Running clean version 8.   2nd chunk replaces item association with first chunk. The issue is the exact same issue as #5354 which was closed with a pull request, but I noticed that the changes were reverted by a subsequent change three months later (I think #5612).

As soon as I work through the issues I'm having building my own version of 9.0-SNAPSHOT I'll retest it there, but the code looks unchanged.

**Environment:**
 - PF Version: _8.0_
 - JSF : jboss-jsf-api_2.3_spec-3.0.0.Final.jar (WildFly 11)
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**Comment by melloware** [comment]
Agreed those look like conflicting changes for two different use cases.  We need a fix that satisfied both use cases.  Are you interested in submitting a PR once you get your environment figured out?

**Comment by SteveIreland** [comment]
Sure ... I'll give it a shot, but it might be a week or two.

**Comment by melloware** [comment]
No problem.  Appreciate the help.

**Comment by melloware** [comment]
This looks related too but not sure if its already fixed or not: https://github.com/primefaces/primefaces/issues/4197

**Comment by melloware** [comment]
@SteveIreland just realized you were from Wilmington..I am right up the road in Philly. small world.

**Comment by SteveIreland** [comment]
Yes, it is definitely smaller than we expect - hard to maintain social distancing  :-).

After spending the day debugging and testing and trying to determine if it was something that I did or an issue with the control I finally settled in on the fact that the LazyDataModel needs to be replaced by a ScrollableLazyDataModel that allows overriding the getRowData method such that if the requested row isn't within the last set of records read then it knows how to retrieve the individual record.

I assumed - falsely - that the control itself somehow managed that under the covers.  But I agree with some that retaining an array of the records that were read - simply for the sake of being able to return the record when the control needs to return it to the user in some form - could consume more memory than might be desirable.

In my case I'd need to adapt a call to a legacy PCML called program to retrieve a single record out of a set of 50 or write a new PCML called program to locate and return the record.  Neither approach is worth the effort or the overhead.  Looks like we'll be staying with the DataTable control for our particular application.
 
I don't know if it's permitted to add a ScrollableLazyDataModel to Primefaces.  That seems like it might be too much.  More appropriate might be to remove the support for LazyDataModel since it doesn't work as expected.

If I've missed something then please let me know.  I'm still learning.

**Comment by melloware** [comment]
Well the lazy support is there so people can plug in their own implementations so removing support for that doesn't feel right.

So I feel like if you create a small reproducer using https://github.com/primefaces/primefaces-test we can debug the problem and fix it.

**Comment by SteveIreland** [comment]
I gave it a bit more thought while I was in the shower (where I do my best thinking).  The control is using the getRowData for two purposes. The first is to populate the screen with records and that is, of course, working as expected.  Then when I click on an anchor tag on the row and have it coded to pass in the associated row object then it appears to use the getRowData for that purpose too.   The problem is that if I have a LazDataModel page size of 50 records then only rows 1 through 50 of the last set read will ever return a record (and if you're on the second virtual page of the control then the first 50 rows will only return the wrong record).   If I don't code the page to pass in the associated object to the method then the control should be usable although I haven't tested for that.

There probably is a way to fabricate a LazyDataModel that knows the context in which the getRowData but it seems like there should be a better approach. 

I'll take a shot setting something up on primefaces-test as soon as I can.

**Comment by SteveIreland** [comment]
[LazyDataScrollerSrc.zip](https://github.com/primefaces/primefaces/files/4871883/LazyDataScrollerSrc.zip)

Attached is a primefaces-test compatible example of the issue with running the DataScroller using a LazyDataModel

**Comment by melloware** [comment]
Do you have your implementation of ScrollableLazyDataModel that makes it work? I would like to see it.

**Comment by SteveIreland** [comment]
Sorry, not yet.  I'm still trying to learn/understand enough of the wiring in PrimeFaces to be able to fabricate a solution.  I was hoping that the issue was that the rowIndexVar associated with the array row was being passed into the getRowData method (that would give me an opportunity to provide a work-around), but it appears based on this exercise that the original rowIndex used to retrieve the row data for the purpose of loading it into the array is what's being used as the key.  That suggests (at this point) that the solution is going to be much more complicated.

**Comment by irieill** [comment]
Today I experienced the same behavior with PrimeFaces 12. My investigations results in the following working solution:

```java
public abstract class LazyAppendingDataModel<T> extends LazyDataModel<T> {

  @Override
  public void setWrappedData(Object list) {
    if (null != list) {
      List oldData = this.getWrappedData();
      if (null != oldData) {
        oldData.addAll((List) list);
        return;
      }
    }
    super.setWrappedData(list);
  }

  @Override
  public void setPageSize(int pageSize) {
    super.setPageSize(super.getRowCount() + pageSize);
  }

}
```

One still needs to call `setRowCount()` in [one of the documented ways](https://primefaces.github.io/primefaces/12_0_0/#/components/datatable?id=lazy-loading).

The behavior is produced by a combination of
https://github.com/primefaces/primefaces/blob/6ec3c4a455e0d03d2e449bd36d5d4f185faf9817/primefaces/src/main/java/org/primefaces/component/datascroller/DataScrollerRenderer.java#L239-L241 and
https://github.com/primefaces/primefaces/blob/6ec3c4a455e0d03d2e449bd36d5d4f185faf9817/primefaces/src/main/java/org/primefaces/model/LazyDataModel.java#L193 

When loading a chunk of data we overwrite any previously loaded data which is not desirable with `DataScroller` that is not (paginated by design nor) virtual scrollable as one has access to the previous data on the page as well. Therefor we must **append** the new chunk. The second part is some kind of index windowing that is not necessary as well for the same reason. The addition of the given page size to the total count as page size in the solution is important! Otherwise, the very first elements would be rendered again as fill-in for final partial chunks. Index overflow on the other hand is protected by https://github.com/primefaces/primefaces/blob/6ec3c4a455e0d03d2e449bd36d5d4f185faf9817/primefaces/src/main/java/org/primefaces/component/datascroller/DataScrollerRenderer.java#L219-L221 The solution does work for inline mode too but not for virtual scroll of course. But I am not sure if there is a problem with virtual scroll and default `LazyDataModel` at all (the provided test does not include it and I have no use case).

Should I create a PR with the above class and supporting documentation or do you guys think all this lazy loading for different components should be aligned properly first?

**Comment by melloware** [comment]
Yes please create a PR @irieill !

**Comment by irieill** [comment]
Working on a reliable PR I did some more investigation and testet all sensible combinations of `chunkSize`, `mode`, `virtualScroll` and `startAtBottom`. Conculsion: nothing works with some default implementation of `LazyDataModel`.

Beside the problem of this issue there are two other problems:
1. With `chunkSize == 0` (default) nothing is displayed for all sensible combinations at all. For `chunkSize != 0` and `startAtBottom == true` the initial loaded chunk is simply wrong. The reason is
https://github.com/primefaces/primefaces/blob/6ec3c4a455e0d03d2e449bd36d5d4f185faf9817/primefaces/src/main/java/org/primefaces/component/datascroller/DataScrollerRenderer.java#L62-L64 At this point the model backs no data.
2. With `virtualScroll == true` on each lazy chunk request the tracked data gets somehow twisted internally. This is hard to describe. I think https://github.com/primefaces/primefaces/issues/5051 and https://github.com/primefaces/primefaces/issues/8949 are affected hereby to.

I already have a solution for 1. The problem with 2 is that the "next" chunk is preloaded.
https://github.com/primefaces/primefaces/blob/6ec3c4a455e0d03d2e449bd36d5d4f185faf9817/primefaces/src/main/java/org/primefaces/component/datascroller/DataScrollerRenderer.java#L127 When doing the modulo stuff in `setRowIndex` the chunks get twisted internally on every even request. My idea is to preload 3 chunks instead ("previous", "current" and "next"). But i have no implementation yet.

From my point of view both points can only be fixed on the renderer side not from the model. When fixed, virtual scrolling works correct with default `LazyDataModel`. Only the data track loosing problem remains for the non-virtual scrollable sensible combinations then.

Thoughts or ideas?

**Comment by melloware** [comment]
I would say fix in the renderer if that is what you are asking?

**Comment by irieill** [comment]
I have created just [another test for DataScroller](https://github.com/irieill/primefaces-test/tree/PF6087) with an implementation of some `LazyScrollableDataModel` that works very well and compares it with the default `LazyDataModel`. With [some additional initialization code](https://github.com/irieill/primefaces-test/blob/33614edc96b229e8624000e132bd092db04ccf04/src/main/java/org/primefaces/test/TestView.java#L80-L84) it works out of the box with current renderer implementation. But i am not sure about it in general. It derives from `LazyDataModel` for compatibility but opts out most of its methods that are not needed. That feels somewhat wrong as approach. What do you think about it?

**Comment by melloware** [comment]
Hmmm I am not an expert on this so would like to hear from @tandraschko @Rapster @jepsar on this one.  I see that DataScroller assumes a LazyDataModel so I would love to fix the renderer to work properly with the lazy data model.  But I do see what you did and it does seem DataScroller has some special requirements.

Maybe we can include your LazyScrollableDataModel and then enforce this component to use it?
