### ISSUE TITLE
SelectOneMenu: add support to use icons

### ISSUE THREAD

**Issue by garcia-jj** [primefaces/primefaces#6140]
**Description**
At this time we are allowed to use icons at SelectOneMenu, but only when the options are expanded. We can see an example in the showcase: https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml. My suggestion is to improve the component to allow us to add only an icon like InputGroup component is.

**Additional context**
Below a screenshot with my proposal. On the right side is the current behavior: the only text is allowed. In the left side the component with icon only support:
<img width="631" alt="Screen Shot 2020-07-11 at 08 45 00" src="https://user-images.githubusercontent.com/140387/87223408-1299e980-c353-11ea-9682-dc503d5cee5f.png">

**Example XHTML**
```xml
<p:selectOneMenu  value="#{selectOneMenuView.theme}">
    <f:selectItems value="#{selectOneMenuView.themes}" var="theme" itemLabel="#{theme.displayName}" itemValue="#{theme}" />
    <p:column>
        <f:facet name="some-facet-name">
             <i class="pi pi-check"></i> <!-- this can be an icon, or another HTML component like image, etc -->
        </facet>
        <h:outputText value=" #{theme.name}" />
    </p:column>
</p:selectOneMenu>
```

With some guidance, helping me to understand the better design for this change, I can try a PR if you like the idea.

Thank you

**Comment by melloware** [comment]
Not sure how i feel about this one.   And InputGroup is not meeting your need?

**Comment by stolp** [comment]
I also have been missing icon support for selectOneMenu in the past. As a workaround I use a menuButton instead, but results are visually not fully convincing as seen in below example (Unable to place an icon in the displayed text, unable to give icons a color). The icon on the left side has been placed there as a seperate entity. I skipped selectOneMenu completely mostly for aesthetic reasons.

![StatusExampleWithMenuButton](https://user-images.githubusercontent.com/522940/87250753-74e40e80-c467-11ea-8485-c355978015e5.png)

To get back to the original proposal: I am not convinced as well with the proposed solution. I think the main problem is here, that the column-based solution for icons in the showcase is more of a hack than a real solution to start with.

Most other components have a clear interface for handling icons, but selectOneMenu does not. The culprit lies in the use of f:selectItem for the menu model, which does not have a way to specify an icon alongside the label and value.

Two possible solutions come to mind here:

1. Replace the f:selectItem(s) with primefaces counterparts which allow additional settings for icons
2. Introduce an iconFactory attribute (naming could be better I think) pointing via el to a server side method which converts a single SelectItem to an icon string.

Additionally other common icon related attributes (iconPos, iconOnly etc.) should be added as well.

I personally would go in favor of the second solution.

What do you think?

**Comment by melloware** [comment]
We can't do Option 1. listed above because then SelectOne does not follow the same as `h:selectOnemenu` and the whole point of the PF SelectOneMenu was to provide a)theming of SelectOne which browser native does not allow and b) customization of the values.  So I don't think we can get away from using `f:selectItem(s)` as the data layer.
See: https://www.tutorialspoint.com/jsf/jsf_selectonemenu_tag.htm

**Comment by stolp** [comment]
You are right, I forgot about that.

**Comment by tandraschko** [comment]
We could option 1) but its a bit more work :P
it should be possible to provide an own p:selectItem/s tag and a inherited model.

**Comment by garcia-jj** [comment]
Hello @melloware. Thank you for you time on this.

The InputGroup is not possible here because it is static. What I need is like an InputGroup, but dynamic. This is the reason because I choose SelectOneMenu.

In my case, I have a contact form, and the user needs to set their contact type (if e-mail, cellphone, home phone or work phone). At this time I have this component:

<img width="392" alt="Screen Shot 2020-07-13 at 06 19 55" src="https://user-images.githubusercontent.com/140387/87287784-e4421880-c4d0-11ea-92dc-d548e46f9384.png">

But when the user selects an option, the SelectOneMenu looks like this (without the related icon):

<img width="376" alt="Screen Shot 2020-07-13 at 06 02 15" src="https://user-images.githubusercontent.com/140387/87285871-7399fc80-c4ce-11ea-8ab6-a4855d50af40.png">

What I need in that case is to have an "e-mail" icon instead of only the e-mail text. The current SelectOneMenu allows me to have an icon + text when the SelectOneMenu is expanded.

Do let me know if I was able to explain my case for you.

Thank you

**Comment by melloware** [comment]
@garcia-jj I understand what you want.

**Comment by jepsar** [comment]
How about
```xhtml
<h:panelGroup styleClass="ui-inputgroup">
    <h:panelGroup id="icon" styleClass="ui-inputgroup-addon">
        <i class="pi pi-#{testView.string}"/>
    </h:panelGroup>
    <p:selectOneMenu value="#{testView.string}" var="item">
        <f:selectItems value="#{['flag','wallet','map','link']}" var="item"
                       itemLabel="#{item}" itemValue="#{item}"/>
        <p:column>
            <i class="pi pi-#{item}"/> #{item}
        </p:column>

        <p:ajax update="@parent:@parent:icon"/>
    </p:selectOneMenu>
</h:panelGroup>
```
```java
@PostConstruct
public void init() {
    string = "flag";
}
```

**Comment by melloware** [comment]
Based on @jepsar excellent example I added this showcase demo...

![image](https://user-images.githubusercontent.com/4399574/165309877-d0133e38-c188-43ff-aa92-90747e84f41c.png)
