### ISSUE TITLE
AutoComplete (dropdown="true") has different styling compared to SelectOneMenu

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6144]
You can see the difference in the showcase:

* https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml
* https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml

It would be nice if there could be consistent styling of the components, and that the `AutoComplete` with dropdown looks the same as the `SelectOneMenu`.

**Comment by melloware** [comment]
@jepsar do you have a proposed fix?

**Comment by jepsar** [comment]
@melloware I haven't looked into it yet, but I was going to. I'm hoping it can be fixed with some CSS.

**Comment by jepsar** [comment]
CSS will get you to some point.. but you will be left with the dropdown not opening when you click the input, and the CSS changes must be applied on all the themes. It's probably better to change the rendered HTML to get it as close as possible to the `SelectOneMenu` and add a click listener (maybe as an optional attribute).

**Comment by jepsar** [comment]
I've been playing around with this for a while. I think this cannot be done without impacting themes. Should we ask @mertsincan for his opinion on this?

**Comment by melloware** [comment]
i added @mertsincan and the label theme for you.

**Comment by jepsar** [comment]
Just a comment to confirm this is still the case with PF10-RC1

**Comment by mertsincan** [comment]
We implemented it like a button in Prime* libraries. So I'm not sure about this change.
https://primefaces.org/primereact/showcase/#/autocomplete

**Comment by buunsal** [comment]
Same for all other prime ui libraries as @mertsincan said. SelectOneMenu is look like an html select element. When clicked, a panel item will definitely open instead of typing. And the other one is a button that opens a panel. You don't have to make a choice and you can choose by typing. Because their intended use is not the same. So we don't want them to look the same either. If we want to make such a design change, we change it in all libraries. We do not have such a plan at the moment.
