### ISSUE TITLE
InputMask: not applying mask to integer

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#6201]
**Describe the defect**
With PrimeFaces 8 the following code worked, master doesn't.

**Reproducer**
https://github.com/erickdeoliveiraleal/primefaces-test/tree/inputmask_integer

**To Reproduce**
Run the code, in 9.0 the input is blank while in 8 the input shows the value.

**Example XHTML**
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>


	<h:form id="frmTest">
		<p:inputMask mask="[99]999999999" maxlength="13" size="14"
			value="#{testView.testNumber}" id="renavam"
			autocomplete="false">
		</p:inputMask>
	</h:form>

</h:body>
</html>
```

**Example Bean**
```java
import java.io.Serializable;

import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class TestView implements Serializable {
	Integer testNumber = 110655605;

	public Integer getTestNumber() {
		return testNumber;
	}

	public void setTestNumber(Integer testNumber) {
		this.testNumber = testNumber;
	}

}

```

**Comment by melloware** [comment]
PF8 (not correct as its blank)??: This makes sense because the optional character in 8 was `?` and in 9 its `[]`
![image](https://user-images.githubusercontent.com/4399574/89561664-d4270b80-d7e6-11ea-9145-da0b5b5e0c8c.png)

So is your goal the first 2 characters are optional?  To me that doesn't make sense the optional characters should be at the end of the mask.

If I do this:
```xml
<p:inputMask mask="999999999[99]"
```
Your code then works fine in PF9...
![image](https://user-images.githubusercontent.com/4399574/89562381-e190c580-d7e7-11ea-88ca-4dab31a35e29.png)

**Comment by melloware** [comment]
@erickdeoliveiraleal can you clarify what you are trying to do with that mask?

**Comment by erickdeoliveiraleal** [comment]
Yes, with 8.0 the mask worked in the beginning of the string, I used your solution at the end and it worked in 9.0, thanks.
