### ISSUE TITLE
DatePicker: built in conversion for LocalDateTime does not support timeZone-attribute

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6238]
**Describe the defect**
When you bind DatePicker (or maybe Calendar) to LocalDateTime and set timeZone-Attribute this does not have any impact. This is because LocalDateTime is without a timezone. (Seems like i forgot this on some point in time.) IMO there´s no easy solution for this. The work-around / solution should be to use `<f:convertDateTime type="zonedDateTime" />`
(I run into this during looking into https://github.com/primefaces-extensions/primefaces-selenium/pull/22.)

**Reproducer**
http://primefaces.org/showcase/ui/input/datepicker/datePickerJava8.xhtml
Input a value into "Time (Timezone GMT+8)" and push submit.

**Thoughts**

- Should we add a note to the documentation of DatePicker and Calendar that timeZone-attribute won´t have an effect on LocalDateTime?
- Should we add a built-in converter for ZonedDateTime?
- ???

(On my day-job this is not an issue because our applications are only used within the default timezone.)

**Comment by melloware** [comment]
this is a tough one.  because the user has chosen LocalDateTime to me they are forgoing a TimeZone.   I think we should add a note to the documention and maybe even throw a FacesException if they have a TimeZone set and are using a LocalDate, LocalTime, or LocalDateTime??

**Comment by GedMarc** [comment]
Hmm LocalDateTIme is always in the local timezone unless specified (loaded) otherwise - 
I think ZonedDateTime is right for the requirement - 

When I came across this in my set, specially on UI inclusion, I had to add quite a few to handle all the types, and then for UI handles, expose the type and allow custom formatting. The java.time set is very very strict on in put formats so a UI with "yyy/MM/dd" doesn't deserialize to a ```LocalDateTime``` but does to a ```LocalDate```

I'm not sure how much of it applies, but I could make a convertor set for the different variations?

https://github.com/GedMarc/GuiceInjection/tree/master/src/main/java/com/guicedee/guicedinjection/json

It's ugly and beautiful at the same time (on a 4k monitor, if you're using less... scroll right xD)

https://github.com/GedMarc/GuiceInjection/blob/master/src/main/java/com/guicedee/guicedinjection/json/LocalDateTimeDeserializer.java
And if you can fix it or make it better! Very grateful!

**Comment by melloware** [comment]
Where did we land on this?  Throwing an error or trying to go through gyrations to convert for timezone?

**Comment by christophs78** [comment]
Throwing an error and add some docu. 
Bonus would be to provide a converter for ZonedDateTime as suggested by @GedMarc. But IMO a stand-alone-converter and not add it implicit to our exisiting Calendar/DatePicker-classes.
