### ISSUE TITLE
Schedule: Allow custom localization

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6344]
**Description**
In PF < 7.0 the Schedule component was configured using PF locales:  https://github.com/primefaces/primefaces/wiki/Locales

When we upgraded to Full Calendar 4.X for PF 8.0 it was decided to use the already built translations that come with FullCalendar so if you used `locale="fr"` for French you would get the French translation from FullCalendar: 
https://github.com/fullcalendar/fullcalendar/blob/master/packages/core/src/locales/fr.ts

Full list of locales: https://github.com/fullcalendar/fullcalendar/tree/master/packages/core/src/locales

However the ability to override the default or customize the localization was lost.

@christophs78 @blutorange @tandraschko

**Comment by melloware** [comment]
OK previously PF was doing this:
```javascript
 configureLocale: function() {
        var lang = PrimeFaces.locales[this.cfg.locale];

        if(lang) {
            this.cfg.firstDay = lang.firstDay;
            this.cfg.monthNames = lang.monthNames;
            this.cfg.monthNamesShort = lang.monthNamesShort;
            this.cfg.dayNames = lang.dayNames;
            this.cfg.dayNamesShort = lang.dayNamesShort;
            this.cfg.buttonText = {today: lang.currentText
                                  ,month: lang.month
                                  ,week: lang.week
                                  ,day: lang.day};
            this.cfg.allDayText = lang.allDayText;
            this.cfg.weekNumberTitle = lang.weekNumberTitle;
            if(lang.eventLimitText) {
                this.cfg.eventLimitText = lang.eventLimitText;
            }
        }
    }
```

However FullCalendar 4+ has removed most of these options except for a couple:
https://fullcalendar.io/docs/buttonText
https://fullcalendar.io/docs/weekText
https://fullcalendar.io/docs/firstDay

So I think all we can put back is this:
```javascript
 configureLocale: function() {
        var lang = PrimeFaces.locales[this.cfg.locale];

        if(lang) {
            this.cfg.firstDay = lang.firstDay;
            this.cfg.buttonText = {today: lang.currentText
                                  ,month: lang.month
                                  ,week: lang.week
                                  ,day: lang.day};
            this.cfg.weekText= lang.weekNumberTitle;
        }
    }
```

**Comment by christophs78** [comment]
My point of view at this time was to define FullCalendars own localication as good enough. (eg because it provides way more locales OOTB and we don´t need to worry about future FullCalendar-updates)

When i look at the commit-history i did this somewhere during my work. 
https://github.com/primefaces/primefaces/commits/321ad2a7acff3e7f55dbc539c8171b0a6175500c/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js with
https://github.com/primefaces/primefaces/commit/7f8eda672320e7179cccd712df08c6c87b2e50c0#diff-bad277cc7c81fa0b282c138e77db2e3e.

**Comment by christophs78** [comment]
I don´t remember all details. But we may need to ensure to have consistent translation. It won´t be ideal to have 3 terms translated and some others not.
Maybe we would need add some more attributes to PF-Locales. (and update this for almost all languages)

**Comment by melloware** [comment]
I agree with your assement the built in Translations are better and future proof us. But this request came from a PRO user who is upgrading to PF 8.0.  Looking at FullCalendar though I don't think PF can customize the way it used to as most of those options are removed and FullCalendar prefers you set `locale` on your Schedule and let it handle it.

**Comment by christophs78** [comment]
This had been the breaking changes for locale with FC 4: https://fullcalendar.io/docs/v4/upgrading-from-v3#locales
Maybe we should sleep one night and then talk about this again.

**Comment by christophs78** [comment]
Which "things" want´s your PRO user customize?
One thing you can always do is to use JS-extender as @blutorange  shows in showcase with ui/data/schedule/extender.xhtml.

**Comment by mertsincan** [comment]
Hi,

Thanks a lot, @melloware and @christophs78. Unfortunately, we need to add these codes for backward compatibility. Of course, we need to tell users the features removed from the FullCalendar component. However, we must continue to support the builds that we previously supported and are still supported by FullCalendar. Unfortunately, such issues will occur with 3rd party components. That's why we need to be careful when updating them. @melloware Could you please add your above fix to 9.0? Thanks a lot again!

```
// PF8.0.x - FullCalendar v4
configureLocale: function() {
        var lang = PrimeFaces.locales[this.cfg.locale];

        if(lang) {
            this.cfg.firstDay = lang.firstDay;
            this.cfg.buttonText = {today: lang.currentText
                                  ,month: lang.month
                                  ,week: lang.week
                                  ,day: lang.day};
            this.cfg.allDayText = lang.allDayText;
            this.cfg.weekLabel = lang.weekNumberTitle;
            if(lang.eventLimitText) {
                this.cfg.eventLimitText = lang.eventLimitText;
            }
        }
    },
```

```
// PF9+ - FullCalendar v5
 configureLocale: function() {
        var lang = PrimeFaces.locales[this.cfg.locale];

        if(lang) {
            this.cfg.firstDay = lang.firstDay;
            this.cfg.buttonText = {today: lang.currentText
                                  ,month: lang.month
                                  ,week: lang.week
                                  ,day: lang.day};
            this.cfg.weekText= lang.weekNumberTitle;
        }
    }
```

**Comment by christophs78** [comment]
At least this was something i explicit noted as part of https://github.com/primefaces/primefaces/pull/5274. (I did not removed this in „secret“ or something like this.)
And i added code to translate old FC-viewnames into new ones.
And we added this to the migration guide. (Something we need to update now.)

**Comment by melloware** [comment]
@mertsincan I will take care of this.  

And yes this is the danger of upgrading 3rd party libs but I think PF absolutely needs to do that to stay on top of browser changes, security fixes, performance, etc.

**Comment by blutorange** [comment]
@melloware It seems the removed localizations options pertain to date and time formatting. By default, FullCalendar uses the native built-in [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) for localizing dates and times. Additionally, there's also the moment plugin (which we use). The built-in formatter is used when the date/time format is an object, moment is used when the date/time format is a string (e.g. "dd-MMMM").

It's possible to customize the dates and times shown in the FullCalendar by setting a date/time format (e.g.titleFormat), and update moment's localization options, like this:

![image](https://user-images.githubusercontent.com/2456413/94343150-1c57f280-000e-11eb-894d-8dc3b80b0032.png)

**Comment by melloware** [comment]
@blutorange care to submit a PR?    

Also what about month short names and days?
```
this.cfg.monthNames = lang.monthNames;
this.cfg.monthNamesShort = lang.monthNamesShort;
this.cfg.dayNames = lang.dayNames;
this.cfg.dayNamesShort = lang.dayNamesShort;
```

**Comment by blutorange** [comment]
* @melloware The settings for FullCalendar are now stored in `this.cfg.calendarCfg`, so this should probably be `this.cfg.calendarCfg.firstDay = lang.firstDay;` etc ?
https://github.com/primefaces/primefaces/blob/fbd18e5afcd51b6f3dbd90fe241c4bab73faf65b/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js#L106-L111
* A few more localized strings in the FullCalendar locales (e.g. https://github.com/fullcalendar/fullcalendar/blob/master/packages/core/src/locales/de.ts) we can change when we pass the locale to FullCalendar:
https://github.com/primefaces/primefaces/blob/fbd18e5afcd51b6f3dbd90fe241c4bab73faf65b/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js#L46
* @christophs78 How is moment.js used currently? As far as I could tell, it's only used for FullCalendar right now? I also didn't find [any locales](https://momentjs.com/docs/#/i18n/) for moment.js - or am I missing something? When I check out the showcase and set the FullCalendar locale to French, everything is in French - but once I change e.g. `dayHeaderFormat`/`columnHeaderFormat` to a moment format string (such as `dd.MM`) -- all localization is lost as it's now using moment and by default there's no locale for moment.js
* @melloware  moment.js also has the options `monthsShort`, `weekdays`, and `weekdaysShort` https://momentjs.com/docs/#/customization/month-abbreviations/

So what we try and see if it works out:

* Expose more formatting settings such as https://fullcalendar.io/docs/v4/titleFormat in the Schedule widget
* Transfer PrimeFaces.locales info to moment.js locales
* Possibly default the formatting options to a moment.js string so that PrimeFaces.locales settings are used by default

**Comment by melloware** [comment]
I like all those ideas and I think we should do it.

**Comment by christophs78** [comment]
@blutorange:
> How is moment.js used currently?

FullCalendar 4 had a long list of breaking changes: https://fullcalendar.io/docs/v4/upgrading-from-v3
It removed jQuery and Moment JS-dependencies.

But it introduced connector plugins for Moment JS and Moment Timezone.

As far as i remember i had removed Moment JS at some point on the way from FC3 to FC4. But there had been existing UseCases which broke by removing Moment JS. So i reintroduced Moment JS.
As you said:

> The built-in formatter is used when the date/time format is an object, moment is used when the date/time format is a string (e.g. "dd-MMMM").

Think this matches https://fullcalendar.io/docs/moment-plugin.

Like @melloware i like all your ideas.

**Comment by melloware** [comment]
OK can you all review my latest PR.  I took most of @blutorange suggestions and I added a new showcase page for IL8N to test it .

Edit: most not all suggestions

**Comment by blutorange** [comment]
Code looks good to me. 

One thing that might cause issues is if somebody has already included their own locale for moment.js -- once they include a schedule component some keys get overwritten. But I guess this is alright since the're still configurable via PrimeFaces.locale

I was also thinking if we could default FullCalendar's date/time format to moment.js format strings -- but that requires we know the appropriate default format string for each locale, and also that PrimeFaces locale is set correctly. FullCalendar uses the browser's built-in formatting by default, I guess this is what most users would want anyways.

Regarding exposing more FullCalendar options for date/time formats, I might take a look at it later, but for now it's still configurable via the extender.

Hmm, so basically users can already configure most aspects as long as they know how, might help to add a few more examples to the docs.

**Comment by melloware** [comment]
Yeah I added a new basic localization.xhtml example where its localized for German but we can add more to that example.  but I wanted to at least test this out.  thanks for the review!

**Comment by christophs78** [comment]
Just to be clear what to expect:
I added a X to almost all PrimeFaces.locales ['de'] =  - entries.

Result is - as expected - following:
![image](https://user-images.githubusercontent.com/10461942/94469243-0ab94b00-01c6-11eb-9a0c-37804e71d373.png)

FullCalendar-Buttons are localized from PrimeFaces.locales ['de']. But monthNames and dayNames are still as-is. (Because FullCalendar does not use Moment.js for this OOTB.)

**Comment by melloware** [comment]
Where does it get those MonthNames from then?  It seems that contradicts what @blutorange demo did with monthnames?

**Comment by christophs78** [comment]
FullCalendar uses Browser-built-in functionality for this:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat

```JavaScript
var date = new Date(Date.UTC(2012, 11, 20, 3, 0, 0, 200));

// request a weekday along with a long date
var options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
console.log(new Intl.DateTimeFormat('de-DE', options).format(date));
// → "Donnerstag, 20. Dezember 2012"
```

Moment.JS is only used for certain UseCases like 

> dayHeaderFormat/columnHeaderFormat to a moment format string (such as dd.MM) 

as @blutorange  wrote.

**Comment by mertsincan** [comment]
Hi all,

I made the following changes;
- Added slotLabelFormat to primefaces-p.taglib.xml 
https://fullcalendar.io/docs/slotLabelFormat
- Removed monthNames, monthNamesShort, dayNames and dayNamesShort;
https://fullcalendar.io/docs/v4/upgrading-from-v3
Users can use the extender method to customize these options. Please see "Locales" section in the above link.
- For backward compatibility, options supported by FullCalendar (not related to any plugin) have been merged with PrimeFaces locale.
- Now two separate local values ​​are passed to the widget for FullCalendar and PrimeFaces.locales. Please see this case;
PrimeFaces.locales -> pt_BR
FullCalendar -> pt-br
Maybe there will be two separate locale attributes for Schedule component in the future.
