### ISSUE TITLE
Class ui-widget on p:commandLink and p:link breaks fontawesome

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#648]
Using a simple `p:commandLink` with themeroller icon was no problem.

```
<p:commandLink styleClass="ui-icon ui-icon-search" .../>
```

Updating all icons to font awesome this does not work:

```
<p:commandLink styleClass="fa fa-search" .../>
```

The reason for this is, that primefaces adds the class `ui-widget` to the `a` anchor tag which selectes different font.

Is `ui-widget` necessary on link? in most cases any parent container or body already has `ui-widget` applied to it. 
## Current workaround

Use child html component:

```
<p:commandLink>
    <i class="fa fa-search"/> 
</p:commandLink>
```

**Comment by cagataycivici** [comment]
``` xml
<p:commandLink styleClass="fa fa-search" .../>
```

Works just fine for me.

**Comment by miguelkv** [comment]
Using Sentinel layout with FontAwesome we get a error, as stated by @djmj.

The reason is the .ui-widget class added to <a>, because it changes the font-family to "'titillium_webregular' !important".

One workaround:
`.ui-widget.ui-commandlink.fa{ font: normal normal normal 14px/1 FontAwesome !important; }`

This error can be seen at http://www.primefaces.org/eos/sentinel/forms.xhtml.
