### ISSUE TITLE
Datatable: Lazy Sorting Regression

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6489]
**Describe the defect**
After the new sorting was implemented in https://github.com/primefaces/primefaces/issues/5438 one of the Integration Test Cases is now failing.

Error `DataTable002Test.testLazyFilter:151 expected: <Language 18> but was: <Language 9>`

**Reproducer**
Integration Test: https://github.com/primefaces-extensions/primefaces-integration-tests/blob/dc72818c1e099191b6e47bf2b9e46ab85801de54/src/test/java/org/primefaces/extensions/integrationtests/datatable/DataTable002Test.java#L126-L154

**Environment:**
 - PF Version: _9.0_

**Example XHTML**
```html
<h:form id="frmTest">
<p:dataTable id="datatable" value="#{dataTable002.lazyDataModel}" var="lang" paginator="true" rows="10" filteredValue="#{dataTable002.filteredProgLanguages}" lazy="true">
           <p:column headerText="ID" sortBy="#{lang.id}">
                <h:outputText value="#{lang.id}" />
            </p:column>

            <p:column headerText="Name" sortBy="#{lang.name}" filterBy="#{lang.name}" filterMatchMode="contains">
                    <h:outputText value="#{lang.name}" />
            </p:column>

            <p:column headerText="First appeared" sortBy="#{lang.firstAppeared}" filterBy="#{lang.firstAppeared}" filterMatchMode="gte">
                    <h:outputText value="#{lang.firstAppeared}" />
            </p:column>
</p:dataTable>
</h:form>
```

**Integration Test**
```java
    @Test
    @Order(3)
    @DisplayName("DataTable: Lazy: filter")
    public void testLazyFilter(Page page) {
        // Arrange
        DataTable dataTable = page.dataTable;
        Assertions.assertNotNull(dataTable);
        List<ProgrammingLanguage> langsFiltered = langs.getLangs().stream()
                .filter(l -> l.getFirstAppeared() >= 1998)
                .sorted(Comparator.comparingInt(ProgrammingLanguage::getFirstAppeared))
                .collect(Collectors.toList());

        // Act
        dataTable.selectPage(1);
        dataTable.sort("First appeared");
        dataTable.filter("First appeared", "1998");

        // Assert
        List<Row> rows = dataTable.getRows();
        Assertions.assertNotNull(rows);
        Assertions.assertEquals(10, rows.size()); //one page

        Assertions.assertEquals(langsFiltered.get(0).getName(), rows.get(0).getCell(1).getText());
        Assertions.assertEquals(langsFiltered.get(1).getName(), rows.get(1).getCell(1).getText()); //fails

        assertConfiguration(dataTable.getWidgetConfiguration());
    }
```

We sort by First Appeared year and you can see its sorted correctly:
![image](https://user-images.githubusercontent.com/4399574/98442084-9af58480-20d0-11eb-9d41-8929853fa695.png)

Then we filter by year `1998` and the filtering works but the list is now unsorted with 1998 and 1999 mixed together even though the column is sorted.  So our test fails because record #2 should not be 1999 it should be another 1998 `DataTable002Test.testLazyFilter:151 expected: <Language 18> but was: <Language 9>`  It appears to be sorted by the `Id` column now again.

![image](https://user-images.githubusercontent.com/4399574/98442117-c7a99c00-20d0-11eb-8a8e-2a2397e8ddad.png)

@christophs78 @Rapster

**Comment by christophs78** [comment]
Following data is passed to load-method of LazyDataModel with sort and filter:
![image](https://user-images.githubusercontent.com/10461942/98446471-e4b88c00-211d-11eb-96ca-7d923a64e3ea.png)

a) no sort-meta (NOK)
b) filter-meta contains both attributs - the one we wanted the filter an the one without filter (this may be OK)

**Comment by Rapster** [comment]
Indeed the issue is that sortBy gets lost during second request (filtering), I don't know yet how it could've work before since sortKeys are not passed to the filtering http request:

![image](https://user-images.githubusercontent.com/7521311/98447629-9360ca80-2126-11eb-80a9-46c30376c01b.png)

An input state holder should put in place to save infos between requests don't you think?

**Comment by christophs78** [comment]
Cross check this with http://primefaces.org/showcase/ui/data/datatable/lazy.xhtml.
Filtering does not send sortKeys as of PF 8.0.

**Comment by christophs78** [comment]
look at
https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/datatable/DataTable.java#L1327 

This seem to be part of our issue.

**Comment by Rapster** [comment]
Well spotted, indeed removing this would make it work. It's actually something I wish we could avoid, that way no need to repopulate sortBy map every request, but here is the thing, some users expect columns to "change" (added/removed) between 2 requests. 

So if I remove that line, and I add/remove columns between 2 requests, sorting would not work since sortBy map would not be updated as it is already saved in statehelper, and as a [quote](https://stackoverflow.com/a/16504252/4605161)

> StateHelper provides a convenience for component developers (who subclass UIComponent directly and not a standard component) **to maintain the state of a component across requests**. It plays an integral role in JSF view state saving and the underlying contract provides more than just a means to stash component attributes.

**Comment by christophs78** [comment]
Sort and filter has to work combined. It can´t be a solution to say you can use sort or filter but not both.

Is there a way to update sortBy map instead of resetting it? Add and remove columns when necessery in the existing sortBy-map we stored via statehelper?

**Comment by christophs78** [comment]
One more thing:
Compare http://primefaces.org/showcase/ui/data/datatable/lazy.xhtml with our current master.

8.0-Final:
![image](https://user-images.githubusercontent.com/10461942/98459782-50dad480-219e-11eb-8797-63e21c37c358.png)

9.0-Snapshot:
![image](https://user-images.githubusercontent.com/10461942/98459808-81227300-219e-11eb-9575-04400d2d2a11.png)

Filter was lost. IMO this is only a showcase-XHTML-issue.

**Comment by Rapster** [comment]
> Sort and filter has to work combined. It can´t be a solution to say you can use sort or filter but not both.

Of course

> Is there a way to update sortBy map instead of resetting it? Add and remove columns when necessery in the existing sortBy-map we stored via statehelper?

Not really, it's more or less the same problem I faced recently trying to fix #6169. I'm gonna try to add an input state holder for sortKeys infos (2 at least, _sortKey and _sortDir)

**Comment by tandraschko** [comment]
Cant we fix it like it worked before?
If it worked before, there must be a better way like adding Inputs on the client

**Comment by Rapster** [comment]
Hard to tell how it worked before... in single mode, the `sortColumnKey` was never reseted from statehelper so it could remember what was the last sorted column, not sure if lazy + multi sorting worked before. 

My attempt to fix this, is to create 2 input state holder

**Comment by tandraschko** [comment]
I think saving it in the state should work fine on the server side, it feels weird to make a workaround on the clientside.
Maybe there is still something weird how you maintain the state or why and when reset

**Comment by Rapster** [comment]
>I think saving it in the state should work fine on the server side, it feels weird to make a workaround on the clientside.

Then the fix is easy, but since component are request scoped, we should proceed in a way that, for example in the present scenario: sort + filter should make two requests:

- first request to sort
- second request to sort and filter.

I don't think it's weird, or you should consider it as a workaround, I think this is how it is supposed to be. Today, few things are saved on server side which are tricky to deal with  _(since component is request scoped)_, which brings me to your second question, when should we save stuff in statehelper? 😅 

Should we assume for now, that datatable structure is not meant to change between 2 requests?

**Comment by melloware** [comment]
I am not sure about anyone else but I don't think the table structure should be changing between two requests it should only change on a full update if the entire datatable is being updated?

**Comment by Rapster** [comment]
@christophs78 JFYI, actually to update sortMeta (in case of adding/removing columns) my best bet would be to play with `PostAddToViewEvent` & `PreRemoveFromViewEvent` events and update sortMeta accordingly

@melloware I'll have to try if updating the whole table will reset the component

**Comment by Rapster** [comment]
@melloware Updating the whole table does not reset statehelper :(

**Comment by tandraschko** [comment]
a component is request scoped yes but the StateHelper is ViewScoped, which is the correct place to save such infos.
When can the sortMeta change?

**Comment by tandraschko** [comment]
i general the filters are working great and like i handled the filterBy map. Why cant you do it like this?

**Comment by Rapster** [comment]
> a component is request scoped yes but the StateHelper is ViewScoped, which is the correct place to save such infos.

Then I'll simply remove setSortMetaAsMap from `DataTable#saveState`?

> When can the sortMeta change?

sortMeta change only when sorting is requested. (and set as null once the request is finished)

> i general the filters are working great and like i handled the filterBy map. Why cant you do it like this?

Not sure what you mean by "like i handled the filterBy map" but I'm sure it worked great. Before I used to think that sorting and filtering were features difficult to understand, but today it's a lot more simple, and you can also have a look at https://github.com/primefaces/primefaces/pull/6486, specially at FilterFeature class, how having those maps make life easier

**Comment by tandraschko** [comment]
i will get a beer now and explain when state/fields etc. are used :)

**Comment by tandraschko** [comment]
Maybe someone can do a small text/guide in our wiki for contributors?
I will explain a bit general stuff and history.

JSF creates a new UIViewRoot instance for each request and, if it's a postback, apply the saved state on it (UIComponent#restoreState). After each request, the state of all components is saved (UIComponent#saveState).

The component/view state is saved in ViewScoped; actualy ViewScope==State, State==ViewScope.
The StateHelper is just a helper or "version 2.0" of the UIComponent#save/RestoreState. I think it was introduced in JSF 2.0 with partial state saving.

The scope of a Renderer is ApplicationScoped - please dont use private variables here!

The scope of a UIComponent is >in general< RequestScoped and can therefore cache stuff in private fields, which can be used during the current request.
This is and should only be used by complex components like DataTable.

Actually all of this would be quite easy. Private fields are automatically "resetted" each request, stuff which needs to be alive over multiple requests can be stored via StateHelper. Thats it!


Now we need to take ViewPooling into account...

In the past some dude (can't remember) did a prototype that the UIViewRoot instance is "reused" in a ApplicationScoped maner, to overcome heavy performance problems of Mojarra in the past (yeah, it's much better now!).
Stated is still saved and restored, but the it's applied on the existing UIViewRoot instance, instead of creating a new object tree.
This was just a third party addon which didnt cover all cases but worked great for simple views.
Leo of MyFaces implemented this concept directly in MyFaces without any contra and even supports complex views (http://myfaces.apache.org/#/coreConceptsViewPooling)
In general its a good performance increasement as it saves GC. The viewRoot and components objects must not be created every request, we use a cache here and reuse instances.

As PrimeFaces should support default UIViewRoot handling and MyFaces ViewPooling, we need to take care.
If we use private fields in a UIComponent, we need to reset before putting it back into MyFaces ViewPooling cache. The correct place here is #saveState.

Hope its a bit clearer now?

**Comment by Rapster** [comment]
Thank you Thomas, yes it's clearer now. Since sortMeta have to live over multiple requests, it stays in StateHelper but is not reseted to null at saveState

**Comment by melloware** [comment]
I think I will try and add this to the contributing guide as this is really good information!

**Comment by melloware** [comment]
@Rapster thank you I can confirm all the Integration Tests are now passing including all of the tests that were added to prove you have fixed the other sorting defects! https://github.com/primefaces-extensions/primefaces-integration-tests/actions/runs/352863652
