### ISSUE TITLE
Calendar js error "wrong time format" with pattern (MM/dd/yyyy hh:mm a)

### ISSUE THREAD

**Issue by cchet** [primefaces/primefaces#649]
When the locale is english and/or the pattern is set to 'MM/dd/yyyy hh:mm a' then the jquery datetime picker fails for "wrong time format" because the datetime picker cannot parse the time part because it thinks the time part is AM/PM.

This seems to be an jquery javascript issue.
The showcase does not contain an example with 12 hour format and therefore I do not know if this would work in version 5.2.10.

primefaces:: 5.2.5
myfaces: 2.1.17

**Comment by mertsincan** [comment]
We could not replicate the issue, please try with 5.2.10 or 5.3

**Comment by cchet** [comment]
Thanks.
We will update to version 5.2.10 and will test it right away.

**Comment by mbechler** [comment]
Seeing the same thing in 5.3, only for mindate and maxdate, the reason seems to be that splitDateTime will use the global default format and not the one passed to parseDateTime as an argument. When the number of separators differs between the default and the pattern format this results in a split at the wrong position.

Also reported to upstream
https://github.com/trentrichardson/jQuery-Timepicker-Addon/issues/875

It looks like this could be worked-around by also passing the time format via the time settings dict.

**Comment by MitchTalmadge** [comment]
Same problem on PrimeFaces 6.0.

**Comment by tandraschko** [comment]
If the issue still persists, please create a new issue and provide every infos required by the issue template.

**Comment by jrcampins** [comment]
The issue persists in version 6.1, but it doesn't fail unless in addition to pattern the calendar component also has mindate/maxdate.

**Comment by melloware** [comment]
I have reopened this ticket here: https://github.com/primefaces/primefaces/issues/4366
