### ISSUE TITLE
Schedule: jQuery 3.5.0 Issue

### ISSUE THREAD

**Issue by ahoflack** [primefaces/primefaces#6493]
Hi, 

Since PrimeFaces team upgrade jquery in PF7.x version to 3.5.0, Day and Week view on p:schedule doesn't work fine (events not showing).
I test on PF8.0 this error.

I think it is due to 7.0.14 upgrade.

this issue is analysed on 
https://github.com/fullcalendar/fullcalendar/issues/5370

which is corrected with jquery 3.5.1.

Please report to upgrade jquery on PF.
Thx

**Comment by melloware** [comment]
Thanks for reporting.  I was wondering why they released Jquery 3.5.1 with just one minor fix but this explains it.

**Comment by melloware** [comment]
@ahoflack jQuery 3.5.1 does not fix this issue. 

I think the issue was introduced because PF 7.0.14 and 8.02 were updated to Jquery 3.5.0 (https://github.com/primefaces/primefaces/issues/5807).  3.5.1 just has one minor backwards compatibility change they are going to remove again in 4.0.
See: https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/

So I think your issue is that in Elite 7.0.14 its broken?  Because I have verified its working fine in 8.0.2 or higher?

If you back up to 7.0.13 is everything working?

@mertsincan this looks like an Elite 7.0.14 issue only.

**Comment by ahoflack** [comment]
Yes, when in comme back to 7.0.13, all work fine. Not with higher version.

It is still broken 
Thx

**Comment by melloware** [comment]
OK @mertsincan is aware and hopefully he will fix for 7.0.15.

**Comment by tandraschko** [comment]
i pinged him also in slack, nothing more we can do.

**Comment by ahoflack** [comment]
Hi,

this issue is closed but jquery version seems to be same like 7.0.13 in last version 7.0.18 yesterday. 

Could you please open this issue ?

How can i check jquery version exactly in PF package 

Thx
Alexander 

----- Mail original -----
De: "Melloware" <notifications@github.com>
À: "primefaces/primefaces" <primefaces@noreply.github.com>
Cc: "Alexandre Hoflack" <alexandre.hoflack@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Lundi 9 Novembre 2020 18:53:02
Objet: Re: [primefaces/primefaces] Schedule: jQuery 3.5.0 Issue (#6493)





OK @mertsincan is aware and hopefully he will fix for 7.0.15.

**Comment by melloware** [comment]
@ahoflack To find out Jquery version open F12 console in your browser and type `jQuery.fn.jquery` to display the Jquery version running.

And since this is an Elite 7.0 issue we will not re-open this ticket this is the Community tracker not for Elite release. If you have an urgent need you should contact PrimeTek directly. Or upgrade to 8.0.2 or higher this issue is definitely fixed.

**Comment by ahoflack** [comment]
Thx for information on 8.0.2 release,

I wish you a merry Christmas and an Happy New Year

Alexander

----- Mail original -----
De: "Melloware" <notifications@github.com>
À: "primefaces/primefaces" <primefaces@noreply.github.com>
Cc: "Alexandre Hoflack" <alexandre.hoflack@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Mercredi 23 Décembre 2020 15:05:33
Objet: Re: [primefaces/primefaces] Schedule: jQuery 3.5.0 Issue (#6493)





@ahoflack To find out Jquery version open F12 console in your browser and type jQuery.fn.jquery to display the Jquery version running. 

And since this is an Elite 7.0 issue we will not re-open this ticket this is the Community tracker not for Elite release. If you have an urgent need you should contact PrimeTek directly. Or upgrade to 8.0.2 or higher this issue is definitely fixed.
