### ISSUE TITLE
partialSubmitFilter does not filter inputs inside p:fieldset in Chrome

### ISSUE THREAD

**Issue by akarpavicius** [primefaces/primefaces#657]
Primefaces 5.2 on Jboss eap 6.2. JSF 2.1

Ajax partial submit with partialSubmitFilter does not filter input components that are placed inside the 
 p:fieldset  tag. Issue is only Chrome (v. 44). In IE (v.11) works fine.

Here is a JSF fragment that fails. "onenewKey" field, thas is inside the  p:fieldset  tag, fails validation even though it should be excluded from ajax submit, as other two inputs are. Bean is irrelevant for the test.

```
    <h:form id="form">
        <p:messages/>
        <h:panelGroup id="fieldGroup">
            <p:inputText id="newKey" value="#{jobInstanceBean.customFieldSelectedPeriodId}" required="true" label="OK" />
            <p:fieldset>
                <p:inputText id="onenewKey" value="#{jobInstanceBean.customFieldSelectedPeriodId}" required="true" label="SHOULD BE IGNORED" />
            </p:fieldset>
            <p:inputText id="twonewKey" value="#{jobInstanceBean.customFieldSelectedPeriodId}" required="true" label="OK again" />
        </h:panelGroup>
        <p:commandButton id="saveButtonAjax" value="#{messages['action.save']} " action="#{jobInstanceBean.saveOrUpdate(false)}" icon="ui-icon-check"
            process="@this :form:fieldGroup" partialSubmit="true"
            partialSubmitFilter=":not([name$='newKey'])" update="@form">
        </p:commandButton>
    </h:form>
```

**Comment by cagataycivici** [comment]
I think this is expected as your query selects the fieldset and serializeArray of jQuery that we use serializes the fieldset so includes the onenewKey. I'd suggest using process option as it can also support jQuery selectors via PFS e.g. @(form) instead of partialSubmitFilter which is low level. It only effects what to send to server, the process attribute defines what to process in the end. So although you don't send values of components to server in some cases, they might still throw validation errors. Better not to include them in partial process using process attribute.

https://api.jquery.com/serializeArray/
