### ISSUE TITLE
Overview Mime-Types over Tika?

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6612]
It only has ~60kb instead of 7mb TIKA. https://github.com/overview/mime-types

Could some check this? Does it cover all cases like TIKA?

**Comment by tandraschko** [comment]
@cnsgithub ?

**Comment by melloware** [comment]
@tandraschko I think we tried before and here was the result: https://github.com/primefaces/primefaces/issues/4244

Because some files can only be detected with magic numbers and not just by file extension.

**Comment by tandraschko** [comment]
Afaics Overview does also content checking?

**Comment by melloware** [comment]
I can give it a shot and let you know.

**Comment by melloware** [comment]
OK now I remmeber why its because Tika plugs into the standard FileContentDetector SPI interface:
https://odoepner.wordpress.com/2013/07/29/transparently-improve-java-7-mime-type-recognition-with-apache-tika/

I am going to submit a PR over at MimeTypes that makes it also an SPI so we can plug it in and give users the choice between Tika or MimeTypes!

https://github.com/overview/mime-types/issues/7

**Comment by tandraschko** [comment]
Ok, we could even integrate it without this SPI but sounds good!

**Comment by tandraschko** [comment]
perfect, he already responded! We must also use this Class.forName hack probably we have for TIKA

**Comment by melloware** [comment]
Yep working on it.

**Comment by Rapster** [comment]
Does it actually matter Tika, Mime-Types or whatever? It's up to `Files#probeContentType` to find the right impl. Now I remember starting working on this... Yeah I think we don't need any of this. As of today,we're doing this:
```java
String contentType = null;
if (context.getFileTypeDetector() != null) {
    contentType = context.getFileTypeDetector().probeContentType(tempFile);
} else {
    // use default Java fallback
    contentType = Files.probeContentType(tempFile);
}
```

but `Files#probeContentType` already does that

**Comment by tandraschko** [comment]
yeah but there was a classloading issue AFAIR, so we did a manual lookup try

**Comment by melloware** [comment]
Correct it was done this way on purpose because of class loading.

**Comment by Rapster** [comment]
Yeah I'm reading this post to understand, though I'm trying to find the source code you mentionned:
 >  If you look in the source code its says that TIKA should have a javax.spi in META-INFO to tell Java its a content prober. That parts seems not to be happening.

Is this problem reproducable on showcase?

**Comment by Rapster** [comment]
Ok I reproduced this problem on the showcase, seems like a classloader issue indeed... I fixed it by reimplementing Files#probeContentType:

```java
    public static String probeContentType(Path path) throws IOException {
        ServiceLoader<FileTypeDetector> loader = ServiceLoader.load(FileTypeDetector.class);
        for (FileTypeDetector detector: loader) {
            String result = detector.probeContentType(path);
            if (result != null)
                return result;
        }

        // fallback to default
        return Files.probeContentType(path);
    }
```

So I think we should no longer bother with tika or whatsoever, though I think we should give the possibility to set the FileTypeDetector, in web.xml for instance, the user might want to prioritize

**Comment by melloware** [comment]
Cool I will update my PR with this and I like your suggestion about priority.

**Comment by Rapster** [comment]
I already work on a proposal, will submit it soon

**Comment by melloware** [comment]
I like your PR.  Now simply including either Tika or MimeType 1.0.0 when it is released will automatically be picked up

**Comment by melloware** [comment]
@Rapster I am testing with MimeTypes and I think we need to put this line back:
```java
 //If Tika is in place, we drop the original file extension to avoid short circuit detection by just looking at the file extension
        String tempFileSuffix = tika ? null : "." + FilenameUtils.getExtension(fileName);
        String tempFilePrefix = UUID.randomUUID().toString();
        Path tempFile = Files.createTempFile(tempFilePrefix, tempFileSuffix);
```

We remove the file extension if Tika so it tests "magic bytes" only but the standar NIO Detector and Mime Types require the file extension to properly evaluate the type.

**Comment by melloware** [comment]
I will submit a PR.

**Comment by Rapster** [comment]
I'll have a closer look regarding Tika

**Comment by melloware** [comment]
I think @cnsgithub removed the extensions because I think Tika will do an extension check first before a magic bytes check.  This way it forced it to not use the file extension.  WE could just remove that requirement and just let Tika be Tika and always use the extension.  We could probably skip this Temp File check altogether because its just being done to test the magic bytes by ignoring the file extension.  But my thought was to leave it in.

**Comment by Rapster** [comment]
I just pinged the Tika guys asking for a new impl of FileTypeDetector... Indeed Tika check on extension first for some reason... For security reasons (and that's the topic here) I would completely ignore the extension, so whether it's mime-types or Tika I can't say I'm happy with what they're doing... Since Tika is the "RI kinda" of content analysis, I guess we can workaround it...

**Comment by melloware** [comment]
OK thanks for researching.  Did you open a Tika ticket you could link here or just ask on the mailing list?

**Comment by Rapster** [comment]
I just pinged an existing ticket where they talk about this https://issues.apache.org/jira/browse/TIKA-1217
