### ISSUE TITLE
DatePicker: TimeOnly 12:04 a.m. (midnight plus 4 minutes) is not handled correctly

### ISSUE THREAD

**Issue by alipsitz-sf** [primefaces/primefaces#6636]
(Apologies in advance, I am new to reporting defects. I kinda just looked at what others were doing to fill in the format below.)

**Describe the defect**
Using the time-only 12-hour datePicker causes 12:04 a.m. to become 12:04 p.m. The input box correctly displays "12:04 AM", but when opening the time picker, it gets changed to 12:04 PM" and updates the input box with the incorrect value.
GIF below:
![PrimefacesDefect](https://user-images.githubusercontent.com/38224657/101688276-ca820e80-3a39-11eb-9dde-a22135f2a66e.gif)

**Environment**

PF Version: 8.0.5
JSF + version: Mojarra 2.3.14
Tomcat 8.5
Affected browsers: Chrome (at least)

**To Reproduce**
1. XHTML:
```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" xmlns:p="http://primefaces.org/ui" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
<h:head>
    <title>Title</title>
</h:head>
<body>
<p:datePicker id="datePickerDemo" hourFormat="12" value="#{rTest.dateExample}" timeOnly="true"/>
</body>
</html>
```

2. Backing Bean (note: same behavior with LocalTime and Date)

```import java.time.LocalTime;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

@RequestScoped
@Named("rTest")
public class RequestTest {

  private LocalTime dateExample = LocalTime.of(0, 4);


  public LocalTime getDateExample() {
    return dateExample;
  }

  public void setDateExample(LocalTime dateExample) {
    this.dateExample = dateExample;
  }
}
```

**Commentary**
The issue appears to be in [this code](https://github.com/primefaces/primefaces/blob/6c67dadd07ab2b7887f43f14da82d73f30427659/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js#L752) snippet. Passing "12:04" and "AM" into parseTime causes the AM to get dropped and hour: 12, minute: 4, second: null to be returned. I'm not much of a JavaScript developer, but maybe the hour needs to get set to zero?

Thanks!

**Comment by melloware** [comment]
Thanks for reporting we will look into it and report back.

**Comment by melloware** [comment]
I have confirmed your issue with reproducer:
[pf-6636.zip](https://github.com/primefaces/primefaces/files/5672953/pf-6636.zip)

**Comment by melloware** [comment]
@christophs78 I can see the problem. 

**8.0**
in 8.0 PF sent this to the UI: `defaultDate:"00:04 AM"` which was both correct and incorrect.  It has "00:04" in the text box which is not even a valid AMPM date.  But had the UI dropdown correct.
![image](https://user-images.githubusercontent.com/4399574/101789704-9c4f0e00-3acf-11eb-867c-940ce70d9b4d.png)


**9.0**
In 9.0 PF sent this to the UI: `defaultDate:"12:04 AM"` which is correct in the box but it makes the AMPM DatePicker off.
![image](https://user-images.githubusercontent.com/4399574/101789544-6f026000-3acf-11eb-8b85-e1dce0af890b.png)

I think this is all due to JavaScript dates not having the concept of AMPM.  So in JS it needs to be hour="0" to be 12:04 AM while if you make it hour="12" it makes it PM because JavaScript hours are 0-23 based.

**Comment by melloware** [comment]
I wrote a failing integration test proving the issue as well so if its fixed we will have a regression test.
https://github.com/primefaces-extensions/primefaces-integration-tests/commit/dc1b455549e771f19347b5ab2365f36cbcfb5c95
