### ISSUE TITLE
Core: After updating a component using AJAX in Safari, the current scroll position changes

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#6700]
Test code;
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
 
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    	xmlns:p="http://primefaces.org/ui"
    xmlns:h="http://java.sun.com/jsf/html">
  
<h:head>
    <title>Test</title>
</h:head>
<h:body>
    <h:form>
	    <div style="height: 1000px">
	    	<div style="height:400px"></div>   
	    	<div style="height:1800px"> 
		        <h:inputText id="name" value="#{testBean.test}"></h:inputText>
		        <p:selectOneMenu>
		        	<f:selectItems value="#{testBean.values}" />
				<p:ajax listener="#{testBean.test()}" update="@form" />        
			</p:selectOneMenu>
		</div>
	    </div>
    </h:form>
</h:body>
</html>
```

**Comment by tandraschko** [comment]
@mertsincan as discussed, this breaks basic AJAX cases, we reverted it for now

**Comment by buunsal** [comment]
I wanted to ask here because I don't know enough core.js and ajax requests. While debugging, something like the following came to my mind and seemed to solve the safari scroll problem. But it can also be wrong.
`var scroll = $(document).scrollTop();`
`$(PrimeFaces.escapeClientId(id)).replaceWith(content);`
`$(document).scrollTop(scroll);`
WDYT @mertsincan @tandraschko

**Comment by melloware** [comment]
Just my two cents I don't love that fix and if we were going to do it I would prefer it be wrapped in `isSafari` like I did in this closed PR: https://github.com/melloware/primefaces/commit/16f2242e5006cd8a46f2271a89314e602e57a67f

I wouldn't want this executed for all browsers.

**Comment by sqores** [comment]
> Just my two cents I don't love that fix and if we were going to do it I would prefer it be wrapped in `isSafari` like I did in this closed PR: [melloware@16f2242](https://github.com/melloware/primefaces/commit/16f2242e5006cd8a46f2271a89314e602e57a67f)
> 
> I wouldn't want this executed for all browsers.

I hadn't seen your commit and I thought the problem persists.  I was also able to reproduce the problem in safari. Thats interesting.

**Comment by sqores** [comment]
If you have resolved the problem and you are sure it is not affecting other browsers, you can ignore what I wrote.

**Comment by buunsal** [comment]
If you have resolved the issue and you are sure it is not affecting other browsers, you can ignore what I wrote.

**Comment by melloware** [comment]
No we haven';t solved it we reverted Mert's change in Master because it broke the integration tests.  I was just wrapping his fix in a Safari check but we reverted that too when we realized the fix does not really fix the issue. So master has the same code it always has had and we reopened this ticket.

**Comment by christophs78** [comment]
https://forum.primefaces.org/viewtopic.php?f=3&t=64889 probably also has this root cause

**Comment by christophs78** [comment]
IMO 8.0.6 and 7.0.18 should be withdrawn. (Or release 8.0.7 and 7.0.19 asap which solves this issue.)

**Comment by tandraschko** [comment]
i cant help debugging here as i dont have an safari here. i would start google if this is a known bug when replacing DOM elements on safari.

**Comment by christophs78** [comment]
Tried to reproduced the original issue with Merts example on my iPad Pro. (iOS/iPadOS 14.2)
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
No scroll-position-issue
On which system with OS and Safari-version was the original issue reproduceable?
Can you record a short video of this issue?

**Comment by buunsal** [comment]
I'm using macOS Catalina 10.15.7 with safari v14.0.2. I was able to reproduce the issue and here is a video for you.

https://user-images.githubusercontent.com/45278820/103731692-d3dda700-4ff6-11eb-83bc-3f3887101bb8.mov

After the adding these lines:

```
if (PrimeFaces.env.safari) {
   var scroll = $(document).scrollTop();
   $(PrimeFaces.escapeClientId(id)).replaceWith(content);
   $(document).scrollTop(scroll);
} else {
   $(PrimeFaces.escapeClientId(id)).replaceWith(content);
}
```

https://user-images.githubusercontent.com/45278820/103733142-1785e000-4ffa-11eb-9b37-2b2dea46aa5f.mov

**Comment by christophs78** [comment]
We should check what happens when eg p:focus is used combined with this.
Or something like https://primefaces.github.io/primefaces/8_0/#/core/javaAPI?id=execute-javascript may change focus, scroll-position,.... To be sure we do not create another regression on Safari.

Personally i only own a iPad but not a MacOS-device. So i can´t do this checks.
I tried do add Safari-support to our integration-tests with https://github.com/primefaces-extensions/primefaces-integration-tests/pull/88. This is not ready but maybe you can have a look at this. My development-cycle is slow, because i always must commit and look what happens on the MacOS-VM used by Github Actions. You may try this on your MacOS-device and have faster progress.

**Comment by buunsal** [comment]
@christophs78 When we use p:focus, chrome also has a bug.

https://user-images.githubusercontent.com/45278820/103749315-6b062700-5016-11eb-8507-d0ac5d419186.mov

**Comment by christophs78** [comment]
Hm. Maybe p:focus is in general a not ideal idea combined with AJAX.

Please try:
```xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

<h:head>
    <title>Test</title>
</h:head>
<h:body>
    <h:form id="form">
        <div style="height: 1000px">
            <div style="height:400px; background-color: red;"></div>
            <div style="height:1800px; background-color: blue;">
                <h:inputText id="name" value="#{testBean.test}"></h:inputText>
                <p:selectOneMenu value="#{testBean.test}">
                    <f:selectItems value="#{testBean.values}" />
                    <p:ajax listener="#{testBean.test()}" update="@form" />
                </p:selectOneMenu>
                <p:commandButton action="#{testBean.test2}" />
            </div>
        </div>
        <h:inputText id="name2" />
    </h:form>
</h:body>
</html>
```

```java
package org.primefaces.test;

import lombok.Data;
import org.primefaces.PrimeFaces;

import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

@Data
@Named
@ViewScoped
public class TestBean implements Serializable {

    private String test;
    private List<String> values = Arrays.asList("a", "b", "c");

    public void test() {

    }

    public void test2() {
        PrimeFaces.current().focus("form:name2");
    }
}
```

What happens for `commandButton` together with `PrimeFaces.current().focus("form:name2")`?

Does the original issue happen in much usecases on Safari or only on some special corner-cases?
Mert´s example looks a bit special because it has a outer div with less height than the inner div.

Just wan´t the figure out what our trade-offs are. And i´d like to hear what @melloware , @tandraschko think.

**Comment by tandraschko** [comment]
IMO none of the fixes are cool currently.
Merts fix duplicates DOM elements and the scripts finds both. So this doesnt work by design, wether Safari nor other browsers.

Remeber the scroll position and restore it on Safari might be the best currently but i wonder why it doesnt happen in other browsers?
Maybe a jquery bug? Maybe other browsers wait to scroll until DOM elements were replaced?
Does it work with plain JS replace of the DOM elements instead of jquery methods?

We must find the root problem before applying hacks.

**Comment by melloware** [comment]
I agree with @tandraschko we should figure out why it doesn't work but to me this feels like a Safari bug.  

@tandraschko this feels an awful lot like this old Edge bug we could never figure out and then went away when MS rewrote Edge with Chromium. See: https://github.com/primefaces/primefaces/issues/3863

@sqores can you try this?  Its another hack but it tries hiding the element then replacing it then unhiding it.  We do this trick in other places in PF whenever components get resized just wondering it that will help here.  we can also try it with `display: none` instead of `visibility`.  

```javascript
if (PrimeFaces.env.safari) {
   var element = $(PrimeFaces.escapeClientId(d));
   element.css('visibility', 'hidden');
   element.replaceWith(b);
    element.css('visibility', '');
} else {
   $(PrimeFaces.escapeClientId(d)).replaceWith(b);
}
```

Not suggesting it as a permanent fix but just trying to get more info.

**Comment by buunsal** [comment]
> Hm. Maybe p:focus is in general a not ideal idea combined with AJAX.
> 
> Please try:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
>         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
> 
> <html xmlns="http://www.w3.org/1999/xhtml"
>       xmlns:f="http://java.sun.com/jsf/core"
>       xmlns:p="http://primefaces.org/ui"
>       xmlns:h="http://java.sun.com/jsf/html">
> 
> <h:head>
>     <title>Test</title>
> </h:head>
> <h:body>
>     <h:form id="form">
>         <div style="height: 1000px">
>             <div style="height:400px; background-color: red;"></div>
>             <div style="height:1800px; background-color: blue;">
>                 <h:inputText id="name" value="#{testBean.test}"></h:inputText>
>                 <p:selectOneMenu value="#{testBean.test}">
>                     <f:selectItems value="#{testBean.values}" />
>                     <p:ajax listener="#{testBean.test()}" update="@form" />
>                 </p:selectOneMenu>
>                 <p:commandButton action="#{testBean.test2}" />
>             </div>
>         </div>
>         <h:inputText id="name2" />
>     </h:form>
> </h:body>
> </html>
> ```
> 
> ```java
> package org.primefaces.test;
> 
> import lombok.Data;
> import org.primefaces.PrimeFaces;
> 
> import javax.faces.view.ViewScoped;
> import javax.inject.Named;
> import java.io.Serializable;
> import java.util.Arrays;
> import java.util.List;
> 
> @Data
> @Named
> @ViewScoped
> public class TestBean implements Serializable {
> 
>     private String test;
>     private List<String> values = Arrays.asList("a", "b", "c");
> 
>     public void test() {
> 
>     }
> 
>     public void test2() {
>         PrimeFaces.current().focus("form:name2");
>     }
> }
> ```
> 
> What happens for `commandButton` together with `PrimeFaces.current().focus("form:name2")`?
> 
> Does the original issue happen in much usecases on Safari or only on some special corner-cases?
> Mert´s example looks a bit special because it has a outer div with less height than the inner div.
> 
> Just wan´t the figure out what our trade-offs are. And i´d like to hear what @melloware , @tandraschko think.


https://user-images.githubusercontent.com/45278820/103773142-abc46700-503b-11eb-817a-a718efc13b52.mov

**Comment by buunsal** [comment]
> I agree with @tandraschko we should figure out why it doesn't work but to me this feels like a Safari bug.
> 
> @tandraschko this feels an awful lot like this old Edge bug we could never figure out and then went away when MS rewrote Edge with Chromium. See: #3863
> 
> @sqores can you try this? Its another hack but it tries hiding the element then replacing it then unhiding it. We do this trick in other places in PF whenever components get resized just wondering it that will help here. we can also try it with `display: none` instead of `visibility`.
> 
> ```js
> if (PrimeFaces.env.safari) {
>    var element = $(PrimeFaces.escapeClientId(d));
>    element.css('visibility', 'hidden');
>    element.replaceWith(b);
>     element.css('visibility', '');
> } else {
>    $(PrimeFaces.escapeClientId(d)).replaceWith(b);
> }
> ```
> 
> Not suggesting it as a permanent fix but just trying to get more info.


This is also a working method. But I haven't tested if it contains errors in the mert's reverted commit.

**Comment by melloware** [comment]
OK a better version would be to check the current visibility and put it back to that state.
```javascript
if (PrimeFaces.env.safari) {
   var element = $(PrimeFaces.escapeClientId(d));
   var visibleCss = element.css('visibility');
   element.css('visibility', 'hidden');
   element.replaceWith(b);
    element.css('visibility', visibleCss);
} else {
   $(PrimeFaces.escapeClientId(d)).replaceWith(b);
}
```

**Comment by buunsal** [comment]
@melloware I don't think it should be specific to safari. there is a general problem. As in the p: focus example, some cases also running buggy with chrome.

**Comment by tandraschko** [comment]
Please lets ignore Focus here, thats not a valid workaround neither really related.

**Comment by christophs78** [comment]
Yep. Focus is not a workaround. Just wanted to be sure we don´t break it by fiddling around with scrollTop().
@melloware suggestion looks good an and @sqores video confirms this does not interfer.

**Comment by tandraschko** [comment]
@sqores can you try native JS without jQuery, to check that is not related to jQuery?
https://stackoverflow.com/questions/843680/how-to-replace-dom-element-in-place-using-javascript

**Comment by buunsal** [comment]
> OK a better version would be to check the current visibility and put it back to that state.
> 
> ```js
> if (PrimeFaces.env.safari) {
>    var element = $(PrimeFaces.escapeClientId(d));
>    var visibleCss = element.css('visibility');
>    element.css('visibility', 'hidden');
>    element.replaceWith(b);
>     element.css('visibility', visibleCss);
> } else {
>    $(PrimeFaces.escapeClientId(d)).replaceWith(b);
> }
> ```

First of all, I apologize for the wrong videos I posted before. I switched from primefaces 8 to 10 to record screen videos. The variables "d" and "b" remained that way because I did copy paste. I haven't noticed that it is a very small source screen. @melloware  your suggestion doesn't work either.

Since it did not give any errors, I did not notice the problem. When I try again "PrimeFaces.env.safari" does not work because we do not keep such a variable. I can say it only works this way.

https://user-images.githubusercontent.com/45278820/103871015-8a1bbc00-50dd-11eb-946f-7a361f8568d7.mov

```
var scroll = $(document).scrollTop();
$(PrimeFaces.escapeClientId(id)).replaceWith(content);
$(document).scrollTop(scroll);
```

@tandraschko No method I've tried with native JS has been successful. Although the replace process was successful on some, the selectonemenu was broken. If you send a sample code that runs successfully in Chrome, i can try it on safari...

![image](https://user-images.githubusercontent.com/45278820/103884921-4f6f4f00-50f0-11eb-9842-7d744e711bd5.png)

**Comment by melloware** [comment]
@sqores Try this..

Replace:
```javascript
 $(PrimeFaces.escapeClientId(id)).replaceWith(content);
```

With:
```javasscript
document.getElementById(id).replaceWith(content);
```

Just to see if that works.  I tested it locally and its working but I did not test thoroughly.

**Comment by tandraschko** [comment]
does replaceWith even exist in native JS? :D

**Comment by melloware** [comment]
I think it does for all but IE11 but I was seeing it if fixes the Safari issue.

**Comment by buunsal** [comment]
> does replaceWith even exist in native JS? :D

Yes but the result is not very good

![image](https://user-images.githubusercontent.com/45278820/103899528-9452b000-5107-11eb-9785-f2904b04c02a.png)

**Comment by melloware** [comment]
Yep using the native DOM replaceWith is definitely not the same for three reasons.

1. JQuery replaceWith removes all Event handlers on the old node being removed and native does not.

2. the output comes out like this:

![image](https://user-images.githubusercontent.com/4399574/103902835-140d5a00-50c9-11eb-905a-f6b395b786ff.png)

3. And its not supported in IE11.

**Comment by christophs78** [comment]
Some thoughts...

- How do Angular, React or Vue handle this? I would expect they also manipulate DOM and have the same challenges.
- https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/replaceWith takes a Node or DOMString; DOMString is handled as text; so it would require to first convert the ajax-response into a Node object

**Comment by tandraschko** [comment]
1) yep, i wondered the same. but in general most of the times just the data is updated in those frameworks, not containers. But maybe someone from PrimeTek could know this.
2) yep; we just should check if Safari works then in this single case; indepdent of IE11 or event handler bindings.

**Comment by christophs78** [comment]
2. https://davidwalsh.name/convert-html-stings-dom-nodes may be to way together with https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/replaceWith. Or at least we may try what this does for Safari.

**Comment by mertsincan** [comment]
Hi all,

Sorry for my delayed response :/ I tried it with replaceWith and replaceChild methods of JS and it works fine for me on Safari and other browsers. Could you please check this solution in the integration tests and Safari?

Also, you can try this issue with;
```
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>replaceWith demo</title>
    <style>
        .test {
            border: 2px solid blue;
        }
    </style>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
</head>

<body>
    <form>
            <div style="height: 1000px">
                <div style="height:400px"></div>   
                <div style="height:1800px">
                    <input>
                    <button type="button" id="button">Click to replace form</button>
                </div>
            </div>
    </form>

    <script>
        $(document.getElementById('button')).on('click', function() {
            var el = $(this);

            el.prev().focus();
            el.closest('form').replaceWith('<form><div class="test" style="height: 1000px"><div style="height:400px"></div><div style="height:1800px"><button>Focused Button</button><button type="button" onclick="replaceFunc(event)">Click to replace form</button></div></div></form>');
        });
    </script>
</body>

</html>
```
A different situation arises here. If you move el.prev().focus(); after the replaceWith method, the scroll problem disappears.

**Comment by mertsincan** [comment]
Hi @christophs78,

Thanks a lot for your solution. Could you please check my commit? WDYT?
https://github.com/primefaces/primefaces/commit/e1654acd2f41228cc68d5a360414c51f6499b238

**Comment by christophs78** [comment]
Hi @mertsincan !

Added a comment to https://github.com/primefaces/primefaces/commit/e1654acd2f41228cc68d5a360414c51f6499b238:
PrimeFaces.escapeClientId IMO returns a string; how should replaceWith work? (DOM won´t even be touched by doing this.)

-->Totally breaks basic AJAX-usecases.

Huge amount of integration-tests broken:
![image](https://user-images.githubusercontent.com/10461942/103937501-1ef7d700-5129-11eb-84db-770d0b9c5537.png)

**Comment by tandraschko** [comment]
STOP STOP STOP :D
we probably CANT use native replaceWith because of jQuery event handlers, DOM destroy event so on. Please just dont commit such core code without talking with us.
I just said that we should try it if it fixes the case and if it may be a jQuery "bug".

Also as @christophs78 already mention, the current will just replace a string or something and the DOM wont be replaced.

**Comment by mertsincan** [comment]
Hi Thomas,
I did not realize that you suggested this. I tested it again. This method does not work with native replaceWith method.

**Comment by tandraschko** [comment]
see https://github.com/jquery/jquery/blob/master/src/manipulation.js#L414
i also think that our widget core would be broken: https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/core/core.widget.js#L283

I really would like to check it by myself but i dont have an apple and probably never have :D

i just wonder why your plain .html sample above works, @mertsincan?
could you try to replace the native replaceWith and jQuery and proove it also works or not?

i would like just like to find out if
1) only safari related and maybe just a newer version? i wonder why we never got a issue before
2) is it jquery related or is it also broken with native JS (replaceChild, replaceWith, whatever)?
3) how can we workaround this? if the bug is there also in older safaris and its also broken with native JS, we can probably need to apply a hack to remember the scroll state.

**Comment by christophs78** [comment]
Maybe we should do a video-meeting with screensharing.

**Comment by tandraschko** [comment]
It could also be caused by any other script.
We need to verify why and how merts plain HTML example works, with native and jquery.
The we know that its not related to ihr Ajax Core.

**Comment by mertsincan** [comment]
I'm running tests without PrimeFaces. I think this issue is completely dependent on focus and replaceWith combinations. Please see my video;
https://www.dropbox.com/s/lap2nm8pgatx954/safari_test.mov?dl=0 (no jquery)
I get the same result with jquery and native javascript. 

Test html;
```
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>replaceWith demo</title>
    <style>
        .test {
            border: 2px solid blue;
        }
    </style>
</head>

<body>
    <form id="form">
            <div style="height: 1000px">
                <div style="height:400px"></div>   
                <div style="height:1800px">
                    <input>
                    <button type="button" id="button" onclick="onClickFunc(event)">Click to replace form</button>
                </div>
            </div>
    </form>

    <script>
        function onClickFunc(event) {
            var el = event.currentTarget;
            el.previousElementSibling.focus();
            
            var content = '<form><div class="test" style="height: 1000px"><div style="height:400px"></div><div style="height:1800px"><button>New ATTACHED Button</button><button>Click to replace form</button></div></div></form>';
            var fragment = document.createRange().createContextualFragment(content);
            document.getElementById('form').replaceWith(fragment);
        };
    </script>
</body>

</html>
```

Please see our focus method;
https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js#L465
It works when we remove the line (selectonemenu.js#L465), but the same thing occurs again when we change the values ​​using the keyboard.

**Comment by tandraschko** [comment]
Nice analysis Mert ✌️
We should search the Bug in selectOneMenu, not hack around in Ajax Core.

**Comment by melloware** [comment]
@mertsincan like @tandraschko couldn't we just do this in SelectOneMenu..
```javascript
var doc = $(document), scroll = doc.scrollTop();
this.focusInput.trigger('focus');
doc.scrollTop(scroll);
```

Even wrap it in `isSafari` if we want to.

**Comment by melloware** [comment]
Interesting that SelectOnemenu has this strangeness too:
```javascript
// Screen Reader(JAWS) hack on Chrome
        if(PrimeFaces.env.browser.webkit) {
            this.input.on('focus', function(){
                setTimeout(function(){
                    $this.focusInput.trigger('focus.ui-selectonemenu');
                },2);
            });
        }
```

**Comment by mertsincan** [comment]
Also, I think the line (selectonemenu.js#L465) is unnecessary. Because the dom changes after the ajax request. Maybe, we can check if there is an ajax request in onchange.

**Comment by tandraschko** [comment]
We should try to find the root bug
Remember scrollTop in the Widget is the same Hack, just different place.

**Comment by melloware** [comment]
Also we are calling this in 4 places in `SelectOneMenu`
```
$this.focusInput.trigger('focus.ui-selectonemenu');
```

When there is a `focus` method.
```
    /**
     * Puts focus on this widget.
     */
    focus: function() {
        this.focusInput.trigger('focus');
    },
```

We should refactor SelectOneMenu to all call `focus()`  if it is necessary.

**Comment by mertsincan** [comment]
We have handleReFocus method in core.ajax.js. The line (selectonemenu.js#L465) is unnecessary for ajax requests.
