### ISSUE TITLE
[DOC] Datatable selectionMode description missing parameter

### ISSUE THREAD

**Issue by Julienng** [primefaces/primefaces#684]
Hi,
The documentation missing parameter for selectionMode.
The doc say:

| name | default | type | Description |
| --- | --- | --- | --- |
| selectionMode | null | String | Enables row selection, valid values are "single" and "multiple" |

But when you read the code of datatable.js, `checkbox` is a valid values too. (cf `bindSelectionEvents` function)

**Comment by sudheerj** [comment]
This issue can be closed.SelectionMode supports only single and multiple options .If we observe the resolveSelectionMode method of DataTable renderer it changes the values as radio and checkbox based on column selection  mode.

public String resolveSelectionMode() {
        String tableSelectionMode = this.getSelectionMode();
        String columnSelectionMode = this.getColumnSelectionMode();
        String selectionMode = null;

```
    if(tableSelectionMode != null)
        selectionMode = tableSelectionMode;
    else if(columnSelectionMode != null)
        selectionMode = columnSelectionMode.equals("single") ? "radio" : "checkbox";

    return selectionMode;
}
```

Since it is not an issue we can close this issue.
