### ISSUE TITLE
FileUpload: Ajax Status is not working while using basic+auto upload

### ISSUE THREAD

**Issue by garcia-jj** [primefaces/primefaces#6912]
The upload component with basic and auto options is not triggering the ajax status. I'm not sure if this component has been designed to trigger ajax status, but I guess this can be a good feature if has not been planned.

**Reproducer**
https://github.com/garcia-jj/primefaces-issue-upload-ajax

**Environment:**
 - PF Version: _10.RC1_
 - JSF + version: _e.g. Mojarra 2.2.
 - Affected browsers:  ALL_

**To Reproduce**
1. Go to http://localhost:8080/primefaces-test/
2. Click on 'Click' button, and you can see that Ajax Status will be updated
3. Upload a file, and you can see that Ajax Status will not be updated while browser is uploading the file.
4. Using Chrome 87.0.4280.141

**Expected behavior**
Ajax status indicator updated while the file is uploading

Thank you, team.

**Comment by melloware** [comment]
I think the problem is right here:
https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/fileupload/3-fileupload.simple.js#L237

it has `global="false"` which tells it not to trigger the AJAX spinner.  Looks like this was intentional not sure why.

**Comment by StevenHachel** [comment]
I have had problems with it since version 8.0.14.

If the Ajax status "Complete" is no longer recognized and the "statusDialog" is no longer hidden after the upload.
This occurs with nested components, i.e. when I use FileUpload documents multiple times.
Is there a trick how I can set this status manually to make it work again?

Problem:
After upload file (mode="auto)" p:ajaxStatus dosent call function oncomplete.

JSF 2.1
EL 2.2
Weblogic 12.1.3.0.0

**Comment by melloware** [comment]
@StevenHachel if your problem truly is this ticket then set `global="false"` on the upload.  That would essentially negate this change and make it work like it did in 8.0.13.  If that does not do it then either A) the Elite merge did not merge all the changes from this ticket or B) This ticket might not be the cause of what you are seeing

**Comment by StevenHachel** [comment]
@melloware thx for help.
The "global" attribute is only available in version 10 and therefore does not work with Primefaces 8.

My workaround is that I click a hidden button after uploading via the attribute fileUpload->oncomplete() so that the Ajax status gets its correct status and my application can be used again.

Steven
