### ISSUE TITLE
StyleBuilder: create style attribute easily

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6917]
**Description**
Similar to #6610 for created style classes we need one similar for creating style attribute.

**Comment by Rapster** [comment]
I wonder if we shouldn't introduce an "HTMLBuilder" on top of that to avoid the whole startElement/writeAttr/writeText/etc. boilderplatecode (it will under the hood). .. As opposite of StyleClassBuilder, instead of storing in a StringBuilder, it will straight away write into the response, this would give a lot of ease to read/write renderers since methods will be like:

```java
HTML.of(context)
    .id(component)
    .class(component)
    .styleClass(component)
    .div()
    .endDiv()
```

**Comment by tandraschko** [comment]
I general yes but i dont think that is an easy task. Different elements, different attributes.
What about creating a PF indepedent prototype and ask the the JSF group to make something for JSF4 to replace/abstract the old ResponseWriter? Of course this needs contributors ;)

**Comment by tandraschko** [comment]
You example wouldnt work as div() needs to be called before the first attr will be written. Otherwise you still need buffering with a StringBuilder
