### ISSUE TITLE
RowsPerPage not sync with Filtering

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#702]
This is reported by a PRO user;

There is a DataTable that shows paginator and it has global filter.
[steps]
1. DataTable shows some records.(rowsPerPage=100)
2. change dropdown value to 10.
3. set global filter value to be no records found.
4. change dropdown value to 100.
5. clear global filter value.
after these steps,I hope dataTable shows 100 records. but it will show only 10 records.

**Comment by jthalmai** [comment]
This still (or again?) seems to be an issue with PrimeFaces 7.0.
In my table I have a paginator on top and on bottom of the table, like in the paginator showcase.

With the bottom one the bug is completely reproducible.

With the top one, when changing the rowsPerPage value, the bottom one is not immediately updated, but only after clearing the filter, the bottom paginator rowsPerPage value is updated and the correct number of rows is shown.
