### ISSUE TITLE
Datepicker: views one more redundant week

### ISSUE THREAD

**Issue by buunsal** [primefaces/primefaces#7040]
![image](https://user-images.githubusercontent.com/45278820/109278450-9abcf880-7829-11eb-8500-39b776743a0e.png)

**Comment by melloware** [comment]
@sqores we have some Integration Tests failing now I am going to investigate.
```
Error:    DatePicker002Test.testWithShowOtherMonths:90 expected: <14> but was: <7>
Error:    DatePicker002Test.testWithoutShowOtherMonths:62 expected: <7> but was: <14>
Error:    DatePicker003Test.testMinMax:55 expected: <30> but was: <23>
```

**Comment by melloware** [comment]
OK its showOtherMonths="true"
```
 <p:datePicker id="datepicker2" value="#{datePicker002.localDate2}" pattern="MM/dd/yyyy" showOtherMonths="true"/>
```

Used to look like this and that is what we were testing for..
![image](https://user-images.githubusercontent.com/4399574/109307771-207f7a80-780f-11eb-8c57-2969ec4ab07c.png)

After your fix its this..
![image](https://user-images.githubusercontent.com/4399574/109308208-b74c3700-780f-11eb-8acc-7e50b700aaa0.png)

So that makes sense but I am wonder if people wanted to see that extra week in showOtherMonths="true"???

**Comment by melloware** [comment]
I say we leave it like this and I will fix my tests.

**Comment by melloware** [comment]
Tests fixed and passing!

**Comment by buunsal** [comment]
Because of when showOtherMonths is false datepicker renders even so extra one week with visibility hidden css. And this sitiuation adds extra empty paddings. We never want this case happen. But I guess you already understood why. thanks for fixed the tests
