### ISSUE TITLE
InputNumber: Separator broken

### ISSUE THREAD

**Issue by JohannesProbst** [primefaces/primefaces#7271]
**Describe the defect**
Using a dot as thousand separator (e.g. _thousandSeparator="."_) and a comma as decimal separator (e.g. _decimalSeparator=","_) on the InputNumber component, leads to a value beeing cut at the thousand separator after leaving the inputfield (e.g. change-event), if the user input value has at least 4 digits (e.g. user input is 4000 -> 4.000) and the attribute '_symbol_' is not set.

**Reproducer**
[Primefaces Version 10.0.0 Showcase for InputNumber](https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml)

**Environment:**
 - PF Version: _10.0.0_
 - JSF + version: _Mojarra 2.3.14_
 - Affected browsers: _Chrome_

**To Reproduce**

1. remove the attributes '**symbol**' and '**symbolPosition**' from the example '_Currency_' in the Primefaces-Showcase for the InputNumber component.
2. Enter a value >= 4 digits without decimals. 
3. Leave the input field via e.g. tab.

**Expected behavior**
If the user enters a value greater 999 without any decimal values the visible value should contain the dot as thousand separator and beeing submitted as the value without the thousand separator - for example: entered value is 4500, then the **submitted** value after leaving the input-field via e.g. tab should be 4500 and NOT 4.5 and the **visible** value should be 4.500 and not 4,5.

**Comment by melloware** [comment]
Confirmed issue with Reproducer:
[pf-7271.zip](https://github.com/primefaces/primefaces/files/6398479/pf-7271.zip)

**Comment by melloware** [comment]
Here is a MonkeyPatch you can add to your project can you please try it by adding this JS your application JS file.
```javascript
if (PrimeFaces.widget.InputNumber) {
    PrimeFaces.widget.InputNumber.prototype.bindInputEvents = function() {
        var $this = this;

        // GitHub #6447: browser auto fill fix
        this.input.off('blur.inputnumber').on('blur.inputnumber', function(e) {
            var element = AutoNumeric.getAutoNumericElement(this);
            if (element && this.value && this.value.length > 0) {
                var newValue = this.value;
                if ($this.cfg.digitGroupSeparator) {
                    newValue = newValue.replaceAll($this.cfg.digitGroupSeparator, '');
                }
                element.set(newValue, null, true);
            }
            $this.copyValueToHiddenInput();
        });
    }
}
```

**Comment by JohannesProbst** [comment]
Thx for the fast response @melloware - your patch is working fine 👍

**Comment by melloware** [comment]
Updated the MonkeyPatch above from replace to replaceAll to catch multiple seaparators.

**Comment by DonVuleone** [comment]
Hello,

I tried your patch and mostly it works fine, thanks for that! 
As a hint, there is one case, when it would not work:

I've implented an inputNumber like the following

`
<p:inputNumber id="i_val" decimalSeparator="," thousandSeparator="." decimalPlaces="0"
					 symbol=" pcs." symbolPosition="s"
					 value="#{cc.attrs.value}" >
	<p:ajax process="@this" update="@this" />
</p:inputNumber>
`

After entering a value (it doesn't matter if the value is 1 or 10000) the field is empty.
The problem is that the Patch also replaces the "." of the symbol, so the set value would be e.g. "1.000 pcs." -> "1000 pcs" and I think the field is empty, because the symbol has also been manipulated.
I think it will happen in any case when the symbol contains a character equal to the thousand separator.

Best regards

**Comment by SoozaV** [comment]
This bug is still present on version 12.0.0, I'v tried with `&#46;` and `.` as decimal separator but isn't working. 

`<p:inputNumber
                                        value="12.00"
                                        symbol="%"
                                        symbolPosition="s"
                                        decimalSeparator="&#46;"
                                        decimalPlaces="2"
                                        />`

Just one zero and no % symbol:
![image](https://user-images.githubusercontent.com/23610892/211600701-3ddbc7a1-03dd-46a2-b784-36408c4b6ed3.png)

Regards.

**Comment by melloware** [comment]
Works fine for me...

![image](https://user-images.githubusercontent.com/4399574/211608267-6dc74a84-7608-412d-a41e-23c8196f9559.png)

Reproducer:
[pf-7271.zip](https://github.com/primefaces/primefaces/files/10384766/pf-7271.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

**Comment by SoozaV** [comment]
I think the problem is in my project's config, because your example works fine, but mine not.

I get this error in the console: `Uncaught Error: autoNumeric will not function properly when the decimal character 'decimalCharacter' [.] and the thousand separator 'digitGroupSeparator' [.] are the same character.`

I got rid of this error setting both `decimalSeparator="."` and `thousandSeparator=","`, now it works fine!

Thanks.

**Comment by melloware** [comment]
Oh yes i was going to ask you if there was a warning in the console. Its due to your country code and locale!  I am in the UI so mine defaults to the EN_US settings.
