### ISSUE TITLE
Schedule: Determine if an event was moved into allDay

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#74]
I ran into a problem using the Schedule compoenent. I use a editable schedule and created a listener for the eventMove ajax-event of the schedule.
The problem is that I cannot determine if an event was moved into the allDay-Slot. Looking into the PrimeFaces sources I found out that the ScheduleEntryMoveEvent isn't filled with this information at all.

So, as far as I can see there's no way to find out if an event was moved into the allDay-Slot or vice-versa. 

I'm using PrimeFaces 3.3.1 on Mojarra 2.1.7

Here is a short example of what my schedule looks like:

``` xml
<p:schedule id="scheduleWidget"
  initialDate="#{scheduleController.selectedDate}"
  value="#{scheduleController.model}"
  draggable="true"
  resizable="true"
  slotMinutes="15"/>
  <p:ajax
    event="eventMove"
    listener="#{scheduleController.onEventMove}" />
</p:schedule>
```

In the onEventMove function I cannot determine if the event was moved into allDay.

**Comment by hlavavit** [comment]
Any change on this? 

Just working on schedule that aggregates schedules from multiple sources with the drag and drop feature enabled. The events start and end time are behaving weirdly . if dragged to all day slot the are the same as they were before,  if dragged from all day slot then they change, this makes it unusable. I had to choose between drag and drop enabled and all day slot enabled because of it.

**Comment by melloware** [comment]
See comment: https://github.com/primefaces/primefaces/pull/6107#issuecomment-654365079
