### ISSUE TITLE
DatePicker: Add support for fractions of a second

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#7448]
To allow migrating some use cases from Calendar component, which is deprecated now, support for entering/selecting milliseconds should be added to DatePicker. It's a functionality that is present in Calendar, but not in DatePicker. While doing this, you may consider adding support for micro- or nanoseconds (any precision from 0 to 9).

**Comment by melloware** [comment]
I didn't realize the old Calendar allowed for partial seconds.   This would be a relatively large change i would think and the DatePicker is shared between PrimeVue, PrimeReact, etc so we could investigate if its been implemented in those other libraries but most likely this would need to be a PRO request or a PR.

Just out of curiosity what is your use case for allowing users to enter partial seconds?

**Comment by morvael** [comment]
Is it really that large change? java.util.Date supports millisecond precision (3), LocalDateTime supports nanosecond precision (9). So it's really just utilising the same types, simply one more input is needed which goes up down from `0` to `(10^precision)-1`, and uses the same types (so the converter may truncate extra data if the underlying type does not support enough precision).

In my use case I have a generic editor framework, so if the source (usually a database) can store time with fractions of a second in a field, I need to support editing that field in its entirety. In case fractions are not supported by the component, I'll have to revert to mask input and forfeit the advantages of using date picker.

**Comment by melloware** [comment]
I didn't investigate it I just assumed it would be a big change involving adding a new UI element and controls, validating all the server side code handles either millis (Java Date) or nano (Java Time) etc.  Probably a new property like `showFractional="true"` because most people won't want this enabled by default.

**Comment by morvael** [comment]
Yes, this should be disabled by default.

**Comment by morvael** [comment]
But it should be simple being a variant of seconds on/off support which is already there. So a copy/paste/replace process :)

**Comment by melloware** [comment]
Feel free to submit a PR!

**Comment by morvael** [comment]
I wouldn't even know where to start :) Just pointing missing functionality because of calendar deprecation as PF Elite user :)

**Comment by melloware** [comment]
Understood.  Then you are definitely not the judge of what changes should be "easy". 😄

**Comment by morvael** [comment]
Perhaps, I can only speak from general experience, sometimes adding a field is a chore if you have very many places to alter :)

**Comment by wal-jan** [comment]
I'll try to create a PR. As @melloware already stated it is not at all trivial. The PR will only support millis (not micros nor nanos) since JS Date only supports milliseconds. `DatePicker` will be extended by 2 properties: `showMilliseconds` (default `false`, implicitly `true` if `pattern` contains upper case `S`), and `stepMillisecond` (default `1`).  The PR will contain changes in `primefaces` and `primefaces-integration-test` projects. Maybe after merge I can add some examples to primefaces-showcase project.

**Comment by melloware** [comment]
@wal-jan that would be great.  and the Showcase is now part of this repo its a submodule.  As well are are integration test suite too.  So everything is all right here now!  A PR would be appreciated!
