### ISSUE TITLE
The timeline component shows some texts by clipping

### ISSUE THREAD

**Issue by ufuk23** [primefaces/primefaces#7507]
Some texts are shown by clipping in the timeline because they have a short time period like below. Is there any way to show the whole text or could you think about that considering it as a new feature?

![image](https://user-images.githubusercontent.com/8513827/124146281-499e6900-da96-11eb-8805-feae6fb51759.png)

**Comment by melloware** [comment]
You might want to check what is possible in the vis-timeline component itself since PF is just wrapping that underlying component.

https://visjs.github.io/vis-timeline/docs/timeline/#Configuration_Options

Also that is being clipped it looks like because that is the length of the time element.  What we do is showa placeholder then use a tooltip to show more detail if they hover over a small event like that.  So if you have a 15 minute event with the text "This is some long text" its never going to be able to fit that in the box.
