### ISSUE TITLE
DataTable: onCellEdit event fires too late

### ISSUE THREAD

**Issue by vfedoriv** [primefaces/primefaces#7546]
**Describe the defect**
Assume we have datatable whit cell we trying edit and some button below that submit that has ajax action
Then
first scenario: we edit datatable cell (enter new value), do mouse click on some form place (to imitate focus lost) - here onCellEdit 
 event will fire, then click the button.
So - **onCellEdit will fire first, then button action will fire second**
second scenario: we edit datatable cell (enter new value), then do mouse click directly on the button.
**The button action will fire first, onCellEdit will fire second**
But de-facto row cell also lost focus when we do click the button

**To Reproduce**
Go to edit datatable cell, change the value then click the mouse on the button that has ajax action event
Firs button action will be fired, then onCellEdit event

**Environment:**
 - PF Version: 10.0
 - Chrome 91

**Expected behavior**
OnCellEdit should fire BEFORE button action.

P.S.
I found the same problem description on StackOverflow, added long time ago:
https://stackoverflow.com/questions/26099330/pcelleditor-does-not-save-textarea-onblur-when-clicking-a-link
The author said he created a bug request in primefaces repo, but I did not found it in issues.

**Comment by melloware** [comment]
I am not quite sure how it will be possible to fix this if the button click is queuing an AJAX event and then the browser notifies the text area focus was lost and queues the OnCellEdit AJAX event.  The ordering will always be like that.  

To me the workaround in the Stack Overflow post is valid because its using the component's `blur` event which does fire before the Document Focus lost event which the OnCellEdit is looking at.

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primefaces/issues/7776 which has a reproducer attached.
