### ISSUE TITLE
FileUpload: Ajax Status component doesn't came back to complete status after upload completes

### ISSUE THREAD

**Issue by garcia-jj** [primefaces/primefaces#7642]
**Describe the defect**
While using file basic upload component, the ajax status component doesn't back to COMPLETE status after upload done. The status component still in the START state.

**Reproducer**
The reproducer is available at https://github.com/garcia-jj/primefaces-upload-issue.

**Environment:**
 - PF Version: _10.0_ downloaded via gradle from Maven Central
 - JSF + version: _e.g. Wildfly 21, but occurs also under Mojarra 2.3 via reproducer
 - Affected browsers: _e.g. ALL_

**To Reproduce**
1. Go to 'http://127.0.0.10:8080/primefaces-test'
2. Click on '+ Choose' button, then select any file to upload.
3. See the status component still shows the message "Running Ajax" even after upload has been performed.

**Expected behavior**
After upload has been performed, the message needs to be hidden.

Thank U team

**Comment by melloware** [comment]
I fixed your reproducer...
[pf-7642.zip](https://github.com/primefaces/primefaces/files/6900362/pf-7642.zip)

Your `complete` facet is empty which means it doesn't get rendered because it has no children. 
```java
if (ComponentUtils.shouldRenderFacet(facet)) {
                encodeFacet(context, clientId, facet, event, true);
            }
```

The JS code ensures that there is a valid complete facet to call and since yours never gets rendered this does not do anything..
```javascript
if (event !== 'complete' || this.jq.children().filter(this.toFacetId('complete')).length) {
            this.jq.children().hide().filter(this.toFacetId(event)).show();
        }
```

So I changed it to...
```xml
<f:facet name="complete">
   <h:ouputText value="" />
</f:facet>
```

And now your code works fine.

**Comment by garcia-jj** [comment]
Thank U @melloware. 👍

**Comment by melloware** [comment]
no prob!
