### ISSUE TITLE
Custom Icon for MenuButton

### ISSUE THREAD

**Issue by crocimi** [primefaces/primefaces#767]
I find that the MenuButton is missing an attribute 'icon'. 

Sure, I could personalize the icon using the css, but if the label is empty, the size of the button is smaller and I should correct it using css again. I find this could be made easier....

**Comment by mbeedub** [comment]
+1

**Comment by sudheerj** [comment]
This might be intentional.Because the drop down icon is a default standard one and existed in many components.We are not using icon attribute for these type of common icons.We just have iconPos to align the icon either left or right side.Or Are you looking for separate new icon along with label(apart from dropdown icon)?

For example, Split button icon attribute is used for the icon which resides on left side of the label but not for the dropdown icon.

**Comment by mbeedub** [comment]
A very good question.  From my point of view it's about having a separate new icon in addition to the standard dropdown arrow label. 

In a UI situation where you've styled several "regular" buttons with icons and then include a MenuButton amongst them, you can't currently style it with the additional icon.  So with this suggested enhancement, it would essentially end up looking similar to splitButton but without the separate action/split (i.e. a click simply displays the menu).  The additional icon would have to always display on the opposite side to the standard drop down icon.

**Comment by crocimi** [comment]
Exactly. It's about having a separate new icon in addition to the standard dropdown arrow label.

**Comment by husnutapan** [comment]
https://github.com/primefaces/primefaces/commit/1f7d8190743bc6ce94b3dba3feded6b340aa6ffa
you can review this fix and and use as

`<p:menuButton value="Options" icon="fa fa-home">
                <p:menuitem value="Save" actionListener="#{menuView.save}" update="messages" icon="ui-icon-disk"/>`
              .....

**Comment by Rapster** [comment]
Duplicate #1459
