### ISSUE TITLE
Selenium / Integration Tests: auto load driver?

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#7674]
I know that arquillian had the feature to download the drivers automatically
maybe a good idea for us, too?
sometimes annoying

@christophs78 @melloware ?

**Comment by melloware** [comment]
I do think that is a good idea.  We can see what they were doing and try and do the same.

**Comment by melloware** [comment]
Looks like its this Arquillian Drone project: http://arquillian.org/arquillian-extension-drone/

**Comment by christophs78** [comment]
Startingpoint:
https://github.com/arquillian/arquillian-extension-drone/blob/master/drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/AbstractBinaryHandler.java

Per-browser implementations:
https://github.com/arquillian/arquillian-extension-drone/tree/master/drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler

More download-code also needed (part of it browser-specific):
https://github.com/arquillian/arquillian-extension-drone/tree/master/drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/downloading

Per-browser factories (ensuring the driver is already there or gets downloaded):
https://github.com/arquillian/arquillian-extension-drone/tree/master/drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory
This factories do the driver-instancing we currently do in org.primefaces.integrationtests.PrimeFacesSeleniumTomEEChromeAdapterImpl and so on.

Some work to do. Not a quick win.

Arquillian Drone is licenced under Apache Licence 2.0. Because we modify Arquillian and/or make a derivate we are allowed to do this under MIT. Right?

Maybe we should start implementing this for Chrome. IMO it´s a nice to have to lower the entry barrier for people who want to contribute integrationtests.

**Comment by tandraschko** [comment]
i would not use drone
also we should not try to rebuild, looks bit to overengineered from a short view? not sure

+1 to implement it very basic for chrome and firefox

**Comment by tandraschko** [comment]
docs still missing + driver.version unused, couldnt find it in the webdrivermanager yet

**Comment by melloware** [comment]
What is left on this ticket?  Just updating the README.MD?
