### ISSUE TITLE
DataTable: Reflow does not work in iOS when using with facelet template

### ISSUE THREAD

**Issue by anuragnz** [primefaces/primefaces#7797]
DataTable reflow does not work with iOS when using facelet template.

With facelet template:

![image](https://user-images.githubusercontent.com/3331466/132202439-63d38718-7d3c-41d4-9b88-64d89bef8ec1.png)

Without using facelet template. Just plain Jsf page, Here is screenshot:

![image](https://user-images.githubusercontent.com/3331466/132202604-2987b113-3611-48f4-b72d-3741d2f15242.png)

Here is the source code for test project

[Experimental.zip](https://github.com/primefaces/primefaces/files/7115194/Experimental.zip)

**Comment by melloware** [comment]
Similar to this issue: https://github.com/primefaces/primefaces/issues/1568

**Comment by melloware** [comment]
Here is a runnable sample with `mvn clean jetty:run`:
[pf-7797.zip](https://github.com/primefaces/primefaces/files/7115726/pf-7797.zip)

There is a big difference in your two examples.  When you use the template you are wrapping it with custom styles...

```xml
        <div id="top" class="top">
            <ui:insert name="top">Top</ui:insert>
        </div>

        <div id="content" class="center_content">
            <ui:insert name="content">Content</ui:insert>
        </div>
```

Please remove those custom styles and try again.  Because these two examples should be identical.  I think its your custom CSS that is messing up the reflow.

**Comment by anuragnz** [comment]
HI @melloware ,

I found a weird thing after spending some time.
In Facelet template client, Nebeans add these 2 lines on top for xml version and  DocTpe as below:

![image](https://user-images.githubusercontent.com/3331466/132267905-518d27ee-cf87-4b7d-bf1f-c5a851bd6b73.png)

When I remove the above top 2 lines then the DataTable reflow works fine in iOS.

Anyway I can work with this and you may close the issue if you like.

**Comment by melloware** [comment]
Wow that is weird Netbeans adds that!
