### ISSUE TITLE
SelectCheckboxMenu: does not show label with multiple="true"

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#8153]
**Describe the defect**
I use this:

```
<p:selectCheckboxMenu  ..
   label="Select .."
   updateLabel="true"
   multiple="true"
   showHeader="false">
```

and expect that the label "Select.." is shown when the component is rendered and no selection is made. However, the inputField is empty (explicitly use `emptyLabel="Select .."` does not help). If I set `multiple="false"`, then the label is shown correctly. 

**Environment:**
 - PF Version: _11.0.0_RC2
 - JSF + version: Mojarra 2.2.20 
 - Affected browsers: ALL_

**To Reproduce**
1. Use any `p:selectCheckboxMenu`  with the following properties:
label="Select .."
updateLabel="true"
multiple="true"
2. No label is shown

**Expected behavior**
The label should be shown (when no selection was made)

**Comment by tandraschko** [comment]
related to: https://github.com/primefaces/primefaces/issues/7241

updateLabel / emptyLabel seems to be not compatible now with multiple=true

**Comment by melloware** [comment]
I think we have a bigger problem with this component as discovered by one of my team members. The name `label` is a bad name. `label`, `emptyLabel` and `updateLabel` should be renamed `placeholder`, `emptyPlaceholder` and `updatePlaceholder` or something like that.  Here is why....

Take this scenario...
```xml
<h:outputLabel for="name" value="Standard Label"/>
<p:inputText id="name" required="true"/>
```

If on the server side you asked the `InputText` for its label by calling `component.getAttribute("label")` it would return "Standard Label" as would most components because `p:outputLabel` has special handling to set the Label field if its not set.

However for SelectCheckBoxMenu:
```xml
<h:outputLabel for="name" value="Standard Label"/>
<p:selectCheckboxMenu id="name" required="true" label="Wrong" />
```

then `component.getAttribute("label")` returns "Wrong" instead of "Standard Label".   So you can't write generic code on the server side to get labels for each component as this one does it wrong.

The standard PF validation that happens on required fields will throw the message **"Wrong is required"** instead of **"Standard Label is required"** for that checkbox menu

**Comment by poppieng** [comment]
Analyzing the css code, I found a temporary solution that works.
Just overwrite the css below.
```css
.ui-selectcheckboxmenu-multiple-container:empty:after{
	content: attr(data-label)!important;
}
```
