### ISSUE TITLE
AutoComplete: support LazyDataModel to search instead of completeMethod

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8202]
You might have many `LazyDataModels` in your project which are almost suitable to serve as an `AutoComplete` suggestions
provider. They could be used with `AutoComplete` in combination with a field attribute. The query string could be applied on the provided `lazyModelField` using `MatchMode.CONTAINS`.

**Comment by Rapster** [comment]
What's the added value of this? Please add description. I have my own  idea but I'd rather hear it from you

**Comment by jepsar** [comment]
@Rapster added description. See also PR.

**Comment by Rapster** [comment]
Understood. Indeed autoComplete feature look a bit similar to filtering in DataTable:
- filter input
- filter mode
 
But could we do more? For example:
- if maxResults was limited to 10, you could request to load more (next page?) There is a moreTextSelect, but reusing LazyDataModel would be a lot more elegant approach
- display the total (matching filter)
- Also, optimizing the fetching process, instead of querying everytime you type, you could use a Trie to save time (this could be a util class, and not set by default or is it?)

One thing I'm not in favor is that new attribute, lazyModelField. It's only meant to be used for LazyDataModel, so it should be set in your LazyDataModel. But my guess, is that you want to simply reuse existing lazyModels and not create new stuff. I don't see any other way except create a AutoCompleteLazyDataModel that wraps a LazyDataModel in which you set also the field name and delegates to your wrapped model

**Comment by jepsar** [comment]
> * if maxResults was limited to 10, you could request to load more (next page?) There is a moreTextSelect, but reusing LazyDataModel would be a lot more elegant approach

Yeah, we could do that. Should be a new issue and PR IMO.

> * display the total (matching filter)

We could add that. Could be a placeholder you could use in moreText.

> * Also, optimizing the fetching process, instead of querying everytime you type, you could use a Trie to save time (this could be a util class, and not set by default or is it?)

There is a queryDelay attribute. I prefer to use that to reduce server load.

> One thing I'm not in favor is that new attribute, lazyModelField. It's only meant to be used for LazyDataModel, so it should be set in your LazyDataModel. But my guess, is that you want to simply reuse existing lazyModels and not create new stuff. I don't see any other way except create a AutoCompleteLazyDataModel that wraps a LazyDataModel in which you set also the field name and delegates to your wrapped model

I initially added an interface, but replaced it with the field. An interface would require you to modify existing lazy models. And, you can expect one generic lazy model which is used for all the entities in an application. This makes it hard to search on different fields in different entities. For example, in one entity I need to search on name, in the other on username or title, etc. So I opted for a field instead.

https://github.com/primefaces/primefaces/pull/8203/files/81543655e368c90f96ed52b3a104fde9219ec928

**Comment by Rapster** [comment]
> There is a queryDelay attribute. I prefer to use that to reduce server load.

Turns out, there is a cache attribute... 

> I initially added an interface, but replaced it with the field. An interface would require you to modify existing lazy models. And, you can expect one generic lazy model which is used for all the entities in an application. This makes it hard to search on different fields in different entities. For example, in one entity I need to search on name, in the other on username or title, etc. So I opted for a field instead.

You shouldn't try too hard to make existing models compatible with autocomplete, there are 2 different components. If one day, we decide to change LazyDataModel again, it'll impact autocomplete and probably not in a good way... Though, you can create an adapter/intermediary to make them compatible

```java
public interface LazyQueryable<T> {

    class Result<T> {
        long total;
        List<T> result;

        public Result(long total, List<T> result) {
            this.total = total;
            this.result = result;
        }
    }

    Result<T> load(int offset, int batchSize, String query);
}
```

And an adapter to make compatible models from DataTable:
```java
public class LazyQueryableAdapterModel<T> implements LazyQueryable<T> {

    LazyDataModel<T> model;

    String field;

    public LazyQueryableAdapterModel(String field, LazyDataModel<T> model) {
        this.model = model;
        this.field = field;
    }

    @Override
    public Result<T> load(int offset, int batchSize, String query) {
        Map<String, FilterMeta> filterBy = MapBuilder.<String, FilterMeta>builder()
                .put(field, FilterMeta.builder()
                        .field(field)
                        .filterValue(query)
                        .matchMode(MatchMode.CONTAINS)
                        .build())
                .build();
        List<T> result = model.load(offset, batchSize, Collections.emptyMap(), filterBy);
        return new Result<>(model.getRowCount(), result); //or use LazyDataModel#count instead of getRowCount
    }
}
```

And now, you can write: `new LazyQueryableAdapterModel("name", new LazyCarDataModel())`. Would that work for you? I made `LazyQueryableAdapterModel `just because you mentionned your use case, otherwise end users should make their own `LazyQueryable`. Being said, I don't see much value to this adapter, IMO, I would make LazyQueryable and LazyDataModel use the same DAO method

**Comment by jepsar** [comment]
> > * if maxResults was limited to 10, you could request to load more (next page?) There is a moreTextSelect, but reusing LazyDataModel would be a lot more elegant approach
> 
> Yeah, we could do that. Should be a new issue and PR IMO.

This is #8

**Comment by tandraschko** [comment]
TBH i like the current way that AutoComplete makes LazyDataModel compatible with it, without introducing new interfaces, changes etc. etc.

We could however introduce a new interface in the future, if we need to support other cases or other components

**Comment by Rapster** [comment]
Let's start with LazyDataModel I gues and see how it goes in the future. Suggestions count should also support DataModel#getRowCount (we don't use count method recently introduced)

**Comment by tandraschko** [comment]
perfekt, thanks for the feedback

#count is already used the current PR, so i will merge it
