### ISSUE TITLE
DataTable: Paginator breaks when table is updated after previous table is filtered

### ISSUE THREAD

**Issue by newk5** [primefaces/primefaces#8347]
**Describe the defect**
For example if you filter a table and then open a dialog with another table, if you change page on that table, the paginator shows the wrong number of pages, it always shows 1 page only. This issue did not happen in PF10

**Reproducer**
[primefaces-test.7z](https://github.com/primefaces/primefaces/files/7962453/primefaces-test-master.2.zip)

**Environment:**
 - PF Version: _11.0.0_
 - PF Theme: ALL?
 - JSF + version:  ALL?
 - Affected browsers: ALL?

**To Reproduce**
1. Filter the table
2. Click on the edit button
3. When the dialog opens, change the page of the datatable
4. The result is that all table pages except the first are removed
5. Video: https://i.imgur.com/x8kKK7M.mp4

**Expected behavior**
Paginator should keep the correct number of pages

@FlipWarthog has noticed that setting partialUpdate="false" on the table inside the dialog fixes the issue

**Comment by melloware** [comment]
When I download your zip above it says its corrupted?  I can unzip it?

**Comment by melloware** [comment]
OK you are right this is so strange that 1 table in 1 form is affecting the paginator of another datatable in another form.

**Comment by melloware** [comment]
OK I think I see the problem.  When you filter the first table this is sent back in the response...

```xml
<extension ln="primefaces" type="args">{&#34;totalRecords&#34;:1}</extension>
```

And then when you open the dialog and then paginate the 2nd datable this is sent back in the response although I have no idea why the callback from `FilterFeature` for a different datable is being sent back to this 2nd datatable.

```java
//Metadata for callback
        if (table.isPaginator() || table.isVirtualScroll()) {
            PrimeFaces.current().ajax().addCallbackParam("totalRecords", filtered.size());
        }

```

**Comment by fanste** [comment]
I just had a quick look into the reproducer. The root cause is, that the `filteredValue` is not stored to the view state anymore, [see here](https://github.com/primefaces/primefaces/blob/68c6afcd5bde4a751c5ac15128a9333c99f1ef95/primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java#L302).

The method `processEvent` is invoked on restore view phase, the datatable checks if it is filtered and if it is filtered it checks if a value expression for the `filteredValue` attribute is given. If not, re-evaluate the filters.

Based on this observation, this bug is not triggered if `filteredValue` is used.

Possible solutions:
- store the filtered values in the view state again, but I don't think that this is desired
- add some kind of check to determine if really 'this' table should be updated with new information => will fail again if multiple tables are updated by the request as `totalRecords` is shared by all datatables because of the common name.
- same as before, but additionally prefix/suffix the name `totalRecords` with e.g. the client ID

**Comment by melloware** [comment]
I think you are right `totalRecords` is too generic and should have the clientId prefix.

**Comment by melloware** [comment]
Nice!

**Comment by jepsar** [comment]
@melloware What is the workaround here? Because I think I'm also running into this, but not in a dialog.

**Comment by melloware** [comment]
@jepsar the workaround is this..

> @FlipWarthog has noticed that setting partialUpdate="false" on the table inside the dialog fixes the issue

However @newk5 reported it doesn't totally fix all the issues it fixes this specific issue.

**Comment by jepsar** [comment]
Okay, thanks! I'll see if that helps and if we are actually running into the same issue...

**Comment by newk5** [comment]
@jepsar Beware, if you use partialUpdate="false" you will then run into another issue, if you're using filters, see here: https://i.imgur.com/EXPS1eM.gif

What you type in the filter keeps "resetting".

Your best solution is pulling the PF12 snapshot, compile it and use that instead. Thomas' commit above fixed the original issue.
