### ISSUE TITLE
FileUpload: java script error on cancel

### ISSUE THREAD

**Issue by german1410** [primefaces/primefaces#844]
I'm seeing the following error on the browser debug console when I cancel a file upload:

Uncaught TypeError: Cannot read property 'fadeOut' of null

I'm using prime faces 5.2 with Mojarra 2.1.29-04
Browser: Chrome Version 46.0.2490.80 m
I'm able to reproduce this on prime faces showcase too

The bigger the file, the more errors I get.

**Comment by german1410** [comment]
More details I was able to capture:
Uncaught TypeError: Cannot read property 'children' of null
ucfg.progress                  @ fileupload.js.jsf?ln=primefaces&v=5.2:1
y.Widget._trigger             @ jquery-plugins.js.jsf?ln=primefaces&v=5.2:27
b.widget._onProgress     @ fileupload.js.jsf?ln=primefaces&v=5.2:1
(anonymous function)     @ jquery-plugins.js.jsf?ln=primefaces&v=5.2:27
(anonymous function)     @ fileupload.js.jsf?ln=primefaces&v=5.2:1
bI.event.dispatch            @ jquery.js.jsf?ln=primefaces&v=5.2:25
ce.handle                        @ jquery.js.jsf?ln=primefaces&v=5.2:25

**Comment by mertsincan** [comment]
I tested with Chrome 46.0.2490 but I couldn't replicate this issue(Exp; http://www.primefaces.org/showcase/ui/file/upload/single.xhtml) Can you please explain your case step by step? What should I do in fileupload demo to see this issue?

**Comment by german1410** [comment]
This happens on the following page http://www.primefaces.org/showcase/ui/file/upload/auto.xhtml

**Comment by sudheerj** [comment]
The upload process begins automatically very quickly in auto mode.When I tried to upload bigger size files then I can find different as follows.

![image](https://cloud.githubusercontent.com/assets/3127317/15091248/8ce39e94-1460-11e6-84df-8b96a8a7228a.png)

**Comment by german1410** [comment]
1) Go to http://www.primefaces.org/showcase/ui/file/upload/auto.xhtml using chrome
2) Open the debug console
3) Upload a file, now limit is 100k there so it will be more difficult to reproduce.
4) Before the file is uploaded cancel the operation

![primefacesuploadcancelerror](https://cloud.githubusercontent.com/assets/4230387/15114422/4d8a35f2-15d0-11e6-86b8-c3bcb4db2444.png)

**Comment by Rapster** [comment]
Interesting, I just reproduced the problem. (@mertsincan you have to try with a bigger file). It looks like it does not cancel the upload at all, it just remove the line from the table :/ See code in fileupload.js line 1999:
```javascript
.on('click.fileupload', this.rowCancelActionSelector, null, function(e) {
    var row = $(this).closest('tr'),
        removedFile = $this.files.splice(row.index(), 1);
    removedFile[0].row = null;

    $this.removeFileRow(row);

    if ($this.files.length === 0) {
        $this.disableButton($this.uploadButton);
        $this.disableButton($this.cancelButton);
    }

    e.preventDefault();
});
```
Once canceled, the output keep showing this:

![image](https://cloud.githubusercontent.com/assets/7521311/21075721/23b1e28c-bf19-11e6-9b3d-6ff2b098d7b1.png)

Once it gets "unfortunately" upload, I see what you were talking @german1410 

![image](https://cloud.githubusercontent.com/assets/7521311/21075732/564fbab6-bf19-11e6-8e0f-2a9390f5de1d.png)

This last error is not a big problem as I think it can easily be fixed. The real problem here is that, as shown on the screenshot, the upload keeps processing. It'd be interesting to know the differences between p:fileUpload and [jQuery-File-Upload](https://blueimp.github.io/jQuery-File-Upload/jquery-ui.html). I noticed few differences. @tandraschko do you have an idea what decisions have been taken on this component on PF side?

**Comment by tandraschko** [comment]
No idea, sry. We simple developed on our own UI and reused the iframe transport. I think a fix could be quite easy. PR is welcome!
