### ISSUE TITLE
AjaxSource: replace global with eventPropagation / deprecate global

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8444]
See #8302

The `eventPropagation` attribute will be used to trigger a local and/or a global Ajax status based on the value.

Possible values: `component`,`global`,`both` (default),`none`.

Whether `component` (or local) Ajax status will be applied depends on the component, if it's implemented in its widget.

`global` will be deprecated in 12, removed in 13. If you would use `global="false"`, that will imply `eventPropagation="none"`. If you would use both `global="false"` and `eventPropagation`, `global` would "win" as `eventPropagation` has a default value.

**Comment by tandraschko** [comment]
i would like to hear opinions of @Rapster @christophs78 @melloware @mertsincan

**Comment by melloware** [comment]
I kinda like this idea but global has been around SOOOO long maybe we log a message like "global is deprecated please use the new eventPropagation property` and if they have...

`global="true"` then convert it to `eventPropagation="both"` under the covers
`global="false"`  then convert it to `eventPropagation="none"` under the covers ?

Just thinking out loud

**Comment by tandraschko** [comment]
yeah
deprecate it for 12 and convert them under the cover 
and remove for 13

**Comment by jepsar** [comment]
Are we still waiting for opinions here? Or can we go ahead with this?

**Comment by christophs78** [comment]
I don't have a strong opinion on this. Scanned our internal repo and found some usages of `global="false"` but not that much. Will realistically cause breaking some applications, because people don´t read migration guid (in depth), jump over multiple versions, ... Maybe it´s worth the price.

**Comment by melloware** [comment]
I am fine with it.

**Comment by mertsincan** [comment]
I'm not sure about adding these to p:ajax. This means deciding where to build the loader elements for each component and where to block based on what conditions. E.g; For dataTable's sort and filter events, will we block the entire dataTable or the elements that trigger that event? In short, I think it would be better to add features like 'ajaxLoading' and 'ajaxLoadingIcon' on a component basis in the first place. In the future, when this structure becomes available for all components, I think we can decide more easily how to produce a general solution.

**Comment by tandraschko** [comment]
I think we should not add such Attributes to each component, therefore just allowing a generic way on p: ajax to limit the event receiver

I, as user, would expect that every component in a modern component lib does it automactically, even not deactivatable

Each component needs then to decide what to block and where to show the loading indicator
Autocomplete should not block input but show a inline loading icon
DataTable should block further actions until e.g. sort request is complete

**Comment by mertsincan** [comment]
Yes, adding an option to p:ajax might be a generic way, but I think some attributes may be required on a component basis as well. Most users will want to customize the loading icon, or they will not want to write this option for all events in components with more than one event. Most importantly, this option added to ajax for most components may not make sense. E.g; p:selectBooleanCheckbox, p:selectManyCheckbox
Should checkboxes be blocked instead of loading icon in component like this? Also, In such cases, should we stop the focus and keyboard accessibility until the component is unblocked?

**Comment by tandraschko** [comment]
yeah, we should really discuss this deeply
why should we NOT block e.g. a checkbox when AJAX is done?
i know there is a async=true flag on p:ajax but does anyone use it? it likely breaks more then it helps

**Comment by rider87** [comment]
I don´t like it to replace "global"... It´s active for years and many people are using it.
In my app I have many many pages which uses "global".

**Comment by tandraschko** [comment]
Sorry but thats not a reason. We always need to rethink old patterns and always do, therefore we have a migration guide.

**Comment by jepsar** [comment]
If we don't want to change `p:ajax`, `p:ajaxStatus` might be an option. See https://github.com/primefaces/primefaces/pull/8302#issuecomment-1019991491

> Maybe using `p:ajaxStatus` is the cleanest solution. We could add properties `disableTriggers` and `inlineStatus`, which we can make available as global JavaScript properties, which can be used by widgets supporting them. This allows us to  eliminate `inlineAjaxStatus` and `disableOnAjax` on various components.

**Comment by rider87** [comment]
> Sorry but thats not a reason. We always need to rethink old patterns and always do, therefore we have a migration guide.

As I said, I don´t like this, and I can understand that many people will not migrate to newer PF version, if they had to adjust so many things before...
`global="false" / global="true"` is on so many components.

I just did a count on one of my big projects:

Searched for  global="false" / global="true"
3.541 entries = global="false"
2.279 entries = global="true"
**= 5.820 entries in total**

If there is a simple fix in the IDE to replace it, I´m fine... But I don´t think it will be the case.

**Comment by tandraschko** [comment]
I think we have to clarify some questions before finding a technical correct and good usable option.
So you will also unterstand the difference between `blocking` and `loading indicator` (especially to clarify your doubts @mertsincan)

1) A `inline` `ajaxStatus` is just some additional loading indicator like the PR for autoComplete and commandButton - they just switch e.g. the icon or display a new icon on the right side.
IMO there is no reason to disable it, its just a nice built-in feature, which can be disabled via CSS in worst case globally. I would NOT add a option to disable it. Also i would NOT add a option to configure the icon as a spinning icon is default since years. A user or theme can still overwrite it, there is no need to make it configurable for each component, thats something global per app.

if we dont need a option to disable a local ajaxStatus, we dont need to introduce new attributes or anything. Just a small JS and CSS. So we can also leave the `global` attribute as it is.

A CSS will look like:
```
.ui-autocomplete .ui-loading-indicator {
      // style some stuff
      display: none;
}
.ui-autocomplete.ui-status-loading .ui-loading-indicator {
      display: inline;
}
```

2) We currently have a option to disable a component on AJAX requests like implemented in `p:commandButton` (`disableOnAjax=true`)
Is there any reason to make it configurable?
This is a hard question. I think it general it makes sense to make it configurable but enable it per default as AJAX requests are queued anyway and does not make problems. Im not sure if anyone use it async requests and spawn multiple requests but...

I think input components can implement the `disableOnAjax` quite easily and does not influence this ticket here. For complex components like `p:dataTable` it would propably makes sense to use a `blockUI` for the whole table. Then there is still a question, if we need a automatic way or should each user add a `blockUI` to the xhtml?

**Comment by jepsar** [comment]
1. I'm okay with a fixed behavior there. We could add a `ajaxStatusIcon` attribute which defaults to spinner, and might even disable the option if you would pass `null` or `"none"`. If we won't add that attribute, also fine with me as it can be done using CSS (see https://github.com/primefaces/primefaces/pull/8302#discussion_r805297664)
2. I'm okay with a fixed behavior there as well. Disabling triggers makes sense to me and prevent double clicking issues. The impact (other than the disablement) is visual and can be overridden in CSS.

I would not disable / block data tables by default. I would stick to command components when it comes to auto disabling.

**Comment by mertsincan** [comment]
1. OK for me.
2. Maybe we can ask the community for feedback on this issue. @jepsar could you please create a ticket in Github Discussions tab? And then, can you share its link on PrimeFaces Discord channel? Hearing some feedback can help us make changes more easily.

My personal opinion is that in components such as dataTable, users use blockUI component and manage it themselves. This will always be flexible.

**Comment by jepsar** [comment]
@mertsincan Okay, I can open a discussion, but what should the question be? Whether or not we should have the `disableOnAjax` attribute on components like `p:commandButton` and `p:commandLink`? Or whether to include Ajax disabling on more complex components like `p:dataTable`?

**Comment by mertsincan** [comment]
Thomas said "This is a hard question. I think it general it makes sense to make it configurable but enable it per default as AJAX requests are queued anyway and does not make problems. Im not sure if anyone use it async requests and spawn multiple requests but..."
@jepsar I added a comment for 2, referring to this. You can ignore my comment about "Discussions". If the disableOnAjax attribute is ok for all of us, I think we can add it.

**Comment by tandraschko** [comment]
ok then i will summarize:

1) we can add inline ajax status to whatever component like commandButton or autoComplete. Its enabled and we dont add any attribute to disable it. A user can overwrite the CSS if really required
2) disableOnAjax can be added to components, with enabled per default. 


The last question is: is `disableOnAjax` the right attribute name and should it be added to e.g. `p:commandButton` or should we allow a much more generic concept with `p:ajax disableTrigger=true`?

**Comment by mertsincan** [comment]
Thanks @tandraschko,
> is disableOnAjax the right attribute name
- I am not sure. If we find a better name, we can use it. I think the "disableOnAjax" is the best name for now :D

> should it be added to e.g. p:commandButton or should we allow a much more generic concept with p:ajax disableTrigger=true
- If we add the disableTrigger property to p:ajax, will there still be a special attribute for <p:commandButton ajax="true" />?

**Comment by tandraschko** [comment]
thats the problem with `p:commandButton` in general :/
it would be great if it would NOT have the `ajax` attribute and `p:ajax` would be mandatory.

if case of 'p:commandButton' 'disableOnAjax' sounds better, in case of `p:ajax`, so everything other component in PF, 'disableTrigger' would be much better

**Comment by jepsar** [comment]
If we go for `p:ajax disableTrigger=true`, I would like to have an option to globally configure it for command components.

**Comment by mertsincan** [comment]
Ok.
For commandButton( and components that have ajax="true | false" option)
```
<p:commandButton disableTrigger=true ../> Or disableTriggerOnAjax=true ?
```

For other components;
```
<p:ajax disableTrigger=true .../>
```

**Comment by jepsar** [comment]
Great! I'll close this issue then and modify https://github.com/primefaces/primefaces/pull/8302
