### ISSUE TITLE
DataTable: selectionMode="multiple" - Selection with shift doesn't work when clicking into a checkbox 

### ISSUE THREAD

**Issue by Strahly** [primefaces/primefaces#8475]
Description:
Multi row selection with the shift key only selects the last checkbox, when clicking the checkbox of a row.

Environment:
PF ShowCase - DataTable: Selection
https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml?jfwid=f4c98

1. In the ShowCase for the  dataTable selection go to the checkbox.
2. Click on the checkbox of the first regular data row.
3. Hold down Shift and click on the checkbox of the last datarow.
4. Only the  first and the last checkbox are checked. Text in row(1) - row(n-1) is marked as selected.

Expected behavior:
All rows and checkboxes are selected/checked

**Comment by melloware** [comment]
@FlipWarthog didn't you see something similar. Want to look into this one?

**Comment by FlipWarthog** [comment]
@melloware I don't think so, but I could be wrong; I know I've definitely been manually disabling row selection when I use checkboxes (as discussed here #8416).

A note, though, I'm not sure the expected behavior described in this ticket is entirely correct. I believe the meta key function (e.g. Shift and Ctrl) are only for row selection, not checkbox. See the example from PrimeReact, it functions the same way

https://www.primefaces.org/primereact/datatable/selection/

**Comment by melloware** [comment]
I am going to close this as WontFix as it does appear other Prime libs do the same thing.

**Comment by jepsar** [comment]
Hmm.. I would like this to be added though. Does it matter if other libraries don't support this?

**Comment by melloware** [comment]
OK reopened.
