### ISSUE TITLE
selectManyMenu only selects one when clicking on the label

### ISSUE THREAD

**Issue by ntobeko-mkhize** [primefaces/primefaces#873]
To reproduce visit http://www.primefaces.org/showcase/ui/input/manyMenu.xhtml

In the advanced menu click on the select item label, ie. Afterdark, Afternoon etc.

Expected Result:
All clicked items should remain selected.

Actual Result:
Only the last clicked item is selected

**Comment by gunnee** [comment]
Have you tried using CTRL + click ? =) This component derives from <select> multiple. Selecting multiple options vary in different operating systems and browsers:
For windows: Hold down the control (ctrl) button to select multiple options
For Mac: Hold down the command button to select multiple options

**Comment by jasonex7** [comment]
I think using selectManyMenu component is intended to, like the name says, select many items not just one, so the component should favor that behavior making easy to do that (select many items). Maybe a parameter to configure this behavior would be great.

I think setting showCheckbox="true" should by default keep the selected items instead of just select the last one and clearing the previous selected ones.

**Comment by smokeybandit** [comment]
I agree.  You've basically got one widget with two different behaviors whether you click on the checkbox or on the label.    Pretty unintuitive to the user.

**Comment by jxmai** [comment]
I will raise a patch.

**Comment by tandraschko** [comment]
Thanks!
