### ISSUE TITLE
Uncaught TypeError: c.replace(...).replaceAll is not a function

### ISSUE THREAD

**Issue by zicheee** [primefaces/primefaces#8798]
### Describe the bug

Today I updated to PrimeFaces 10.0.12 and I cannot use the SelectOneMenu anymore. 
When I click on the list, a JavaScript error is thrown in the console:

Uncaught TypeError: c.replace(...).replaceAll is not a function   components.js.xhtml?ln=primefaces&v=10.0.12:20

### Reproducer

Use Android 7 with WebView or Firefox 75 or Chrome 80 and try to use the SelectOneMenu component.

### Expected behavior

The commit 775c5e8c20f44ff23caa9105d275716a1e143d38 changed the selectOneMenu code and a "replaceAll" was added.

According to https://caniuse.com/?search=replaceAll this feature was mainly introduced mid of 2020 and so many old browsers cannot use it. 

Maybe it is possible to find another solution for "replaceAll" and so be compatible with older browsers

### PrimeFaces edition

Elite

### PrimeFaces version

10.0.12

### JSF version

2.3

**Comment by tandraschko** [comment]
if you check the commit, replaceAll was removed

@melloware can you check and close if required?

**Comment by melloware** [comment]
So a few things. 

1. 1, Yes that issue in SelectOne was fixed in 11.0.0 and confirmed its in master fixed.
2. We do use `replaceAll` in a few places throughout the JS code base but we use a PolyFill so its always available in all browsers https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/core/core.polyfill.replaceall.min.js
3. It was fixed with this ticket for 11.0: https://github.com/primefaces/primefaces/issues/7451
