### ISSUE TITLE
Dynamic columns fail inside Repeating

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#88]
When a datatable with dynamic columns are placed inside a repeating component, columns do not reflect the model being iterated.

**Comment by kukel** [comment]
For 'reverse'  linking: [Issue in google](https://code.google.com/p/primefaces/issues/detail?id=6276)

**Comment by kukel** [comment]
> We've reviewed the patch but only solves a small part of the issue. DataTable just like other JSF components keep other information in viewstate like pagination, sorting and more. So a proper patch should also consider these, not just columns.

If I don't use this patch, use a `ui:repeat`  with 2 normal datatables (no dynamic columns) and one datatable with dynamic columns, it renders the page and the dynamic columns ok and I only have a problem with ajax (some casting error because the wrong type of object is in the model)

> General alternative is using c:forEach, not sure why it failed for you, so that same table is not repeated instead a separate table will be used instead.

In this case (also without the patch)I get the same classcast exception when **rendering** the page. So the patch at least improves something. 

> Having said this, we believe this should be solved by JSF runtime not by component itself where JSF runtime gives a different statemap per each iteration for the same component.

This might explain why I still get the classcast exception with ajax when **using** the patch. Will try sorting and filtering to and try to find improvements (might be somewhere in 'visitTree'), but it could also be that https://code.google.com/p/primefaces/issues/detail?id=4811 is the real cause?
