### ISSUE TITLE
Dialog content with scrollbar does not resize correctly when dialog resized

### ISSUE THREAD

**Issue by javaone199** [primefaces/primefaces#8989]
### Describe the bug

If a dialog content has scroll bar, there will be a gap between dialog content and dialog border when dialog is resized.

### PrimeFaces version

11.0.0

### Theme

Saga

### Browser(s)

Chrome 103

**Comment by tandraschko** [comment]
Please provide a reproducer

**Comment by patzi** [comment]
I just stumbled upon this problem with chromium based browsers as well.
To reproduce just go to https://www.primefaces.org/showcase/ui/overlay/dialog.xhtml with a chromium based browser open the basic dialog and shrink it so that you get a vertical scrollbar. Release the mouse while the dialog still has the scrollbar and then resize again.
The glitch right/under the scrollbar even gets bigger the more you repeat this.

I checked it with chromium and edge on linux
See attached video
[primefaces_8989.webm](https://user-images.githubusercontent.com/255512/189861103-117d3f97-635e-4fc4-822f-c8450053cf44.webm)

**Comment by patzi** [comment]
This seems to be a bug upstream in jqueryui https://github.com/jquery/jquery-ui/issues/2083
@tandraschko please reopen this one

**Comment by melloware** [comment]
This is fixed for 13.0.0 and you can test in RC1: https://github.com/primefaces/primefaces/issues/9882

**Comment by melloware** [comment]
@patzi this was reported again today. I tried the jQuery fix and it still does not fix the issue on Chrome.  Firefox is working fine but no chromium based browsers.
