### ISSUE TITLE
PFExtensions Migration: KeyFilter

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#902]

**Comment by Julienng** [comment]
I link you there [inputMask](https://github.com/RobinHerbots/jquery.inputmask) . I talk about it [here](http://blog.primefaces.org/?p=3652). I implement it at work and that can provide inputMask & inputFilter feature. That could be awesome

**Comment by tandraschko** [comment]
does it cover 100% of each component?
Not sure if i will invest time into such a new component for now, i would just like to migrate every with without introducing bugs or incompatibility for now.

**Comment by Julienng** [comment]
Yeah, can cover inputMask, inputNumber and keyFilter feature. The only this that can make time to implement is the testFunction of the keyFilter because:

You can implement your own behavior, called alias to handle some scenario (ex: email, phone-number, numeric, regex). Every alias can inherit from a another alias (ex: currency, decimal, integer, percentage aliases override numeric).

So, to implement a test function, you have to implement the behavior with an alias.

And every alias can be override by classical parameter like mask at runtime.
At work, I use alias and parameter like that:

``` javascript
// for a mask of numeric value with 2 number before dot and an optional decimal value
// of 3 number max.
// numeric alias is used for justify right the input.
'alias': 'numeric', 'mask' : '9{0,2}[,9{0,3}]' 

// for all character with a maximum length of 9
'alias' : 'all', 'reapeat' : '9'
```

I understand you prefer merge and limit incompatibility for the next release. But implement something like that offer more option available for you to implement new component or new behavior with custom alias easily. I really think it's worth. Think about it if you have time to :smile:

**Comment by tandraschko** [comment]
For now, lets migrate the components and evaluate your component later.
Feel free to provide your component code - i will take a look at it.
