### ISSUE TITLE
DataTable: Not compatible with MyFaces' component tree manipulation

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#9171]
### Describe the bug

Our custom library utilizes the PF datatable in a very dynamic manner. Columns are populated dynamically based on runtime configurations. Everything worked fine with Mojarra, but because of other bugs, I tried MyFaces as the JSF implementation.

MyFaces performs way better and everything works as expected, but therefore I got a new bug: The contents of the dynamic columns is duplicated on view restore (e.g. pagination).

After digging around, the root cause is probably not MyFaces but PF itself.

During `DefaultFaceletsStateManagementStrategy#saveView` (MyFaces class) all dynamically created components are stored to the view state for restore at a later time. In `#saveStateOnMapVisitTree` a tree visit is started which tries to collect those dynamic components and if one is found, the state is serialized (including the children) and `VisitResult.REJECT` is returned, so the tree-visit does not visit the children again (see [here](https://github.com/apache/myfaces/blob/2.2.x/impl/src/main/java/org/apache/myfaces/view/facelets/DefaultFaceletsStateManagementStrategy.java#L1066) for the MyFaces source code).
 
 

But PF does not respect that `VisitResult.REJECT` in UIData. The problematic lines of code are https://github.com/primefaces/primefaces/blob/2b1384a3c6464c995e029757eeebd8cb6144f4d9/primefaces/src/main/java/org/primefaces/component/api/UIData.java#L771 and https://github.com/primefaces/primefaces/blob/2b1384a3c6464c995e029757eeebd8cb6144f4d9/primefaces/src/main/java/org/primefaces/component/api/UIData.java#L897.

The first code stops the processing of the children, as only the UIColumn itself should be visited at that place. But the result 'REJECT' is never stored. During the second code, the column content is visited which clearly is not expected, as the save-state-logic of MyFaces previously rejected the processing of the children of the column.

### Reproducer
https://github.com/fanste/primefaces-test/tree/test-9171
Just use the paginator and have a look at the second column.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### JSF implementation

MyFaces

### JSF version

2.2.15

### Java version

8

**Comment by tandraschko** [comment]
IMO a integration test is absolutely required here
also it would be great if you can work on a PR

**Comment by fanste** [comment]
I'm a bit confused, as my reproducer behaves differently from the real application.

My application works, but duplicates the components, but only once.
The reproducer throws a duplicate-ID exception. When I set the reproducer to production and disable ID-checking, it duplicates the child-component of the column per request.

@tandraschko as you are in the MyFaces Team (or am I wrong?), any idea why it behaves so different?

**Comment by tandraschko** [comment]
TBH no idea; this requires a lot of debugging and some samples to understand
that facelet-algorithm things are old and very complex
Leonardo had the most knowledge about it but he is not active anymore

**Comment by fanste** [comment]
Added a reproducer.
I just ignored that behavior, as a fix is more important ;)

PR is also available: https://github.com/primefaces/primefaces/pull/9191

**Comment by melloware** [comment]
Integration Test: https://github.com/primefaces/primefaces/pull/9361

**Comment by Rapster** [comment]
I'm very confused about this, UIData from PF is basically a copy of UIData from Mojarra, so whether it's MyFaces used or not, it shouldn't make a difference at UIData level.

Which makes me think, the bug is most likely to be on MyFaces side then, and at a glance, the visitTree algorithm in MF and Mojarra are similar _(OT: even though there is a diff when SKIP_ITERATION comes in place_)

There was no bug with Mojarra so it can't come from PF, I'm guessing there is a diff in what you mention in the StateManagementStrategy, and they look quite different between Mojarra and MyFaces. Does Mojarra also return a REJECT? It can't be otherwise you would have the very same issue

Ideally, I would like to get rid of that class in PF code or at least, have it as light as possible... so PF can focus only in PF code and stop fixing JSF impl issues

Sorry to dig out that issue, but I really want make sure this is a PF problem...

FYI: I tried to run your reproducer with PF 11/12, and MyFaces 2.2, but I can't even navigate on 2nd page and I have this error showing:

> mars 18, 2023 11:37:54 PM org.apache.myfaces.context.servlet.ServletExternalContextImpl setResponseContentType
SEVERE: Cannot set content type. Response already committed
