### ISSUE TITLE
Header do not render correctly with initial selection value on MultiSelectListbox

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#919]
Details; http://forum.primefaces.org/viewtopic.php?f=23&t=43915

**Comment by melloware** [comment]
[pf-multiselect.zip](https://github.com/primefaces/primefaces/files/2927536/pf-multiselect.zip)

Posting this working example with 6.2 here due to a forum request.  Everything is working fine for me just run "mvn clean jetty:run-exploded" and navigate to http://localhost:8080/primefaces-test/test.xhtml
