### ISSUE TITLE
SelectOneMenu: add direction support

### ISSUE THREAD

**Issue by elmehdi09** [primefaces/primefaces#933]
I am working on application which also supports arabic (rtl) but primefaces selectOneMenu does not support dir="rtl".

![bug_selectonemenu_rtl](https://cloud.githubusercontent.com/assets/13622810/11535710/f164c692-990c-11e5-934e-81b85520a4de.PNG)

**Comment by kukel** [comment]
PF version?

**Comment by elmehdi09** [comment]
PF 5.1

**Comment by kukel** [comment]
Tried a newer version

**Comment by Macadoshis** [comment]
Still not working with PF 5.2.
**dir** attribute not provided for component <p:selectOneMenu />.

I first opened this issue on December 2013 but they've judged it was more simple to reject my submission rather than caring to reproduce it... It's a shame, because 2+ years later it's still unresolved.
https://code.google.com/archive/p/primefaces/issues/6424

**Comment by kazsakke** [comment]
OK, I know this issue is almost a year old, but I faced the same problem and I figured out a workaround.

First you need to flip the whole component with a css transform:

`.ui-selectonemenu {
    -moz-transform: scaleX(-1);
    -webkit-transform: scaleX(-1);
    -o-transform: scaleX(-1);
    -ms-transform: scaleX(-1);
    transform: scaleX(-1);
}`

After that don't forget to flip back the text in the menu and align it to the right:

`.ui-selectonemenu .ui-selectonemenu-label {
    -moz-transform: scaleX(-1);
    -webkit-transform: scaleX(-1);
    -o-transform: scaleX(-1);
    -ms-transform: scaleX(-1);
    transform: scaleX(-1);
    text-align: right !important;
}`

And last but not least align the items in the list to the right:

`.ui-selectonemenu-panel .ui-selectonemenu-list-item {
	text-align: right !important;
}`

That's it.

**Comment by melloware** [comment]
@kazsakke Awesome work.  I just submitted a PR incorporating your suggestions and I was able to remove the !important stuff.

![image](https://user-images.githubusercontent.com/4399574/64653413-5ac74300-d3f4-11e9-97ae-c22bb9d0fb72.png)
