### ISSUE TITLE
Using invalid `autocomplete` attribute on hidden elements

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#9410]
Reported By PRO User;
> our HTML Checker is reporting an error regarding the autocomplete component.

>Error: An input element with a type attribute whose value is hidden must not have an autocomplete attribute whose value is on or off.
<input id="j_idt166:j_idt167_hinput" name="j_idt166:j_idt167_hinput" type="hidden" autocomplete="off" />

> You can also see this issue in the primefaces autocomplete showcase
https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml
field: "POJO"

This may be related to https://github.com/primefaces/primefaces/issues/7851. 
Details; https://www.w3.org/WAI/standards-guidelines/act/rules/73f2c2/

**Comment by mertsincan** [comment]
@tandraschko @melloware @jepsar @Rapster @christophs78 What do you think?

**Comment by melloware** [comment]
Let us review and do some reading.  We will get back to you!

**Comment by melloware** [comment]
I can confirm the NuHTML5 Checker doesn't like it either:

![image](https://user-images.githubusercontent.com/4399574/202181839-5d49aee2-df89-440c-83da-340c9dfe64bc.png)

**Comment by melloware** [comment]
OK after researching this was originally added to hidden inputs because of a Firefox issue.  see: https://stackoverflow.com/questions/18460909/firefox-overrides-javax-faces-viewstate-with-old-value-on-f5-how-to-turn-off-au

But that is old Firefox 23 i will check if its still an issue with newer Firefox.

**Comment by melloware** [comment]
OK @BalusC recommends to do nothing and ignore the W3C validator: https://stackoverflow.com/a/18463706/502366

_"If W3 conformance is really that important, consider rendering `<input type="text" style="display:none">` instead of `<input type="hidden">`. This goes however far overboard IMO."_ – 
[BalusC](https://stackoverflow.com/users/157882/balusc)

**Comment by melloware** [comment]
Going to close this for now as not necessary.
