### ISSUE TITLE
PrimeFaces 5.2 - DataTable RowExpansion <p:rowExpansion> with <p:selectBooleanCheckbox> along with pagination has weird behavior

### ISSUE THREAD

**Issue by PrateepT** [primefaces/primefaces#942]
My requirement is to show checkbox inside a rowexapansion of a datatable

Problem:
All the boolean attributes for the entities in the list for which the datatable is referring become false when I use <p:datatable> with <p:selectBooleanCheckbox> along with pagination

Steps to reproduce:
1. Try to use the prime faces rowExpansion from PrimeFaces showcase
2. Place selectBooleanCheckbox which shows the boolean value
3. Access the pagination of the datatable
4. See that for all the entries in the list the boolean attribute become false, also I tried to print the datatable in the managed bean, the data in the list also got modified, it is bit weird that with row expansion the data in list is being modified
6. When I test the same feature with rowExpansion and without selectBooleanCheckbox everything works normally

For more clarity I have attached the screenshots (data_after_row_exapantion.png, data_modifed_auto_after_row_exapantion.png)

![data_after_row_exapantion](https://cloud.githubusercontent.com/assets/16047587/11593571/4b4b82b0-9aa5-11e5-8434-ef41af82c578.png)
![data_modifed_auto_after_row_exapantion](https://cloud.githubusercontent.com/assets/16047587/11593570/4b4b3b0c-9aa5-11e5-8aa3-bb38911864f1.png)

Am I missing anything or it is a defect in PrimeFaces?

**Comment by kukel** [comment]
Use the forum for this first... and create a working minimal example that demonstrates the problem https://stackoverflow.com/tags/jsf/info

**Comment by mrclBIE** [comment]
I have the same problem with PrimeFaces 5.2 and 5.3. It appears even without pagination and it doesn't matter if i use 'p:selectBooleanCheckbox' or 'h:selectBooleanCheckbox'... seems like a bug for me. Is it already solved @kukel @PrateepT ?

**Comment by mrclBIE** [comment]
[00PrimefacesComponentBug Maven Webapp.zip](https://github.com/primefaces/primefaces/files/279003/00PrimefacesComponentBug.Maven.Webapp.zip)

**Comment by dhladky** [comment]
Also do notice, that if you let the rowExpansion closed, the value is set to "null" no matter what was set by the user. 

The problem is the rowExpansion removes the checkbox from the DOM while closing and recreates it when the expansion is opened. This is the reason, why it is reset when opening the expansion and this is the reason, why null is set when closed and the submit takes place. 

The same incorrect behaviour is for selectOneRadio.

**Comment by last-free-nick** [comment]
Is there something new about this bug?

We experience a problem which should have the same issue. 

We have a data table with row expansion and selectonemenu. Below is a button where you can open a dialog with another table. You can add this table entries to the other table with a commandButton (ajax, process="@this" update="@form"). 

Each time a new entry is added every setter of the checkboxes in the row expansion is called with false. Also selectonemenues get reset to the default value.

With normal inputText there's no problem. Only checkbox und selectonemenu setters are called, no matter if the expansion of the row is opened or closed.

/edit: Were using primefaces elite version 6.1.4

**Comment by dhladky** [comment]
I realized this issue affects also other field types, such as text boxes. This makes the rowExpansion basically useless.

**Comment by jxmai** [comment]
In addition, I can replicate this issue in the latest trunk build  which is a quite annoying bug causing data lost for user.  It also affects `selectBooleanButton`.  I have tried to debug but I am not quite sure which part could be the potential failure point as debugging from bottom up blindly without a high level design in mind is quite painful.

**Comment by jxmai** [comment]
Analysis: this issue could be as @dhladky's description. I have briefly examined the rowExpansion's internal implementation, and I noticed that the row will be removed during collapsed.

https://github.com/primefaces/primefaces/blob/6f8aa2bf30ebf599597e77c9df587e4d5039c64c/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L2109-L2111

So if the content inside row toggler is **label**, the content won't be altered. But if the content inside row toggler is **input** such as checkbox, the form mapping will treat the value to be false.

a workaround is to make use of datatable celleditor's output mode to prevent data being altered, but that's not applicable to checkbox component. In order to make checkbox works, a label representation is needed such as setting checkbox to be `disabled` or output as icon or text.

If the rowToggler is expanded, there is no such issue since the row will be loaded back via AJAX

https://github.com/primefaces/primefaces/blob/6f8aa2bf30ebf599597e77c9df587e4d5039c64c/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L2044-L2068

I guess we shouldn't actually remove the row from the view when a row is collapsed but to hide the content somehow.

**Comment by dhladky** [comment]
FYI: I also noticed, that the content of the standard text box is reset to its starting value. I thought I found a workaround - trigering "update" of another component did the trick, but it worked only sometimes. 

So the final workaround I had to use was when entering edit mode expand everything and remove the toggler so collapsing is prevented. The result is uggly, but reliable form.

**Comment by jxmai** [comment]
Thanks for sharing the workaround. Just a few notes:

> workaround - trigering "update" of another component did the trick, but it worked only sometimes.

I guess the key here is to use partial form submit (`process`) to avoid mapping the content inside rowExpansion as `update` has nothing to do with this issue.

> I had to use was when entering edit mode expand everything and remove the toggler so collapsing is prevented

Yes, it will work as the form mapping is correct since you are forcing the toggler to keep expanding.

---

I think I found a way to solve this issue by hiding the content. The `loadExpandedRowContent` can be refactor to improve the performance but that's later concern.  I will raise a PR shortly.
