### ISSUE TITLE
DataTable: Paginator does not get dynamically rendered when filtering

### ISSUE THREAD

**Issue by fcjm** [primefaces/primefaces#9432]
### Describe the bug

We have a DataTable with predefined filters and paginatorAlwaysVisible=false and we page for every 5 entries. Now we have 6 results in total, but the filter is set in such a way, that less than 5 results show up initially. In that case the Paginator does not get rendered, which is to be expected. If you now remove the filter from the table (and all 6 results should show up again), the paginator does not get automatically added and only the first page (5 results) are visible to the user.

### Reproducer

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/10066858/primefaces-test.zip)

1. remove the filtering for "Price" -> Paginator does not get added (there are 6 results in total)
2. press "Update Form" Button -> Paginator gets added

Alternatively
1. remove filtering for Price
2. press "Update Form"
3. add filtering for Price, so that less than 5 items get shown -> Paginator still visible
4. press "Update Form" -> Paginator disappears
5. remove filtering for Price -> Paginator does not get added 

### Expected behavior

The Paginator should get added/removed dynamically once there are more/less than X rows.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
This is by design.  You have `paginatorAlwaysVisible="false"` which only gets evaluated at first render.   This is the expected behavior of 99% of users.  Showing and hiding the paginator dynamically is a jarring UI/UX experience for users and in that circumstance you would just choose `paginatorAlwaysVisible="true"`.   

It was not designed to show hide with AJAX and filtering.
