### ISSUE TITLE
Cache and move_scripts_to_bottom breaking the menu bar

### ISSUE THREAD

**Issue by MatthiasScherrerFGCZ** [primefaces/primefaces#9464]
### Describe the bug

Having move_scripts_to_bottom=true and caching a menu bar makes so that the menu items are not rendered anymore after the component is fetched from the cache.

### Reproducer

I checked out the PrimeFaces reproducer and put in the code of the menu bar showcase (https://www.primefaces.org/showcase/ui/menu/menubar.xhtml).

1. Click on any menu item except 'Logout'.
2. Click on 'Logout'.
3. Hover over the menu bar and no items are rendered.

With move_scripts_to_bottom=false, everything works as expected.

Here is the reproducer: [cache-move-scripts-to-bottom.zip](https://github.com/primefaces/primefaces/files/10141198/cache-move-scripts-to-bottom.zip)

### Expected behavior

The menu items should be rendered as it is the case with move_scripts_to_bottom=false.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

**Comment by melloware** [comment]
Not sure how it will be possible to make these two features work together.  

The problem is with MOVE_SCRIPTS_TO_BOTTOM the scripts are moved outside of running inline in your component and put on the bottom of the page.  However your `cache` is caching the menu and it would normally be caching those inline scripts along with it.   Now that it has been moved out your cache contains just the HTML/CSS of your menu but `none` of the JS code.   And the page has no idea to reload that JS because the cache is saying "just render this cached component as is.

**Comment by tandraschko** [comment]
yeah, not sure if we can fix it
propably there are other weird cases with p:cache and MOVE_SCRIPTS_TO_BOTTOM

**Comment by tandraschko** [comment]
in general p:cache is feature which is a bit errorprone

**Comment by melloware** [comment]
i think we should just a log a warning stating something to this effect if Cache is being used with MOVE_SCRIPTS_TO_BOTTOM?

**Comment by melloware** [comment]
Added a log warning only in Project Stage Development because in some cases Cache will work fine and wouldn't want it logging that in Production mode.
