### ISSUE TITLE
facet type "filter" of a column is not rendered

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9569]
### Describe the bug

facet type "filter" of a column is not rendered (see reproducer).

Maybe it is related to https://github.com/primefaces/primefaces/issues/8091

### Reproducer

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/10328698/primefaces-test.zip)

### Expected behavior

render facet type "filter" of a column.

### PrimeFaces edition

Community

### PrimeFaces version

12

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

Firefox 107

**Comment by melloware** [comment]
Fixed your reproducer:
[pf-9569.zip](https://github.com/primefaces/primefaces/files/10328983/pf-9569.zip)

You had multiple bugs in the code but the reason the filter was not showing up is because on the column you did not declare EITHER `filterBy="#{user.gender}"` or `field="gender"`  either one of those makes the filter appear.  Without it the column has no idea what it would be filtering.
