### ISSUE TITLE
CurrencyValidator: restore getExcelPattern method

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#9610]
@jxmai has requested we restored CurrencyValidator.getExcelPattern() method that previously existed in PF11.   It is harmless to add this method back in.

```java
    /**
     * <p>
     * Returns a <code>String</code> representing the Excel pattern for this currency.
     * </p>
     *
     * @param locale The locale a <code>NumberFormat</code> is required for, system default if null.
     * @return The <code>String</code> pattern for using in Excel format.
     */
    public String getExcelPattern(Locale locale) {
        DecimalFormat format = (DecimalFormat) DecimalFormat.getCurrencyInstance(locale);
        String pattern = format.toLocalizedPattern();
        pattern =  pattern.replace(CURRENCY_SYMBOL_STR, format.getDecimalFormatSymbols().getCurrencySymbol());
        String[] patterns = pattern.split(";");
        return patterns[0];
    }
```

**Comment by jxmai** [comment]
@melloware , @mertsincan Would it be possible to include this ticket as well as https://github.com/primefaces/primefaces/issues/9612 to the  elite version in PF 12? The reason is that it was not supposed to be the breaking changes in PF 12 and it should be harmless to add. They only restore the feature we have and PF 13 release will be half year later if I am not mistaken. Thank you in advance!

**Comment by melloware** [comment]
I marked it for Elite release and its up to @mertsincan to pick it up.
