### ISSUE TITLE
DataExporter: leading zeroes getting removed when exporting data in Excel format

### ISSUE THREAD

**Issue by touazib** [primefaces/primefaces#9699]
### Describe the bug

When all values in a string column contains only digits with leading zeros, after exporting data in Excel format, the leanding zeros are removed from the Excel file. 

### Reproducer

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/10438322/primefaces-test-master.zip)
1. mvn jetty:run 
2. Click on XLS or XLSX button to export data
3. Open the Excel file to see all leading zeros are removed in the first column "Code".

![image](https://user-images.githubusercontent.com/15329653/212987358-f5fcaa9e-df0b-43de-8b41-b5fee17da02f.png)

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

2.3.x

### Java version

11

**Comment by melloware** [comment]
Documented here: https://primefaces.github.io/primefaces/12_0_0/#/components/dataexporter?id=customization

Because "0001" is not a valid number in Excel its formatting it. To leave it formatting as a String simply set `excelOpt.setStronglyTypedCells(false);` to leave it as a raw String.

Reproducer attached:
[pf-9699.zip](https://github.com/primefaces/primefaces/files/10438747/pf-9699.zip)
