### ISSUE TITLE
Spacer: Generated HTML does not pass safe CSP policy for img-src directive

### ISSUE THREAD

**Issue by mihaiDumea** [primefaces/primefaces#9782]
### Describe the bug

HTML generated by the Spacer component will trigger a CSP violation for `img-src 'self'` directive. Changing the directive to `img-src 'self' data:` will not be safe.
[SpacerRenderer](https://github.com/primefaces/primefaces/blob/49857d00a0c81450fa8e80ab51f39c0c10d166e6/primefaces/src/main/java/org/primefaces/component/spacer/SpacerRenderer.java#L47) is embedding the image in the HTML.

You may choose to use the version before [5794](https://github.com/primefaces/primefaces/issues/5794), make the implementation conditional to CSP enable, or change the img tag with svg.

### Expected behavior

Pass the `img-src 'self'` CSP.

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.2.19

### Java version

11

**Comment by melloware** [comment]
Can you do Spacer with SVG with just SVG instead of image?  That would be ideal it would fix this issue without needing both a GIF and the DATA URl and switching based on CSP.

**Comment by melloware** [comment]
SVG works like a charm!

**Comment by mihaiDumea** [comment]
Indeed!

**Comment by melloware** [comment]
Great suggestion!

**Comment by jepsar** [comment]
Didn't we deprecate spacer?

**Comment by melloware** [comment]
It is but we decided to leave it in just hide the showcase example because there are thousands of PF projects that still use it.  From PF3-PF7 that was even how most PrimeFaces templates and demo's were using it so a lot of people wrote their code with Spacer.  

So its a really tiny component and harmless to leave in there to help people upgrade.  Same reason we don't want to delete Calendar we just hid the showcase demo because for 10 years that WAS the calendar. :)
