### ISSUE TITLE
DataTable: layout breaks when dataTable is scrollable in dialog

### ISSUE THREAD

**Issue by brunoroland** [primefaces/primefaces#9831]
### Describe the bug

Layout of the rowToggler column in dataTable breaks in following conditions : 

- dataTable with rowToggler and scrollable="true"
- dataTable is inside a dialog
- web.xml contains the following config :
```
    <context-param>
        <param-name>primefaces.MOVE_SCRIPTS_TO_BOTTOM</param-name>
        <param-value>true</param-value>
    </context-param>
```
    

### Reproducer
Use attached project 'primefaces-test.zip'

1. Go to page 'http://localhost:8080/primefaces-test/test.xhtml'
2. In that page the rowToggler column is displayed as expected (style="width:2rem")
3. Click on button 'show dialog'
4. In the dialog, the rowToggler column is too large (expected is style="width:2rem").
5. Click on the buton 'refresh'
6. the rowToggler column is displayed as expected (style="width:2rem")

If we change the dataTable attribute scrollable="false", then the rowToggler column is displayed as expected
If we comment or remove the following config the in the web.xml, then then the rowToggler column is displayed as expected
```
<context-param>
        <param-name>primefaces.MOVE_SCRIPTS_TO_BOTTOM</param-name>
        <param-value>true</param-value>
</context-param>
```

### Expected behavior

the rowToggler column should be displayed as expected (style="width:2rem")

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### Theme

saga

### JSF implementation

All

### JSF version

2.2 + 2.3

### Java version
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/10827060/primefaces-test.zip)

jdk11.0.5

**Comment by melloware** [comment]
@brunoroland it is because DialogFramework renders in an IFRAME so its not a normal dialog.  The code when using move scripts to bottom is delayed so the table doesn't know what width="100%" means.  I simply changed 1 line in your code and it seems to work.

```java
options.put("contentWidth", "790");
```

Basically give the content a width instead of saying 100%.   If you look at the docs https://primefaces.github.io/primefaces/12_0_0/#/core/dialogframework?id=dialog-framework

<html>
<body>


contentWidth | 640 | String | Width of the dialog content. NOTE: 'auto' cannot be used because the dialog is displayed in an IFrame.
-- | -- | -- | --
contentHeight | auto | String | Height of the dialog content.


</body>
</html>

It `auto` is not allowed and `100%` must also be causing issues as its similar to auto.  If you give it an actual size the datatable can render its columns properly.
